### ISSUE TITLE
how to make emacs always start with state <E> instead of <N, I, M etc> while i have evil-mode installed?

### ISSUE THREAD

**Issue by chenpoyang** [emacs-evil/evil#1000]
i have evil-mode installed, but i don't want to start with
evil-state(N, I or M) at every mode started, so i set: 
(setq evil-default-state 'emacs), but it doesn't work while i enter
erc-mode, term-mode, that means, the status bar's state is not<E>. 

how to fix it? and , sorry about that i don't know how to pick up a tag, like bug or question etc.

**Comment by justbur** [comment]
The documentation for `evil-default-state` says

```
The default state.
This is the state a mode comes up in when it is not listed
in ‘evil-emacs-state-modes’, ‘evil-insert-state-modes’ or
‘evil-motion-state-modes’. The value may be one of ‘normal’,
‘insert’, ‘visual’, ‘replace’, ‘operator’, ‘motion’ and
‘emacs’.
```
You therefore need to clear out the modes listed in `evil-{motion,insert}-state-modes` if you really want all modes to start in emacs state. It's possible you have a mode listed in `evil-normal-state-modes` too.

**Comment by chenpoyang** [comment]
@justbur thanks

**Comment by chenpoyang** [comment]
use the following code instead:
<pre>
(use-package evil
  :init(setq evil-default-state 'emacs)
  :config
  (evil-mode 1)
  (evil-set-initial-state 'special-mode 'emacs)
  (evil-set-initial-state 'eshell-mode 'emacs)
  (evil-set-initial-state 'comint-mode 'emacs)
  (evil-set-initial-state 'git-commit-mode 'emacs)
  (evil-set-initial-state 'diff-mode 'emacs)
  (evil-set-initial-state 'custom-mode 'emacs)
  (evil-set-initial-state 'dired-mode 'emacs)
  (evil-set-initial-state 'calendar-mode 'emacs)
  (evil-set-initial-state 'help-mode 'emacs)
  (evil-set-initial-state 'term-mode 'emacs))
</pre>
maybe using dolist will be better.:)
