### ISSUE TITLE
SQL keywords are upcased when leaving insert state

### ISSUE THREAD

**Issue by davidshepherd7** [emacs-evil/evil#1004]
# Issue type
- Bug report

# Environment

Emacs version: 25.2.1
Operating System: Ubuntu 16.04
Evil version: 1.2.13
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Turn on sql-mode
- Enter insert mode
- Type `select`
- Hit ESC

# Expected behavior
Nothing in the buffer should change.

# Actual behavior
The word select is changed to SELECT.

# Further notes

- Doesn't happen in text mode.
- Also happens for other SQL keywords like user, select, where.
- Doesn't seem to matter if the keyword is in a valid position to be a keyword (e.g. it affects keywords within table names, column names etc).

**Comment by wasamasa** [comment]
FWIW, I cannot reproduce this.  From the description it reads like abbrevs are expanded, something you can disable by customizing `evil-want-abbrev-expand-on-insert-exit`.

**Comment by davidshepherd7** [comment]
>  it reads like abbrevs are expanded

Yes! that was it, thank you so much :tada: 

Sorry to have wasted your time, I assumed that because I could reproduce it with `emacs -Q` and with `make emacs` in evil it couldn't be a  problem with my config. I guess somehow it still found my old abbrev file.
