### ISSUE TITLE
y w (yank word) does not yank when new evil directory is installed

### ISSUE THREAD

**Issue by wolfv6** [emacs-evil/evil#1012]
y w (yank word) does not yank when new evil-commands.el is installed
# Issue type
- Bug report for a enhancement request

# Environment
Emacs version: 25.3.1
Operating System: Fedora 26
Evil version: evil-git-8e1af145
Evil installation type: MELPA stable
Graphical/Terminal:  under X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): 

# Reproduction steps
make emacs:

        $ cd
        $ git clone https://github.com/emacs-evil/evil
        $ cd evil
        $ make emacs

From Emacs, install org-mode:

        M-x org-mode

Install new evil-commands.el:
- backup ~/evil/evil-commands.el to ~/evil/evil-commands.el.bak
- save file at https://github.com/justbur/evil/blob/fold-sub/evil-commands.el > Raw, to ~/evil/evil-commands.el
- start Emacs
- open ~/evil/evil-commands.el
- M-x eval-buffer

Test evil-commands.el:
- open an .org file
- y w (yank word), then p (put)

# Expected behavior
Insert yanked word.

# Actual behavior
Text from the previous clipboard is inserted.
This only happens when I am running the new file from https://github.com/justbur/evil/blob/fold-sub/evil-commands.el

# Further notes
I also tried installing the entire https://github.com/justbur/evil  directory.
But then the substitute command did not unfold the headings.

This is for the PR: https://github.com/emacs-evil/evil/pull/1009

**Comment by justbur** [comment]
Not sure what's going on, but here is a clean way to do what your trying to do. I can't reproduce the problem with these steps either

From a terminal
```
git clone https://github.com/justbur/evil
cd evil
git checkout fold-sub
emacs -Q -L $(pwd)
```
In emacs
```elisp
M-: (require 'evil)
M-x evil-mode
```

Type some text and try `yw`. This works correctly for me.

**Comment by wasamasa** [comment]
I cannot reproduce this either in a graphical Emacs.
