### ISSUE TITLE
Find home for evil search highlight persist

### ISSUE THREAD

**Issue by quicknir** [emacs-evil/evil#1017]
There's been a recent mess around wiki packages being removed. One of the things that this highlighted is a small set of packages that despite having a fair number of users, are totally unmaintained (and thus, nobody was paying attention to their dependency on wiki packages): https://github.com/melpa/melpa/pull/5008#issuecomment-360103510.

One of those packages is evil-search-highlight-persist: https://github.com/juanjux/evil-search-highlight-persist. Since this package is providing functionality that is widely used and part of vim out of the box, it's unmaintained and only 218 lines of elisp, can this simply be merged into evil? We have to figure out what will happen wrt the highlight requirement so maybe this cannot happen instantly, but hopefully it can be merged in when that issue is dealt with (or perhaps there is now an alternative that can be used to highlight).

**Comment by wasamasa** [comment]
No need, if you customize `evil-search-module` to `evil-search`, you get persistent highlighting (which you can turn off with `:noh[lsearch]`) and a search that's closer to Vim generally.

That aside, the package did already find a new maintainer: https://github.com/juanjux/evil-search-highlight-persist/issues/19.  Please take it up with them if you still feel strongly about this.  Personally, I'd just rewrite the code to not make use of `highlight.el`.

**Comment by quicknir** [comment]
Ah, thanks for the info, I didn't realize this was implemented in evil already, thank you.
