### ISSUE TITLE
Using <D> with a count doesn't make it go to the next line

### ISSUE THREAD

**Issue by umnikos** [emacs-evil/evil#1020]
# Issue type

- Bug report

# Environment

Emacs version: Spacemacs 0.200.13@25.3.1
Operating System: Windows 7
Evil version: 
Evil installation type: 1.2.13
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Type into a scratch buffer:
```
one 
two
three
four
```
Put the cursor on the t of two and type `2D`

# Expected behavior
This should end up deleting the line containing the words two and three, leaving us with:
```
one
four
```

# Actual behavior
It just deletes to the end of the line, leaving us with:
```
one

three
four
```

# Further notes
`2d$` is very close to how `2D` should behave but it leaves a blank line where the deletion occured, resulting in:
```
one

four
```

**Comment by wasamasa** [comment]
Thanks, I can reproduce this. The thing is that `D` behaves differently from `Y` as it deletes from point instead of start of line, so it cannot reuse line motion and uses the end of line as limit.  I'm not sure how to fix this actually.

**Comment by AlexStefanov2** [comment]
If cursor at start of line:
    nD = ndd
else:
    nD = nd$

This pretty much fixes it behavour-wise

**Comment by dzop** [comment]
I think this can be fixed by normalizing to an`exclusive` range first before the call to `evil-delete` in `evil-delete-line`. The `exclusive` range type states

```
If the end position is at the beginning of a line, then:

* If the beginning position is at or before the first non-blank
  character on the line, return `line' (expanded).

* Otherwise, move the end position to the end of the previous
  line and return `inclusive' (expanded).
```

this is the exact behavior described by @AlexStefanov2. So you can modify `evil-delete-line` to take a count argument and first expand the range using

```
(evil-normalize beg (line-beginning-position (1+ count)) 'exclusive)
```

and pass the resulting bounds to the call to `evil-delete`.

**Comment by umnikos** [comment]
Closing because this bug is extremely minor and very old so it will probably never be looked at.
