### ISSUE TITLE
evil-fill-and-move does not split strings properly in Textproto mode

### ISSUE THREAD

**Issue by quaker4lyf** [emacs-evil/evil#1023]
# Issue type
- Bug report

# Environment
Emacs version: GNU Emacs 25.2.50.1
Operating System: Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
Evil version: I use spacemacs only and I'm an emacs dummy, so I don't know how to find this out. I see there's this directory in my spacemacs repository (~/.emacs.d is the git repo): ~/.emacs.d/elpa/evil-20180126.1159/
Evil installation type: Spacemacs 0.300.x, i.e. the develop branch at this commit c130014ff0f263e14bd93786f880d2679958b484
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No, sorry I don't know how to do that with my set up :/

# Reproduction steps
- Start spacemacs
Open a .textpb file that contains a single line long string:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae tempor ex. Proin posuere consequat ultricies. Duis commodo vestibulum erat eu pharetra. Curabitur porta tempor ante volutpat pellentesque. Proin arcu nibh, efficitur eget enim dignissim, imperdiet placerat eros. Pellentesque quis nisl id sem porta condimentum. Cras sed cursus turpis. Nunc rutrum lorem vitae pretium faucibus. Cras ac velit ac arcu placerat consequat ut quis lectus. Nullam eu tempor lectus, in porta neque. Duis efficitur nibh in libero tempor venenatis. Nulla bibendum at erat eu tempor. Vivamus tempus, nibh a suscipit ultrices, elit dui ultricies tellus, id aliquet urna arcu ac lorem."
Notice that the major mode is "Textproto".
Hit "gqq" to reflow the string. C-k g q says (evil-fill-and-move BEG END) is bound to g q

# Expected behavior
Because the file type is text proto, the string should be broken down to consecutive lines of strings, like so:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae tempor "
"ex. Proin posuere consequat ultricies. Duis commodo vestibulum erat eu "
"pharetra. Curabitur porta tempor ante volutpat pellentesque. Proin arcu nibh, "
"efficitur eget enim dignissim, imperdiet placerat eros. Pellentesque quis "
"nisl id sem porta condimentum. Cras sed cursus turpis. Nunc rutrum lorem "
"vitae pretium faucibus. Cras ac velit ac arcu placerat consequat ut quis "
"lectus. Nullam eu tempor lectus, in porta neque. Duis efficitur nibh in "
"libero tempor venenatis. Nulla bibendum at erat eu tempor. Vivamus tempus, "
"nibh a suscipit ultrices, elit dui ultricies tellus, id aliquet urna arcu ac "
"lorem."
(I got that from vim. In vim ":set ft" returns "filetype=textpb")

# Actual behavior
The behaviour is as if the text file type were regular plain text. I get:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae tempor ex.
Proin posuere consequat ultricies. Duis commodo vestibulum erat eu pharetra.
Curabitur porta tempor ante volutpat pellentesque. Proin arcu nibh, efficitur
eget enim dignissim, imperdiet placerat eros. Pellentesque quis nisl id sem
porta condimentum. Cras sed cursus turpis. Nunc rutrum lorem vitae pretium
faucibus. Cras ac velit ac arcu placerat consequat ut quis lectus. Nullam eu
tempor lectus, in porta neque. Duis efficitur nibh in libero tempor venenatis.
Nulla bibendum at erat eu tempor. Vivamus tempus, nibh a suscipit ultrices, elit
dui ultricies tellus, id aliquet urna arcu ac lorem."
That's the same as if I do in vim ":set ft=txt", then "gqq"

# Further notes
I'm happy to provide more info or try more things, but I'll need some hand holding because I'm an emacs noob. Thanks

**Comment by dieggsy** [comment]
I'd strongly suggest trying to reproduce in a more minimal emacs environment or with make-emacs (from this repo). Especially with a project as big as spacemacs, it can become hard (and is not really their responsibility) for evil maintainers to track down where the bug is coming from.

For example, where does this textproto major mode come from? I can't find it through a google search or even searching the spacemacs repo?

**Comment by dieggsy** [comment]
@quaker4lyf as for how to "do" make emacs, you should be able to just clone this repo, `cd` into it, and `make emacs`

**Comment by wasamasa** [comment]
Filling is delegated to the major mode. If the major mode sets `fill-paragraph-function` smart things may happen, otherwise not. Assuming the editor support files you're speaking of are https://github.com/google/protobuf/tree/master/editors then that doesn't look good at all.  Go bug them about it.

**Comment by quaker4lyf** [comment]
Thanks for the info, both
