### ISSUE TITLE
how to end a macro in insert mode

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [emacs-evil/evil#1028]
# Issue type

- Question

# Environment

Emacs version: 25.3
Operating System: macOS

# Reproduction steps
- Start Emacs
```
<div>|</div>       ;; use `qq` to start a macro

<div>              ;; now the state is in insert mode, I want to end the macro immediately
  |
</div>
```

**Comment by edkolev** [comment]
You can use `C-o` followed by `q`, as described here https://www.quora.com/How-do-you-stop-recording-a-Vim-macro-when-in-insert-mode

It's working for me with evil.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
Things might not as easily as it should be:
```
<div>|</div>       ;; use `qq` to start a macro

<div>              ;; now the state is in insert mode, I want to end the macro immediately
  |
</div>

<div>              ;; if use `C-o`, the position of cursor will have a change
|
</div>
```

**Comment by TheBB** [comment]
`C-o` shouldn't change the position of the cursor. I can't reproduce that.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
which package might cause this type operating?
