### ISSUE TITLE
evil-core makes mac want to install gcc

### ISSUE THREAD

**Issue by gusberinger** [emacs-evil/evil#1030]
# Dev Tools

- Bug report/Other

# Environment
Emacs version: GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-12
Operating System: macOS Sierra
Evil version: 1.2.13
Evil installation type: manual
Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs without development tools on Mac

# Expected behavior

Doesn't ask to install gcc.
# Actual behavior

Asks to install gcc.
# Further notes
I'm new to emacs and I can't install dev tools on the mac I'm using. I know the code that's launching gcc is in evil-core. I want to just temporarily disable it while I have this computer.

Thanks for the help!

**Comment by wasamasa** [comment]
Sorry, but how do you know that?  Can you elaborate on how you found that to be the case?  And out of curiosity, do you have a screenshot?

**Comment by gusberinger** [comment]
Basically, when I turn everything off and I turn on evil in init.el, it happens. I'm no longer sure that evil-core is causing it, that was a result of experimentation from someone that doesn't really know how emacs works.


This is what it looks like when I launch emacs. It's not the worst thing in the world, but it's just kind of annoying.
![screen shot 2018-03-10 at 6 40 56 am](https://user-images.githubusercontent.com/7536330/37242382-13121728-242e-11e8-98f3-1c7cf089cc9c.png)

**Comment by wasamasa** [comment]
What if you

- Run `emacs -Q`
- `M-x package-initialize`
- `M-x evil-mode`

Does that give you the popup and at which point?

**Comment by gusberinger** [comment]
How do I ``` run emacs -Q ``` for the Gui emacs?

**Comment by wasamasa** [comment]
On macOS, emacs.app and alike are directories containing the application files, including executables. You'll want to prod around that directory to find the `emacs` executable, that can be run from the terminal as necessary.

**Comment by gusberinger** [comment]
Nothing happened so I guess it wasn't evil-mode. Thanks for the help!
