### ISSUE TITLE
evil-yank doesn't copy to clipboard with prefix arg

### ISSUE THREAD

**Issue by introom** [emacs-evil/evil#1031]
I am on OSX GUI. I used to do this to copy to system clipboard.

>   (defun my-evil-yank-to-system nil
    (interactive)
    (let ((current-prefix-arg 1))
      (call-interactively #'evil-yank)))

However, with the latest evil, it no longer works.

**Comment by wasamasa** [comment]
Please do not ignore the bug report template. It's there for a reason.

I can't help you with this at all. Use `git bisect` to figure out which commit introduced the issue. Chances are it's a customization anyway and the fix will be to customize clipboard-related variables.
