### ISSUE TITLE
Commands using "j" don't behave like vim

### ISSUE THREAD

**Issue by NightMachinary** [emacs-evil/evil#1034]
Commands using "j"  don't behave like vim. In vim j means a line starting from the current line; In evil it means a line starting from the cursor.
For example pressing 'comment command' 2j produces this:
![image](https://user-images.githubusercontent.com/36224762/37875484-74724050-3055-11e8-80d3-e8361ae7eebc.png)

![image](https://user-images.githubusercontent.com/36224762/37875481-700b6e6a-3055-11e8-9aea-6c26b2ae8a1a.png)

If this is intentional, is there any thing like a text object for lines?

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: added-dvorak-right-handed-to-keyboard-layout-layer (rev. 90440e5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript vimscript
            (rust :variables rust-format-on-save t)
            (haskell :variables haskell-enable-hindent t)
            semantic lsp
            (c-c++ :variables c-c++-enable-clang-support t)
            html python chrome
            (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
            autohotkey kotlin helm
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
            emacs-lisp
            (ibuffer :variables ibuffer-group-buffers-by 'modes)
            coq emoji
            (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
            git markdown org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-tooltips t)
            (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
            version-control osx racket clojure)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by wasamasa** [comment]
Please adhere to the bug report template. This isn't the spacemacs repository, so you play by our rules, not theirs.

**Comment by NightMachinary** [comment]
Three years later, I have found the issue (which is probably a config "bug" introduced by both Spacemacs and Doom); The operator mode mappings need to be:
```
(define-key evil-operator-state-map (kbd "j") #'evil-next-line)
(define-key evil-operator-state-map (kbd "k") #'evil-previous-line)
```
for `evil` to behave like `vim`. `evil` is awesome. :)
