### ISSUE TITLE
evil-initialize-local-keymaps is a memory hog and exacerbated by mmm-mode

### ISSUE THREAD

**Issue by aaronjensen** [emacs-evil/evil#1037]
# Issue type

- Perf bug report/Enhancement request

# Environment

Emacs version: GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin17.4.0, NS appkit-1561.20 Version 10.13.3 (Build 17D102)) of 2018-03-30
Operating System: macOS High Sierra
Evil version: Evil version evil-git-f5d47df3
Evil installation type: Melpa
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Install markdown-mode and mmm-mode
- Start Emacs
- `M-x eval-buffer` with (first fix your elpa path):

    ```elisp
    (let ((default-directory  "~/.emacs.d/elpa/27.0"))
      (normal-top-level-add-subdirs-to-load-path))
    (require 'package) ;; You might already have this line
    (let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                        (not (gnutls-available-p))))
           (url (concat (if no-ssl "http" "https") "://melpa.org/packages/")))
      (add-to-list 'package-archives (cons "melpa" url) t))
    (require 'markdown-mode)
    (require 'mmm-mode)
    (markdown-mode)
    (mmm-mode-on)
    (setq garbage-collection-messages t)
    ```

- `M-x profiler-start` select mem
- Go into insert mode and hold a letter

# Expected behavior

Few garbage collections, little memory used

# Actual behavior

Garbage collections every few characters. Megs of memory used very quickly

# Further notes

Here is a sample profile:

```
+ command-execute                                          14,493,471  48%
- redisplay_internal (C function)                           9,124,634  30%
 - jit-lock-function                                        8,956,466  30%
  - jit-lock-fontify-now                                    8,956,466  30%
   - jit-lock--run-functions                                8,951,186  30%
    - run-hook-wrapped                                      8,951,186  30%
     - #<compiled 0x46d6c171>                               8,951,186  30%
      - font-lock-fontify-region                            8,951,186  30%
       - mmm-fontify-region                                 8,951,186  30%
        - mapc                                              4,922,690  16%
         - #<compiled 0x40e78771>                           4,922,690  16%
          - mmm-fontify-region-list                         4,921,634  16%
           - mapc                                           4,921,634  16%
            - #<compiled 0x46b4a531>                        4,921,634  16%
             - mmm-set-local-variables                      3,158,772  10%
              - mapcar                                      3,153,492  10%
               - #<lambda 0x14b8d8a74>                        133,852   0%
                - if                                          133,852   0%
                 - funcall                                    133,852   0%
                  - use-local-map                             133,852   0%
                   - apply                                    133,852   0%
                    - ad-Advice-use-local-map                 133,852   0%
                     - evil-normalize-keymaps                 133,852   0%
                      - let                                   133,852   0%
                         evil-initialize-local-keymaps        120,384   0%
                       + when                                  12,412   0%
                       + dolist                                 1,056   0%
               + #<lambda 0x14b8d8a74>                        132,796   0%
               + #<lambda 0x14b8d8a74>                        132,796   0%
               + #<lambda 0x14b8d8a74>                        125,664   0%
               + #<lambda 0x14b8d8a74>                        124,608   0%
               + #<lambda 0x14b8d8a74>                        124,608   0%
               + #<lambda 0x14b8d8a74>                        124,608   0%
               + #<lambda 0x14b8d8a74>                        124,608   0%
               + #<lambda 0x14b8d8a74>                        124,608   0%
               + #<lambda 0x14b8d8a74>                        124,608   0%
```

**Comment by wasamasa** [comment]
Sorry, but this doesn't look convincing at all. The biggest jump is from the `mapcar` line and the following lambda. Fix that transition (from a measly 3M to 133K) and then we'll talk. I expected something like a memory leak of at least a hundred megabytes from that title.

**Comment by aaronjensen** [comment]
@wasamasa sorry, I didn't paste the entire thing. All of those lambdas are ALL evil-initialize-local-keymaps. The jump to 3mb is built entirely from that. There are many more lambdas below that.

**Comment by aaronjensen** [comment]
Oh, and when the default gc size is 800k, this causes a GC every 4-5 keypresses. When you have 100mb un-gc'd memory, this means a 100ms pause every 4-5 keypresses. It is noticeable. Does this help:

```
- redisplay_internal (C function)                         139,857,524  22%
 - jit-lock-function                                      114,628,221  18%
  - jit-lock-fontify-now                                  114,609,213  18%
   - jit-lock--run-functions                              114,003,949  18%
    - run-hook-wrapped                                    113,917,093  18%
     - #<compiled 0x40c59319>                             113,904,421  18%
      - font-lock-fontify-region                          113,904,421  18%
       - mmm-fontify-region                               113,904,421  18%
        - #<compiled 0x49b19fed>                          103,477,059  16%
         - mmm-set-local-variables                        103,477,059  16%
          - mapcar                                        102,734,691  16%
           - #<compiled 0x452309c1>                       102,734,691  16%
            - use-local-map                               102,730,467  16%
             - apply                                      102,730,467  16%
              - ad-Advice-use-local-map                   102,730,467  16%
               - evil-normalize-keymaps                   102,730,467  16%
                - evil-initialize-local-keymaps            97,111,963  15%
                   keymapp                                      2,849   0%
                + evil-state-keymaps                        3,657,516   0%
                  evil-minor-mode-keymap-p                    916,476   0%
                  evil-auxiliary-keymap-p                     908,288   0%
            mmm-get-saved-local-variables                     360,096   0%
        + mapc                                             10,059,522   1%
        + mmm-regions-alist                                   367,840   0%
```

That profile is with more things byte compiled so the lambdas aren't spread out.

**Comment by wasamasa** [comment]
This still looks the same. The biggest jumps stem from Smartparens and MMM. Use a less crappy multi-mode and you'll no longer experience needlessly many garbage collections.

**Comment by aaronjensen** [comment]
I apologize the title of the report was offensive. I see how it could have been.

You're saying the fact that any time anything sets a local variable evil does a whole lot of allocation isn't an evil problem? There's no way to memoize or cache what `evil-initialize-local-keymaps` does?

What would you recommend as a less crappy multi-mode?

Thanks!

**Comment by wasamasa** [comment]
The memory footprint of that operation doesn't matter because normally an interactively used buffer is initialized exactly once.  MMM does this apparently very often.  This causes lots of GCs for you and things showing up in your memory trace involve SP, MMM and Evil.  Note that `evil-initialize-local-keymaps` does already check whether it has to create a new keymap, so I don't even see how you'd do better.  Skip the whole iteration if a buffer-local variable has been set?  How much memory does an iteration even use?  You see, it's getting kind of ridiculous at this point without knowing what exactly MMM is doing here.

No idea really about what would be better than MMM.  It's a well-known fact that multi-modes are a traditional weakness of Emacs.  web-mode is the least bad I've used so far, but very specific. There's a mthml-mode on Emacs master, maybe that one will pave the way forward to more modes like web-mode.

**Comment by aaronjensen** [comment]
Ok, thanks. FWIW, it seems like the memory usage is coming from `assq`, which is called 11 times per `evil-initialize-local-keymaps` for me, which is called at least twice per command. I'll keep digging.

**Comment by wasamasa** [comment]
Looks like that part can be safely replaced with `(local-variable-p map)` instead of `(assq map (buffer-local-variables))`.

**Comment by aaronjensen** [comment]
That makes a huge difference. `evil-normalize-keymaps` is now 474k for over 600 keypresses. Thank you! Would you like a PR for that or do you want to make the change?

**Comment by aaronjensen** [comment]
It's probably not a hot path, but there's a similar change that could probably be made in `evil-save-transient-mark-mode`

**Comment by aaronjensen** [comment]
Just in case it helps: https://github.com/emacs-evil/evil/pull/1039 Thanks again.

**Comment by aaronjensen** [comment]
Makes sense, thanks.
