### ISSUE TITLE
Evil breaks when I restart emacs

### ISSUE THREAD

**Issue by yur3i** [emacs-evil/evil#1041]
- Bug 
Emacs version: 25.3.1
Operating System: Void Linux
Evil version: 1.2.13
Evil installation type: MELPA Stable
Graphical/Terminal: Terminal
Tested in a `make emacs` session: No

- Install Evil
- Exit Emacs
- Start Emacs

Should still be able to run M-x evil-mode

Can't run M-x evil-mode

my config is here:
https://github.com/yur3i/emacs-settings

**Comment by yur3i** [comment]
My init file doesn't contain any errors ; I just linked it in case you needed it for anything. the `elpa` directory does contain `evil-1.2.13` and `Mx find-library RET evil RET` does open `evil.el` and `emacs -Q` `M-x package-initialize` doesn't let me run `M-x evil-mode` either

**Comment by wasamasa** [comment]
Time to check the generated autoloads file in that directory then (should be `evil-autoloads.el`).  If it's not there or malformed, you have a borked install.

**Comment by yur3i** [comment]
Solved by just installing evil manually instead

`git clone https://github.com/emacs-evil/evil ~/.emacs.d/evil`


`(add-to-list 'load-path "~/.emacs.d/evil")`
`(require 'evil)`
`(evil-mode 1)`
