### ISSUE TITLE
error loading Cjk custom settings

### ISSUE THREAD

**Issue by abrace** [emacs-evil/evil#1046]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-12
Operating System: macOS 10.13.4
Evil version: evil-git-5fa065c
Evil installation type: manual
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
`M-x customize-group evil-cjk`

# Expected behavior
The Evil Cjk custom group and settings are displayed properly with no errors.

# Actual behavior
The error `custom-variable-value-create: Wrong type argument: symbolp, (character . character)
` occurs.
The "Evil Cjk group" has the State "UNKNOWN, you should not see this."
The only setting displayed is "Evil Cjk Emacs Word Boundary" with the state "UNINITIALIZED, you should not see this."

# Further notes
Perhaps this has to do with the `:type '((character . character))` given in the DEFCUSTOM expressions for evil-cjk-word-separating-categories and evil-cjk-word-combining-categories in evil-vars.el .

**Comment by abrace** [comment]
One possible solution would be to change the `:type` of evil-cjk-word-separating-categories to `'(alist :key-type character :value-type character)`, and the `:type` of evil-cjk-word-combining-categories to something like:
```
'(alist :key-type (choice character (const nil))
        :value-type (choice character (const nil)))
```

(If NIL is an acceptable value for evil-cjk-word-separating-categories, then the second `:type` form could be used for evil-cjk-word-separating-categories as well.

**Comment by wasamasa** [comment]
Thanks, I can reproduce this as well. I've checked the documentation and didn't find it terribly informative, but given that the default value of `word-combining-categories` uses `nil` in both position of the alist entries, your type looks good to me.
