### ISSUE TITLE
<$> goes to next line in visual mode

### ISSUE THREAD

**Issue by tsoernes** [emacs-evil/evil#1047]
- Bug report

# Environment

Emacs version: 25.3.1
Operating System: Fedora 27
Evil version: git d4017b1c
Graphical/Terminal: X

# Reproduction steps
- Start Emacs
- Make buffer
```
abc
def
```
- Set cursor on `a`
- Go into visual mode
- <$>
- evil-surround-region X

# Expected behavior
```
XabcX
def
```

# Actual behavior
```
Xabc
Xdef
```
I think the issue is that `<$>` in visual mode includes newline character. In Vim that's not the case.

**Comment by wasamasa** [comment]
Sorry, but this isn't an issue with Evil, rather evil-surround.

**Comment by tsoernes** [comment]
That's not true.
1) Go to the middle of a line
2) Visual Mode
3)  <$>
4)  <x>
Then newline character gets deleted and current line and next line become
joined. That does not happen in vim.

2018-05-06 22:49 GMT+02:00 Vasilij Schneidermann <notifications@github.com>:

**Comment by wasamasa** [comment]
I suspect this is a variation of what #1033 needs to fix where the submitter noted that you need an individual solution for each command.
