### ISSUE TITLE
evil-repeat shows "'.' is not defined" in visual line mode

### ISSUE THREAD

**Issue by TommyX12** [emacs-evil/evil#1052]
# Issue type
- Bug report

# Environment

Emacs version: 25.3.1
Operating System: ArchLinux
Evil version: 1.2.13
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs (with evil)
- Enter a few lines
- Navigate to first line, press shift-a then insert some character, then press esc to return to normal mode.
- Go to the second line and press shift-v to start visual line mode
- Select the remaining lines by navigating to last line
- Press '.'

# Expected behavior
All lines should have the same characters appended.

# Actual behavior
No change to the buffer, and minibuffer outputs "'.' is not defined".

# Notes
The expected behavior can be achieved by manually running M-x evil-repeat while in visual line mode.

**Comment by wasamasa** [comment]
Vim doesn't implement `.` in visual state either.

**Comment by noctuid** [comment]
@TommyX12 Use `:norm.` if you want to do this.

**Comment by TommyX12** [comment]
@noctuid Thanks. How would I map visual '.' to :norm .<cr> (or achieve the same) in evil / emacs?

**Comment by noctuid** [comment]
You could bind it to a keyboard macro, for example:
```elisp
(evil-define-key 'visual 'global
  "." (kbd ":norm. RET"))
```
