### ISSUE TITLE
evil-shift-left moves cursor on wrong character

### ISSUE THREAD

**Issue by vxid** [emacs-evil/evil#1053]
# Issue type

- Bug report

# Environment

Emacs version: "GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-09"
Operating System: Linux y 4.16.8-1-ARCH #1 SMP PREEMPT Wed May 9 11:25:02 UTC 2018 x86_64 GNU/Linux
Evil version: "Evil version 1.2.13"
Evil installation type: MELPA
Graphical/Terminal: GUI
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  No

# Reproduction steps
- Start Emacs
- In the scratch buffer type

```
aaa
bbb
```
- Call  `evil-shift-right` twice anywhere on the first line.
- Call `evil-shift-left` on the first line once.

# Expected behavior
```
    |aaa
bbb
```

Like in vanilla Vim (or when using `evil-shift-right`), the cursor should be in the first non-whitespace character of the indented line.

# Actual behavior
```
|    aaa
bbb
```

Cursor is on the first charcacer of the line, even though it is whitespace.

# Further notes
Tested in a blank config file only containing:

``` emacs-lisp
(add-to-list 'load-path "~/.emacs.d/elpa/evil-20180517.1300/")
(require 'evil)
(evil-mode 1)
```

**Comment by TheBB** [comment]
I think #1225 should fix this.
