### ISSUE TITLE
`<C-o>` behaviour is not consistent when used with helm-gtags-dwim

### ISSUE THREAD

**Issue by vmandela** [emacs-evil/evil#1054]
# Issue type
- Bug report

# Environment

Emacs version: 26.1
Operating System: Ubuntu 16.04
Evil version: evil-git-c7a103a772d8
Evil installation type: Spacemacs
Graphical/Terminal: under X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps

- Start Emacs
- Open a C source file. I am assuming that gtags has been run in the project root directory.
- Place the cursor on a function call and invoke `helm-gtags-dwim`
- On reaching the implementation of the function, run `<C-o>`.

# Expected behavior

The expectation is that <C-o> returns the editor to the location from which the `helm-gtags-dwim` call is invoked.

# Actual behavior

- Sometimes the editor returns to the location(file & line) from which `helm-gtags-dwim` call is invoked.
- Sometimes the editor jumps to the start of the file from which `helm-gtags-dwim` call is invoked.

# Further notes

- Reproducing this issue requires helm, projectile and helm-gtags in addition to evil.

**Comment by edkolev** [comment]
> On reaching the implementation of the function, run .

I'm assuming you mean "run C-o".

If that's the case - evil doesn't know whether your last command was a jump or not.

This is what I use to tell evil specific commands are jumps, I'm not sure if it's the cleanest solution.

```elisp
(defmacro jump! (fun)
  "Register the given function as an evil jump"
  (let ((advice (intern (concat "evgeni-evil-jump-advice--" (symbol-name fun)))))
    `(progn
       (defun ,advice (&rest args)
         (evil-set-jump))

       (advice-add (quote ,fun) :before (quote ,advice)))))

;;; then:

  (jump! counsel-imenu)
```

I don't think there's a generic way to make evil aware of what is a jump and what isn't.

**Comment by vmandela** [comment]
@edkolev Thank you. This seems to be working for me. Why not make this into a PR ?

**Comment by TheBB** [comment]
@edkolev Unless I'm misunderstanding something, shouldn't this work?

```elisp
(evil-set-command-property 'consel-imenu :jump t)
```

**Comment by noctuid** [comment]
The `:jump` evil command property is the way to make evil aware of what is a jump. The only case where you should need to use advice is if you wanted to conditionally add to the jump list (e.g. only if the old position is a certain distance from the new one).

**Comment by vmandela** [comment]
I tested both the options again separately.

1.  `(jump! helm-gtags-dwim)`
2.  `(evil-set-command-property 'helm-gtags-dwim :jump t)`

Both are showing the same inconsistent behaviour. If I run `evil-show-jumps`, there are unexpected references to the beginning of visited files in addition to the lines visited.

is there a way to log message when the jump list is updated?

**Comment by TheBB** [comment]
You could advise `evil-set-jump` I suppose.

**Comment by edkolev** [comment]
> Unless I'm misunderstanding something, shouldn't this work?
> 
> (evil-set-command-property 'consel-imenu :jump t)

Yes, this is much cleaner, thanks!
