### ISSUE TITLE
`ct;` on a line with semicolons and colons will change up till the colon as well

### ISSUE THREAD

**Issue by ar1a** [emacs-evil/evil#1056]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-29
Operating System: Arch linux
Evil version: 1.2.13
Evil installation: MELPA
Graphical/Terminal: graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Insert text "foo: bar;"
- Go to start of line
- press ct;

# Expected behavior
Should delete all up to the semicolon and put into insert mode

# Actual behavior
Deletes up to the colon and put into insert mode

# Further notes

**Comment by ninrod** [comment]
can't reproduce.

**Comment by ar1a** [comment]
ah, yeah i can't either. must be an issue with my config, will post it upstream https://github.com/hlissner/doom-emacs/tree/develop

**Comment by ar1a** [comment]
yep, it was - https://github.com/hlissner/doom-emacs/blob/7a61615666573587bb77b3b4ab48cd6096eaa918/modules/feature/evil/config.el#L345

`[9:36 AM] Henrik: I set up an evil-snipe alias for : to jump to both : and ;. Mostly just a leftover default I forgot to move to my private config, haha.
`
