### ISSUE TITLE
Moving to the next/previous matched regexp term

### ISSUE THREAD

**Issue by pera** [emacs-evil/evil#1057]
# Issue type

- Bug report

# Environment

Emacs version: 26.1
Operating System: Arch Linux
Evil version: 1.2.13
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Enter a few words
- Search for words (i.e `/\w+`)
- Press <kbd>n</kbd>

# Expected behavior
Go to the next match

# Actual behavior
It goes to the next matching character

**Comment by edkolev** [comment]
Emacs and vim have different regex engines. It would be impractical for evil to re-implement regex to make it identical to vim's.

With that said, there's a way to get most common (such as `\d` and `\w`) vim style regexes into evil's search. Please see this variable's documentation:

```
evil-ex-search-vim-style-regexp is a variable defined in ‘evil-vars.el’.
Its value is nil

Documentation:
If non-nil Vim-style backslash codes are supported in search patterns.
See ‘evil-transform-vim-style-regexp’ for the supported backslash
codes.  Note that this only affects the search command if
‘evil-search-module’ is set to ’evil-search. The isearch module
always uses plain Emacs regular expressions.
```

End then:

```
evil-transform-vim-style-regexp is a compiled Lisp function in
‘evil-common.el’.

(evil-transform-vim-style-regexp REGEXP)

Transforms vim-style backslash codes to Emacs regexp.
This includes the backslash codes \d, \D, \s, \S, \x, \X,
\o, \O, \a, \A, \l, \L, \u, \U and \w, \W. The new
codes \y and \Y can be used instead of the Emacs code \s and
\S which have a different meaning in Vim-style.
```

Make sure `evil-search-module` is set to `evil-search` before loading evil.

Hope that helps!

**Comment by pera** [comment]
@edkolev thanks so much for your response, but I'm still unable to use <kbd>n</kbd> to go to the next match (it seems like Evil is trying just `\w` instead of `\w+`). This is how my init file looks like now:

```elisp
(setq evil-search-module 'evil-search
      evil-ex-search-vim-style-regexp t)
(require 'evil)
(evil-mode 1)
;; (evil-select-search-module 'evil-search-module 'evil-search)
```

What I find strange is that <kbd>C-M-s</kbd> (`isearch-forward-regexp`) does exactly what I expect <kbd>n</kbd> to do. Also, when I introduce the regexp, the highlighting indicates that `\w+` is recognized correctly (i.e. it matches the whole word, not just one character).

**Comment by edkolev** [comment]
It works as I expect it to on my side. For example:
- with text `hello` in a buffer (point on `h`)
- I search for `\w+`, point goes go `e` (because "ello" satisfies "\w+")
- I press `n`, point goes to first `l` (because "llo" satisfies "\w+)

This is how vim works as well.

@pera Is this what you're observing or is it something completely different? If it's different, please try to reproduce with a bare evil setup (clone this repo, then run `make emacs`).

**Comment by pera** [comment]
@edkolev yes, but this is not how Vim works (or at least not by default): if one searches for `\w\+` on a buffer with the text "hello", only one match will be produced, so then pressing <kbd>n</kbd> in normal mode will move the point/cursor to the beginning of the matched term (in this case "h"), and if one hits <kbd>n</kbd> again it will stay in the same place (i.e. over the "h").

Another example: a buffer with text "this is a test". If one searches for `\w\+`, pressing <kbd>n</kbd> (and <kbd>N</kbd>) will move the cursor to the beginning of each word, so if I hit <kbd>^</kbd> and then <kbd>n</kbd>, the cursor will move to the beginning of the word "is", and pressing <kbd>2n</kbd> will move it to the beginning of the word "test".

Thanks again.

**Comment by justbur** [comment]
The way this works now is essentially how @edkolev described it. Basically, evil treats the rest of the buffer starting from the cursor as the text to search, so if you are on the e of hello, llo will be the first string to match `\w+`. I see that isearch does something different here, but isearch is pretty complicated, so it would take some time to figure out how that happens. 

I think both behaviors make sense from different perspectives, but I also agree that vim's behavior is not being replicated here.

**Comment by quicknir** [comment]
Just chiming in as I encountered this: I understand the logic of how this works as given by @edkolev and @justbur, but I fail to see how this could be considered "expected" or even making sense. Neither emacs, nor vim, nor any other editor with similar functionality I've ever used, handles it this way, so I'm genuinely puzzled at how this was expected. And while it may make sense considered from a low level, implementation-aware viewpoint, it doesn't really make any sense for the end user in the vast majority of cases; the whole point of `n` is to move through matches and operate match by match (which is probably why no editor does it this way).

So I think it's inarguably a bug, whether you looking at it in terms of mimicking vim, or usability. The question is, how hard it actually is to fix? `n` would need to be aware of where the current match ends, not just where it starts, and just begin the search from there. This might be very easy, it might be a little less so, but hopefully not too bad?

**Comment by bpic** [comment]
It should be noted that the behavior also occurs with simple searches and not only with regex classes.
If you have the text "aaaaa" and search with "/a+", the cursor goes to the second 'a', and "gn" only visually selects the second 'a', when it would be expected to select the whole sequence.

**Comment by bpic** [comment]
Interestingly enough, `2/` and `2n` have the behavior that I would expect from `/` and `n`.  However `2/` has a very different behavior from `/` then `/` (and the same goes with `n`).
Example: Buffer is:
`abcdef ghij`

The cursor is on a.
`2/\w+` -> the cursor goes to g (behavior of `/\w\+` in VIM), `n` -> the cursor goes to h, `2n` -> the cursor goes to a
The cursor is on a.
`/\w+` -> the cursor goes to b, `/\w+` -> the cursor goes to c, `2n` -> the cursor goes to g
