### ISSUE TITLE
`Symbol’s function definition is void: evil-copy-to-end-of-line` after I hit "Y"

### ISSUE THREAD

**Issue by mrbig033** [emacs-evil/evil#1060]
# Issue type
- Bug report

# Environment

* Emacs version: GNU Emacs 26.1.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2018-05-29
* Operating System: MX-LINUX 17
* Evil version:  Evil version 1.2.13
* Evil installation type: MELPA
* Graphical/Terminal: Graphical
* Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  Yes.
* [complete environment](https://gist.github.com/mrbig033/63fd7f4f51b6a8ae379abae74c52aff2)

# Reproduction steps
- Start Emacs
- Open an elisp buffer
- Type `Y`

# Expected behavior
- Evil should copy till the end of the sentence

# Actual behavior
- No characters are copied, and the follow message is displayed:
`Wrong type argument: commandp, evil-copy-to-end-of-line`
- And on the \*\*Messages\*\* buffer:
`help-fns--analyze-function: Symbol’s function definition is void: evil-copy-to-end-of-line`

**NOTE**: the command `evil-copy-to-end-of-line` doesn't show up on `M-x`, nor in `C-h f`, `C-h F`, `C-h v` or `C-h a`.

**Comment by justbur** [comment]
That function is not defined in evil, at least not in the current master.

**Comment by mrbig033** [comment]
Okay, I understand, but why is it bound to Y then?

**Comment by justbur** [comment]
You must have done it on your own or through another package

**Comment by mrbig033** [comment]
I really didn't change this binding, but I do have other packages that might be interfering. Do you any suggestions on how I could find that out?

**Comment by justbur** [comment]
I could look at your config file, but the link you have doesn't seem to work. I haven't seen that function before

**Comment by mrbig033** [comment]
I'm really sorry, I changed from .emacs to init.el and forgot to update the gist. Here you go:
[init.el](https://gitlab.com/mrbig/dotfiles/blob/master/emacs/emacs.d/init.el)
[.emacs.d](https://gitlab.com/mrbig/dotfiles/tree/master/emacs/emacs.d)

Any help is appreciated

**Comment by justbur** [comment]
The binding is in your init.el on line 546, but there's no corresponding function definition. 

Evil has built-in support for this through `evil-want-Y-yank-to-eol`

**Comment by mrbig033** [comment]
Ah, okay, thank you very much! Have a good day.
