### ISSUE TITLE
]' (jump to next line with a lowercase mark) is undefined

### ISSUE THREAD

**Issue by unhammer** [emacs-evil/evil#1067]
# Issue type
vim compatibility

- Enhancement request

# Environment

Emacs version: 25.3.2
Operating System: Xubuntu 18.04
Evil version: 1.2.13  (package says 20180307.109)
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- `make emacs`
- say `n` to run tests
- `G` to go to end of buffer, then add a mark with `ma`
- `gg` and from the top of the buffer do `]'` to go to the first lowercase mark

# Expected behavior
evil should move to the first lowercase mark (ie. the second line)

# Actual behavior
emacs says `] ' is undefined`

# Further notes
works in vim 8
http://vim.wikia.com/wiki/Using_marks

**Comment by axelf4** [comment]
Fixed by #1364.
