### ISSUE TITLE
Incorrect operator shortcut keys when SPC used as prefix

### ISSUE THREAD

**Issue by noctuid** [emacs-evil/evil#1073]
# Issue type
- Bug report

# Reproduction steps
Bind `SPC <key>` to an operator and attempt to use the operator linewise with `SPC <key> <key>`

# Expected behavior
Operator should act on line.

# Actual behavior
`<key>` and `SPC <key>` are not bound correctly in `evil-operator-shortcut-map`. This is because `evil-extract-count` in  `evil-operator-range` returns `SPC` as the seq instead of `SPC <key>`, so `SPC` is bound to `evil-line` instead of the expected `SPC <key>` and `<key>`. I haven't looked further into the issue in `evil-extract-count`.

# Further notes
I couldn't find any other issues like this by searching but apologize if it is a duplicate.

Originally reported in noctuid/general.el#124
@aqua36 Follow this issue for updates.

**Comment by aaronjensen** [comment]
This fix broke evil-surround as it relied on the second argument to `evil-operator-range`. Was that change essential to this fix?
