### ISSUE TITLE
Auto insert `h` when I switch from insert to normal 

### ISSUE THREAD

**Issue by FirstLoveLife** [emacs-evil/evil#1075]
# Issue type Bug report

# Environment

Emacs version: GNU Emacs 26.1
Operating System: Arch
Evil version: 1.2.13
Evil installation type: Melpa
Graphical/Terminal: Both
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs

Here is the text in insert mode and `|` is the cursor:
> whic`|`h

When I type <kbd>ESC</kbd> or / <kbd>C-[</kbd>, It now turns to normal as expected, 

# Expected behavior
> whi`|c|`h

# Actual behavior
> whic`|h|`h

# Further notes

Yes, one more redundant `h` occur!

**Comment by VanLaser** [comment]
I also have emacs 26.1 on Arch Linux, and can't reproduce.

**Comment by edkolev** [comment]
For sure this is something in your setup. When you fix it (I would suggest a binary search in your init file), please share what it was in case others run into something similar.

**Comment by FirstLoveLife** [comment]
I know the reason now. I have one abbrev:J ("whic" "which" nil 0). Thus once normal state `whic`, it will be expanded into `which`, the last `h` is redundant
