### ISSUE TITLE
Move cursor to its last position

### ISSUE THREAD

**Issue by yuanlai** [emacs-evil/evil#1076]
# Issue type
- Bug report

# Environment

Emacs version: 26.1
Operating System: macOS
Evil version: latest version
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- create four test line, the cursor locate at line 1

```
line |1|    <- cursor position
line 2
line 3
line 4
```

- typo `3j`

```
line 1
line 2
line 3
line |4|    <-cursor position
```

- typo `''` or ` `` ` or `C-o`

# Expected behavior

Expecting cursor position return to `line |1|`.

# Actual behavior

Unknown position related position ring.

**Comment by edkolev** [comment]
I don't think `3j` is considered a jump. Quote from vim's jump-motions:

```
8. Jumps                                        jump-motions

A "jump" is one of the following commands: "'", "`", "G", "/", "?", "n",
"N", "%", "(", ")", "[[", "]]", "{", "}", ":s", ":tag", "L", "M", "H" and
the commands that start editing a new file.
```
