### ISSUE TITLE
Proper way of callin `evil-execute-macro` inside other interactive function.

### ISSUE THREAD

**Issue by ChoppinBlockParty** [emacs-evil/evil#1083]
I have a keybinding in my vim that repeats a last command.

                                                            *@:*
    @:			Repeat last command-line [count] times.
                            {not available when compiled without the
                            |+cmdline_hist| feature}

I am trying to call `evil-execute-macro` inside my interactive function like this

    (define-key evil-normal-state-map (kbd "SPC r")
      (lambda (count)
        (interactive
          (let (count)
              (setq count (if current-prefix-arg
                              (if (numberp current-prefix-arg)
                                  current-prefix-arg
                              0) 1))
            (list count)))
        (evil-execute-macro count ?:)
      )
    )

to emulate this behavior but I cannot. It say always about 'No previous macro', though when I manually hit `@:` it works. Apparently, I am doing something wrong, could you suggest, please?

**Comment by noctuid** [comment]
You can just bind `SPC r` to `evil-ex-repeat`. If `evil-ex-repeat` didn't exist, you could bind it to `"@:"` (which will run as a keyboard macro basically). Bound keyboard macros are automatically run with current prefix argument (though it's not always the same as running the command with that prefix argument; you can use something besides a keyboard macro in these cases).

**Comment by ChoppinBlockParty** [comment]
I need a similar function to run my macros from a predefined name, as well, so this example is not only bounded to a last command.

**Comment by noctuid** [comment]
Your example doesn't use a named command. It's not exactly clear what you want to do. Do you specifically want to run a macro stored in a register? Or was that just for this example? You can store a string in a variable if you want a name. You might also want to look at `general-simulate-key`. If you provide more details a out what you want to do, I can probably help more.

**Comment by noctuid** [comment]
Is there a reason you wouldn't want or be able to bind `SPC e` to `"@a"`? I think that would be the simplest way to do it.

**Comment by noctuid** [comment]
What I'm saying is that you can just do `(evil-define-key... (kbd "SPC e") "@a")`

**Comment by ChoppinBlockParty** [comment]
I found a way to do it, this way

    (evil-define-key 'normal 'global (kbd "SPC r") 'evil-ex-repeat)
    ;;; The code is almost a copy-paste from `evil-execute-macro
    (define-key evil-normal-state-map (kbd "SPC e")
      (lambda (count)
        (interactive
          (let (count)
              (setq count (if current-prefix-arg
                              (if (numberp current-prefix-arg)
                                  current-prefix-arg
                              0) 1)
              )
            (list count)))
        (let ((macro (evil-get-register ?a t)))
          (cond
            ((or (and (not (stringp macro))
                  (not (vectorp macro)))
                  (member macro '("" [])))
               (user-error "No previous macro"))
            (t (condition-case err
                 (evil-with-single-undo
                   (execute-kbd-macro macro count))
                 (error
                  (evil-normal-state)
                  (evil-normalize-keymaps)
                  (signal (car err) (cdr err)))
                 ))
          ))
        )
      )
