### ISSUE TITLE
Jumping to the end of a match in a search?

### ISSUE THREAD

**Issue by JulianKniephoff** [emacs-evil/evil#1084]
# Issue type

- Question

# Environment

Emacs version: GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian
Operating System: Ubuntu 18.04
Evil version: Evil version evil-git-a2b3838
Evil installation type: 
Graphical/Terminal: Both
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Enter insert mode
- Enter some text, like `foo bar baz`
- Leave insert mode
- Go back to the start of the line
- Optionally enable evil-search: `M-S-:` `(setq evil-search-module 'evil-search)`
- Search `/bar/e` and hit enter

# Expected behavior
The cursor should jump to the end of `bar`.

# Actual behavior
The cursor lands on the start of `bar` and you get the message that their is no match.

# Further notes
So in vim you can jump to the end of the match of a search by ending your search with `/e`. Does this work in `evil`, too? #692 somehow suggests that it **did** work at least at some point in the past, but I couldn't reproduce it. :thinking:

**Comment by TheBB** [comment]
My guess is that you are using the `isearch` search module. This should work with `evil-search`. The latter is closer to vim functionality but the former is better integrated with Emacs.

**Comment by JulianKniephoff** [comment]
So I would do `(setq evil-search-module 'evil-search)`, yes? I tried that, too, (and forgot to add it to the repro steps) and got the same result. I will add it to the description above.

So is this actually a bug? Or am I still doing something wrong?

**Comment by JulianKniephoff** [comment]
Cool, that worked! Except the function seems to be called evil-**select**-search-module.

Thanks for the quick and helpful replies! :smile:
