### ISSUE TITLE
Make paren highlighting consistent with evil-move-cursor-back

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#109]
Originally reported by: **dnquark (Bitbucket: [dnquark](https://bitbucket.org/dnquark), GitHub: Unknown)**

----------------------------------------

The paren highlighting behavior is different in insert and normal states: in normal state, it occurs when the cursor is on the closing paren, and in insert/emacs states it occurs when the cursor is right after the closing paren, as is standard Emacs behavior.

When evil-move-cursor-back is set to t, this makes sense since the highlighting of a parentheses pair persists through the state change.  However, when one sets
    
    (setq evil-move-cursor-back nil)
    
(e.g. to get familiar Emacs behavior when cursor is at the end of line) this leads to inconsistent paren highlighting / conflicting visual feedback as one switches between insert and normal modes.  For instance, the backward/forward-sexp commands should take one from the opening to the closing (and vice versa) highlighted paren regardless of the mode.  

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/109

**Comment by wasamasa** [comment]
Closing because a fix has been implemented.
