### ISSUE TITLE
Substitutions using * are broken

### ISSUE THREAD

**Issue by neildurant** [emacs-evil/evil#1092]
# Issue type

- Bug report

# Environment

Emacs version: 26.1
Operating System: Windows 10
Evil version: 6fde982d731e2cc4e5f6bded6f8955ab2daee3b7
Evil installation type: ELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Open scratch buffer
- Enter the following text:
```
111222
111333
```
- Move the cursor to the first line and do this substitution: `:s/2*/x/`

# Expected behavior
The result should be:
```
111x
111333
```

# Actual behavior
The substitution has been applied incorrectly on the first line, and the second line has also been modified:
```
x111222
x111333
```

# Further notes

**Comment by TheBB** [comment]
1. I can't confirm that your expected behaviour is the actual behaviour in vim.
2. Are you sure the regex shouldn't be `2+`? With that I get your expected result.
3.  `2*` matches zero or more instances of the digit `2`, and the first match of this regexp on both lines is the empty string at the start. It seems reasonable then that you get what you get.

**Comment by neildurant** [comment]
Ah yes, you're right about the zero or more matches - it would indeed match at the start, my mistake.

However, I'm still seeing that substitution happen on the second line, which definitely doesn't seem right, since it's a single-line substitution.

**Comment by TheBB** [comment]
Yeah, I agree with that.

**Comment by dieggsy** [comment]
I can reproduce this - agree that the second line should be untouched. Weirdly, the substitution overlay only shows the first line changing, but on pressing RET to accept the substitution the second line is also changed.
