### ISSUE TITLE
Ex considers a `C-u` as initial input

### ISSUE THREAD

**Issue by dzop** [emacs-evil/evil#1095]
# Issue type

- Bug

# Environment

Emacs version: GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.5.0, Carbon Version 158 AppKit 1561.4) of 2018-06-17
Operating System: macOS Sierra
Evil version: evil-git-3d9f76
Evil installation type: El-get
Graphical/Terminal: GUI
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs, enable evil
- Type `C-u:`

# Expected behavior
Ex does not consider the `C-u` prefix as initial input.

# Actual behavior
Ex will have as input `.,.+3` before the user types anything.

# Further notes
The reason for this behavior is because `evil-ex` uses the `prefix-numeric-value` of the `current-prefix-arg` when it is non-nil, and in the case of a `C-u` prefix, the `prefix-numeric-value` will be 4. It seems quite arbitrary to consider a `C-u` prefix to mean the 4 lines after point including the one containing point. Also `C-u` prefixes are unique to Emacs so it really doesn't look like `evil-ex` should consider them. I'm wondering if there is any reasoning for this behavior?

**Comment by TheBB** [comment]
`C-u` prefixes aren't unique to Emacs. Evil's numeric arguments are just the same thing. So `C-u :` is the same as saying `4 :`. So this isn't a bug, it's expected behaviour.
