### ISSUE TITLE
Increment number

### ISSUE THREAD

**Issue by sidhartharya10** [emacs-evil/evil#1100]
# Suggestion
- Enhancement request

# Environment

Emacs version: Remacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-10-22
Operating System: Linux Arya 4.14.65-gentoo #3 SMP Tue Oct 16 18:17:37 IST 2018 x86_64 Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz GenuineIntel GNU/Linux

Evil version: evil-git-0d5720c
Evil installation type: manual
Graphical/Terminal: Graphical X

# Content

I would love to see more vim features in evil mode emacs like incrementing and decrementing numbers in evil with "C-a" and "C-x" in normal mode. I can contribute the code for this feature as well.

**Comment by VanLaser** [comment]
This plugin works: https://github.com/cofi/evil-numbers

**Comment by sidhartharya10** [comment]
Okay Thanks :+1:

**Comment by dieggsy** [comment]
I also have a fork of it with some fixes: https://github.com/dieggsy/evil-numbers

**Comment by noctuid** [comment]
The original package is dead with various useful open PRs; I've been using @dieggsy's  fork. :+1: for it.

**Comment by ideasman42** [comment]
This fork is now maintained (used by Melpa for e.g.): https://github.com/juliapath/evil-numbers
