### ISSUE TITLE
Emacs may hang when invisible text searching is disabled. 

### ISSUE THREAD

**Issue by justintaft** [emacs-evil/evil#1101]
# Issue type
- Bug report

# Environment

Emacs version: GNU Emacs 26.1 (build 1, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G1314)) of 2018-04-17
Operating System: macOS Sierra
Evil version: Evil version evil-git-6fde982
Evil installation type: melpa
Graphical/Terminal: graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
-  Set 1st line of scratch buffer to `* header`, followed by 100 lines that read `test`. Keystrokes:  `I* hello<CR><esc>100itest<CR><esc>`
- Enable outline-mode.  Keystrokes :  `m-x outline-mode`
- Fold all content. Keystrokes: `C-c C-c`
- Set search-invisible to nil. Keystrokes: `m-x set-variable<CR>search-invisible<CR>nil<CR>`
- Search for `test`, and notice how Emacs hangs. Keystrokes:  `/test`

# Expected behavior
User should be notified no matches were found.

# Actual behavior
Emacs hangs. Must use ctrl-g ctrl-g to cancel search.

# Further notes

**Comment by justintaft** [comment]
It appears `evil-search-function` may be involved. https://github.com/Bogdanp/evil/blob/master/evil-search.el#L176 . While debugging, commenting out the when  expression on line 194 prevents the hang.

**Comment by TheBB** [comment]
Yep, I can reproduce this.

**Comment by TheBB** [comment]
Here's a backtrace I got.

    Debugger entered--returning value: (7)
      isearch-unread(7)
      isearch-search()
      isearch-search-and-update()
      isearch-process-search-string("e" "e")
      isearch-process-search-char(101 1)
      isearch-printing-char(101 1)
      funcall-interactively(isearch-printing-char 101 1)
      call-interactively(isearch-printing-char nil nil)
      command-execute(isearch-printing-char)
      recursive-edit()
      isearch-mode(t t nil t)
      isearch-forward(t)
      evil-search-incrementally(t t)
      evil-search-forward()
      funcall-interactively(evil-search-forward)
      call-interactively(evil-search-forward nil nil)
      command-execute(evil-search-forward)

The hang doesn't originate in our own search function, but it is caused by somehow it because it's not reproducible with basic isearch. It's also not reproducible with evil's own search module.

**Comment by justintaft** [comment]
Hm, so it appears to be stuck within this while loop

https://github.com/emacs-mirror/emacs/blob/master/lisp/isearch.el#L2917-L2927

The go-to char statement may be causing the infinite to occur somehow... https://github.com/Bogdanp/evil/blob/master/evil-search.el#L195

**Comment by justintaft** [comment]
It appears the loop which is continually executed is here

https://github.com/emacs-mirror/emacs/blob/master/lisp/isearch.el#L2917-L2927

It also appears the combination of  `goto-char` and `search-fun` prevents the loop from terminating. 
https://github.com/emacs-evil/evil/blob/master/evil-search.el#L195-L199

If the result is `nil`, then goto-char moves the cursor to the beginning of the buffer.  As `search-fun` returns hidden content, the lambda returned by `evil-search-function` will return a result, which will be ignored by while loop. Since the cursor is at the beginning of the buffer, the whole process repeats again.

**Comment by TheBB** [comment]
Should have been fixed.
