### ISSUE TITLE
Implement regex option for :sort

### ISSUE THREAD

**Issue by wberrier** [emacs-evil/evil#1102]
# Issue type
- Enhancement request

# Environment

Emacs version: 26.1
Operating System: Fedora 29 x86_64
Evil version: 1.2.13
Evil installation type: MELPA
Graphical/Terminal: Terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Enter some text:

```
yIgnore Sort3
zIgnore Sort2
Ignore Sort1
```
- Sort lines with sort regex (begin sorting with the character after the regex match, space in this case): `:sort / /`

# Expected behavior

Lines should be sorted by the second word on each line (ie: can be used to sort a list of names sorted by last name even though they are in "First Last" format)

```
Ignore Sort1
zIgnore Sort2
yIgnore Sort3
```

# Actual behavior

Minibuffer says: "Unsupported sort option: /"

and lines are not altered.

# Further notes

**Comment by dzop** [comment]
There is an open pull request, #1065, that implements sorting by pattern. Maybe that will work out for you.
