### ISSUE TITLE
defcustom not working properly

### ISSUE THREAD

**Issue by Silex** [emacs-evil/evil#1104]
# Issue type

- Bug report

# Environment

Emacs version: 26.1
Operating System: Ubuntu 18.04
Evil version: 1.2.13
Evil installation type: MELPA
Graphical/Terminal: X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): no, with `emacs -Q`

# Reproduction steps

``` emacs-lisp
(use-package dired-x
  :bind ("C-d" . dired-jump))

(use-package evil
  :ensure t
  :custom
  (evil-want-C-d-scroll nil)
  (evil-want-C-i-scroll nil)
  (evil-want-Y-yank-to-eol t)
  (evil-default-cursor '(t "white"))
  (evil-magic 'very-magic)
  (evil-shift-width 2)
  :config
  (evil-mode)
  (setq evil-emacs-state-modes (append evil-emacs-state-modes '(docker-container-mode docker-image-mode docker-volume-mode docker-network-mode docker-machine-mode))))

```

# Expected behavior

Pressing `C-d` calls `dired-jump`.

# Actual behavior

Pressing `C-d` calls `evil-scroll-down`.

# Further notes

It's very weird:

- The variables are set properly (`C-h v` show the correct values).
- The customization of `evil-want-Y-yank-to-eol` makes it work properly.
- If I evaluate the use-package form a second time, then everything works as expected (wtf?).
- Disabling then re-enabling `evil-mode` does not fix it, only the re-evaluation of the form does (wtf2).

**Comment by TheBB** [comment]
Thanks. Can you try with #1105 please.

**Comment by Silex** [comment]
:+1: #1105 fixes it
