### ISSUE TITLE
Unexpected behavior when using I to insert from visual block mode

### ISSUE THREAD

**Issue by diamond-lizard** [emacs-evil/evil#1110]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu) of 2018-10-09
Operating System: Gentoo Linux
Evil version: evil-git-99bcf8c
Evil installation type: manual
Graphical/Terminal: terminal
Tested in a make emacs session (see CONTRIBUTING.md): Yes

# Reproduction steps
1 - Start Emacs with `make emacs`
2 - delete the scratch buffer with: `dgg`
3 - insert 6 lines with `i` followed by `<RET>` 6 times
4 - Type: `<ESC>gg<C-v>GIX<ESC>`

# Expected behavior
I expect to see an `X` on each of the six lines.

# Actual behavior
Only the first line has an `X`

# Further notes

**Comment by TheBB** [comment]
I can't reproduce this.

**Comment by TheBB** [comment]
Same evil, but Emacs 27.

**Comment by CeleritasCelery** [comment]
I can reproduce this with 

GNU Emacs 26.1 (build 1, x86_64-suse-linux-gnu, GTK+ Version 2.18.6) of 2018-06-06

**Comment by Kuresov** [comment]
I have the same issue, though it's intermittent- if I disable and re-enable `evil-mode` the problem goes away for a few minutes. Not 100% on what it is I'm doing to cause this behavior- I'll try to keep note and update here if I can figure it out.

GNU Emacs 26.2, evil from Melpa (so, commit 297b8f).

**Comment by omidmnz** [comment]
I can reproduce this on Evil `a7ffa73` and both Emacs `29.2` and  `30.0.50` (master from 2024-03-22). The behavior is exactly as described in the issue with 6 empty lines. But with non-empty lines (for example 6 lines containing the word "test") after trying to go back to normal state, the cursor jumps to the next instance, and pressing Esc again only prepends that line with the entered character, refusing to switch to normal state. (@diamond-lizard can you reproduce the behavior I'm describing with non-empty lines? Trying to make sure we're all talking about the same issue.)

One noteworthy detail is that my modeline shows a MACRO (as in `kmacro.el` Macro) being recorded after pressing Esc the first time.

**Comment by tomdl89** [comment]
@omidmnz (and anyone else still following!) You'll see from the above noise I've attempted a fix. It's in master so please check if it works for you.

**Comment by omidmnz** [comment]
Works for me on Emacs 29.3, but not on Emacs 30+. However it's fine since Emacs 30+ is alpha software and not supported. Thank you for the fix.

**Comment by tomdl89** [comment]
Thanks for the feedback @omidmnz . The CI runs the test against emacs snapshot, i.e. version 30, and those do pass, so I would be interested in repro steps for it not working for you in 30.

**Comment by omidmnz** [comment]
@tomdl89 I finally got to bisect my configuration, and found the culprit: `flyspell-prog-mode`.

I can reproduce this on latest git Emacs (run with `emacs --init-directory=~/tmp`, where `~/tmp` is an empty directory) and the following configuration run in the scratch buffer (which installs Evil 1.15.0):
```emacs-lisp
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)

(use-package evil
  :ensure t
  :config (evil-mode 1))
```

After evaluating this, everything works as expected. However, the issue can be reproduced after `M-x flyspell-prog-mode`, and weirdly, even if `flyspell-prog-mode` is disabled afterwards!

I can also reproduce using latest git Emacs and latest Evil from git (https://github.com/emacs-evil/evil/commit/76667a1a46d896d673f51f7f5782125d06b3a022).
