### ISSUE TITLE
Disable relative line number motions, but not prefix numbers altogether

### ISSUE THREAD

**Issue by mrbig033** [emacs-evil/evil#1113]
#### Runtime Environment

- MX Linux 17
- GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
of 2018-11-28
- Evil version 1.2.13
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)

# Issue type

- Question

# Reproduction steps
- Start Emacs
- Eval `(define-key evil-normal-state-map (kbd "8j") nil)`

# Expected behavior

`8j` should be disabled, but not `8`.

# Actual behavior

I cannot use `8` as a prefix argument.

# Further notes

I know about [General](https://github.com/noctuid/general.el#mapping-under-non-prefix-keys), but I'd rather avoid the timeout if possible. My reason to disable these motions is forcing me to use [Vertigo](https://github.com/noctuid/vertigo.el) instead.

**Comment by edkolev** [comment]
Without me being an expert at bindings, I'm confident this isn't possible with the way emacs bindings work.

**Comment by TheBB** [comment]
Yes, this is not how prefix arguments work. There aren't explicit bindings for each number (luckily, there being an infinite amount of them), so they can't be individually disabled.

Better is to advise evil-forward-line to do nothing in the situations you are interested in, or bind j to a new function that behaves the way you want.
