### ISSUE TITLE
buffer list for each split

### ISSUE THREAD

**Issue by sei40kr** [emacs-evil/evil#1114]
# Issue type

- Enhancement request

# Reproduction steps

- Start Emacs
- Open a file
- Split the window
- Focus the other split and open another file there
- Delete the buffer created above step

# Expected behavior

The split disappears when the last buffer in the split is deleted.

# Actual behavior

The split remains.

# Further notes

**Comment by axelf4** [comment]
I believe this is outside the domain of Evil (it simply cannot be done in a non-hacky general way, since existing code relies on the previous buffer list of a fresh buffer being empty), but here is what I am using in my init file to get the expected behavior:

```elisp
;; Inherit split window's previous buffers
(let ((f (lambda (fun &rest args)
           (let ((prev-buffers (copy-sequence (window-prev-buffers))))
             (apply fun args)
             (set-window-prev-buffers nil prev-buffers)))))
  (advice-add #'evil-window-split :around f)
  (advice-add #'evil-window-vsplit :around f))
```
