### ISSUE TITLE
evil-set-initial-state doesn't seem to work for org-capture-mode

### ISSUE THREAD

**Issue by kshenoy** [emacs-evil/evil#1115]
# Issue type

- Bug report

# Environment

Emacs version: 25.2.1
Operating System: Ubuntu Budgie 18.04
Evil version: 1.2.13
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Add the following to the scratch buffer and evaluate it
````
(evil-set-initial-state 'org-capture-mode 'insert)
(setq org-capture-templates
      '(("t" "Test" entry (file "/tmp/test.org") "* %?")))

````
- Call `org-capture RET t`

# Expected behavior
We should be in insert mode

# Actual behavior
We seem to be in normal mode

# Further notes
This seems to be an old issue as seen by this SO response: https://stackoverflow.com/a/17310180/734153

**Comment by TheBB** [comment]
`evil-set-initial-state` only works for major modes, and `org-capture-mode` is a minor mode. The other answer in that stackoverflow link works for me. Did you try it?

    (add-hook 'org-capture-mode-hook 'evil-insert-state)

**Comment by kshenoy** [comment]
Thanks for the explanation. Yes, the other answer works for me but I was curious as to why it didn't seem to work in this particular case. I wasn't aware that `evil-set-initial-state` only works for major modes. I didn't find any mention of that in the function's docstring. Could we update the docstring to mention this? Also, is there a counterpart to `evil-set-initial-state` that works for minor modes?

**Comment by TheBB** [comment]
There's no counterpart for minor modes. You'll have to work from the hook of each one.

I'll update the docstring. Thanks!
