### ISSUE TITLE
Major Hybrid Mode improvement suggestion

### ISSUE THREAD

**Issue by chrisvacc** [emacs-evil/evil#1123]
Let's face it, while vim's `NORMAL` mode is one of the most amazing text innovations of all time, vim's `INSERT` mode is useless in comparison to Emacs iteration. 

I wonder if it would make more sense to just code out vim's `INSERT` mode completely and replace it with emacs iteration of "`INSERT`" mode. So that entering `INSERT` mode automatically takes you to emacs editing style, after positioning the cursor correctly (BOL, EOL, Before, After, etc). For instance, `i`, `I`, `a`, `A`, `o`, `O`, etc would just cursor correctly, then switch you to emacs `INSERT` mode. So you’re in `NORMAL` mode, and you hit `A`, the cursor would position to the End Of Line, then enter Emacs mode. Then `ESC` would bring you back to vim’s `NORMAL` mode.

I think having 3 editing styles is redundant, especially vim's `INSERT` mode brings nothing to the table, and have to be remapped anyway.

I know that hybrid tries to emulate it, but there are a number of really useful commands that it leaves out.

Evil mode

```
   Standard Key   Command                     In Your Emacs   
   C-b 		  backward-char		      M-x backward-char more info
   C-d 		  delete-char		      M-x delete-char  more info
   C-e		  move-end-of-line	      M-x move-end-of-line more info
   C-f 		  forward-char		      M-x forward-char more info
   RET 		  newline		      M-x newline      more info
   C-n 		  next-line		      M-x next-line    more info
   C-p 		  previous-line		      M-x previous-line more info
   C-r 		  isearch-backward	      the ‘Edit’ menu  more info
   C-v 		  scroll-up-command	      <kp-next>        more info
   C-w 		  kill-region		      s-x              more info
   C-x u 	  undo			      C-_              more info
   C-y 		  yank			      s-v              more info
   C-z 		  suspend-frame		      C-x C-z          more info
   DEL 		  delete-backward-char	      M-x delete-backward-char more info

```

So some bindings work, some don’t. C-e and C-a definitely don’t.

Emacs/mode
```
   Standard Key   Command                     In Your Emacs   
   RET 		  newline		      M-x newline      more info
   C-x u 	  undo			      C-_              more info
   C-z 		  suspend-frame		      C-x C-z          more info
```

I usually just enter  #`INSERT` mode, then manually switch to emacs mode. When I have to leave, I switch back to Evil mode, then hit `ESC`

to just code out vim’s INSERT mode altogether.

 

Maybe I should submit a Pull or feature request?   hey buddy.. i saw the post on switching between evil//emacs mode

How does this work exactly? in spacemacs there’s ‘hybrid’ mode, where it had vi key bondings in NORMAL mode and emacs key bindings in INSERT mode. If there’s any way to just bind them like that? maybe binding “enter emacs mode” to the “i, o, s, a,” etc keys and binding "enter evil mode” to esc? So NORMAL / VISUAL modes == vim, INSERT mode(s) == emacs.

Why have two INSTER modes when it's clear one is superior.

**Comment by justbur** [comment]
I may be missing something, but I think you just want

```elisp
  (setq evil-disable-insert-state-bindings t)
```

**Comment by chrisvacc** [comment]
> I may be missing something, but I think you just want
> 
> ```emacs-lisp
>   (setq evil-disable-insert-state-bindings t)
> ```

And that enables full-blown emacs editing in `INSERT` ?

**Comment by justbur** [comment]
Yes, with the exception of escape, delete and evil-toggle-key.

**Comment by chrisvacc** [comment]
So `ESC` would still bring you back to evil `NORMAL` mode, `C-z` (or evil toggle remap) would just toggle you to emacs mode, and when you say `delete` you mean actual delete, not backspace

**Comment by justbur** [comment]
Yes, that's all correct. To be safe you should set that variable before loading `evil` in your init file. Something like this will work.

```elisp
(setq evil-disable-insert-state-bindings t)
(require 'evil)
```

However, there are many ways to organize things in emacs...

**Comment by TheBB** [comment]
This has been answered I think.

**Comment by chuxubank** [comment]
> Yes, that's all correct. To be safe you should set that variable before loading `evil` in your init file. Something like this will work.
> 
> ```emacs-lisp
> (setq evil-disable-insert-state-bindings t)
> (require 'evil)
> ```
> 
> However, there are many ways to organize things in emacs...

So what's difference between it and Spacemacs's hybrid mode?

**Comment by nixmaniack** [comment]
@chuxubank Based on my usage, I don't see much difference. The hybrid mode in spacemacs has its reason for its existence - keep clear distinction between the three styles(vim, emacs, hybrid). 

Unless you use all three styles for some reason - there's no real benefit if you're configuring on your own(personal config). Spacemacs needs that distinction as it has to cater keybindings in all those three styles and requirements differ slightly for `vim(insert)` and `hybrid`. e.g. availability of `hjkl` style navigation in certain popups.

A bit more context be found in following issues and commit messages.

- https://github.com/syl20bnr/spacemacs/commit/82fdd9a511f1f5cc4f371b91ce691308686f8ec6
- https://github.com/syl20bnr/spacemacs/commit/cfdfcfab402849b4cfd23c3485d0808d43bcfeb7
- https://github.com/syl20bnr/spacemacs/pull/4456

**Comment by chuxubank** [comment]
@nixmaniack Thanks for your detailed explanation!
[This](https://github.com/syl20bnr/spacemacs/pull/4456/files#diff-1c384b9389d56768d30decc088e3529e) implementation is impressive.

**Comment by echozhangxiaomin** [comment]
要得就是这个功能。good
