### ISSUE TITLE
Question: how to find what function an ex command is binded to

### ISSUE THREAD

**Issue by xsrvmy** [emacs-evil/evil#1126]
How do I find the function that is executed when an ex command is executed? For example, I want to change the behaviour of :q in my init file, but I want to see the current function is executes. Is there an equivalent to Ctrl-H F but for ex commands? Thanks.

**Comment by dzop** [comment]
All of the ex commands are defined in the evil-maps.el file https://github.com/emacs-evil/evil/blob/506f758aa431128b40c987ff634b56c49f69fdb8/evil-maps.el#L471

Alternatively you can examine the `evil-ex-commands` variable.

**Comment by xsrvmy** [comment]
Thanks for the help. Closing.
