### ISSUE TITLE
]s (evil-next-flyspell-error): from buffers first char

### ISSUE THREAD

**Issue by duianto** [emacs-evil/evil#1133]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30
Operating System: Windows 10 Version 1803
Evil version: 1.2.14
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps

- Start Emacs
- Create a new buffer `C-x b` `test` `RET`
- Type (or copy and paste) the following on the `test` buffers first line:
```
oen otw thre
```
- Move the cursor to the buffers first character: `gg`
- Spellcheck the buffer: `M-x` `flyspell-buffer` `RET`
- Try to move to the next spelling error: `]s`
(`]s` calls `evil-next-flyspell-error`)

# Expected behavior

The cursor should move to the `o` in the second word `otw`.

# Actual behavior

The cursor doesn't move.

# Further notes

The issue seems to be limited to the buffers first character, because adding a space or newline before the first word, makes `]s` move to the next spelling error as expected.

Moving to the previous spelling error with `[s` works as expected.

`]s` works as expected from the buffers first character in `Vim 8.1.978`.

**Comment by dzop** [comment]
I can confirm this behavior. It has to do with the special handling of `point-min` in `evil--next-flyspell-error`

https://github.com/emacs-evil/evil/blob/3766a521a60e6fb0073220199425de478de759ad/evil-commands.el#L596-L601

Considering the surrounding code it looks like this special handling has to do with being able to wrap around to the first error when no more errors are present in the buffer, not 100% sure though.

**Comment by duianto** [comment]
Maybe it's enough to change `/=` to `>=` on line `597`:

### Before

```
(if (/= pos (point-min))
```

### After

```
(if (>= pos (point-min))
```

https://github.com/emacs-evil/evil/blame/3766a521a60e6fb0073220199425de478de759ad/evil-commands.el#L597

Navigating to the next and previous spelling errors with `]s` and `[s` still works, including wrapping past the beginning and end of the buffer.

### Additional notes:

The `(goto-char pos)` expression on line `598`:
```
       (setq pos (save-excursion (goto-char pos)
```

https://github.com/emacs-evil/evil/blame/3766a521a60e6fb0073220199425de478de759ad/evil-commands.el#L598

Might not be needed, because `pos` is set to `(point)` at the start of the `evil--next-flyspell-error` function:
```
    (let ((pos (point))
```
https://github.com/emacs-evil/evil/blame/3766a521a60e6fb0073220199425de478de759ad/evil-commands.el#L593

And it isn't changed before the `goto-char` expression, so the cursor doesn't move.

Navigating to the next/prev spelling error still works as expected.

**Comment by dzop** [comment]
After taking a closer look at this, it does appear that the entire `if` branch should be removed and to keep the `save-excursion` part.

The reason for the `when` condition is to move past any overlay at point since the function `evil—flyspell-overlay-after` will return the overlay under point if there is one and return the overlay after point if there isn’t. The desired behavior is to move past any overlay under point to the next overlay after point, and the `save-excursion` form ensures that happens at least for the forward case. For the backward case, the search for overlays wraps around to the end of the buffer when point is at point-min.

**Comment by duianto** [comment]
Confirmed. that works.

**Comment by dzop** [comment]
It is actually the same as your change since `(>= pos (point-min))` is always true.
