### ISSUE TITLE
command :Ex[plore] is missing 

### ISSUE THREAD

**Issue by pyluyten** [emacs-evil/evil#1140]
# Enhancement request

# Environment

Emacs version: 26.1
Operating System: Arch Linux
Evil version: 1.2.13
Evil installation type: melpa-stable

# Reproduction steps
- Start Emacs
- Type :Ex

# Expected behavior
Current file directory does open

# Actual behavior
Command not found

# Further notes
I wonder if i missed something, since code would be trivial.

```
(defun Explore ()
  (interactive)
   (dired default-directory))

(defalias 'Ex 'Explore)
```

**Comment by dzop** [comment]
There are many commands available in Vim that could be implemented in Evil which are not. Evil's goal is not to implement the entirety of Vim commands in Emacs, but to implement those features of Vim that are at the core of the editing experience and provide a way for users to extend those features in any way they find suitable. `:Explore` is not a part of core Vim, but a part of the `netrw` Vim plugin that is included with Vim.

So it seems to me that `:Explore` is better left to be implemented by users of Evil who would like to have it. A more convenient solution would be to have someone clone the features of `netrw` in Evil, or at least alias those features to the equivalent `dired` commands in some package that users can install.

The more Evil based way to implement `:Explore` than what you provided would look something like

```
(evil-ex-define-cmd "Ex[plore]" 'dired-jump)
```

**Comment by pyluyten** [comment]
Thanks for the better implementation. And the explanation.  To me it's fair to close this issue but i let you confirm.

So I will see if evil-collection want this. After all they may make dired mappings compatible with netrw ( https://github.com/emacs-evil/evil-collection/issues/227 ).

**Comment by dzop** [comment]
I myself would close the issue as I don't see Evil adding this command. But the maintainers might have other opinions...

**Comment by edkolev** [comment]
I don't see this as part of evil, nor evil- collection.

I could consider adding it to https://github.com/edkolev/evil-expat however, I'm not sure it's worth it, since it's so simple to add to your config, plus it's not core vim.

Finally, I hope you don't care that much about adding :Sex as well :)
