### ISSUE TITLE
next-match text objects only work with Evil search module

### ISSUE THREAD

**Issue by Geremia** [emacs-evil/evil#1142]
When I run the Vim key sequence `cgn` I get:
>next-match text objects only work with Evil search module.

What is the Evil search module? Is it something extra I need to install?

**Comment by dzop** [comment]
You need to set the `evil-search-module` variable to `evil-search`. The error you got should at least point to that variable. The documentation of `evil-search-module` doesn't help either. So you will need to evaluate
`(setq evil-search-module 'evil-search)`.

**Comment by wasamasa** [comment]
As pointed out above, customize `evil-search-module` to `evil-search`, be it in your init file *before* the package is loaded up or via custom.el.
