### ISSUE TITLE
Call evil-command-window-ex with keybinding C-f in evil-ex

### ISSUE THREAD

**Issue by socksy** [emacs-evil/evil#1147]
# Issue type
- Enhancement request

# Reproduction steps
- Start Emacs
- Press `:`
- press C-f

# Expected behavior
`(evil-command-window-ex)` is run (same as `q:` in normal mode)

# Actual behavior
Says "end-of-buffer"

# Further notes
As complained about here: https://news.ycombinator.com/item?id=19899436

I would open a PR, but my elisp skills are basically non-existent.

**Comment by xabbu42** [comment]
C-f in the minibuffer is not exactly the same as q:, as it also adds the current line as the last command. This is very useful if you are writing a complex command and need/want a full featured buffer for editing that command. Below is my current implementation of vim Ctrl-f (keep in mind that I neither know vim nor emacs all to well and this code was mostly generated by trial and error):

`(defun evil-ctrl-f-execute (config result)
  (select-window (active-minibuffer-window) t)
  (set-window-configuration config)
  (delete-minibuffer-contents)
  (insert result)
  (exit-minibuffer)
)

(defun evil-ex-ctrl-f ()
  "Vim ctrl-f in command-mode"
  (interactive)
  (let ((current (minibuffer-contents))
		(config  (current-window-configuration)))
	(evil-ex-teardown)
	(select-window (minibuffer-selected-window) t)
	(evil-command-window (cons current evil-ex-history)
						 ":"
						 (apply-partially 'evil-ctrl-f-execute config))))

(defun evil-search-ctrl-f ()
  "Vim ctrl-f in search"
  (interactive)
  (let ((current (minibuffer-contents))
		(config  (current-window-configuration)))
	(select-window (minibuffer-selected-window) t)
	(evil-command-window (cons current evil-ex-search-history)
						 (evil-search-prompt (eq evil-ex-search-direction 'forward))
						 (apply-partially 'evil-ctrl-f-execute config))))

(evil-select-search-module 'evil-search-module 'evil-search)
(define-key evil-ex-completion-map "\C-f" 'evil-ex-ctrl-f)
(define-key evil-ex-search-keymap "\C-f" 'evil-search-ctrl-f)
(setq enable-recursive-minibuffers t)
`

**Comment by xabbu42** [comment]
set-window-configuration seems to be necessary so that minibuffer-selected-window is still defined after exiting the command window. also i need to to set the minibuffer contents and exit-minibuffer instead of directly calling the known action as I can not properly close the minibuffer otherwise (abort-recursive-edit restores the buffer and overwrites the effect of some ex commands).

**Comment by xabbu42** [comment]
I can do a proper pull request, but I need to know where in the repo the code should go and how to make the search part independent of the used search module.

**Comment by TheBB** [comment]
Sorry, I'm still not totally sure what `C-f` does in vim so I'm not sure how to answer. I guess the functions would be at home in `evil-ex.el` or `evil-search.el`. As for the search module you'll have to condition on the value of `evil-search-module` in your code (either `evil` or `isearch`) and choose the right implementation.

**Comment by xabbu42** [comment]
Actually does evil overwrite any keybindings for isearch? If not then we don't need Ctrl-f support for isearch as evil is the vim-compatible search module?

In vim pressing C-f while entering an ex command or a search pattern opens a commands window with the appropriate history and the currently entered string as the last entry.

I assume evil should not do `(setq enable-recursive-minibuffers t)` by itself, especially as ctrl-f is still useful without it. Should I document somewhere that this setting is necessary for full compatibility with vim?

**Comment by xabbu42** [comment]
It seems like isearch key bindings are not changed by evil at all. So I made a pull request which only supports Ctrl-f for ex and evil-search.

**Comment by TheBB** [comment]
Closed by #1240
