### ISSUE TITLE
Documentation: evil-find-skip-newlines -> evil-cross-lines

### ISSUE THREAD

**Issue by ddoherty03** [emacs-evil/evil#1148]
# Issue type
- Other

Info Documentation

# Environment

Emacs version: 26.2
Operating System: Ubuntu 18.04
Evil version: evil-git-9865e7731

Evil installation type:  MELPA
Graphical/Terminal: Yes

# Further notes
The info file documents `evil-find-skip-newlines` as the variable to alter the behavior of `f`, `t`, `F`, and `T` commands.  Should refer to `evil-cross-lines`.

**Comment by edkolev** [comment]
Good catch, PRs are welcome :)
