### ISSUE TITLE
evil-visual-paste doesn't respect evil-kill-on-visual-paste

### ISSUE THREAD

**Issue by QiangF** [emacs-evil/evil#1152]
- Bug report
Evil version: 1.2.13
Evil installation type: MELPA
- Start Emacs
1. (setq evil-kill-on-visual-paste nil) (kill-new "hello")
2. select some text in evil visual mode
3. evil-visual-paste over the selected text
4. now the kill ring "hello" is replaced with the selected text, it should left unmodified.

The solution :

    modified the line containing evil-delete in evil-visual-paste as follows :

          (evil-delete evil-visual-beginning evil-visual-end
                       (evil-visual-type) ?_)

**Comment by QiangF** [comment]
Also for evil-delete-char

    (evil-define-operator evil-delete-char (beg end type register)
    "Delete next character."
    :motion evil-forward-char
    (interactive "<R><x>")
    (if register (evil-delete beg end type register)
      (evil-delete beg end type ?_)))

**Comment by QiangF** [comment]
I found a workaround:

    (defun evil-delete-no-kill (orig-fun beg end &optional type register yank-handler)
      (let ((register (or register ?_)))
          (apply orig-fun beg end type register yank-handler)))

    (advice-add 'evil-delete :around #'evil-delete-no-kill)

**Comment by yqrashawn** [comment]
Same problem here.

**Comment by JacksonGariety** [comment]
It would be really great if this worked as expected :)

**Comment by ericdallo** [comment]
+1

**Comment by laishulu** [comment]
@QiangF 
这个问题困扰我很久了。。。。烦得很
你这个ID可是熟面孔
smart-input-source上面我们有很多交流

**Comment by chorakm** [comment]
Same problem here.

**Comment by laishulu** [comment]
Nobody create a PR to fix it?

**Comment by QiangF** [comment]
Many people find vanilla emacs is better, maybe we should move our focus away from evil mode.

**Comment by laishulu** [comment]
？？？

If without evil mode, I will quit emacs back to vim.

**Comment by TheBB** [comment]
My apologies that I don't have much time for Evil any more. I'm happy for other maintainers to join if anyone would like to step up.

That said, if none of you can make a PR for a two-line fix that someone else already pointed out, that is so breaking that you'd rather quit Emacs for it, then I don't know what to say.
