### ISSUE TITLE
install evil for emacs  of android 

### ISSUE THREAD

**Issue by iT-Boyer** [emacs-evil/evil#1177]
# Issue type
incompat

# Environment

Emacs version: 
Operating System: 
Evil version: last
Evil installation type: MELPA
Graphical/Terminal: Emacs in termux  of android
![18F5859A-9D9D-4B9C-82C2-4A1BBCDE5C5B](https://user-images.githubusercontent.com/4022953/62421346-c241f280-b6d2-11e9-99e4-928412fd4d0f.png)
spacemacs|add-company-backends

**Comment by wasamasa** [comment]
Considering all packages in the screenshot are highlighted as incompat, it's most likely an issue with your Emacs setup on termux and not Evil's fault.
