### ISSUE TITLE
Setting evil-move-cursor-back to nil causes evil-move-beyond-eol to be ignored

### ISSUE THREAD

**Issue by undergroundquizscene** [emacs-evil/evil#1178]
# Issue type

- Bug report

# Environment

Emacs version: 26.1
Operating System: macOS Mojave
Evil version: Evil version evil-git-874beba
Evil installation type: Cloned git repository, used make emacs
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- In the scratch buffer, type (setq evil-move-cursor-back nil)
- Eval expression with C-x C-e
- Press $

# Expected behavior

Cursor should move to the last character in the line (as `evil-move-beyond-eol` is nil).

# Actual behavior

Cursor moves beyond the last character in the line.

**Comment by undergroundquizscene** [comment]
I tried finding an old commit that worked as I expected and failed – once I got back to May 2016 the `make emacs` command stopped working correctly. Does this mean it's deliberate, or caused by an error introduced by emacs itself?

**Comment by VanLaser** [comment]
AFAIK  most evil variables must be set *before* loading evil, or it may work if using the 'customize' interface or functions instead of setq.

**Comment by undergroundquizscene** [comment]
Ah, interesting! I will try that and see if that fixes my problem – thanks.

**Comment by undergroundquizscene** [comment]
This hasn't fixed my problem in my normal setup (spacemacs). How can I test this using the `make emacs` setup?

**Comment by justbur** [comment]
In most cases, you need `evil-move-cursor-back` to be non-nil in order for `evil-move-beyond-eol` to have any effect. I'm not sure why it was designed this way, but I'm also not sure why you would want `evil-move-cursor-back` and `evil-move-move-beyond-eol` to both be `nil`.

**Comment by undergroundquizscene** [comment]
Hmmm, maybe I’ve misunderstood the purpose of `evil-move-cursor-back`. I have `evil-move-beyond-eol` set to `nil` because when I hit `$`, I want the cursor to be positioned on the last character before the line-ending newline. I set `evil-move-cursor-back` to `nil` so that if I hit `i` to enter insert mode and then change my mind and return to normal mode, the cursor will remain where it was before I entered insert mode.

Is there a way to get the cursor movement behaviour I want without allowing the cursor to move past the last character on a line (excluding the newline)?

**Comment by justbur** [comment]
@undergroundquizscene try #1184

**Comment by undergroundquizscene** [comment]
Sorry for the delay! When I test as I did at the beginning, I still have the same problem, I'm afraid – after setting `evil-move-cursor-back` to `nil`, `$` still moves the cursor one past the end of the line.

**Comment by justbur** [comment]
I see the problem. I just pushed another commit.

**Comment by undergroundquizscene** [comment]
Yup, that's working for me now. Thanks very much.
