### ISSUE TITLE
Support for evil-visual-line/block-state-tag

### ISSUE THREAD

**Issue by jandamm** [emacs-evil/evil#1180]
# Issue type

- Enhancement request

# Expected behavior

There should be a `state-tag` for every `evil-state`.

# Actual behavior

There are two tags missing:
`evil-visual-line-state-tag`
`evil-visual-block-state-tag`
The corresponding messages are present though.

# Further notes
In vim using lightline I get the different visual states as well. By default they're named `V-LINE` and `V-BLOCK`. I'd love to have matching labels in Emacs as well.

**Comment by grigorievich** [comment]
related: https://github.com/emacs-evil/evil/issues/1141
