### ISSUE TITLE
MacEmacs: cannot load evil

### ISSUE THREAD

**Issue by 9527KGG** [emacs-evil/evil#1181]
- Bug report

# Environment

Emacs version: 26.2
Operating System: MacOS Mojave
Evil version: Cannot load. So I cannot see
Evil installation type: MELPA
Graphical/Terminal: GUI
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
"brew cask install emacs". The .emacs is:

(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
))
(package-initialize)

;; Bootstrap `use-package`
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)

(use-package evil
  :ensure t
  :init
  :config
  (evil-mode)
)

# Expected behavior
evil can be loaded

# Actual behavior
Error (use-package): Failed to install evil: Package ‘undo-tree-0.6.3’ is unavailable
Error (use-package): Cannot load evil

# Further notes

**Comment by firstrow** [comment]
Looks like issue may be related to TLS connection issues.
Paste this code in the beginning of init file:
```
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
```

**Comment by 9527KGG** [comment]
Thanks. Just gave a try. Not working. Same error prompted.

**Comment by 9527KGG** [comment]
More suggestion？

**Comment by TheBB** [comment]
Undo-tree is on ELPA. What's the value of your `package-archives`?

https://elpa.gnu.org/packages/undo-tree.html

**Comment by 9527KGG** [comment]
I'm new to Emacs, from Vim. 

Sorry what do you mean of "value of package-archive"?

**Comment by TheBB** [comment]
The variable `package-archives`. What is its value? It should have a list of the servers you are getting packages from. If you are trying to install from MELPA you *must* have edited it somewhere in your config, because MELPA is not the default setting.

**Comment by 9527KGG** [comment]
(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
))

Thanks.

**Comment by TheBB** [comment]
Right, so evil depends on a package that is only on ELPA. Since you've removed ELPA, you can't install evil. Instead of setting `package-archives`, just add to the existing list instead.

    (add-to-list 'package-archives '("melpa" . "...."))

or something like that.

**Comment by TheBB** [comment]
Can you install undo-tree manually? Have you done M-x *package-refresh-contents*?

**Comment by 9527KGG** [comment]
@TheBB , since the issue is not resolved, may you please keep the it open? Thanks.

**Comment by TheBB** [comment]
Fair enough, but I don't consider it likely to be a problem with Evil.

**Comment by 9527KGG** [comment]
Thanks, @TheBB . Do you have a Mac to give a try? If working on your side, what's the minimized .emacs on your side (with package auto download/management please)?

**Comment by TheBB** [comment]
I don't have a mac. 

I'm generally not in the business of writing people's init files for them. Especially not with special requests like "automatic package management". That's not my job. However I'll let it slide for now. This works fine for me.

    (require 'package)
    (setq package-archives
          '(("melpa" . "https://melpa.org/packages/")
            ("gnu" . "https://elpa.gnu.org/packages/")))
    (package-initialize)
    (package-refresh-contents)
    (package-install 'evil)
    (package-activate 'evil)
    (require 'evil)

**Comment by 9527KGG** [comment]
Thanks. I think you need
(evil-mode) to enable it.

I delete .emacs.d folder. The above script works on Linux. But Mac still does not work.

**Comment by 9527KGG** [comment]
Just wondering: does anyone have a chance to take a look at the bug? This is really a blocker on Mac OS. Thanks.

**Comment by mortenfroelich** [comment]
I can see the same issue on debian buster running emacs 26.1 even with the simple init file suggested by @theBB.

I hardly have any knowledge of how emacs handles package dependencies but I can see that he undo-tree package in elpa is 0.6.5 not 0.6.3 as is required by evil. Can this be the cause of the issue?

**Comment by 9527KGG** [comment]
Seems Emacs community is much less active than Vim.

Anyway, I've given up Emacs and switched back to Vim.

I've unsubscribed the thread. Free feel to close the ticket or take some action. ^_^.

Thanks.
