### ISSUE TITLE
Solving the underscore word motion problem with `(defalias #'forward-evil-word #'forward-evil-symbol)`

### ISSUE THREAD

**Issue by amiryal** [emacs-evil/evil#1185]
# Issue type

- Question

# Environment

Emacs version: GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.7) of 2019-04-11, modified by Debian
Operating System:  Ubuntu 19.04
Evil version: evil-git-fc3677131
Evil installation type: Spacemacs
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Question

With the goal of making word motions behave more like Vim, [an answer on Stack Exchange](https://emacs.stackexchange.com/a/20717) suggests to change the behaviour from using Emacs’s idea of a word to using Emacs’s idea of a _symbol_. The suggested code snippet is:

```lisp
(with-eval-after-load 'evil
    (defalias #'forward-evil-word #'forward-evil-symbol))
```

1. Are there any potential downsides in doing it this way?
2. Would you consider to change or rewrite [the README section](https://github.com/emacs-evil/evil#underscore-_-is-not-a-word-character) to include this advice?

**Comment by Alexander-Shukaev** [comment]
That's just ordinary Emacs configuration hacking.  This can be achieved in many different ways: advice, remap, alias, `modify-syntax-entry`, etc.

I don't see any downsides apart from limiting yourself to only symbol-based jumps as per syntax table.  Adding to the already dedicated section of `README` as another less intrusive option may be a good idea.
