### ISSUE TITLE
when use dd remove line got an error

### ISSUE THREAD

**Issue by glepnir** [emacs-evil/evil#1189]
# Issue type

- Question

# Environment

Emacs version: 
 GNU Emacs 26.3 (build 1, x86_64-apple-darwin17.7.0, Carbon Version 158 AppKit 1561.6) of 2019-08-25 
Operating System: macos 10.13.6
Evil version: Evil version evil-git-735da1a
Evil installation type: MELPA
Graphical/Terminal: 
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): 

# Reproduction steps
- Start Emacs

- open a go file 
- `dd` to remove a line ,the cursor at  the head of line
# Expected behavior

remove a line 
# Actual behavior

got an error 
![image](https://user-images.githubusercontent.com/41671631/63833656-27bd9200-c9a6-11e9-8c5a-f3fc2bd92097.png)

new come to emacs from vim..need help. this gif can show this problem
  
![git](https://user-images.githubusercontent.com/41671631/63834039-ef6a8380-c9a6-11e9-9d51-f9c6096e6113.gif)

# Further notes

**Comment by TheBB** [comment]
Would it be possible to get some reproduction steps that start with `make emacs`? I can't reproduce this and I'm guessing I need some sort of `go-mode` to do it.

**Comment by taigacute** [comment]
@TheBB  hi thanks for your reply. i dont find makefile in the evil-20190729.204 folder.

**Comment by TheBB** [comment]
Yes, it's not in the package distributed on MELPA. It's in this source repository.

**Comment by taigacute** [comment]
tested  run `make test` in evil source code folder..it works well.

**Comment by taigacute** [comment]
@noctuid  we have same setting with bind `k` to `evil-previous-visual-line` ?can reproduce

**Comment by hisnawi** [comment]
I am seeing the same. Has this been resolved?

**Comment by TheBB** [comment]
No, I don't have a repro.

**Comment by hisnawi** [comment]
I found out that these two lines caused my issue.
Once removed, I stopped getting the error.
```
    (define-key evil-normal-state-map (kbd "j") 'evil-next-visual-line)
    (define-key evil-normal-state-map (kbd "k") 'evil-previous-visual-line)

```
Which I don't remember why I had placed them in my config file.
