### ISSUE TITLE
An unmatched quote breaks yi" and yib

### ISSUE THREAD

**Issue by grigorievich** [emacs-evil/evil#1190]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-04-13
Operating System: Arch Linux
Evil version: Evil version 1.2.14
Evil installation type: MELPA
Graphical/Terminal: X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs

- Insert the following in the buffer (note the unmatched quote):
```
"
(insert "str")
```
- Place cursor on 'str'.

- Try `yib` -> `No surrounding delimiters found`
- Try `yi"` -> `No quoted string found`

# Expected behavior

Things get copied.
# Actual behavior

Errors show up, as noted above.
# Further notes
An unmatched quote may show up somewhere in the document. Take this issue for instance: the  `yi"` above.

It would seem, if evil searched starting at the cursor, it should stop before seeing the stray quote as it doens't have to be greedy.

**Comment by dzop** [comment]
This is related to the fact that `evil` uses Emacs's built-in syntax parsing facilities (`parse-partial-sexp`, `up-list`, ...) to find the bounds of strings and parenthetical groups. So depending on the `major-mode` (and in this specific case),

```
"
(insert "str")
```

is being viewed syntactically as a string `"\n(insert "`, followed by a top level expression `str`, followed by an unterminated string `")`. This is why `yib` and `yi"` give the results they do whenever `point` is on `str`. Syntactically, `str` is at top level and not in any nested parenthesis nor is it inside a string.

Are you aware of `electric-pair-mode` and packages like `smartparens`? Although not a solution to the problem, they greatly reduce the likelihood of having unmatched quotes in your own code.

**Comment by grigorievich** [comment]
Thanks for clarifying. Yeah, seems to be a tradeoff between syntactic selection and simple, brute selection. Since evil picks the former, maybe showing an error is the right thing to do after all.

> electric-pair-mode and packages like smartparens

Somehow I found them quite intrusive. But speaking of the origin of my error, it was in an org-mode file where I keep track of some hairy emacs bindings as an occasional guide, the quote was meant to be unmatched there : ) It was my first encounter with this behavior.
