### ISSUE TITLE
Missing some of Vim's mark-based features in ex-mode

### ISSUE THREAD

**Issue by karthink** [emacs-evil/evil#1192]
# Issue type
- Bug report

# Environment
Emacs version: GNU Emacs 26.3
Operating System: Arch linux
Evil version: evil-git-3028d8e
Evil installation type: MELPA
Graphical/Terminal: X
Tested in a `make emacs` session: No

# Reproduction steps
From normal-mode, type
```:'[,'] some-command```
```:m '[```
```:,$ some-command```

where `some-command` is a valid ex command.

# Expected behavior
 some commonly used mark-based range features from Vim command-mode that seem to be missing:

1. Drop the `.` when referring to ranges. Vim lets me do
```:,$ s/what/ever/```

to mean the range `.,$`, current line to end of buffer. In evil I have to type the dot.

2. Marks as arguments to Ex commands. For instance, in Vim I can type
```:m '[```

To move the current line to where I last pasted text (which is the location `'[`).

3. For that matter ```:'[,'] some-command``` doesn't work either (such as ```:'[,'] !wc -w```)

# Actual behavior
Throws an error: `Invalid address` or `Ex: syntax error`

# Further notes
Perhaps these are implemented but disabled by default? I couldn't find them in the customization options.

Another possibility is these aren't available in vanilla Vim and are enabled by some plugin. I did test these on vim with ```vim -u NONE``` and they worked fine.

For some of these there are emacs commands (like `flush-lines` for `:%g/regexp/ d`) and `swiper` handles a few more, but in general ex commands are usually the fastest way to do one-time structured transformations that it doesn't make sense to write some elisp or define a macro for.

**Comment by dzop** [comment]
I was able to get the `,$` behavior by adding  

```emacs-lisp
("," line #'(evil-ex-range (evil-ex-current-line) $2))
```

to the `range` entry in `evil-ex-grammer`.

For (2) it looks like you found a bug that can be fixed by replacing the regex in the `marker` entry of `evil-ex-grammer` with  `"\\(?:[-a-zA-Z_<>']\\|\\[\\|\\]\\)"`. This change will probably have to be made elsewhere to fix (3).

**Comment by mohkale** [comment]
@dzop could you share how you added it exactly? I tried

```elisp
(push '("," line #'(evil-ex-range (evil-ex-current-line) $2))
      evil-ex-grammar)
```

but I get a syntax error :disappointed:.
