### ISSUE TITLE
Vertical split behaviour inconsistent with vim

### ISSUE THREAD

**Issue by WesleyAC** [emacs-evil/evil#1195]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10)
Operating System: NixOS 19.09
Evil version: Evil version 1.2.14
Evil installation type: Doom emacs
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Type `:vsp`

# Expected behavior
Two splits are open, and the cursor is in the left split

# Actual behavior
Two splits are open, and the cursor is in the right split

**Comment by hlissner** [comment]
@WesleyAC This is [Doom's doing](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/config.el#L133-L134), and not any fault of `evil`'s.

A quick workaround:

```elisp
(after! evil
  (advice-remove #'evil-window-split   #'+evil-window-split-a)
  (advice-remove #'evil-window-vsplit  #'+evil-window-vsplit-a))
```

**Comment by WesleyAC** [comment]
Thanks! Sorry for filing in the wrong location.
