### ISSUE TITLE
Paste with universal-argument reports error

### ISSUE THREAD

**Issue by xuhdev** [emacs-evil/evil#1199]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.3.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-28
Operating System: Debian Buster
Evil version: Evil version evil-git-195ba335785f
Evil installation type: MELPA
Graphical/Terminal: 
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Visit a Python file `a.py` with the following content:

```python
import sys
```

- Move point to the beginning of the file. Type `yy` to copy the line.
- `C-u p`.

# Expected behavior
Line pasted.

# Actual behavior

Error message:

> apply: Wrong type argument: wholenump, (4)

# Further notes

The Python file is one of the example. In some major mode there won't be this message, but some other mode, such as Python mode (as used in the example), yaml-mode, this error message would show up.

**Comment by TheBB** [comment]
Thanks. I believe #1222 should fix this.

**Comment by xuhdev** [comment]
Yes, thanks, it fixed it. But now it pastes 4 times...

**Comment by TheBB** [comment]
Yeah, one prefix argument interpreted as a number is four. If you want a specific number of pastes (ilke 2) you need to do `C-u 2 p` Emacs style or of course `2 p` Vim/Evil style.
