### ISSUE TITLE
evil-goto-definition - Getting error `run-hook-with-args-until-success: Symbol’s value as variable is void: user-error `

### ISSUE THREAD

**Issue by jayka** [emacs-evil/evil#1206]
# Issue type
- Bug report

# Environment

Emacs version: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02

Operating System: macOS Mojave 10.14.6 (18G1012)
Evil version:  1.2.14
Evil installation type: MELPA
Graphical/Terminal: Graphical/Windowed
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Install Evil package from MELPA (build# 20191125.1525) or Checkout from Github `master` branch (`56eb22ac71f10a5475945086ebb9ed45af0a6638`) 
- While in `evil-normal-state`, goto a symbol definition by typing `gd`  ( bound to `evil-goto-definition` by default)

# Expected behavior
- `evil-goto-definition` should navigate to symbol's definition

# Actual behavior
- Getting error `run-hook-with-args-until-success: Symbol’s value as variable is void: user-error
`

# Further notes
Below is debug trace while trying to `evil-goto-definition` for symbol `package-initialize`
**Debug trace:**
```
Debugger entered--Lisp error: (void-variable user-error)
  evil-goto-definition-xref("package-initialize" 1857)
  run-hook-with-args-until-success(evil-goto-definition-xref "package-initialize" 1857)
  evil-goto-definition()
  funcall-interactively(evil-goto-definition)
  call-interactively(evil-goto-definition nil nil)
  command-execute(evil-goto-definition)
```

**Possible Fix/Patch:**
#https://github.com/emacs-evil/evil/pull/1205

**Comment by TheBB** [comment]
I can't reproduce this. What is the contents of the buffer, the major-mode and what symbol are you looking up to cause this error?

`user-error` is not used as a variable in the location indicated, `ignore-error` is a macro that should expand it to

          (condition-case nil
              (progn
                (xref-find-definitions identifier))
            (user-error nil))

Does the following execute without error for you?

    (ignore-error user-error (user-error "oh no"))

**Comment by jayka** [comment]
I'm getting error when executing in minibuffer 
```
Debugger entered--Lisp error: (void-function ignore-error)
  (ignore-error user-error (user-error "oh no"))
  eval((ignore-error user-error (user-error "oh no")) nil)
  eval-expression((ignore-error user-error (user-error "oh no")) nil nil 127)
  funcall-interactively(eval-expression (ignore-error user-error (user-error "oh no")) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

I executed this in emacs `26.3` with just evil package version `evil-20191125.1525` from MELPA

**Comment by jayka** [comment]
I executed in minibuffer. Getting error
```eval: Symbol’s function definition is void: ignore-error```

I'm getting the error if I try to find definition of any symbol eg. `add-to-list`

```Debugger entered--Lisp error: (void-variable user-error)
  evil-goto-definition-xref("add-to-list" 237)
  run-hook-with-args-until-success(evil-goto-definition-xref "add-to-list" 237)
  evil-goto-definition()
  funcall-interactively(evil-goto-definition)
  call-interactively(evil-goto-definition nil nil)
  command-execute(evil-goto-definition)
```

I'm using vanilla emacs 26.3 with just evil package version `evil-20191125.1525` from MELPA

**Comment by jayka** [comment]
Where is `ignore-error` macro defined? I couldn't find it

**Comment by TheBB** [comment]
That's weird. `ignore-error` is defined in `subr.el` and it works fine on my installs of Emacs 24, 25, 26 and 27. It seems something is strange with your installation. But if it's a pervasive problem I don't see a problem with replacing the offending sexp with its macro expansion.

**Comment by jayka** [comment]
Hmm.. Seems the `ignore-error` macro was added only 4 months ago. May be its missing in my Emacs from https://emacsformacosx.com/

https://github.com/emacs-mirror/emacs/blame/master/lisp/subr.el#L337

**Comment by TheBB** [comment]
Oops, I tried to `C-h f` for it and it showed me `ignore-errors` instead, and I didn't notice that it was a different one. Sorry about that. I'll fix it.

**Comment by jayka** [comment]
@TheBB Thanks!! :)
