### ISSUE TITLE
C-[ does not exit insert state while in evil-local-mode

### ISSUE THREAD

**Issue by ajpaon** [emacs-evil/evil#1210]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.3
Operating System: Gentoo Linux
Evil version: 1.2.14
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes, the same problem exists at head in `make emacs`

# Reproduction steps

```
make emacs
M-x evil-mode # to leave evil global mode
M-x evil-local-mode # to enter evil mode for this buffer
i # to enter insert state
this is a test # to enter text
C-[
```

# Expected behavior
Buffer should be back in normal state.

# Actual behavior
Buffer is still in normal mode, and "Esc- " is present in the minibuffer

# Further notes

**Comment by TheBB** [comment]
This isn't a bug. You're using evil in a way that it's not intended to be used. `evil-mode` does more than just enable `evil-local-mode` in buffers:

- it also calls `(evil-initialize)` once per buffer
- most importantly for you, it also calls `(evil-esc-mode)` which you neglect, causing this issue

Please see [here](https://github.com/emacs-evil/evil/blob/fa54bb984d73f08422d22545e166fc95c5c70876/evil-core.el#L167-L205).

**Comment by ajpaon** [comment]
I see. I found this recommendation in a few places online (not in the evil manual.)

Is there a recommended way to enable evil only in select buffers (or to disable it in select buffers)? I was experimenting with this in my init.el:

```
;; Enable evil in all non-lisp programming buffers
(add-hook 'prog-mode-hook
	  (lambda ()
	    (unless (apply 'derived-mode-p '(emacs-lisp-mode lisp-mode))
	      (evil-local-mode))))
```

**Comment by TheBB** [comment]
The best way is to enable it globally, but configure which buffers default to which state. Those where you don't want to use evil should go to emacs state, which is a special state with only one non-default keybinding: `C-z` for going to normal state.

Evil has a few mechanisms for choosing the default state, but the most typical entry point is `evil-set-initial-state`.

**Comment by TheBB** [comment]
I'll close this, but feel free to follow up.

**Comment by ajpaon** [comment]
Thanks for the pointer! This sounds like what I want. I'll give it a shot
