### ISSUE TITLE
Poor search performance in evil-local-mode

### ISSUE THREAD

**Issue by ajpaon** [emacs-evil/evil#1211]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.3
Operating System: Gentoo Linux
Evil version: 1.2.14
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes, the same problem exists at head in `make emacs`

# Reproduction steps

```
make emacs
M-x evil-mode # to leave evil global mode
M-x evil-local-mode # to enter evil mode for this buffer
i # to enter insert state
this is a test<cr> # to enter text
<ESC> # to return to normal state
50.gg # to repeat this line many times and return to the top
/test<cr> # start a search
nnn  # press n a few times to jump to later matches
```

# Expected behavior
cursor is on the fourth or fifth match

# Actual behavior
emacs is frozen until I hit C-g several times. cursor is still on the first or second match. movement performance is noticeably degraded

**Comment by TheBB** [comment]
Like in #1211 I cannot reproduce this with the global minor mode enabled, which is the intended and supported way of running evil. Unlike that issue I'm not exactly sure what causes the problem. From some cursory back-and-forth it seems to be one of the advices enabled [here](https://github.com/emacs-evil/evil/blob/fa54bb984d73f08422d22545e166fc95c5c70876/evil-core.el#L198-L199), which you do not get when you just enable the local mode.
