### ISSUE TITLE
It is an error (case error) when replace whole line to some word?

### ISSUE THREAD

**Issue by xuebo** [emacs-evil/evil#1214]
# Issue type

- Question

# Environment

Emacs version: 27.0.50
Operating System: macOS Sierra
Evil version: 1.2.14
Evil installation type:  MELPA stable
Graphical/Terminal: 
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): 

# Reproduction steps
- Start Emacs

# Expected behavior
two lines like below:
123A
123a

 when we use follow comman 
command 1) :s/.*/\Uupercase/
output:
UPERCASE
it's correct!

command 2.1) :s/.\*/lowercase/
command 2.2) :s/.\*/\llowercase/
expected output :
lowercase
lowercase

# Actual behavior
LOWERCASE
lowercase

# Further notes

**Comment by axelf4** [comment]
This is intended behavior (see the docstring of `query-replace` about `case-replace`). To turn off, run
```elisp
(setq evil-ex-substitute-case 'sensitive)
```
