### ISSUE TITLE
Every time I start Emacs I get `Error loading autoloads: (void-function evil-define-motion)`

### ISSUE THREAD

**Issue by mrbig033** [emacs-evil/evil#1215]
# Issue type

- Bug report

# Environment

- Emacs version: 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2019-11-19
- Operating System: MX Linux 18
- Evil version: 1.2.14
- Evil installation type: MELPA
- Graphical/Terminal: Graphical
- Tested in a `make emacs` session: No. I tried [the instructions](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports): went to `~/.emacs.d/elpa/evil-20191203.1616` and ran `make emacs`. Got the message `make: *** No rule to make target 'emacs'.  Stop.` Please advise if I did something wrong. 

# Reproduction steps
- Run emacs from a terminal. 
- `Error loading autoloads: (void-function evil-define-motion)` should appear in the command line.

# Expected behavior
There should be no error. 

# Actual behavior
The error shows every time Emacs is started. 

# Further notes
The issue does not occur with `emacs -Q` or `emacs -q`, but it does happen if I merely move `init.el` away from `~/.emacs.d`.

**Comment by TheBB** [comment]
You probably have another package that uses this function in the autoloads. Try removing packages until you find the offending one?

> Please advise if I did something wrong.

You have to do it in a checkout of this repository. The package distributed by MELPA does not include everything, such as the makefile.

**Comment by TheBB** [comment]
Another thing you can do is to start `emacs -q`, then

    (require 'package)
    (package-initialize 'noactivate)

Then proceed to `(package-activate ...)` all your packages manually. One of them should throw an error.

**Comment by TheBB** [comment]
I'm closing this now since it's unlikely to be a problem with evil. Let me know if you need more help.
