### ISSUE TITLE
Evil mode in *Packages*?

### ISSUE THREAD

**Issue by ianpan870102** [emacs-evil/evil#1234]
[Question]
Does Evil-mode have a way to support the \*Packges\* buffer as well? Using j/k as navigation but also utilising 'd', 'i', 'x' to delete, install, and execute.

**Comment by TheBB** [comment]
You can do it yourself or use [evil-collection](https://github.com/emacs-evil/evil-collection). See [here](https://github.com/emacs-evil/evil-collection/blob/master/modes/package-menu/evil-collection-package-menu.el#L38-L54) for example.
