### ISSUE TITLE
weird docstring

### ISSUE THREAD

**Issue by yunhao94** [emacs-evil/evil#1236]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-30
Operating System: Arch Linux
Evil version: 1.13.0
Evil installation type: MELPA
Graphical/Terminal: both
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- <kbd>C-h evil-want-C-i-jump RET</kbd>

# Expected behavior
the docstring should not have redundant M-x prefixed

# Actual behavior

``` text
evil-want-C-i-jump is a variable defined in `evil-vars.el'.
Its value is t

Documentation:
Whether M-x C-i jumps forward in the jump list (like Vim).
Otherwise, M-x C-i inserts a tab character.
```

# Further notes

https://github.com/emacs-evil/evil/blob/30e951fd41ae408fab7fc19004f88c31205c0e4a/evil-vars.el#L430

don't know why ```\\[C-i]``` comes to M-x C-i in doc

**Comment by TheBB** [comment]
Thanks. I misunderstood what `\\[ ... ]` does. This is annoying because I want to render keybindings specially in generated documentation but I don't have a way to mark them.
