### ISSUE TITLE
evil-define-key with 'global and 'dired-mode-map not working as expected

### ISSUE THREAD

**Issue by yatsky** [emacs-evil/evil#1241]
# Issue type
- Bug report
(Looks like a bug to me but not sure)

# Environment

Emacs version: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-17
Operating System: Windows Subsystem Linux V1
Evil version: Evil version 1.2.14
Evil installation type: MELPA
Graphical/Terminal: under X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Add the following in `init.el`
```
(define-key evil-normal-state-map " " nil)

(evil-define-key 'normal  'global; this does not work in dired but works in *scratch* and when editing files
;(evil-define-key 'normal  'dired-mode-map; this works in dired and *scratch* and when editing files
  (kbd "SPC e") 'evil-end-of-line
  ;; global-set-key expects an interactive command
  (kbd "SPC i e") (lambda() (interactive) (find-file "~/.emacs.d/init.el"))
  (kbd "SPC i l") (lambda() (interactive) (load-file "~/.emacs.d/init.el"))
  (kbd "SPC k") 'describe-key
  (kbd "SPC f") 'describe-function
  (kbd "SPC m u") 'mu4e
  )
```
- Restart Emacs
- Open a directory in `dired`
- Hit `SPC`

# Expected behavior
Mini buffer waits for remaining key strokes.

# Actual behavior
`dired-next-line` is called.

# Further notes
The following works in `dired-mode` and other modes after restarting Emacs.
All I did was change the map from `global` to `dired-mode-map`. This even works in `help-mode`.
```
(define-key evil-normal-state-map " " nil)

;(evil-define-key 'normal  'global; this does not work in dired but works in *scratch* and when editing files
(evil-define-key 'normal  'dired-mode-map; this works in dired and *scratch* and when editing files
  (kbd "SPC e") 'evil-end-of-line
  ;; global-set-key expects an interactive command
  (kbd "SPC i e") (lambda() (interactive) (find-file "~/.emacs.d/init.el"))
  (kbd "SPC i l") (lambda() (interactive) (load-file "~/.emacs.d/init.el"))
  (kbd "SPC k") 'describe-key
  (kbd "SPC f") 'describe-function
  (kbd "SPC m u") 'mu4e
  )
```
- Restart Emacs
- Open a directory in `dired`
- Hit `SPC`

Thanks!

**Comment by TheBB** [comment]
Dired already has its own evil keybindings which I suppose you have not
disabled.

https://github.com/emacs-evil/evil/blob/36d4cfb5919d2b7c6c24478ef62d0820a5590b72/evil-keybindings.el#L59-L69

See also the `evil-want-keybindings` variable.

**Comment by yatsky** [comment]
Thanks @TheBB . This could be the issue. Another thing here is that when I use `evil-define-key 'normal  'dired-mode-map`, `SPC` works in all buffers (org files, scratch, and dired). Not sure why this is the case?
