### ISSUE TITLE
Error occurred in Emacs batch mode.

### ISSUE THREAD

**Issue by gujiaxi** [emacs-evil/evil#1243]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.3
Operating System: macOS Catalina
Evil version: 1.13.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Clean all the things in `~/.emacs.d/`
- Use the config file, i.e. `~/.emacs.d/init.el`, provided by [Evil](https://github.com/emacs-evil/evil#installation):
``` emacs-lisp
;; Set up package.el to work with MELPA
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages"))
(package-initialize)
(package-refresh-contents)

;; Download Evil
(unless (package-installed-p 'evil)
  (package-install 'evil))

;; Enable Evil
(require 'evil)
(evil-mode 1)
```
- Run `emacs --batch --load="~/.emacs.d/init.el"` in terminal.

# Expected behavior

The `init.el` loads correctly.

# Actual behavior
An error occurred:
```
Wrong type argument: number-or-marker-p, nil
```

# Further notes
The Graphical Emacs can be opened correctly without any error using the same `init.el` file.

**Comment by TheBB** [comment]
This is caused by `global-undo-tree-mode`. You should be able to produce the same error if, instead of enabling evil, you just do:

```elisp
(require 'undo-tree)
(global-undo-tree-mode)
```

So this is not a bug in evil.
