### ISSUE TITLE
Insert state backwards-delete selection not working

### ISSUE THREAD

**Issue by aaronstockdill** [emacs-evil/evil#1253]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4) of 2019-12-03
Operating System: macOS Catalina 10.15.2
Evil version: 1.13.0
Evil installation type: MELPA
Graphical/Terminal: Graphical – Emacs-mac-port
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  No

# Reproduction steps
- Start Emacs, load evil
- Open a buffer in fundamental mode (or any mode with a "normal" delete, not something like Paredit)
- Enter insert state
- Visually select some text
- Press backspace (delete key on Mac)

# Expected behavior
Selected text is deleted. 

# Actual behavior
Only the character under the point is deleted.

# Further notes
I have found replacing line 1482 in `evil-commands.el` (found in `evil-delete-backward-char-and-join`, originally the line read `(delete-char -1)`) with `(call-interactively 'delete-backward-char)` results in the correct behaviour. 
This change  effectively reverts part of commit 1d6ba80956677caef1d249d7c25209f29c6cd416.
I am not sure what motivated the change (core dump? https://github.com/emacs-evil/evil/pull/1159) so do not know how suitable this would be as a fix.

**Comment by TheBB** [comment]
Can you reproduce in `make emacs` please? I'm not sure what key you are pressing. Can you report the output of `C-h k <KEY>`? When I press backspace the cursor moves to the left, as it also does in vim.

**Comment by TheBB** [comment]
> I am not sure what motivated the change (core dump? #1159) so do not know how suitable this would be as a fix.

Well, it makes the tests work. Now to be honest I'm not sure why because I can't reproduce the test failure in regular usage. So I'd be happy to revert if I could figure that out.

**Comment by TheBB** [comment]
I was able to make the tests pass with #1254, which I'm assuming fixes your problem?

I've seen some unfortunate problems with the `(delete-char -1)` myself so I am happy to commit this even if I'm not sure exactly what problem you are experiencing though.
