### ISSUE TITLE
`(message "action: symbol...")` are overly annoying

### ISSUE THREAD

**Issue by kiennq** [emacs-evil/evil#1257]
# Issue type
- Bug report

# Environment

Emacs version: GNU Emacs 27.0.60
Operating System: Windows 10
Evil version: 1.13.0
Evil installation type: MELPA
Graphical/Terminal: Graphic

# Reproduction steps
- Start Emacs
- Type `: b`

# Expected behavior
No message should be logged

# Actual behavior
An "action: symbol ..." message is logged.
![image](https://user-images.githubusercontent.com/2631472/73298811-61ded880-4251-11ea-8146-53a63275f4f4.png)

# Further notes
This seems to be regression of dee23238d32b

**Comment by mcdejonge** [comment]
Same here. It makes evil mode pretty much unusable. Searching, saving, opening files, every command you type is obscured by this message.

I’m on Mac, homebrew cask version .

**Comment by TheBB** [comment]
Thanks. It's late and I can't look at this now so I'll revert that change for the moment.

**Comment by TheBB** [comment]
I don't see why this makes anything unusable though. In my case the message is printed after whatever you type in the minibuffer, and it doesn't obscure anything.

**Comment by kiennq** [comment]
I think just remove the `(message "action: ...")` line would be fine.
Although it's not make evil unusable, it makes evil becomes overly annoying

**Comment by mcdejonge** [comment]
> I don't see why this makes anything unusable though. In my case the message is printed after whatever you type in the minibuffer, and it doesn't obscure anything.

In my case it's displayed after every keystroke, so you can't see what you're typing in the minibuffer unless you wait a few seconds. This is on an early 2015 retina macbook pro 13". A bit old, but until Apple starts releasing new small notebooks with working keyboards ;-) there will probably be a lot of these around.

Out of curiosity: what is the reason this message was put in?

**Comment by TheBB** [comment]
Ah shit, this was just a debug message that I forgot to remove. I thought the issue would be something more obscure than that.

If you noticed that right away feel free to just point it out by the way.

Un-reverted and fixed.

**Comment by mcdejonge** [comment]
Yup, fixed. Thanks!
