### ISSUE TITLE
evil makes pre-command-hook permanently buffer-local

### ISSUE THREAD

**Issue by mohkale** [emacs-evil/evil#1261]
# Issue type
After activating evil-mode, pre-command-hook becomes permenently buffer-local. meaning packages such as [keycast](https://github.com/tarsius/keycast) which add to `pre-command-hook` don't actually add to it.

- Bug report

# Environment

Emacs version: GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
Operating System: Windows 10
Evil version: Evil version 1.13.0
Evil installation type: MELPA
Graphical/Terminal: Graphics
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Run `emacs -q`
- enter `C-h v pre-command-hook` to see the current value of `pre-command-hook`.
  - You should note, at this point, it should not be labeled "This variable’s buffer-local value is permanent."
- Run `M-x evil-mode` to activate evil mode.
- enter `C-h v pre-command-hook` to see the current value of `pre-command-hook`.
  - For me it is now permanently buffer local..

# Expected behavior
`pre-command-hook` should not be permanently set anywhere.

# Actual behavior
`pre-command-hook` is permanent.

# Further notes

**Comment by TheBB** [comment]
I might need some help to figure out why this happens. It's not immediately clear to me.

**Comment by mohkale** [comment]
I agree, I honestly have no idea why this is happening. Running ripgrep over the evil repository doesn't show `pre-command-hook` being modified in such a way, all interactions are done through `add-hook` and `remove-hook`.

For now can you replicate the issue in question. If someone else can do so that'll at least verify there's not something wrong with my emacs install.

**Comment by mohkale** [comment]
When I get a chance I'll try going through the tag history for this repo to see where this issue first sprung up and eventually what's causing it.

**Comment by TheBB** [comment]
Yeah I can reproduce.

**Comment by axelf4** [comment]
This is intended. `evil-local-mode` marks the hooks it adds as `permanent-local-hook` so it can stay enabled whenever the major mode changes. Since the hooks are added buffer-locally, a sentinel `t` flag is added so that the non-local hooks also are run (see `add-hook`), like those of keycast. That is to say, this should not be the cause of any issues.

I tried keycast and it seems to work just fine with Evil on GNU Emacs 28.2.
