### ISSUE TITLE
"." Repeats `flycheck-next-error` not last edit command after using `flycheck-next-error`

### ISSUE THREAD

**Issue by jsoo1** [emacs-evil/evil#1272]
# Issue type
- Question

# Environment

Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G2022))
 of 2020-01-03
Operating System: macOS Mojave
Evil version: Evil version 1.2.14
Evil installation type: MELPA
Graphical/Terminal: Terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No (Sorry, I was having a hard time getting flycheck up)

# Reproduction steps
In a buffer with more that one flycheck error:
- `flycheck-next-error` - say it is a typo.
- `caw` and correct typo then escape to normal mode
- `flycheck-next-error`
- `.` to repeat the edit

# Expected behavior
- The correction made on the first error is repeated.

# Actual behavior
- Jumps to the next flycheck error

# Further notes
This could be intended, maybe it is a question for flycheck. I would like to be able to repeat fixes on a lot of similar flycheck errors, if possible.

**Comment by edkolev** [comment]
I would suggest you propose a fix in evil-collection.

The fix is to tell evil this command is not repeatable, but the fix shouldn't live in the evil repo.

**Comment by jsoo1** [comment]
Ah I see! Maybe they already have it! I don't use evil-collection currently. I figured I could just be ignorant of something that existed already.

**Comment by jsoo1** [comment]
I think I understand that I should probably just use `evil-declare-not-repeat`, thank you!
