### ISSUE TITLE
Compile warning: `undo-elt-crosses-region` is an obsolete function

### ISSUE THREAD

**Issue by JeremyDurnell** [emacs-evil/evil#1275]
The following compile warning is observed upon initial installation with following code in `~/.emacs`:
```
(use-package evil
  :ensure t
  )
```
```
Compiling file /home/jkdurnell/.emacs.d/elpa/evil-20200203.2006/evil.el at Mon Feb 17 19:38:21 2020

Compiling no file at Mon Feb 17 19:38:21 2020
Warning (bytecomp): ‘undo-elt-crosses-region’ is an obsolete function (as of 25.1). [2 times]
```

It seems like it might be the following line in `undo-tree.el`
https://github.com/emacs-evil/evil/blob/d14e9e2cac539f388a1f4699eb3ffab0834aa3e4/lib/undo-tree.el#L2231

**Comment by TheBB** [comment]
Closing as outdated, vendored library removed.
