### ISSUE TITLE
C-r doesn't prompt for a register

### ISSUE THREAD

**Issue by duianto** [emacs-evil/evil#1285]
# Issue type
- Bug report

# Environment

Emacs version: GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
Operating System: Windows 10 1903
Evil version: Evil version 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Open a new buffer: `C-x b` `test` `RET`
- Enter insert state: `i`
- Type: `abc`
- Exit to normal state: `ESC`
- Select the word: `viw`
- Store the selection in the `a` register: `"ay`
- Open a new line below: `o`
- Insert from a register: `C-r`

# Expected behavior
`"` (double quote) should appear, indicating that it's waiting for a register key to be pressed.

# Actual behavior
`abc` is inserted without the `"` prompt appearing.

# Further notes
The expected behavior is observed in Vim:
>VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2020 23:02:28)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-352
Compiled by appveyor@APPVYR-WIN

The issue was previously reported in the Spacemacs repository:
C-r in insert mode should prompt for register to pull from. https://github.com/syl20bnr/spacemacs/issues/9894

Miciah found a possible solution/workaround:
https://github.com/syl20bnr/spacemacs/issues/9894#issuecomment-405063789

>The following resolves the problem for me and not seem to cause any new problems:
```elisp
(add-hook 'evil-visual-state-exit-hook (lambda () (setq evil-this-register nil)))
```

Evaluating that expression results in the expected behavior.

**Comment by axelf4** [comment]
I cannot reproduce this using `make emacs` on the current master branch (commit 13f01f6245629a8a5c402ca51a4738c96e4b2315).

**Comment by duianto** [comment]
Confirmed.
Evil version 1.15.0
GNU Emacs 28.1 (build 52, x86_64-w64-mingw32) of 2022-04-04

In insert state: `C-r` shows `"`
and pressing `a` inserts register a's contents: `abc`
