### ISSUE TITLE
gI not same as vim, works the same as I

### ISSUE THREAD

**Issue by mangelozzi** [emacs-evil/evil#1287]
# Issue type
- Bug report

# Environment
Emacs version: 26.3
Operating System: Ubuntu 18.04
Evil version: Can't figure it out even with googling. Installed from MELPA a few days ago
Evil installation type: MELPA
Graphical/Terminal: Graphical

# Reproduction steps
1. Open a new file, type "   hello"
2. Enter normal mode.
3. Press gI (Capital i)

# Expected behavior
The cursor to go to column 1.

# Actual behavior
The cursor goes to the start of hello (after the whitespace).

**Comment by TheBB** [comment]
We don't actually have an implementation for `gI`. I guess you're seeing the behaviour of `gi` instead. You can check if you do `C-h k gI`. I get something like

> g i (translated from g I) runs the command evil-insert-resume

I'll tag this as an enhancement request then, not as a bug, because it's really just a missing feature.

**Comment by michael-angelozzi** [comment]
Fair enough. When reading about evil mode, before I started making the switch, I read an article which said Evil's standard is VIM, and if it doesnt work like VIM, then its considered a bug, but maybe that was just a bit of poetic license on the writers side.

**Comment by axelf4** [comment]
This can be closed as it was fixed by PR #1502.
