### ISSUE TITLE
'dd' with whitespace-mode sometimes raises 'wrong-type-argument wholenump -[integer]'

### ISSUE THREAD

**Issue by hisnawi** [emacs-evil/evil#1297]
This has been driving me insane for a while.
I first thought it was a spacemacs problem but it turned out to be an "Evil" related issue.

This is a copy/paste from the cross issue:

When placed on a whitespace character at the beginning of the line, using dd to delete a line (or yy to yank, gcc to comment, likely more) results in the error wrong-type-argument wholenump -5. This does not happen with D.

This seemingly only happens with whitespace-mode enabled. I tried debugging with only evil and whitespace-mode (using make emacs in a fresh evil source dir) and did not encounter this issue even with the same reproduction method.

I can't confirm this, but after testing for a minute or so it seems like this only happens when the line contains or is immediately preceded or followed by "invalid" whitespace (e.g. a line containing only non-newline whitespace or that has trailing whitespace).

After more testing, I have determined that the error occurs when either

    1. Trying to perform such an action on a line when the cursor is placed on a whitespace character in column 0. In this case, the error is random and I sometimes have to keep undoing the action (in case of deleting), moving back and forth between lines, and trying again in order to encounter it.
    2. Trying to perform such an action after moving the cursor up or down off of the second whitespace character in a line and not having moved left or right. When the cursor is first moved up or down, it will jump to column 0. With this method, the error occurs every time.

**Comment by JadElClemens** [comment]
Thanks for cross-reporting!

See [here](https://github.com/syl20bnr/spacemacs/issues/12651) for the issue reported in the spacemacs repo. Slightly more details there.

**Comment by scsmithr** [comment]
I believe this might be a bug in Emacs itself.

I run into this error most frequently when jumping up and down a buffer via `C-u` and `C-d`. Evil's `evil-ensure-column` uses `temporary-goal-column` to calculate the column to jump to. In some cases the value for `temporary-goal-column` occasionally gets set to `(-5 . 0)` (or similar), and `evil-ensure-column` will normalize that to `-5` when calling `line-move-to-column`.

The only place where I can find that would set a cons pair with a possibly negative value for `temporary-goal-column` was at https://github.com/emacs-mirror/emacs/blob/9370a4763aacbb9278b5be9c92a2484e3652bc29/lisp/simple.el#L7388-L7391.

Every time I got the wholenump error, I evaluated the following via `M-:` and got `-5` back:

```elisp
(/ (float (- (car (posn-x-y (posn-at-point)))
             (line-number-display-width t)))
   (frame-char-width))
```

This is the same expression as what's in the above link, just without the intermediate variables.

In most cases, I get 65 when evaluating `(car (posn-x-y (posn-at-point)))` when my cursor is at the beginning of a line. I also get 65 when evaluating `(line-number-display-width t)`. However, I'll occasionally get 0 for `(car (posn-x-y (posn-at-point)))` which would explain the negative value. I don't know enough about the Emacs code base to understand why this expressions returns 0 sometimes. I saw that @Eli-Zaretskii has touched that part of the code base most recently, so they might be able to chime in.

I'm on Emacs 28.1, haven't had a chance to test against other versions of emacs. I also don't have reproduction steps other than continually pressing `C-u` to reach the top of a buffer then continually pressing `C-d` to reach the bottom. Eventually the the "wholenump" error shows up.

**Comment by Eli-Zaretskii** [comment]
If you can come up with a simple enough recipe starting with `emacs -Q` and demonstrating the issue with `whitespace-mode`, I will look into it.

**Comment by Eli-Zaretskii** [comment]
I cannot reproduce the problem, with the above recipe, neither in Emacs 28.1 nor with the current master branch of the Emacs Git repository.  I always get zero value of `temporary-goal-column` after `C-n`.

Perhaps the recipe is not detailed enough, and I didn't perform exactly the same steps as you did?  For example, in which buffer to paste those 4 lines, and how to evaluate them?  IOW, please try to show a more detailed, step-by-step, recipe, with all the commands and key sequences explicitly mentioned.

**Comment by Eli-Zaretskii** [comment]
Sorry, still not reproducible.

Does this happen for you with any font and any font size?  Or does it only happen for some fonts/sizes?

If it happens for any font, then I have no idea why I cannot reproduce this.

**Comment by scsmithr** [comment]
This seems to happen no matter the font or font size I pick. Specifically I ran each of these expressions in turn and repeated the above steps:
```elisp
(set-face-attribute 'default nil :family "PragmataPro Mono" :height 120 :weight 'normal)
(set-face-attribute 'default nil :family "PragmataPro Mono" :height 100 :weight 'normal)
(set-face-attribute 'default nil :family "Source Code Pro" :height 120 :weight 'normal)
(set-face-attribute 'default nil :family "Source Code Pro" :height 100 :weight 'normal)
(set-face-attribute 'default nil :family "Fira Mono" :height 120 :weight 'normal)
(set-face-attribute 'default nil :family "Fira Mono" :height 100 :weight 'normal)
```

To make sure it wasn't something with Arch, I spun up an Ubuntu 22.04 vm on Google Cloud and installed emacs via `apt update && apt install emacs` on that vm. Below is a short mp4 showing a reproduction on that vm using the steps I've listed above. 

https://user-images.githubusercontent.com/4040560/168129862-33de4d07-c76b-48c4-968d-4a3bbe302a09.mp4

**Comment by Eli-Zaretskii** [comment]
I believe you.  I just cannot reproduce this on my machine, and without that I cannot debug this.

I even tried Source Code Pro font, and still no cigar.  Sorry.

**Comment by scsmithr** [comment]
No worries, the linked PR fixes the immediate issue with evil passing around negative numbers, so that's probably good enough for now.

When I have time, I'll try to dive in deeper into them emacs code base and see what's up.
