### ISSUE TITLE
:delmarks doesn't appear to do anything

### ISSUE THREAD

**Issue by tmalsburg** [emacs-evil/evil#1301]
- Bug report

# Environment

Emacs version: `GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-04-05`
Operating System: Ubuntu 18.04
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: under X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Create a mark, e.g. `ma` in normal mode.
- To confirm: move point somewhere else and then `'a` (point jumps to mark).
- In normal mode: `:delmarks!` (should delete all marks)
- To test: move point somewhere else and then `'a` (point still jumps to mark).

Likewise `:delmark a` doesn't work either.  No error message.

# Expected behavior
`:delmarks` should delete marks but doesn't.

# Actual behavior
Marks still there.

# Further notes:
Relevant Vim documentation:
https://vimhelp.org/motion.txt.html#%3Adelmarks

**Comment by tomdl89** [comment]
Should be closed by #1428 - can you confirm @tmalsburg

**Comment by tmalsburg** [comment]
Works.  Thank you!!
