### ISSUE TITLE
Replacing visual selection with expression register

### ISSUE THREAD

**Issue by bepvte** [emacs-evil/evil#1305]
# Issue type

- Bug report

# Environment
Emacs version: GNU Emacs 27.0.91 (build 2, x86_64-redhat-linux-gnu, GTK+ Version 3.24.18, cairo version 1.16.0) of 2020-04-29
Operating System: Fedora 32
Evil version: Evil version 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs

- Select something in visual mode
- Type `"=p(+ 1 1)`
# Expected behavior

Selection should be replaced with 2
# Actual behavior

Selection is either deleted or an error of "kill ring is empty" appears

**Comment by tomdl89** [comment]
@bepvte I can't replicate this in make emacs in master. Can you still?
