### ISSUE TITLE
Visual linewise mode, movement binding not working

### ISSUE THREAD

**Issue by joshcho** [emacs-evil/evil#1307]
Visual linewise mode, movement bindings

Bug report

# Environment

Emacs version: 26.3
Operating System: macOS Catalina
Evil version: 1.14
Evil installation type: MELPA stable
Graphical/Terminal: terminal emulator
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): no

# Reproduction steps
- Start Emacs
- Shift+v (linewise visual mode)
- Eval (evil-next-line 10)
- returns nil

- Try this with any other visual mode (block or regular), and it works. The above only doesn't work with linewise visual mode.

# Expected behavior
As in vim, linewise visual mode should select 10 lines including and below the current line. (like 10j in vim)

# Actual behavior
Does nothing.

# Further notes
I tried evil-scroll-down, which works, but I want to be able to move my cursor without moving my screen.

**Comment by asymmetric** [comment]
@joshcho I've seen this too. How come you've closed the issue?

**Comment by joshcho** [comment]
@asymmetric The issue is a duplicate of https://github.com/emacs-evil/evil/issues/826. I changed my settings according to the link and it works now.

**Comment by joshcho** [comment]
> I was told I should use `evil-define-motion` for this, and so I did
> 
> 
> ```
> (evil-define-motion move-15-lines-down ()
>   (evil-next-visual-line 15))
> ```
> 
> And now it works. If that is the intended behavior then close this issue.
> 
> However, this seems a little unnecessary from my perspective (not knowing the internals of Evil), since `evil-next-visual-line` takes an argument. One could perhaps reasonably expect my original attempt to work.
> 
> By the way, I suggest including the documentation for `evil-define-motion` from [the PDF manual](https://raw.githubusercontent.com/emacs-evil/evil/master/doc/evil.pdf) in the docstring, so it's easily accessible in Emacs.

**Comment by joshcho** [comment]
> > One could perhaps reasonably expect my original attempt to work.
> 
> Not really. Keep in mind that `evil-define-motion` does not only define a command, but also adds metadata to it that is read in by Evil at a different time (like, in visual line mode when deciding what to do with the visual selection). Defining a plain function will _not_ do this and therefore fail behaving as expected. The specific keyword responsible for correct visual selection behavior is most likely `:keep-visual` as it's used in the `evil-define-motion` macro and mentioned in the commentary above the visual state definition:
> 
> > If the command is a motion, the translation is postponed until a non-motion command is invoked (distinguished by the :keep-visual command property).
> 
> This also means that you should be able to achieve your goal with `evil-declare-motion` as it sets that metadata.
> 
> Documentation fixes are always a good idea, feel free to make a PR for it.
