### ISSUE TITLE
evil conflict with ess

### ISSUE THREAD

**Issue by mcooganj** [emacs-evil/evil#1315]
#885 Issue type
- Bug report

Emacs version: 26.3
Operating System: Windows 10
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): no (not applicable)

# Reproduction steps
- Start Emacs
- Open R file & R
- send some R code to the terminal
- put point over a token and use a short-cut to send a function operating on 'token' to the terminal. 

```
(defun r-summary-at-point ()
  (interactive)
  (let ((sym (ess-symbol-at-point)))
    (if sym
        (ess-send-string (get-buffer-process "*R*") 
                         (concat "summary(" (symbol-name sym) ")\n") t)
      (message "No valid R symbol at point"))))

(define-key ess-r-mode-map (kbd "C-c :") 'r-summary-at-point)

```
# Expected behavior
it should send `summary(token)` to the R terminal

# Actual behavior
`Wrong type argument: processp, nil`

# Further notes
My hunch was that this is something about how to map keys and that the interaction with ESS is making things more complex, but a little googling suggested that this type of error may be something else. 

I tried an `evil-define-key` mapping, but it yielded the same error.  
`(evil-define-key 'normal ess-mode-map (kbd "C-s") 'r-summary-at-point)`

**Comment by TheBB** [comment]
Can you be more specific what the error is? If `(get-buffer-process "*R*")` returns nil when it shouldn't, I doubt that is evil's fault.

A backtrace would also help determine what is wrong.

**Comment by mcooganj** [comment]
Sorry I’m very new to emacs — if you could coach me a little I’d be happy
to give you what you require.

**Comment by mcooganj** [comment]
stepping through the code using `backtrace` allowed me to see that you're right -- the problem was with `(get-buffer-process *R*)`.  For some reason the name of the buffer that the `R` process runs in is now `*R:R*`; once i changed my function to find the buffer's new name, things worked once again. 

I"m interested to know, is this change of name a side-effect from using `evil`?
