### ISSUE TITLE
file name register % not work

### ISSUE THREAD

**Issue by tshu-w** [emacs-evil/evil#1316]
# Issue type

- Bug report
# Environment

Emacs version: GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.4.0, Carbon Version 162 AppKit 1894.4) of 2020-03-27
Operating System: macOS Catalina 10.15.5
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: both
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- open any file
- use `:reg` to see registers

# Expected behavior
filename register % should have the current file name.

# Actual behavior
filename register % is empty.

# Minimal config
```emacs-lisp
;;; emacs -nw -Q -l test.el

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org"   . "https://orgmode.org/elpa/")
                         ("gnu"   . "https://elpa.gnu.org/packages/")))

;; initialize packages
(unless (bound-and-true-p package--initialized) ; To avoid warnings in 27
  (setq package-enable-at-startup nil)          ; To prevent initializing twice
  (package-initialize))

;; setup `use-package'
(unless (package-installed-p 'use-package)
  (when (not package-archive-contents)
    (package-refresh-contents))
  (package-install 'use-package))

(eval-when-compile
  (setq use-package-always-defer  t
        use-package-expand-minimally t)
  (if init-file-debug
      (setq use-package-verbose t
            use-package-minimum-reported-time 0
            use-package-expand-minimally nil
            use-package-compute-statistics t
            use-package-inject-hooks t
            debug-on-error t))

  (require 'use-package))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(use-package evil
  :ensure t
  :init
  (setq evil-want-keybinding nil)
  (evil-mode))
```

<img width="1920" alt="Screen Shot 2020-05-31 at 10 00 56 AM" src="https://user-images.githubusercontent.com/13161779/83342820-54804a80-a326-11ea-90c8-10fda3bb87f4.png">

**Comment by mohkale** [comment]
how strange, I've got the same issue when using `evil-show-registers` but if I'm in the buffer in insert state and enter `C-r %` it enters the file name as appropriate.
