### ISSUE TITLE
evil-ex substitute :'<,'>s/$/, adds an additional replacement on the empty line.

### ISSUE THREAD

**Issue by templateK** [emacs-evil/evil#1321]
# Issue type

- Bug report

# Environment

```
Emacs version: 27.0.91
Operating System: macOS Mojave
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a make emacs session (see CONTRIBUTING.md): Yes
```

# Reproduction steps

1. Start Emacs (make emacs)

2. Paste the following text and additional empty line below the `wat`

  ```
  foo
  bar
  wat
  <empty line>
  ```

3. Enter visual line mode on all three lines which contains non-empty texts

4. Run evil-ex substitution by following: `:'<,'>s/$/,` 

# Expected behavior

  ```
  foo,
  bar,
  wat,
  <empty line>
  ```

# Actual behavior

  ```
  foo,
  bar,
  wat,
  ,
  ```

# Further notes

- When the right below line of the end of visual line/block is non-empty, it behaves correctly.

**Comment by axelf4** [comment]
Similarly, I found that `:s/\w*/foo` also affects the line below.
