### ISSUE TITLE
Yet another bug with evil-scroll-up, causing by tab-line

### ISSUE THREAD

**Issue by sorawee** [emacs-evil/evil#1322]
The very same problem as #713, #965, and #1063, but it's a problem with `tab-line` in Emacs 27 rather than `header-line`. See also a merged PR that almost fixed the problem and my merged PR that also fixed the problem: #1154 and #1238.

# Issue type
- Bug report

# Environment

Emacs version: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.4.0, NS appkit-1894.40 Version 10.15.4 (Build 19E287)) of 2020-06-07

Operating System: macOS Catalina
Evil version: Evil version 1.14.0
Evil installation type: via Doom Emacs
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps

- Open a file whose content doesn't fit the screen
- `C-u` and `C-d` from the top of the file to the bottom of the file and vice versa.

# Expected behavior
It scrolls normally.

# Actual behavior

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  evil-scroll-down(nil)
  funcall-interactively(evil-scroll-down nil)
  call-interactively(evil-scroll-down nil nil)
  command-execute(evil-scroll-down)
```

**Comment by sorawee** [comment]
The fix should be pretty simple. Will submit a PR.

**Comment by sgleizes** [comment]
I just stumbled upon this issue and was glad to find your patch.
May I ask if you can open the PR so that we can hope to see this merged? Thanks!

**Comment by sorawee** [comment]
There's an open PR at https://github.com/emacs-evil/evil/pull/1323

The Evil maintainers have been busy and haven't merged it.

**Comment by countvajhula** [comment]
+1 Have been seeing this issue of late as well.
