### ISSUE TITLE
Evil Needs a User Guide

### ISSUE THREAD

**Issue by davidkrauser** [emacs-evil/evil#1328]
# Issue type
- Enhancement request

# Overview
As a Vim to Emacs convert, I had a lot of trouble getting started with Evil mode in Emacs. The current Evil documentation does a good job describing how to install Evil, and it does a good job describing how to configure Evil; however, it doesn't provide much guidance for new Evil users in actual usage. I would love to see a detailed User Guide for Evil users.

Some possible content for this user guide:
- A quick start of Evil + Emacs keybindings and features
- A section describing differences between what a user expects in Vim vs. Evil (Emacs window management was a big stumbling block for me here!)
- A best practices section (get the most out of Evil, packages to add, settings to tweak, etc.)
- A common pitfalls section (packages, features to avoid, etc.)

I'd be happy to help with this effort if you think it would be useful.

Anyway, thanks for making a great package :-)

**Comment by davidkrauser** [comment]
Sorry, I accidentally hit the submit a bit too early - I'm updating the description now with more details.

**Comment by TheBB** [comment]
I'll be happy to accept documentation PRs, especially from people who have all the minutiae in recent memory. I don't, any more. :-)

**Comment by wasamasa** [comment]
There you go: https://github.com/noctuid/evil-guide
