### ISSUE TITLE
Can't run a macro a second time

### ISSUE THREAD

**Issue by juacq97** [emacs-evil/evil#1331]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-19
Operating System: Arch Linux
Evil version: 1.14.0
Evil installation type: Melpa
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Record a macro with Q-<character>, example Q-1
- Play the marco with @-<character>, example @-1
-Play the macro again

# Expected behavior
The macro is played again

# Actual behavior
The macro isn't played and I get an error `After 0 kbd macro iterations: evil-execute-macro: Keyboard macro terminated by a command ringing the bell`

**Comment by TheBB** [comment]
I don't understand your reproduction steps. `Q-1`? `Q` isn't how you record a macro.

> Tested in a `make emacs` session (see CONTRIBUTING.md): No

We have this question for a reason.

**Comment by juacq97** [comment]
My bad, I mean `q-1`, a lowercase q and the any character.

I ran `make emacs`. I get the next error:

```
F evil-test-flyspell-motions
    Test flyspell motions
    Info: Simple
    (ert-test-failed
     ((should
       (string=
	(buffer-substring
	 (max ... ...)
	 (point))
	before))
      :form
      (string= "I cannt tpye " "I cannt tpye for ")
      :value nil))
```

**Comment by TheBB** [comment]
Sorry, I still can't reproduce. Is the hyphen supposed to be 'any' character? This is what I tried:

- `qa1xq` record a macro in register *a* that deletes a character
- `@a@a` replay macro, works fine

`q` followed by any character followed by `1` is an incomplete macro.

> I ran `make emacs`. I get the next error:

I'm not sure why the tests are failing for you, but when asked whether you want to run the tests you can safely answer no. The point is just to reproduce the error in a `make emacs` instance.

**Comment by juacq97** [comment]
I tried tpo reproduce the error on the `make emacs` instance, I tried two macros:

- `q1ihello<ESC>q`: write the word "hello". I can reproduce it at many times I want, just as expected.
-`df"i[[<ESC>f"a][<ESC>ldf>f<Da]]` (`<ESC>` means press the ESC key): This is the one that trigger my error: I have a list of links like this `<DT><A HREF="https://doc.opensuse.org/" ADD_DATE="1543974418" LAST_MODIFIED="1590776675">openSUSE Documentation</A>` on a html file and I want to transform it to org-mode links with that macro. I can reproduce the macro just one time, the second time I get the error. This happens both the normal emacs and the `make emacs` instance
