### ISSUE TITLE
`x` no longer modifies register

### ISSUE THREAD

**Issue by bsuh** [emacs-evil/evil#1335]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.3.0, Carbon Version 162 AppKit 1894.3) of 2020-03-28
Operating System: macOS Catalina 10.15.5
Evil version: Evil version 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- In normal mode, press `x`.
- In normal mode, press `p`.

# Expected behavior
- `p` should paste the deleted character.

# Actual behavior
- `p` pastes whatever was in register, before pressing `x`

# Further notes
Reverting the changes to `evil-delete-char` operator in #1333 fixes the problem.

**Comment by TheBB** [comment]
Thanks, you're right. That change can't have been right.

**Comment by bsuh** [comment]
Wow that was a fast response
![image](https://user-images.githubusercontent.com/47231/87848576-7877fb00-c896-11ea-84b8-e96cd3383298.png)

Thanks!

**Comment by TheBB** [comment]
It's easier to respond when I'm the one who fucked up, as opposed to bugs which have been around for ages. :-P
