### ISSUE TITLE
Normal state entry hook called over and over

### ISSUE THREAD

**Issue by angrybacon** [emacs-evil/evil#1341]
# Issue type

- Question

# Environment

Emacs version: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2020-07-06
Operating System: macOS Catalina 10.15.5
Evil version: evil-git-3312345
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps

```elisp
(use-package evil
  :preface
  (defun me/hydra-evil-with-delay ()
    ;; (run-at-time 0.1 nil #'hydra-evil/body)
    (hydra-evil/body))
  :hook
  (after-init . evil-mode)
  (evil-normal-state-entry . me/hydra-evil-with-delay))
```

# Expected behavior

Emacs starts, Evil kicks in, normal state is active, the Evil hydra shows up.

# Actual behavior

Backtrace: http://ix.io/2sI9

# Further notes

With the delay, Emacs just freezes in appearance and take 99% of the CPU.

Possibly related: #685

**Comment by axelf4** [comment]
Appears to just be Evil initializing itself in a buffer that pops up... Try disabling `evil-local-mode` for the buffer in question with e.g.
```elisp
(setf (alist-get "^ \\*LV\\*$" evil-buffer-regexps nil nil #'equal) nil)
```
