### ISSUE TITLE
How to define functions like vim?

### ISSUE THREAD

**Issue by HouraisanReimu** [emacs-evil/evil#1349]
# Issue type
- Question

How to define functions like vim? I want to define command `:%s/abc/def/g` as a function, how can I implement it?

**Comment by wasamasa** [comment]
By writing vanilla Emacs Lisp code such as the following:

```elisp
(defun my-command ()
  (interactive)
  (goto-char (point-min))
  (while (re-search-forward "def" nil t)
    (replace-match "def")))
```

While one could try to reuse Evil's code for this, it's not advisable to do so unless you want to extend Evil itself.
