### ISSUE TITLE
"'<,'>g/fee/copy ." different behaviour from vim

### ISSUE THREAD

**Issue by Andre0991** [emacs-evil/evil#1353]
# Issue type
- Bug report
# Environment

Emacs version:GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.4.0, NS appkit-1894.40 Version 10.15.4 (Build 19E287)) of 2020-08-26
Operating System: macOS Catalina
Evil version: 1.14.0
Evil installation type: I use Doom Emacs, it uses straight, I suppose it gets evil from melpa
Graphical/Terminal: graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Past this:
```
foo-bar-fee
foo-bar-xum
bar-fee
bar-xum
```
- Select all text and use `'<,'>g/fee/copy .`

# Expected behavior
This is the result in `vim`:
```
foo-bar-fee
foo-bar-fee
foo-bar-xum
bar-fee
bar-fee
bar-xum
```

# Actual behavior
```
foo-bar-fee
bar-xum
foo-bar-xum
bar-fee
bar-fee
bar-xum
```

**Comment by axelf4** [comment]
I cannot reproduce this using the latest version of Evil.
