### ISSUE TITLE
evil-search ? doesn't search backwards if current location matches

### ISSUE THREAD

**Issue by saurik** [emacs-evil/evil#1355]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu) of 2020-03-26, modified by Debian
Operating System:  Ubuntu 20.04.1 LTS
Evil version: Evil version 1.14.0
Evil installation type: MELPA (?)
Graphical/Terminal: mintty (Cygwin terminal, ssh'd to a Linux machine)
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): NO

(I couldn't figure out how to set evil-search without using a .emacs file because I am not good at emacs.)

# Reproduction steps
- Start Emacs
- (evil-select-search-module 'evil-search-module 'evil-search)
- put "hello world world hello" in your buffer

- go to the end of the line
- search backwards for world using "?world"
- search backwards again using "?"

(alternatively)

- put your cursor on the "w" of the second "world"
- search backwards for world using "?world"

# Expected behavior
The cursor should move to the first "world".

# Actual behavior
The cursor remains on the second "world".

**Comment by saurik** [comment]
(I figured out how to turn on evil-search while using make emacs; the issue definitely happens there.)

**Comment by tomdl89** [comment]
Fixed by #1436
