### ISSUE TITLE
Visual mappings have no effect in visual line mode

### ISSUE THREAD

**Issue by iansinnott** [emacs-evil/evil#1359]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2020-08-12
Operating System: macOS Catalina
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start emacs without any config `emacs -Q`
- Paste the following code into the scratch buffer:
```emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)

;; Download Evil
(unless (package-installed-p 'evil) (package-install 'evil))

;; Enable Evil
(require 'evil)
(evil-mode 1)

(defun +evil-five-down () (interactive) (evil-next-line 5))
(defun +evil-five-up   () (interactive) (evil-previous-line 5))

(evil-define-key 'visual 'global-map "J" '+evil-five-down)
(evil-define-key 'visual 'global-map "K" '+evil-five-up)

;; Not sure if 'visual-line is valid, just thought I'd try it
(evil-define-key 'visual-line 'global-map "J" '+evil-five-down)
(evil-define-key 'visual-line 'global-map "K" '+evil-five-up)
```
- `M-x eval-buffer`
- Create a visual selection using `V` (shift+v) then press `J` or `K`. The cursor does not move.

# Expected behavior
The cursor should jump up or down by 5 lines.

# Actual behavior
The cursor does not move.

# Further notes

Notably, visual mode and visual block mode work as expected with this mapping which is why I'm raising it here.

I'm rather new to emacs config. Apologies if I'm missing something obvious.

**Comment by TheBB** [comment]
The binding is fine, it's just that your function is not properly defined as a line-based motion.

```elisp
(evil-define-motion +evil-five-down (count)
  :type line
  (evil-next-line (* 5 (or count 1))))
```

**Comment by iansinnott** [comment]
Thank you! I'm curious why this is needed, or why it isn't needed for standard `v` mode. Anyway, this solved the issue.

**Comment by TheBB** [comment]
I don't remember the details but there's a post-command hook in visual line mode that evil uses to ensure that, no matter what, the selection is always a whole number of lines. To do this it inspects the properties of the previous command.
