### ISSUE TITLE
Paste over visual does not register the replaced text like vim

### ISSUE THREAD

**Issue by triplc** [emacs-evil/evil#1365]
# Bug (may be)

- Bug report

# Environment

Emacs version: 27.1
Operating System: Archlinux, kernel 5.8.13
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Both GUI and in terminal
Tested in a `make emacs`: No, I use the emacs provided by Archlinux

# Reproduction steps

- Start Emacs: emacs -Q

When pressing `p` to paste text over a visual text, that visual text is replaced but not saved to the register.

Check variable: evil-kill-on-visual-paste, and it is "t".

# Expected behavior:

The  replaced text should be registered for the next paste.

# Actual behavior:

The replaced text is deleted.

# Further notes:

I notice that it was ok --like vim-- in the past. So I believe it is a bug of some newer evil version

**Comment by tomdl89** [comment]
I can replicate this. It is being caused (in part, at least) by this:
```
(evil-delete evil-visual-beginning evil-visual-end
             (evil-visual-type) ?_)
```
[here](https://github.com/emacs-evil/evil/blob/373a57e5fc41b9597ed7f7223806ae2ffc16ade6/evil-commands.el#L2071)
I'll take a look soon if I can. I know it was part of a change done to fix behaviour related to `evil-kill-on-visual-paste` so need to understand what edge cases were being addressed.

**Comment by tomdl89** [comment]
Fixed in this PR. Hopefully gets merged soon.
