### ISSUE TITLE
How to properly overwrite a motion binding using evil-define-key

### ISSUE THREAD

**Issue by angrybacon** [emacs-evil/evil#1370]
# Issue type

- Question

# Environment

<dl>
  <dt>Emacs version:</dt>
  <dd>GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G2021)) of 2020-09-07</dd>
  <dt>Operating System:</dt>
  <dd>macOS Catalina</dd>
  <dt>Evil version:</dt>
  <dd>Evil version 1.14.0</dd>
  <dt>Evil installation type:</dt>
  <dd>MELPA</dd>
  <dt>Graphical/Terminal:</dt>
  <dd>Graphical</dd>
</dl>

# Reproduction steps

Minimal Evil configuration that I use and could reproduce with (no extra bindings, no extra text objects).

```elisp
(use-package evil
  :hook
  (after-init . evil-mode)
  (with-editor-mode . evil-insert-state)
  :preface
  (defun me/evil-indent (original &rest arguments)
    "Like `evil-indent' but save excursion."
    (save-excursion
      (apply original arguments)))
  :commands
  (evil-define-key)
  :custom
  (evil-echo-state nil)
  (evil-emacs-state-cursor 'bar)
  (evil-want-C-u-scroll t)
  (evil-want-keybinding nil)
  :config
  (advice-add 'evil-indent :around #'me/evil-indent))

(use-package helpful
  :config
  (evil-define-key* 'normal helpful-mode-map
    "q" #'quit-window
    "<backtab>" #'backward-button
    "<tab>" #'forward-button))
```

1. Start Emacs
1. Open a `helpful` buffer

# Actual behavior

✔️ <kbd>q</kbd> runs `quit-window`
✔️ <kbd>Shift</kbd><kbd>Tab</kbd> runs `backward-button`
:x: <kbd>Tab</kbd> runs `evil-jump-forward` instead of `forward-button`

# Further notes

Could be that my code runs before Evil applies the motion bindings to the `helpful-mode-map`. How do I prevent that?

**Comment by TheBB** [comment]
It's not so easy for me to figure out because your repro isn't very minimal (what is helpful? did you really need the advice to repro? etc), but you probably need `(kbd "<tab>")`. *evil-define-key\** does not apply *kbd* for you. The backtab binding maybe works because helpful already has it.

**Comment by angrybacon** [comment]
@TheBB Indeed that was it good catch! Thanks for the help.
