### ISSUE TITLE
Can't move more than 1 line in visual-line state without using C-u

### ISSUE THREAD

**Issue by SpringHan** [emacs-evil/evil#1371]
# BUG

- Bug report

# Environment

Emacs version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-29
Operating System: Arch Linux
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs

# Expected behavior
I hope I can move in lines normally in visual-line state.

# Actual behavior
When I use Evil, every time I tried to move more than 1 line in visual-line state can be a very difficult thing.(Not all of the visual mode, I can move in lines easily in visual state or visual-block state.)  
I tried to use function to solve it:
```emacs-lisp
(defun spring/evil-movement-do (direction num)
	"A function to do movements in each line in `evil-mode'."
	(if (eq evil-state 'visual)
			(cond ((eq direction 'up)
						 (dotimes (n num) (evil-previous-line))) ; It can't work.
						((eq direction 'down)
						 (dotimes (n num) (evil-next-line))))
		(cond ((eq direction 'up)
					 (evil-previous-line num))
					((eq direction 'down)
					 (evil-next-line num)))))
```
But it can't work.(When I use this funciton, the cursor went to the next line. When I finished my motion, it backed to the original place.)  I can only use `C-u` with number to move more than 1 lines.

# Further notes

**Comment by TheBB** [comment]
Same issue and solution as #1359 probably.

**Comment by SpringHan** [comment]
Oh, it's really useful.Thanks!
