### ISSUE TITLE
evil-redo does not work if evil-undo-system set to undo-tree

### ISSUE THREAD

**Issue by diamond-lizard** [emacs-evil/evil#1372]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu) of 2020-09-22
Operating System: Gentoo Linux amd64
Evil version: evil-git-32b2783
Evil installation type: manual
Graphical/Terminal: terminal
Tested in a `make emacs` session: Yes

# Reproduction steps
- make emacs
- eval the following
```
  (require 'undo-tree)
  (global-undo-tree-mode)
  (setq evil-undo-system 'undo-tree)
```
- insert some text
- in normal mode, type ```u``` to undo, then ```control-r``` to redo

# Expected behavior
What was undone should have been redone

# Actual behavior
No redo happens.  Instead, a message appears:
Customize 'evil-undo-system' for redo functionality.

# Further notes
This does seem to work if ```evil-undo-system``` is set using ```M-x customize-variable```, but not with the setq as described above, and I can't figure out why.

**Comment by TheBB** [comment]
Because it has a setter function. Customize calls it but setq doesn't.
Either set it before evil loads, use customize or call the setter manually.
