### ISSUE TITLE
Quitting command-line window after c_CTRL-F leads to bad state

### ISSUE THREAD

**Issue by axelf4** [emacs-evil/evil#1379]
# Issue type
- Bug report

# Environment

Emacs version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu)
Operating System: NixOS 20.09
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Terminal with tmux
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No, but tested with only straight.el and Evil

# Reproduction steps
- Start Emacs
- Press <kbd>:</kbd> to enter command-line mode
- Press <kbd>CTRL-F</kbd> to open the command-line window
- Press <kbd>CTRL-W</kbd><kbd>CTRL-Q</kbd> to quit the command-line window

# Expected behavior
After quitting the command-line window we should have exited command-line mode and be back in command mode.

# Actual behavior
Instead all operators now act immediately on lines without waiting for motion and the mode indicator in the bottom-left is stuck showing `:`.

# Further notes

**Comment by ChoppinBlockParty** [comment]
Can observe the same issue with Emacs 26.3 on Ubuntu 20 using X11 UI.
