### ISSUE TITLE
Is there a way to use elisp expressions in ex-commands?

### ISSUE THREAD

**Issue by f4nyc** [emacs-evil/evil#1381]
# Issue type
- Enhancement request
- Question

# Problem
Is there a way to use elisp expressions in ex-commands?
For example
```
a
b
c
```
I expect this replacement command to work 
```
:%s/^/<some escape symbol>(+ (line-number-at-pos) 1)<some escape symbol>/g

```
and get the following result
```
2a
3b
4c
```
Thanks for your help !

**Comment by wasamasa** [comment]
For authoritative answers, study `evil-ex-grammar`. From that you can see that Ex supports top-level s-expressions (like `:(message "Hello")`), but nothing beyond that. What you ask for is more about the search/replace parts and the vanilla ones do support s-expressions using the `\,(...)` construct. See (info "(emacs) Regexp Replace") for further details.

**Comment by f4nyc** [comment]
Thanks for your nice helping !

**Comment by f4nyc** [comment]
> For authoritative answers, study `evil-ex-grammar`. From that you can see that Ex supports top-level s-expressions (like `:(message "Hello")`), but nothing beyond that. What you ask for is more about the search/replace parts and the vanilla ones do support s-expressions using the `\,(...)` construct. See (info "(emacs) Regexp Replace") for further details.

I would like to know  if Ex  supports s-expressions like `:'<,'>(message "%d" (line-number-at-pos))` ?

**Comment by wasamasa** [comment]
No. See the whole text you're quoting, it explains why.
