### ISSUE TITLE
`nil` state not working for `evil-set-leader`

### ISSUE THREAD

**Issue by lygamac** [emacs-evil/evil#1383]
# Issue type

- Bug report

# Environment

Emacs version: 27.1
Operating System: Windows 10
Evil version: 20201107.1830
Evil installation type: MELPA
Graphical/Terminal: GUI Emacs
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Install evil and add in `init.el`:
```
(use-package evil
  :ensure t
  :config
  (evil-mode 1))

(evil-set-leader nil (kbd "SPC"))
(evil-define-key 'normal 'global
  (kbd "<leader>x") 'execute-extended-command)
```
- Restart Emacs

# Expected behavior

Pressing <kbd>space</kbd> + <kbd>x</kbd> would call the function `'execute-extended-command`

# Actual behavior

When pressing <kbd>space</kbd> key, it acts like it's not a leader key (jumps to the next character).

# Further notes
```
(evil-set-leader 'normal (kbd "SPC"))
(evil-define-key 'normal 'global
  (kbd "<leader>x") 'execute-extended-command)
```
Does work.

And when defining localleader too, it won't work again: `(evil-set-leader 'normal (kbd "SPC"), (kbd ","))` or adding `(evil-set-leader 'normal "," t)` (localleader is undefined).

I followed this [guide](https://evil.readthedocs.io/en/latest/keymaps.html#leader-keys), and [this](https://github.com/noctuid/evil-guide#leader-key)

**Comment by tcstory** [comment]
met the same problem
