### ISSUE TITLE
`gv` doesn't work correctly after visual line-selection replace

### ISSUE THREAD

**Issue by geza-herman** [emacs-evil/evil#1387]
# Issue type

- Bug report

# Environment

Emacs version: both 26.3 and 28.0.50
Operating System: Debian unstable
Evil version: 20201107.1830
Evil installation type: MELPA
Graphical/Terminal: Happens both terminal and X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Enter some several-line text (I'll call this TextA)
- Enter some other several-line text below it (I'll call this TextB)
- Move to the first line of TextA, press `V`, select TextA and then press `y` (TextA is yanked here)
- Move to the first line of TextB, press `V`, select TextB and then press `P` (TextB is replaced with TextA)
- press `gv`

# Expected behavior
`gv` should select the newly pasted TextA

# Actual behavior
`gv` selects a line above the newly pasted TextA

# Further notes
Doing the same with char (`v`) or block (`C-v`) selection works correctly.

**Comment by tomdl89** [comment]
@geza-herman this should now be fixed in master. Please let us know if you notice otherwise.
