### ISSUE TITLE
evil-search-next highlight works little oddly

### ISSUE THREAD

**Issue by tttuuu888** [emacs-evil/evil#1389]
# Issue type

- Bug report

# Environment

Emacs version:  GNU Emacs 27.1 
Operating System:  Linux archlinux 5.9.11-arch2-1 
Evil version:  Evil version 1.14.0
Evil installation type:  MELPA
Graphical/Terminal:  Both
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  Yes

# Reproduction steps
- Start Emacs
 
make emacs
(in scratch buffer)
`/is`
`RET`
`n`
`n`

# Expected behavior
 
work same as Vim. 

# Actual behavior

1. `/is`
![1](https://user-images.githubusercontent.com/8042298/101232944-4e658f00-36f8-11eb-9c38-dfefad194265.png)
 -> all `is` are highlighted.

2. `RET`
![2](https://user-images.githubusercontent.com/8042298/101232966-663d1300-36f8-11eb-8058-28302f1bf9d9.png)
 -> unhighlited.

3. `n`
![3](https://user-images.githubusercontent.com/8042298/101232973-71903e80-36f8-11eb-8e6a-4c85c9dfffb5.png)
 -> only second `is` is highlighted.

4. `n`
![4](https://user-images.githubusercontent.com/8042298/101232978-8a98ef80-36f8-11eb-93c4-d164f493ad06.png)
 -> now all `is` are highlighted.

# Further notes
I tested both `make emacs` session and `emacs -Q` session and found same result.

Thanks.

**Comment by tomdl89** [comment]
By default, evil uses isearch for searching. This is how isearch's highlighting works. If you would like search behaviour more similar to vim (in more ways than just this) you could take a look at putting `(setq evil-search-module 'evil-search)` and the necessary keybindings in your config.
