### ISSUE TITLE
artist-mode does not work when evil-mode is on

### ISSUE THREAD

**Issue by johannesneyer** [emacs-evil/evil#1392]
# Issue type

- Enhancement request

# Environment

Emacs version: 27.1
Operating System: Arch
Evil version: master (d6cf668)
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Use minimal init.el from the [Installation section](https://github.com/emacs-evil/evil#installation)
- Start Emacs
- Open scratch buffer
- Run (artist-mode)

# Expected behavior
I am able to draw stuff using my mouse.

# Actual behavior
Holding down the left mouse button while moving the mouse makes a selection instead of printing characters.

**Comment by johannesneyer** [comment]
I got it working by adding a hook to artist-mode:
```elisp
(use-package evil
  :config
  (evil-mode)
  :hook
  (artist-mode . (lambda () (define-key evil-motion-state-map [down-mouse-1] nil))))
```

**Comment by wasamasa** [comment]
Consider using Emacs state instead.

**Comment by johannesneyer** [comment]
Ah nice, thanks:

```elisp
(use-package evil
  :config
  (evil-mode)
  :hook
  (artist-mode . evil-emacs-state)
```
