### ISSUE TITLE
How can I simply get the redo C-r function back?

### ISSUE THREAD

**Issue by ianpan870102** [emacs-evil/evil#1393]
I'm on Emacs 27 with the latest evil package installed.
I just simply need the original vim-like C-r functionality back, which redo's my previous undo. What's the easiest way to achieve this? (Mini rant)

**Comment by TheBB** [comment]
The message should tell you what to do. Install either undo-fu or undo-tree, if the latter then also enable undo-tree-mode. Then setthe undossystem variableto whichever package you chose.

**Comment by ianpan870102** [comment]
Cheers! Solved it.
