### ISSUE TITLE
Make Y behave like yy, copy whole line without moving a cursor evil command

### ISSUE THREAD

**Issue by Rareform** [emacs-evil/evil#1395]
# Issue type

- Question

# Environment

Emacs version: 
Operating System: 
Evil version: 
Evil installation type: 
Graphical/Terminal: 
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): 

# Expected behavior
Good day, I would really like to remap Y to copy the whole line instead of the standard behavior of copying the content from the cursor to the end of the line. That is, I want the shortkey Y to behave like yy, how can I realize it in the confige file? I am using doom-emacs. Thanks for your help! 

# Further notes

**Comment by TheBB** [comment]
https://evil.readthedocs.io/en/latest/settings.html#elispobj-evil-want-Y-yank-to-eol

You're describing the default evil behavior.
