### ISSUE TITLE
eager macro-expansion failure wrong number of arguments with emacs 28

### ISSUE THREAD

**Issue by codygman** [emacs-evil/evil#1403]
# Issue type
- Bug report

# Environment

Emacs version: "GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.16.0)"
Operating System: NixOS 21.03pre257780.e9158eca70a
Evil version: "Evil version 1.14.0"
Evil installation type: Melpa (used readme code directly then emacs -Q)
Graphical/Terminal: X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
```sh
[cody@nixos:/tmp]$ git clone git@github.com:emacs-evil/evil.git
Cloning into 'evil'...
remote: Enumerating objects: 84, done.        
remote: Counting objects: 100% (84/84), done.        
remote: Compressing objects: 100% (63/63), done.        
remote: Total 9118 (delta 37), reused 47 (delta 17), pack-reused 9034        
Receiving objects: 100% (9118/9118), 41.62 MiB | 5.76 MiB/s, done.
Resolving deltas: 100% (5914/5914), done.

[cody@nixos:/tmp]$ cd evil/

[cody@nixos:/tmp/evil]$ make emacs
Compute dependencies
emacs -Q -L . -L lib -l goto-chg.el -l evil-tests.el \
	--eval "(evil-mode 1)" \
	--eval "(evil-tests-initialize '() '() t)"

(emacs:16780): Gtk-WARNING **: 14:41:21.839: Theme parsing error: colors.css:71:44: Invalid number for color value
...
```

Messages buffer says:

```
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
define-obsolete-function-alias: Wrong number of arguments: (3 . 4), 2
```

# Expected behavior
no error

# Actual behavior

gives macro expansion and obsolte function alias error

# Further notes

https://www.reddit.com/r/emacs/comments/kqd9wi/changes_in_emacshead2828050_break_many_packages/

**Comment by TheBB** [comment]
Fixed in #1401

**Comment by unhammer** [comment]
should probably be in a new evil release before 28 hits us ?

**Comment by tomdl89** [comment]
@TheBB I'm happy to do a new release if you'll talk me through it?

**Comment by TheBB** [comment]
As far as I can remember, the process is as follows:

- Create a new branch from master, and call it `release-1.14`.
- On that branch, create a commit that looks like [this](https://github.com/emacs-evil/evil/commit/5162d1ce3660e6a3730201e0c3797d83bf89594a), only with `1.14.1` instead of `1.13.1`.
- Tag that commit with `1.14.1` and push the tag.
- On the master branch, make a similar commit, only use `1.15.0` as version number.
- Move the `stable` branch to point to the new release commit and force push it.

**Comment by tomdl89** [comment]
Awesome, thanks. I'll take a look over the next week or so.

**Comment by tomdl89** [comment]
Will melpa-stable automatically pick that up?

**Comment by TheBB** [comment]
Yeah, the tag is the magical thing that melpa-stable looks for. Everything else is just bookkeeping for our own sake.
