### ISSUE TITLE
Some basic questions

### ISSUE THREAD

**Issue by iris-garcia** [emacs-evil/evil#1408]
# Issue type
- Question
# Questions
Is it possible to change the behaviour of the following:
- When there is a selection, yank will move the cursor to the begining of the selection (I would like to have the default emacs behaviour)
- The selection, includes an extra char compared to the default emacs selection.

Thanks.

**Comment by tomdl89** [comment]
- It's not possible to change the behaviour with a setting, but if you build evil from source, you can comment out `(evil-visual-rotate 'upper-left)` in the `evil-define-operator` macro (evil-macros.el). The reason you'd have to do it there is that this behaviour is common to all operators - it's not specific to yanking.
- There's no way I know to not "include the extra char". I expect this is more deeply ingrained into evil than the operator behaviour above.
