### ISSUE TITLE
Why are evil-shift-width etc. forced buffer-local?

### ISSUE THREAD

**Issue by Janfel** [emacs-evil/evil#1416]
# Issue type

- Question

# Environment

Emacs version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28
Operating System: Manjaro Linux 20.2.1 Nibia
Evil version: 1.14.0
Evil installation type: straight.el pinned to cc9d6886b418389752a0591b9fcb270e83234cf9
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Further notes

Why are the following variables (and maybe more) forced to be buffer-local using `make-variable-buffer-local`?

- `evil-auto-indent`
- `evil-shift-width`
- `evil-shift-round`
- `evil-bigword`
- `evil-symbol-word-search`

This seems to contradict the [relevant section of the Emacs Manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Creating-Buffer_002dLocal.html), which clearly states:

> **Warning:** Don’t assume that you should use `make-variable-buffer-local` for user-option variables, simply because users might want to customize them differently in different buffers. Users can make any variable local, when they wish to. It is better to leave the choice to them.
> The time to use `make-variable-buffer-local` is when it is crucial that no two buffers ever share the same binding. For example, when a variable is used for internal purposes in a Lisp program which depends on having separate values in separate buffers, then using `make-variable-buffer-local` can be the best solution.

This does not seem to be the case with these variables. This decision also causes some concrete issues for me. For example, I would like to put this in my `.emacs`:

```elisp
(defvaralias 'evil-shift-width 'standard-indent)
```

This, however, does not work because `evil-shift-width` has been passed to `make-variable-buffer-local`. I would therefore prefer the offending lines to be removed, if there is no valid reason to keep them.

**Comment by Ghosty141** [comment]
I had the same issue today!  I also wonder what's the point, especially considering the part of the manual you posted.

**Comment by tomdl89** [comment]
We'll probably never know the answer, as @epsil is long gone from evil, but my guess is that is was done without awareness of that warning. I'd accept a PR to change these back.

**Comment by Ghosty141** [comment]
> We'll probably never know the answer, as @epsil is long gone from evil, but my guess is that is was done without awareness of that warning. I'd accept a PR to change these back.

Great to hear this! I'll try to do this in the coming days unless somebody is faster than me :)
