### ISSUE TITLE
evil-mode exec register ignores pipe

### ISSUE THREAD

**Issue by base698** [emacs-evil/evil#1418]
- Bug report

# Environment

Emacs version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.32) of 2020-09-25
Operating System: Debian Jessie
Evil version: Evil version 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Terminal
Tested in a `make emacs` session: No

# Reproduction steps
- Start Emacs

Assume `:r!ls | grep foo` is in the register **l**.

You can then do: `@l` to exec `ls | grep foo` and insert the contents matching foo in to the current buffer.  

In evil-mode I get: 
```
    Usage: grep [OPTION]... PATTERN [FILE]...
    Try 'grep --help' for more information.
```

# Expected behavior
Contents of the command in the current buffer

# Actual behavior
Last command exec'd with no pipe.

**Comment by tomdl89** [comment]
I can't replicate this. It works for me fine in a `make emacs` session on master. @base698 can you try to replicate in a `make emacs` session?

**Comment by base698** [comment]
On latest it appears to be working for me as well.

**Comment by tomdl89** [comment]
Ah weird. I'll close this issue, but please let us know if you see anything like this again. 🙂
