### ISSUE TITLE
Variable binding depth exceeds max-specpdl-size

### ISSUE THREAD

**Issue by gregrwm** [emacs-evil/evil#1420]
- Bug report

No problem on focal (ubuntu 20.04, emacs-gtk 1:26.3+1-1ubuntu2).  Evil comes up and works.

This problem happens on centos7 (emacs-24.3-23.el7.x86_64, Evil version 1.14.0)

# Reproduction steps
- Start Emacs
- :e .bash_[tab]

# Expected behavior
complete filename or show available completions

# Actual behavior
says `Lisp nesting exceeds max-lisp-eval-depth`

"Variable binding depth exceeds max-specpdl-size" often shows at startup, or when attempting various operations.

Same thing with or without undo-tree and goto-chg.

# my .emacs
```
(require'package)
(add-to-list'package-archives'("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)
(unless(package-installed-p'undo-tree)(package-install'undo-tree))
(unless(package-installed-p'goto-chg )(package-install'goto-chg))
(unless(package-installed-p'evil     )(package-install'evil))
(add-hook'after-init-hook(lambda()
   (require'undo-tree)
   (require'goto-chg)
   (require'evil)
   (global-undo-tree-mode)
   (evil-mode 1)))
```
TERM=xterm, inside xterm

**Comment by axelf4** [comment]
I am unable to reproduce, please comment if the issue remains even with up-to-date versions.
