### ISSUE TITLE
Is there a way to hook into :q or :wq?

### ISSUE THREAD

**Issue by jeyj0** [emacs-evil/evil#1423]
# Issue type

- Question

# Environment

Emacs version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.23.23, cairo version 1.16.0)
Operating System: NixOS 20.09
Evil version: 1.14.0
Evil installation type: [emacs-overlay](https://github.com/nix-community/emacs-overlay)'s `emacsWithPackagesFromUsePackage`
Graphical/Terminal: Graphical (+Terminal)
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
n/a

# Expected behavior

I'd like to have the option to run arbitrary elisp code when running `:wq`, `:w`, or `:q` using evil via a hook, for specific modes. I haven't found a way to do that currently. This might already be possible, however I wasn't able to find anything in the way that I have looked so far.

# Actual behavior
n/a

# Further notes

A workaround is to use a custom keybinding instead.

**Comment by tomdl89** [comment]
Check `evil-maps` for the functions these call. e.g. `:wq` calls `evil-save-and-close`. You can either advise this, or check to see what emacs functions are being called, and what hooks they call. Does that help?
