### ISSUE TITLE
Thoughts on implementing :[bro]wse [ol]dfiles?

### ISSUE THREAD

**Issue by tejasvi** [emacs-evil/evil#1433]
# Issue type

- Enhancement request

# Environment

Emacs version: 26
Operating System: Debian
Evil version: 1.14
Evil installation type: MELPA
Graphical/Terminal: X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- :browse oldfiles

# Expected behavior
It should list recently opened files.

# Actual behavior
Errors with "Unknown command".

# Further notes
`:h :browse`, `h oldfiles`

**Comment by tomdl89** [comment]
The emacs equivalent is `recentf-open-files`. We can probably add a mapping from `:browse oldfiles` to this. @tejasvi would that suffice?

**Comment by tejasvi** [comment]
@tomdl89 It will and is better in certain aspects. I was new to Emacs when I opened the issue. Thanks.
