### ISSUE TITLE
C-v with End and A broken

### ISSUE THREAD

**Issue by PRESFIL** [emacs-evil/evil#1434]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28
Operating System: Manjaro
Evil version: evil-git-134970b
Evil installation type: MELPA
Graphical/Terminal: Xorg
Tested in a `make emacs` session : Yes

# Reproduction steps
- Start Emacs
- Type some text:
```
asdasd
asas
asdasdasd
asdasdas
```
- select second row and <kbd>C-V</kbd><kbd>End</kbd>

# Expected behavior
![image](https://user-images.githubusercontent.com/20644917/111074005-36b95600-84f2-11eb-8ce5-1a494fee993c.png)

# Actual behavior
![image](https://user-images.githubusercontent.com/20644917/111074067-6ff1c600-84f2-11eb-94ca-74d6bbbd211e.png)

# Further notes

This problem is exactly the same as - but the <kbd>End</kbd> key is expected to work like in Vim and not <kbd>$</kbd>.

**Comment by tomdl89** [comment]
Looks like we just needed mapping from `[end]` to `evil-end-of-line`.  Added one for `[home]` too, although that should make little/no difference. Lemme know if that fixes this for you.

**Comment by duianto** [comment]
The latest version shows the expected behavior 👍 
| before | after |
|-|-|
| ![emacs_2021-04-01_11-08-37](https://user-images.githubusercontent.com/13420573/113273058-8d89a280-92dc-11eb-8ada-7fd0606aabfe.png) | ![emacs_2021-04-01_11-09-41](https://user-images.githubusercontent.com/13420573/113273081-911d2980-92dc-11eb-95ed-447f43d9aaf5.png) |

**Comment by PRESFIL** [comment]
Yes, that is working now:
![image](https://user-images.githubusercontent.com/20644917/113390381-47931400-939a-11eb-8667-49c7cd9f7e0b.png)
Thanks!
