### ISSUE TITLE
"evil-execute-in-normal-state" moves back one character when executed at the end of a line

### ISSUE THREAD

**Issue by daurenm** [emacs-evil/evil#1460]
# Issue type
- Enhancement request

# Environment

Emacs version: GNU Emacs 27.2
Operating System: macOS Catalina 
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Graphical 
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Create an empty file. Type some text and stay in Insert mode at the end the line.
- Execute *C-o* (evil-execute-in-normal-state)
- Run some command, e.g zz/zt/zb
 
# Expected behavior
Cursor stays at the end of the line, where it was left off before *C-o*

# Actual behavior
Moves back one character in Insert Mode when executed at the end of a line

# Further notes 
I moved from neovim few days ago.  It works properly there, staying where it was left off and not moving back.

**Comment by tomdl89** [comment]
@daurenm thanks for the bug report. I've just merged a fix into master. Let me know if that solves the problem for you.

**Comment by tomdl89** [comment]
I've noticed this isn't fixed. Will revisit.

**Comment by tomdl89** [comment]
Fixed in #1464 (mislabled in commit msg)
