### ISSUE TITLE
in visual block mode, "o" doesn't behave as expected

### ISSUE THREAD

**Issue by wickedjargon** [emacs-evil/evil#1462]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 27.2
Operating System: OS: EndeavourOS Linux x86_64
Evil version:  Installed in ‘evil-20210515.1807/’
Evil installation type: MELPA
Graphical/Terminal:  Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps / Actual behavior
- Start Emacs
- copy/paste a block of text (with line breaks)
- M-x evil-mode RET
- C-v to start visual block mode 
- use arrow keys or hjkl to select a block of text within a block of text:
![](https://imgur.com/qbZ1Xuo.png)
- hit "o" to exchange-point-and-mark, and this happens:
![](https://imgur.com/9470fmpl.png)

# Expected behavior

The selection shouldn't change after hitting "o". Only the mark and point should exchange.

performing the following resolves the issue:

`(define-key evil-visual-state-map (kbd "o") 'cua-exchange-point-and-mark)`

**Comment by tomdl89** [comment]
Hi @wickedjargon thanks for the bug report. I can't replicate this. If you navigate to the evil repo and run `make emacs` (and quickly say no running the tests) and try this there, do you still have this problem? That is just emacs with evil, so eliminates the possibility that another package is interfering.

**Comment by wickedjargon** [comment]
my apologies, yes, this appears to be config specific. Thanks

**Comment by mgraham** [comment]
I also am experiencing this - @wickedjargon did you track down what was causing it?

**Comment by mgraham** [comment]
Nevermind.  It must be a configuration issue on my side too.  I was experiencing this issue, but then after restarting emacs without a configuration change it fixed itself. 

Before restarting, while it was broken, running the following fixed it and made `o` work for both visual and line blocks:
```
(define-key evil-visual-state-map (kbd "o") 'exchange-point-and-mark)
```
