### ISSUE TITLE
How to prevent evil-delete/paste to put region to kill ring?

### ISSUE THREAD

**Issue by Abdillah** [emacs-evil/evil#1466]
# Issue type
- Question

# Environment
Emacs version: GNU Emacs 28.0.50
Operating System: Linux NixOS
Evil version: v1.14.0+ (commit 1b3db6349d04adfc68f707b0edd800f5ab3cb374)
Evil installation type: Doom
Graphical/Terminal: X / Wayland
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Question
How to use evil delete, replace, and paste command (e.g. `evil-delete`, `evil-paste-before`) without put the region to kill ring or register?
For paste, if there is a region selected it will be stored in the kill ring while replacing it.

**Comment by tomdl89** [comment]
I'm not clear exactly what you're asking, but this will answer your question. If you don't want the visual selection to be added to the kill ring or register when pasting, you can set `evil-kill-on-visual-paste` to `nil`. If you want to `evil-delete` but not send to a register, you should use the "black hole register" (`"_`). If you _never_ want `evil-delete` to add to the kill-ring or a register, you'd have to edit the evil source code to stop doing `evil-yank` as part of it. Does that answer your questions?

**Comment by Abdillah** [comment]
Thank you for the insight.
Specifically, how do I "use the 'black hole register' (`"_`)" when using evil-delete? Can I assign a key to that evil-delete + black hole?

**Comment by tomdl89** [comment]
In normal mode, you type `"_` before deleting.
For example, if you want to delete the current line and bypass the kill-ring, you would type:
`"_dd`
More details about the registers of vim can be found by typing `:h registers` in vim, or visiting https://vimhelp.org/change.txt.html#registers

**Comment by tomdl89** [comment]
If you want to always bypass the kill-ring, you can define a new evil operator:
```
(evil-define-operator evil-black-hole-delete (beg end type)
  (interactive "<R>")
  (evil-delete beg end type ?_))
```
and then assign that to d:
```
(define-key evil-normal-state-map "d" 'evil-black-hole-delete)
```
