### ISSUE TITLE
How to set evil state property properly?

### ISSUE THREAD

**Issue by whitemuu** [emacs-evil/evil#1468]
I try to 
    
      (evil-put-property 'evil-state-properties 'emacs :input-method nil)

the value is altered but have no effect, since evil is already running.

Maybe this api is not intended for end users? How could I achieved my goal.

**Comment by tomdl89** [comment]
I don't know much about this part of evil, but I think you're right that emacs-state may have to be restarted for this to take effect. What's the use case for this elisp? Do you want to put it as a top form in your init.el, or bind to a key sequence? Presumably not planning to type this at the eval-expression prompt? Knowing this may help with thinking of a solution to your issue.

**Comment by whitemuu** [comment]
I want it as a top form in init.el.

**Comment by tomdl89** [comment]
If you want to set your input-method to `nil` when you enter emacs-state, I'd recommend using a hook:
```
(add-hook 'evil-emacs-state-entry-hook (lambda () (set-input-method nil)))
```
There may be a more idiomatic way, but I am not aware of it. @whitemuu does this help?

**Comment by whitemuu** [comment]
@tomdl89 Yes, it works as I expected. 

I thought this way, when switching back to insert-state from emacs-state, it might lose the input-method. But it didn't. Thanks.
