### ISSUE TITLE
Alternating between visual line mode aware commands and regular commands breaks the visual line mode aware commands

### ISSUE THREAD

**Issue by DevJac** [emacs-evil/evil#1469]
# Issue type
- Bug report

# Environment

Emacs version: 27.2
Operating System: Linux, Fedora
Evil version: 1.14.0
Evil installation type: MELPA (?)
Graphical/Terminal: X
Not tested with `make emacs`

# Reproduction steps
- Fill a buffer with a line or two of text that are long enough to wrap
- Turn on visual line mode
- Place you cursor on one of the long lines
- Run `evil-end-of-line`
- Run `evil-previous-visual-line`
- Observe that `evil-previous-visual-line` does not work as expected

# Expected behavior
I expect `evil-previous-visual-line` to move the cursor up one visual line.

# Actual behavior
The cursor moves to the beginning of the actual previous line (not the previous **visual** line, the previous **actual** line).

# Further notes
This happens because `evil-end-of-line` sets `last-command` to `next-line`. This then causes problems in `line-move` (a function in `simple.el`) on the following lines:

```
...
      (if (and line-move-visual
...
	       (not (and (memq last-command
			       `(next-line previous-line ,this-command))
...
	  (prog1 (line-move-visual arg noerror)
...
	(line-move-1 arg noerror)))))
...
```

I've chopped up the `line-move` function, you can of course view the entire thing in Emacs. The problem is that when `last-command` is `next-line` it causes the cursor to move via `line-move-1`, but we want to cursor to move via `line-move-visual`. I don't know what the right fix is.

**Comment by DevJac** [comment]
```
(evil-define-motion evil-end-of-line (count)
  "Move the cursor to the end of the current line.
If COUNT is given, move COUNT - 1 lines downward first."
  :type inclusive
  (move-end-of-line count)
  (when evil-track-eol
    (setq temporary-goal-column most-positive-fixnum
          this-command 'next-line))
  (unless (evil-visual-state-p)
    (evil-adjust-cursor)
    (when (eolp)
      ;; prevent "c$" and "d$" from deleting blank lines
      (setq evil-this-type 'exclusive))))
```
Why does this function set `this-command` to `next-line`? `this-command` later becomes `last-command` and is the cause of this bug.

**Comment by DevJac** [comment]
I created a workaround for this issue by changing the following two functions:
```
(evil-define-motion evil-next-visual-line (count)
  "Move the cursor COUNT screen lines down."
  :type exclusive
  (let ((line-move-visual t))
    (if (eq last-command 'next-line) (setq last-command 'evil-end-of-line))
    (evil-line-move (or count 1))))

(evil-define-motion evil-previous-visual-line (count)
  "Move the cursor COUNT screen lines up."
  :type exclusive
  (let ((line-move-visual t))
    (if (eq last-command 'next-line) (setq last-command 'evil-end-of-line))
    (evil-line-move (- (or count 1)))))
```
This does not appear to cause a regression of https://github.com/emacs-evil/evil/issues/120 .

**Comment by DevJac** [comment]
I attempted a solution in https://github.com/emacs-evil/evil/pull/1470, but it caused a regression described in the PR.

**Comment by tomdl89** [comment]
I wonder if you may want `(eq real-last-command 'evil-end-of-line)` in your test case, to exclude when the actual last-command _was_ `next-line`?

**Comment by DevJac** [comment]
Good tip, I'm experimenting with real-last-command. I think simply replacing last-command with real-last-command for the two functions mentioned earlier might be the general fix.

There's another failure case I found. If you are in the middle of a wrapped line, and then go up a few real lines,

**Comment by tomdl89** [comment]
Looks like you've done some good investigation. I won't have time to look at this in any more detail soon, so feel free to continue your efforts. Seeing as this is so poorly tested in evil, and how prone the solutions thus far have been to regressions, I think a testing strategy should form part of any PR for this. I've briefly looked at using `set-frame-width` and (more flexibly) doing a vertical split and using `window-resize` to make the buffer's visual width deterministic, but I'm open to any better ideas on this.

**Comment by DevJac** [comment]
```
(evil-define-motion evil-next-visual-line (count)
  "Move the cursor COUNT screen lines down."
  :type exclusive
  (let ((line-move-visual t))
    (line-move-visual (or count 1))))

(evil-define-motion evil-previous-visual-line (count)
  "Move the cursor COUNT screen lines up."
  :type exclusive
  (let ((line-move-visual t))
    (line-move-visual (- (or count 1)))))
```
This works the best of all that I've tried.
