### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by tomdl89** [emacs-evil/evil#1473]
@TheBB it looks as though Evil's travis builds will deactivate in 5 days.
Migration instructions are here: https://docs.travis-ci.com/user/migrate/open-source-repository-migration
I assume I cannot do this, so you will have to, unless you would like to give me the necessary permissions?

**Comment by TheBB** [comment]
I have migrated most of my active repos to Github Actions instead and found
that to be a much less unpleasant experience. Although I haven't tried the
new Travis, unless you have specific reasons to prefer it I'd recommend to
use Actions instead.

**Comment by tomdl89** [comment]
Ok sounds good to me. I'll look into it.
