### ISSUE TITLE
"ex" move command not working with line matching destination ADDR

### ISSUE THREAD

**Issue by mtwomey** [emacs-evil/evil#1482]
# Issue type

- Bug report

# Environment

Emacs version: 27.2
Operating System: OSX
Evil version: 1.14
Evil installation type: Doom
Graphical/Terminal: Graphics
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Create empty buffer
- Insert the following

```
TARGET

OTHER STUFF

thing1
thing2
thing3
```
- Type ':' to enter command mode and enter `g/thing/m /TARGET/`

# Expected behavior
Lines containing `thing` move to below the line containing /TARGET/

# Actual behavior
Lines do not move.

# Further notes
Works in vim, I'm not 100% sure if this _should_ work for evil or not (or if the syntax is slightly different).

**Comment by tomdl89** [comment]
Thanks for the bug report. If you want to move to `TARGET` in this case, you'll need to use `?` rather than `/` (because `TARGET` is backwards). In vim , the search wraps around, and in evil it doesn't. So indeed this _should_ work for evil.

**Comment by tomdl89** [comment]
@mtwomey this should now be fixed in master. Feel free to reopen this issue if you notice otherwise.

**Comment by mtwomey** [comment]
Thanks sir!
