### ISSUE TITLE
`evil-disable-insert-state-bindings` cannot be set to t by use-package `:custom`

### ISSUE THREAD

**Issue by KSSysLab** [emacs-evil/evil#1486]
# Issue type

- Bug report

# Environment

Emacs version: Emacs 28
Operating System: macOS 
Evil version: evil-20210705.2021 
Evil installation type: melpa
Graphical/Terminal: GUI
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps

``` elisp
;; /tmp/a.el
;; Package Management
(require 'package)
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
	("gnu" . "https://elpa.gnu.org/packages/")
	("org" . "http://orgmode.org/elpa/")))
(package-initialize)

;; lisp equivalent of a while loop
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  ;; We're using package install to install use-package
  (package-install 'use-package)
  ;; to install newer version when available
  (setq load-prefer-newer t))
;; This line is just a raincheck
(defvar use-package-verbose t)
;;Always ensure that the package is installed
(defvar use-package-always-ensure t)
(require 'use-package)

(use-package evil
  :ensure t
  :custom
  (evil-disable-insert-state-bindings t)
  :config
  (evil-mode))
```

```
emacs -Q -l /tmp/a.el
```

Switch to `*scratch*` buffer, press `i` to make evil into insert state.

# Expected behavior

`C-e` will move to the end of line.

# Actual behavior

`C-e` runs `evil-copy-from-below`.

# Further notes

**Comment by condy0919** [comment]
But if I use `setq` in `:init` block, it works.

```
(use-package evil
  :ensure t
  :init
  (setq evil-disable-insert-state-bindings t)
  :config
  (evil-mode))
```

**Comment by tomdl89** [comment]
Yeah looking at use-package's code, `:custom` is equivalent to doing `custom-set-variable` in a `:config` section, whereas you'd need to do it in the `:init` section because it needs setting before evil is loaded. I don't think this is an evil bug.

**Comment by condy0919** [comment]
Thanks for explanation. :)
