### ISSUE TITLE
Change default value of `evil-overriding-maps` to an empty list

### ISSUE THREAD

**Issue by condy0919** [emacs-evil/evil#1488]
# Issue type

- Question

# Further notes

``` elisp
(defcustom evil-overriding-maps
  '((Buffer-menu-mode-map . nil)
    (color-theme-mode-map . nil)
    (comint-mode-map . nil)
    (compilation-mode-map . nil)
    (grep-mode-map . nil)
    (dictionary-mode-map . nil)
    (ert-results-mode-map . motion)
    (Info-mode-map . motion)
    (speedbar-key-map . nil)
    (speedbar-file-key-map . nil)
    (speedbar-buffers-key-map . nil)))
```

Where

- `Buffer-menu`
- `comint`
- `compile`
- `grep`
- `dictionary`
- `ert`
- `Info`
- `speed`

are all supported by evil-collection except for [`color-theme`](https://github.com/emacsattic/color-theme/tree/3a2f6b615f5e2401e30d93a3e0adc210bbb4b7aa) which is a third library and obsolete. So I propose to change the default value of `evil-overriding-maps` to `'()`.

**Comment by tomdl89** [comment]
This is a tricky one. There are three types of users I'm thinking about:

1. Experienced users who don't want evil overridden anywhere (who would customize this to `'()`
2. Experienced users who want finer control or wider support (who would probably use evil-collection)
3. New users who are not aware of evil-collection

My concern is that by defaulting this to `'()` we'd be making life a little more difficult for users in the third category when visiting buffers in the above modes.
Thoughts?

**Comment by condy0919** [comment]
We can experimentally set it to `'()` as emacs maintainers unbind `M-o` https://lists.gnu.org/archive/html/emacs-devel/2021-02/msg00537.html

If there is no bug reports for 3 months, it means this change is accepted by most of users.

**Comment by tomdl89** [comment]
The problem with this idea, is that waiting for complaints or running a poll, almost by their nature, exclude new users. Newbies are not going to know what they're missing, and they're most likely not going to be browsing this repo, or any other forum where you may want to run a poll. Before we try experimental changes or polling, I think it would be most helpful if you could make an argument or two in favour of your idea, so I can weigh up the pros/cons.

**Comment by condy0919** [comment]
For the case 3, the most frequent keys, such as `h`, `l` and `g`, are not evilified (h -> `Info-help`, `l` -> `Info-history-back`, `g` -> `Info-goto-node`) which is more confusing for evil beginners. They don't known why `hl` not working.

**Comment by condy0919** [comment]
@tomdl89 ping. Thoughts?

**Comment by tomdl89** [comment]
I think you're right actually. The topic of where evil is or is not overriding / being overridden is complicated, and `evil-overriding-maps` doesn't appear to help newbies as much as I had thought. When I changed the value to `'()` and restarted emacs, I could still see that some evil keys were overridden by e.g. buffer-menu-mode-map, (although some were no longer overridden). If this variable's current value resulted in intuitive behaviour, I would be inclined to keep it as it is. But it does not, so feel free to make a PR and we'll see if we get any bug reports.
