### ISSUE TITLE
org-cycle broken while using evil

### ISSUE THREAD

**Issue by mukundzare** [emacs-evil/evil#1505]
# Issue type

- Bug report

# Environment

Emacs version: 27.1
Operating System: Ubuntu 20.04
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: GUI
Tested in a `make emacs` session No

# Reproduction steps
- Start Emacs
1. Open any Org file which has headings and subheading
2. Place point on a heading which is currently in a collapsed state and contains subheadings
3. Press Tab

# Expected behavior
The subheadings should open

# Actual behavior
Nothing happens

# Further notes
I see that the key-binding for `org-cycle` doesn't exist anymore. It has stopped working since today. It was working yesterday but I had also updated my packages yesterday. Running `emacs -q` doesn't exhibit this behaviour and tab-cycling works fine. Furthermore, `evil-jump-forward` has been assigned the `TAB` key as a minor-mode command.

**Comment by mukundzare** [comment]
One more thing that I discovered: org-cycle seems to be only working in in INSERT-mode but not in NORMAL-mode

**Comment by tomdl89** [comment]
I'm not sure I understand why this is a bug. Evil emulates vim, and tab does jump through the jump list in vim. Sounds like it works properly to me (unless I'm missing something?) Looks like you updated evil and gained a new feature. You can always rebind tab if you prefer the old behaviour, right?

**Comment by tomdl89** [comment]
Looks like https://github.com/Somelauw/evil-org-mode may be worth a look.

**Comment by toma-te** [comment]
I think the point @mukundzare is trying to make is that it used to work out of the box before a recent update. It can be fixed by  setting `(setq evil-want-C-i-jump nil)` in case anyone stumbles over this issue wondering what's going on.
