### ISSUE TITLE
A fast input of j and k in input mode cancels the input mode

### ISSUE THREAD

**Issue by rako233** [emacs-evil/evil#1514]
# Issue type
Fast input of "j" and "k" in inut mode, is ending input mode.
- Bug report

# Environment

Emacs version: 28.0.50
Operating System: Ubuntu 20.04
Evil version: 1.14.0
Evil installation type:  MELPA
Graphical/Terminal: X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): <No

# Reproduction steps
- Start Emacs 
- Go activate input mode
- put fast in the sequence of j and k
- Input mode will be ended

# Expected behavior
- Start Emacs 
- Go activate input mode
- put fast in the sequence of j and k
- looking at the sequence in the buffer  of jkjkjkjkjkjkj

# Actual behavior
after 4 x jk the input mode ends

# Further notes
evil-mode comes with the last version of Doom

**Comment by TheBB** [comment]
https://github.com/hlissner/doom-emacs/issues/1946
