### ISSUE TITLE
pressing Backspace while in Replace mode does not put back a character that had been replaced

### ISSUE THREAD

**Issue by tex** [emacs-evil/evil#1522]
# What did you expect to happen?

pressing Backspace while in Replace mode puts back a character that had been replaced

# What actually happened?

pressing Backspace while in Replace mode does not put back a character that had been replaced but only a space

# Steps to reproduce

Open Emacs
To Insert mode
Type: Hello
To Replace mode
Go to beginning of the line
Type World
Press backspace 5 times
See empty (5 spaces) space, in VIM you get Hello.
System Information

https://pastebin.com/vy0TcGCf

https://github.com/hlissner/doom-emacs/issues/5546

**Comment by tomdl89** [comment]
Thanks for the bug report @tex. I cannot replicate this in a `make emacs` session, so I'm inclined to believe it is an issue with your config. Can you replicate it in a `make emacs` session?

**Comment by tex** [comment]
@tomdl89 Hi Tom, I have this issue in Emacs Doom, reported it at hlissner/doom-emacs#5546 where https://github.com/hlissner reported that he is able to reproduce it in vanilla Emacs + evil. I will try the `make emacs` as soon as I figure out what it is (sorry, I am new to Emacs).

**Comment by tomdl89** [comment]
Navigate to the evil repository (git clone it if you don't have the source code locally already) and type `make emacs`. This will spin up vanilla emacs, loading only evil. You can then see if your bug is still present.

**Comment by tex** [comment]
I did it, emacs version 28.0.50 and it behaves as I described. See attached video.

https://user-images.githubusercontent.com/27386/136093370-befe0575-b434-41db-a552-cf1ea613c78d.mp4

**Comment by tomdl89** [comment]
Thanks for the video @tex - If only all bug reports had one! You're accessing replace state by pressing `<insert>` in insert state (right?) which indeed works in vim. Right now, it is entering overwrite-mode, which is an emacs mode, rather than an evil state. I have just merged a fix to master. The reason this has gone unnoticed for so many years is that most users enter replace state from normal state by pressing `shift-R` rather than pressing `<insert>` in insert state.

**Comment by tex** [comment]
Thanks! Yes I got there by pressing insert key in insert state.

**Comment by tex** [comment]
@tomdl89 I tested it and it works. But one nitpick. Try to hold insert key in the middle of line. You'll see how cursor moves to left. This is not happening in VIM. Cursor should stay at the same position. This is different than what happens when switching from insert to normal or replace to normal, where cursor goes one character to left. I am looking at source code but I am still very new to emacs and lisp :)...

**Comment by tomdl89** [comment]
Ah yes - I think I should have set `[insert]` to `evil-append` in replace state, rather than `evil-insert`. I will change it. You may be the only person in the world holding down the insert key in evil, but even so, it should work for you as you expect.

**Comment by tex** [comment]
Sorry! :) But thank you!

**Comment by tomdl89** [comment]
Haha great job! That's in master now.
