### ISSUE TITLE
Add WHEN argument to define-obsolete-* calls

### ISSUE THREAD

**Issue by skangas** [emacs-evil/evil#1523]
In Emacs 28.1, `define-obsolete-(function|variable|face)-alias`  requires a non-nil third argument. Please update your calls to include the WHEN argument so that evil will work in Emacs 28.

For background:
https://lists.gnu.org/archive/html/emacs-devel/2021-10/msg00096.html

Note: I don't use evil myself, so I can't help with testing this. I'm just forwarding the issue for your information.

**Comment by tomdl89** [comment]
@skangas thanks for the heads-up! Out of interest, if you don't use evil yourself, why have you opened this issue? I expected to see similar issues on your github profile, but looks like you've just made one here. Although confused, I'm grateful nonetheless. Cheers

**Comment by vizs** [comment]
This was brought up in a thread in emacs-devel.  See here: https://lists.gnu.org/archive/html/emacs-devel/2021-10/msg00096.html

**Comment by tomdl89** [comment]
Yes I see that, thanks. My question is a curiosity about _who_ not _what_. And now there's another _who_ @vizs 😂
As I said, I'm grateful for the heads up, but now slightly more confused!

**Comment by tomdl89** [comment]
OK now I _am_ confused about the _what_ too. There's only one usage of `define-obsolete...` in evil and it _does_ have an argument for `WHEN`. If I'm wrong, can one of you two please direct me to the file & line?

**Comment by TheBB** [comment]
Indeed, this was fixed in January. https://github.com/emacs-evil/evil/issues/1403

**Comment by tomdl89** [comment]
🤦 and I was in the thread. Thanks @TheBB - reminds me I still need to do the release 🏃
