### ISSUE TITLE
Why is evil-visual-update-x-selection called during evil-visual-pre-command?

### ISSUE THREAD

**Issue by wpcarro** [emacs-evil/evil#1537]
Why am I asking? This results is undesirable and difficult-to-troubleshoot behavior when a user has the following (likely common) configuration:

```elisp
(customize-set-variable 'select-enable-clipboard t)
```

...which results in pasting in visual mode being (effectively) a no-op because the text within the visually selected region is added to the `kill-ring`, which `evil-visual-paste` subsequently reads (i.e. `(current-kill 0)`). Can you help me (and others) understand why `evil-visual-update-x-selection` is even called during `evil-visual-pre-command`?

**Comment by tomdl89** [comment]
Sorry I'm a bit confused - assuming you know that vim has autoselect enabled by default in [clipboard](http://vimdoc.sourceforge.net/htmldoc/options.html#'clipboard')/[guioptions](http://vimdoc.sourceforge.net/htmldoc/options.html#'guioptions') and you agree that evil should emulate vim, what's the problem? Maybe you'd like the option proposed [here](https://github.com/emacs-evil/evil/pull/1536)?
