### ISSUE TITLE
evil-find-file-at-point-with-line make configurable between ffap-other-window vs find-file-at-point

### ISSUE THREAD

**Issue by e-carlin** [emacs-evil/evil#1538]
# Issue type
- Enhancement request

# Environment

Emacs version: GNU Emacs 27.1 (build 1, x86_64-redhat-linux-gnu) of 2020-08-20
Operating System: Fedora 32 (Cloud Edition)
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- M-x shell
- git clone https://github.com/emacs-evil/evil.git
- cd evil
- grep -rn ffap-other-window
- ESC # Enter normal mode
- k # up one line
- ^ # start of line
-  gF # evil-find-file-at-point-with-line

# Expected behavior
It opens the file in the same window (`find-file-at-point`)

# Actual behavior
It opens the file in another window (`ffap-other-window`)

# Further notes
Doing the same in vim (8.2) it opens the file at the line in the same window. I don't have a strong preference for what the behavior should default to but I'd like to at least make it configurable. If you all are open to making this configurable and can point me to an example of configuring this code I'd be happy to open a PR.

Thanks!

**Comment by tomdl89** [comment]
This looks to be a mistake to me. I'd welcome a PR, or I can make the change? It's simple but low priority. Don't think adding a config would be great because there isn't one in vim afaik.

**Comment by e-carlin** [comment]
Thanks for getting back to me @tomdl89. I've opened a PR https://github.com/emacs-evil/evil/pull/1540.
