### ISSUE TITLE
Email address for build notifications

### ISSUE THREAD

**Issue by monnier** [emacs-evil/evil#1543]
NonGNU ELPA's build scripts want to have an email address to which they can send notifications (mostly to confirm when a new release tarball is created, in response to a change in the `Version:` header).  This address is taken from the `Author:` or the `Maintainer:` header which needs to be in `evil.el`.
Currently no such email address is provided, so those notifications aren't sent.

**Comment by tomdl89** [comment]
@monnier thanks for letting us know. Will the referenced PR suffice?

**Comment by monnier** [comment]
Yes, that should do just fine, thank you.
