### ISSUE TITLE
keybindings don't repeat on press and hold

### ISSUE THREAD

**Issue by rgnns** [emacs-evil/evil#1548]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.1.0, NS appkit-2113.00 Version 10.16 (Build 21A559))
Operating System: macOS Monterey 12.0.1
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Have a buffer with plenty of text to test.
- Try `j`, `h`, `k` (`l` doesn't have this issue), and other commands such as `x`, by pressing it and holding. The key press works, but holding doesn't repeat the command.

# Expected behavior
Vim press and hold works and this *should* be expected for Evil too. Emacs without Evil also allows press-and-hold with its native keybindings (i.e. `C-f`, `C-b`, etc). Arrow keys also work the expected way with or with no Evil.

# Actual behavior
Evil only recognizes first press but doesn't allow continuation by holding.

# Further notes

**Comment by tomdl89** [comment]
Thanks for the bug report @rgnns but I can't reproduce this behaviour. I can repeat `j`, `h` `k`, `x` and other keys by holding them. Can you reproduce this in another environment (non-mac, or an earlier version of emacs)? I don't have easy access to a non linux os, but I will upgrade from emacs 28->29 sometime soon. Until then I probably won't be able to make progress on this, other than reviewing a PR, if you have the time/inclination.

**Comment by rgnns** [comment]
Thanks @tomdl89 for taking a look at this. I looked into the different versions and here are my findings:
- Running Emacs 29 on Linux: works as expected.
- Running Emacs 29 (same build) on Mac: issue.
- Running Emacs 28 (custom Homebrew) on Mac: works as expected.
I'm trying to get a similar Emacs build as the one I have from Homebrew for 29, maybe the reason is that. But after seeing it works on both Linux and Mac, regardless of Emacs version, I believe the reason is probably how I built my current Emacs 29. I'll keep you posted once I finish building Emacs and have tried it out.

**Comment by rgnns** [comment]
One other thing to note is this have nothing to do with Evil. Typing any of the keys that block key repeat also get blocked if typing without Evil.

I initially associated the moving cursor action (i.e. C-f, C-b, C-n, C-p) as not having the issue, because they don't. So sorry about that. You can mark this issue as won't fix.
