### ISSUE TITLE
Using mouse in Completions buffer throws an error

### ISSUE THREAD

**Issue by d9d6ka** [emacs-evil/evil#1551]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 27.2 (build 1, x86_64-w64-mingw32) of 2021-03-26
Operating System: Windows 10 21H2 19044.1387
Evil version: 1.14.0
Evil installation type: straight.el (via use-package), I think it uses MELPA recipes
Graphical/Terminal: GUI
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Enter `:`, then start typing in any command (i.e. `evil-`).
- Press <kbd>Tab</kbd>
- When the `*Completions*` minibuffer appears try to mouseclick any suggestion.

# Expected behavior
Clicked command is inserted into the command line (sorry, not quite familiar with Emacs terminology).

# Actual behavior
I receive the following error:
> mouse-minibuffer-check: Wrong type argument: window-valid-p, #<window 8>

`*Messages*` buffer shows the following messages before it:

> Making completion list...
> Quit
> Error in post-command-hook (evil-ex-abort): (user-error "No recursive edit is in progress")

# Further notes

The problem occurs specifically when I try to complete the command via mouseclick in the completion list for `:` (evil-ex-completion, if I understand correctly).
In other situations that allow using mouse (e.g. completions for `eval-expression`) mouseclicking works as expected.

I've added a small video from `make emacs` session:

![Анимация](https://user-images.githubusercontent.com/29946047/145665751-d059a191-1e6f-43e1-8945-e1246e9c1d78.gif)

**Comment by tomdl89** [comment]
Thanks for the bug report. Should be fixed in master. Feel free to reopen if you think otherwise.

**Comment by d9d6ka** [comment]
Thanks, problem is gone!
