### ISSUE TITLE
Move with 'startofline' on does not reset curswant

### ISSUE THREAD

**Issue by axelf4** [emacs-evil/evil#1557]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu)
Operating System: NixOS 21.11
Evil version: evil-git-b00018b
Evil installation type: MELPA
Graphical/Terminal: Terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs using `make emacs`.
- Set `evil-start-of-line` to `t`.
- Enter a new buffer containing

  ```
  foo
  [b]ar
  ```
  
  where `[]` indicates the cursor.
- Type `$ggj`.

# Expected behavior
The cursor should end up on the `b` as it does in Vim 8.2.3451.

# Actual behavior
The cursor keeps sticking to EOL even though `gg` should have reset the wanted cursor column along with the actual column.

# Further notes

**Comment by tomdl89** [comment]
Thanks for the bug report @axelf4 - this should now be fixed in master. Let me know if you observe otherwise.
