### ISSUE TITLE
Advice of `set-window-buffer` unconditionally enables `evil-local-mode`

### ISSUE THREAD

**Issue by condy0919** [emacs-evil/evil#1561]
# Issue type

- Bug report

# Environment

Emacs version:  Emacs 29.0.50
Operating System:  archlinux
Evil version:  1.14.0
Evil installation type:  melpa
Graphical/Terminal:  GUI
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  No

# Reproduction steps
- Start Emacs

Eval the following recipe.

```elisp
(package-initialize)
(setq evil-want-minibuffer nil)
(require 'evil)
(evil-mode +1)

(defun test-setup ()
  (let* ((temp (generate-new-buffer "*temp*"))
         (win (with-minibuffer-selected-window (display-buffer temp))))
    (message "BEFORE %S" evil-local-mode)
    (set-window-buffer win (current-buffer))
    (message "AFTER %S" evil-local-mode)
    (kill-buffer temp)))

(defun test ()
  (interactive)
  (minibuffer-with-setup-hook #'test-setup
    (read-from-minibuffer "Prompt: ")))
```

`M-x test`

# Expected behavior

 `ESC` could exit the minibuffer.

# Actual behavior

`ESC` is bound to `evil-force-normal-state` since `evil-local-mode` is enabled.

# Further notes

It's originally reported at https://github.com/minad/vertico/issues/171, minad has identified the bug:

https://github.com/emacs-evil/evil/blob/652d726ebd8cdfcac3e97a801721f33b5b832a0a/evil-core.el#L362-L373

The advice of `set-window-buffer` unconditionally enable `evil-local-mode`. IMHO, the buffer `(ad-get-arg 1)` shouldn't be evilfied if it satisfies `(minibufferp)` and `evil-want-minibuffer` is `t`.

See https://github.com/emacs-evil/evil/blob/652d726ebd8cdfcac3e97a801721f33b5b832a0a/evil-core.el#L167-L178

**Comment by Delapouite** [comment]
Hi

Sorry in advance if I hijack the thread but I have a feeling that what I observed is related to this topic.

I have many org-mode buffers with tables with about 100 lines and 5 columns (so not that huge).
Every time I press the `Tab` key in order to trigger the realignment of cells after some editing, the operation is verryy slow (about 15 secs) and my laptop fans start spinning.

Here's an extract of a profiler-report, just analyzing what's going on : 

```
10436  98% - command-execute
10436  98%  - call-interactively
 9846  92%   - funcall-interactively
 9839  92%    - org-cycle
 9836  92%     - call-interactively
 9836  92%      - funcall-interactively
 9836  92%       - org-table-next-field
 9836  92%        - org-table-align
 5028  47%         - cl-mapcar
 5024  47%          - cl--mapcar-many
 5024  47%           - apply
 5014  47%            - org-table--align-field
 5011  47%             - org-string-width
 4749  44%              - set-window-buffer
 4749  44%               - apply
 4749  44%                - ad-Advice-set-window-buffer
 4708  44%                 - evil-local-mode
 1936  18%                  + run-hooks
 1563  14%                  + add-hook
 1185  11%                  + evil-initialize-state
    3   0%                  + evil-concat-lists
    3   0%                  + evil-disabled-buffer-p
    3   0%                    evil-initialize-local-keymaps
   41   0%                 + #<subr set-window-buffer>
  235   2%              + #<compiled -0x1c8ae47fe622b71b>
   13   0%              + version<
 4795  45%         - org-string-width
 4564  43%          - set-window-buffer
 4564  43%           - apply
 4564  43%            - ad-Advice-set-window-buffer
 4517  42%             - evil-local-mode
 1870  17%              + run-hooks
 1547  14%              + add-hook
 1084  10%              + evil-initialize-state
    4   0%              + evil-concat-lists
```

So my current understanding is that to perform string width calculation, a throw-away buffer is created, but as an extraneous evil-local-mode is triggered, it slows down everything.

I guess in this context, the advice should not enable evil-local-mode as well.

Thanks
