### ISSUE TITLE
evil moving lines doesn't always preserve column

### ISSUE THREAD

**Issue by ngharrison** [emacs-evil/evil#1564]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 28.0.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2021-12-27
Operating System: Linux Mint 20.2
Evil version: Evil version 1.14.0
Evil installation type: Github
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Open buffer with text
- Use `evil-previous-line`, `evil-next-line`, `evil-previous-visual-line`, or `evil-next-visual-line`.

# Expected behavior
When moving the cursor up and down lines, the same column should be maintained.

# Actual behavior
Sometimes the cursor jumps a few characters side to side.

# Further notes
I'm using a mono-space font. I can't say yet in exactly which scenarios this happens. It happens more with the visual line movements, but often when lines aren't even visually wrapped. It might happen more when there is whitespace at the beginning of the line.

The biggest problem I have is that when using the visual line commands the cursor shifts to a column 4 characters to the right when moving up and then back to the original column when moving down. This is very consistent, occurs when moving across logical lines, and occurs even when I switch to fundamental mode.

I've narrowed it down to the behavior coming directly from `vertical-motion`, which is used by `line-move` inside the simple.el package. All the evil line commands use these functions. Since `vertical-motion` is a C function, I haven't gotten any farther. Maybe there is a better mechanism to use than the one in simple.el?

EDIT: I've now tried this from an `emacs -Q` session and I'm not seeing the behavior, so it's probably the interaction between evil and other packages.

**Comment by tomdl89** [comment]
Thanks for the bug report @ngharrison - as soon as you find out which other packages cause this problem, please let us know if there is any bug in evil which seems to be contributing to the problem.

**Comment by ngharrison** [comment]
I'm closing this for now. Still not sure of the cause and don't have the time right now to debug it. If someone else can identify the actual cause, feel free to re-open or make a new issue.

**Comment by tdehaeze** [comment]
I have the same annoying issue using Doom Emacs. But I don't know which packages causes this issue.

**Comment by mentalisttraceur** [comment]
The main/only time I've seen this is with Unicode "characters" composed with the Zero-Width Joiner.

For example, "🐦‍🔥" (firebird) is actually a font-level ligature for the three Unicode characters "🔥 <zero-width-joiner> 🐦".

There's a lot of more recent emoji that work like this. For example, IIRC, emoji with different skin tones are implemented this way.

Only some parts of Emacs are "aware" of this. `string-width` accounts for it correctly. But key pieces of vertical motion code in Emacs, such as `current-column`, treat "🐦‍🔥" as if it's "🔥🐦" (sum of `char-width` on all three of the characters, but Zero-Width Joiner is always zero width).

In fact, I partly mitigate this problem in Emacs config with this advice:

```lisp
(defun fixed-current-column (column)
    (let ((bound (point)))
        (goto-char (pos-bol))
        (while (re-search-forward ".\u200d." bound 'x)
            (let* ((match  (match-string 0))
                   (actual (string-width match))
                   (wrong  (+ (char-width (aref match 0))
                              (char-width (aref match 2)))))
                (setq column (- column (- wrong actual))))))
    column)

(advice-add 'current-column :filter-return 'fixed-current-column)


(defun fixed-move-to-column (move-to-column column &optional force)
    (funcall move-to-column column)
    (let ((bound (point)))
        (goto-char (pos-bol))
        (while (re-search-forward ".\u200d." bound t)
            (let* ((match  (match-string 0))
                   (actual (string-width match))
                   (wrong  (+ (char-width (aref match 0))
                              (char-width (aref match 2)))))
                (setq column (+ column (- wrong actual))))))
    (funcall move-to-column column force))

(advice-add 'move-to-column :around 'fixed-move-to-column)
```
