### ISSUE TITLE
evil-inner-xml-attr dont reconize rjsx attributes

### ISSUE THREAD

**Issue by the-moriarty** [emacs-evil/evil#1569]
`<ul onClick={} /> `<- Dont work
`<ul onClick="" /> ` <- Work

**Comment by tomdl89** [comment]
@the-moriarty thanks for the bug report. I'm having trouble reproducing. If I have:
```
<ul onClick={}>foo bar</ul>
```
I can do `vit` and see `foo bar` is highlighted.

If I am testing the wrong thing, please let me know. A step by step of what keys you press and what you expect to be selected/operated over would be great. There's not quite enough for me to go on as it is.

**Comment by the-moriarty** [comment]
> @the-moriarty thanks for the bug report. I'm having trouble reproducing. If I have:
> 
> ```
> <ul onClick={}>foo bar</ul>
> ```
> 
> I can do `vit` and see `foo bar` is highlighted.
> 
> If I am testing the wrong thing, please let me know. A step by step of what keys you press and what you expect to be selected/operated over would be great. There's not quite enough for me to go on as it is.

Hi @tomdl89 

The problem is with `vix`

**Comment by tomdl89** [comment]
@the-moriarty `x` is not in the `evil-inner-text-objects-map` (or the outer map for that matter) so `vix` should not "work" (you still haven't explained exactly what "work" means - please do). `vix` also doesn't do anything in vim or neovim from what I can tell. What's making you think `vix` should do anything?

**Comment by tomdl89** [comment]
I can only assume there is some confusion with a package such as https://github.com/ninrod/exato ?
