### ISSUE TITLE
cit dont work on specific scenario

### ISSUE THREAD

**Issue by the-moriarty** [emacs-evil/evil#1572]
On rjsx:

      <button style={{
        marginTop: "5px",
        backgroundColor: "red",
        color: "white",
        width: "20vh",
        height: "8vh",
        color: "white",
        border: '3px solid #fff',
        borderRadius: "5px"
      }} onClick={() => randomizeBalls()}>Generate</button>

With cursor on Generate, press cit.

It will delete randomizeBalls()

**Comment by tomdl89** [comment]
Interesting bug! It's also a bug in vim & neovim btw.

**Comment by tomdl89** [comment]
@the-moriarty this should now be fixed in master. Please let me know if you observe otherwise.
