### ISSUE TITLE
extra empty line when deleting across lines with `dw` or `de`

### ISSUE THREAD

**Issue by josephmturner** [emacs-evil/evil#1576]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 27.2 (build 1, x86_64-unknown-linux-gnu)
Operating System: Debian Bullseye, with Emacs from Guix package manager
Evil version: 1.14.0
Evil installation type: Guix
Graphical/Terminal: terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs (from within `evil` git repo, using `make terminal`)
- Given a buffer containing:
```
1
2
3
4
```
- Place cursor on `2` in normal state
- Type `d2w`

# Expected behavior
```
1
4
```

# Actual behavior
```
1

4
```

# Further notes
A similar issue arises with `de`.

**Comment by tomdl89** [comment]
relevant comment in vim's source:
>/*
     * Imitate the strange Vi behaviour: If the delete spans more than one
     * line and motion_type == MCHAR and the result is a blank line, make the
     * delete linewise.  Don't do this for the change command or Visual mode.
     */

**Comment by tomdl89** [comment]
@josephmturner this should now be fixed in master. Please let me know if you observe otherwise.

**Comment by josephmturner** [comment]
Works fine on my machine. Thank you for fixing this bug so quickly! Have a good day :)
