### ISSUE TITLE
In insert state, `C-h` does not delete the preceding character

### ISSUE THREAD

**Issue by josephmturner** [emacs-evil/evil#1577]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 27.2 (build 1, x86_64-unknown-linux-gnu)
Operating System: Debian Bullseye, with Emacs from Guix package manager
Evil version: 1.14.0
Evil installation type: Guix
Graphical/Terminal: terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs (from within `evil` git repo, using `make terminal`)
- In insert state, type `emacs`
- While still in insert state, type `C-h`

# Expected behavior
`emac`

# Actual behavior
`C-h` help prefix

# Further notes
The vim-like behavior can be replicated with
`(define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join))`

What do you think about a `evil-want-C-h-delete` flag? Maybe the current behavior should be the default since its useful for determining what commands are bound to insert state keybindings, like `C-h k C-w`.

**Comment by tomdl89** [comment]
This would need addressing for replace state too (where backspace "reverts" overwritten chars). Although technically any deviation from vim is a "bug", I see this more as a feature request, so I won't work on this anytime soon. I'm not opposed to it, so PR welcome.

**Comment by josephmturner** [comment]
I agree, and I'm happy with the current behavior. Just thought I'd let you know. Thank you!
