### ISSUE TITLE
evil's ex command line should understand %

### ISSUE THREAD

**Issue by g-gundam** [emacs-evil/evil#1579]
# Issue type

- Enhancement request

# Environment

Emacs version: 27.1
Operating System: Pop!_OS 21.04
Evil version: evil-git-0206197b2
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps

- Start Emacs
- Open a file and let its contents be:
```
3
2
1
```
- Save the file to disk.
- Go to the bottom of the file.
- In the evil command line, type `:r!sort %`

# Expected behavior
The contents of the buffer should be

```
3
2
1
1
2
3
```

# Actual behavior

```
3
2
1
sort: cannot read: %: No such file or directory
```

# Further notes
In vim, refer to the following help documents.
- :help :read!
- :help :_%
- :help current-file

**Comment by leungbk** [comment]
@g-gundam Try this patch:

```diff
diff --git a/evil-commands.el b/evil-commands.el
index 3584616..3c77b1d 100644
--- a/evil-commands.el
+++ b/evil-commands.el
@@ -3199,7 +3199,7 @@ If no FILE is specified, reload the current buffer from disk."
           (save-excursion
             (forward-char (cadr result))
             (unless (bolp) (insert "\n"))))
-      (shell-command (substring file 1) t)
+      (shell-command (evil-ex-replace-special-filenames (substring file 1)) t)
       (save-excursion
         (goto-char (mark))
         (unless (bolp) (insert "\n"))))))
-- 
2.34.1

```

If you're happy with it, I'll PR. Let me know if there's something wrong.
