### ISSUE TITLE
Issue with call to `with-demoted-errors` in `evil-fold-action` (evil-commands.el)

### ISSUE THREAD

**Issue by polaris64** [emacs-evil/evil#1585]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.17.4) of 2022-02-22
Operating System: Arch Linux, 5.16.10-arch1-1 #1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000 x86_64 GNU/Linux
Evil version: 1.14.0
Evil installation type: tracking `master` from here (commit 00fca685479e772361765b13de4689099a328c28)
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Open a source code buffer
- Enable `hs-minor-mode`
- Try toggling folding of a block with `z a`

# Expected behavior
`hs-toggle-hiding` should be called and folding of the block should be toggled

# Actual behavior
Nothing appears to happen, no errors are displayed

# Further notes
This appears to be due to a missing `FORMAT` argument in the call to `with-demoted-errors` in `evil-fold-action`.

See: - https://github.com/emacs-evil/evil/blob/00fca685479e772361765b13de4689099a328c28/evil-commands.el#L3068

Changing this line to the following solves the problem: -

```elisp
              (with-demoted-errors "evil-fold-action: %S" (funcall fn))))
```

**Comment by tomdl89** [comment]
Thanks for the bug report. I can't understand why adding a `FORMAT` argument to `with-demoted-errors` should fix this. The docstring says (and the code confirms:
>For backward compatibility, if FORMAT is not a constant string, it
is assumed to be part of BODY, in which case the message format
used is "Error: %S".

**Comment by Claude-Ray** [comment]
@tomdl89 The compatibility code has been dropped by this commit https://github.com/emacs-mirror/emacs/commit/d52c929e31f60ff0462371bfe27ebd479e3e82bd

**Comment by polaris64** [comment]
Hi @tomdl89, any news about the fix for this, it seems like it should be straightforward? As the previous default was to use "Error: %S" as the format string, just adding this as the first argument to the call to `with-demoted-errors` should fix the issue while maintaining the previous behaviour.

**Comment by tomdl89** [comment]
Hi @polaris64 sorry just very busy. If you want to make a PR I'll merge. Otherwise you'll have to wait a few days until I'm back at my desk.

**Comment by polaris64** [comment]
Hi @tomdl89, no problem at all, here's the PR: https://github.com/emacs-evil/evil/pull/1586

**Comment by polaris64** [comment]
Thanks @tomdl89 for merging my PR.

As a quick follow-up, it looks like this was actually an error in Emacs (see https://lists.gnu.org/archive/html/bug-gnu-emacs/2022-03/msg00061.html). However it's still good to have this explicit `FORMAT` argument I think as using the function without it is marked as obsolete.
