### ISSUE TITLE
Multi Select and surround

### ISSUE THREAD

**Issue by i-have-no-name** [emacs-evil/evil#1588]
# Issue type

- Question

# Environment

Emacs version: 27.2
Operating System: macOS Monterey
Evil version: 20220309.2216
Evil installation type: EmacsDoom

# Further notes

Hello. Sorry, maybe it's not a right place for such question, but does evil mode can make such thing ?

![ezgif-5-e088706bcd](https://user-images.githubusercontent.com/7874052/158854949-c79badb5-bb50-42c0-a386-23f650248be1.gif)

**Comment by tomdl89** [comment]
Evil doesn't directly provide this, but evil-surround does provide the wrapping with tags. Multiple cursors isn't super necessary with evil because you can repeat things so easily with dot, but there I do seem to recall there are packages which support this.

**Comment by tomdl89** [comment]
Take a look at https://github.com/gabesoft/evil-mc
?
