### ISSUE TITLE
:4y moves cursor

### ISSUE THREAD

**Issue by mcp292** [emacs-evil/evil#1593]
# Issue type

- Bug report

# Environment

- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. f54897584)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm

# Reproduction steps
- Start Emacs
- Type or copy more than four lines into buffer
- `G` to the bottom
- `:4y`

# Expected behavior

The cursor shouldn't move. See [this SO post](https://unix.stackexchange.com/q/1295/409331).

# Actual behavior

The cursor moves to the line in question. 

# Further notes
This is true for ranges, `:4,7y`, and relative yanks and ranges, `:+4y`, `:-2,-5y`.

**Comment by tomdl89** [comment]
@mcp292 this should now be fixed in master. Please let me know if you observe otherwise.

**Comment by mcp292** [comment]
Can confirm, it now works as expected. Thank you!
