### ISSUE TITLE
C-w f is undefined

### ISSUE THREAD

**Issue by SeveralPeople-a** [emacs-evil/evil#1622]
# Issue type

- Enhancement request

# Environment

Emacs version: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31) of 2022-04-04
Operating System: Gentoo on WSL
Evil version: 1.15.0
Evil installation type: probably MELPA
Graphical/Terminal: Terminal emulator (WSL in Windows Terminal)
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Move the pointer to a file name
- Type C-w f

# Expected behavior
- Should split the screen and open the selected file

# Actual behavior
- "C-w f is undefined"

**Comment by tomdl89** [comment]
PR Welcome!

**Comment by tomdl89** [comment]
Actually I think I mostly fixed this here: https://github.com/emacs-evil/evil/commit/5e562ae0a5775a6928fddb6f97a76d770a59dfa6
