### ISSUE TITLE
:q on last window in tab kills emacs

### ISSUE THREAD

**Issue by JoshMcguigan** [emacs-evil/evil#1624]
# Issue type

- Bug report

# Environment

Emacs version: 28.1
Operating System: Arch
Evil version: evil-git-1fde8719e
Evil installation type: Not sure, spacemacs
Graphical/Terminal: GUI
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Create at least one new tab with `tab-new`
- Run `:q` in a tab

# Expected behavior

Close tab

# Actual behavior

Closes emacs

# Further notes

I believe the issue is in the `evil-quit` command. The following modified version of that command solves the issue I am describing by attempting to close a tab (`tab-bar-close-tab`) before falling back to killing emacs.

```elisp
(evil-define-command evil-quit (&optional force)
  "Closes the current window, current frame, current tab, Emacs.
If the current frame belongs to some client the client connection
is closed."
  :repeat nil
  (interactive "<!>")
  (condition-case nil
      (delete-window)
    (error
     (if (and (boundp 'server-buffer-clients)
              (fboundp 'server-edit)
              (fboundp 'server-buffer-done)
              server-buffer-clients)
         (if force
             (server-buffer-done (current-buffer))
           (server-edit))
       (condition-case nil
           (delete-frame)
         (error
          (condition-case nil
              (tab-bar-close-tab)
            (error
             (if force
                 (kill-emacs)
               (save-buffers-kill-emacs))
             ))
          ))))
    ))
```

**Comment by tomdl89** [comment]
Sounds sensible. Would you like to open a PR?

**Comment by JoshMcguigan** [comment]
> Would you like to open a PR?

Yes absolutely! The one thing I wasn't sure about is `tab-bar-close-tab` would only be available since (I believe) emacs version 27, while I see evil supports emacs back to version 24. 

I believe this still works because in the case this function is missing we'll catch the error and close emacs just like `evil-quit` did before, but I wasn't sure if there was some specific way to handle this? 

Either way, I'll get a PR up soon.

**Comment by JoshMcguigan** [comment]
Opened PR #1625 implementing the proposed fix for this. Thanks for the quick response!
