### ISSUE TITLE
Feature request: Increment number

### ISSUE THREAD

**Issue by samimb** [emacs-evil/evil#1631]
# Issue type
- Enhancement request

# Environment

Emacs version: 28.1
Operating System: macOS Monterey 12.4
Evil version: 1.15.0
Evil installation type: MELPA
Graphical/Terminal: Terminal

# Further notes
Request for vims functionality of incrementing visual-state values
https://vim.fandom.com/wiki/Increasing_or_decreasing_numbers

This should ideally be unbound as `C-a` is bound to beginning of line

**Comment by tomdl89** [comment]
Please check out https://github.com/juliapath/evil-numbers which is available on melpa.
To anticipate a follow-up question, I can't se a good reason not to include this code in evil itself, but surprisingly this doesn't come up often.
