### ISSUE TITLE
undo-redo functionality not working with emacs 29

### ISSUE THREAD

**Issue by sethen** [emacs-evil/evil#1641]
# Issue type
- Bug report

# Environment
Emacs version: 29.0.50
Operating System: Ubuntu 22.04
Evil version: 1.15.0
Evil installation type: Melpa
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Type something
- Undo with undo
- Try and redo change

# Expected behavior
- Should redo

# Actual behavior
- Throws error about redo functionality not being on

# Further notes

Here is a video of the issue

https://user-images.githubusercontent.com/1493530/181132347-0a910168-9ca9-45ad-a339-c63073d8a5f0.mp4

**Comment by tomdl89** [comment]
@sethen can you try replacing
```
:config (setq evil-undo-system 'undo-redo)
```
with
```
:custom (evil-undo-system 'undo-redo)
```
It's a good idea to use use-package's `:custom` for defcustoms, or outside of use-package, to use `custom-set-variables` in case the customization runs code (like in this case) rather than just setting a variable.

**Comment by tomdl89** [comment]
I'll close, assuming my suggested fix is ok. Please feel free to reopen if not.

**Comment by sethen** [comment]
@tomdl89 

I changed my code this this:

```elisp
(require 'consult)
(require 'treemacs)
(require 'use-package)

(use-package evil
  :commands
  (evil-define-key* evil-mode evil-set-leader)
  :custom
  (setq evil-search-module 'evil-search
		evil-undo-system 'undo-redo)
  :defines
  (evil-search-module)
  :init
  (evil-mode 1))

(provide 'sethen-evil)
```

Still seeing the same issue as before

**Comment by sethen** [comment]
Oh nevermind -- the issue was I was setting this a variable rather than calling the function -- sorry about that!  Works now
