### ISSUE TITLE
Regression: `daw` and other "around word" commands seem broken for the last word in a line or sentence

### ISSUE THREAD

**Issue by kenranunderscore** [emacs-evil/evil#1644]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0)
Operating System: NixOS (unstable)
Evil version: Commit `5826a8877736fc734ea9da7d2bba11ef2b05032c`
Evil installation type: `straight.el` via MELPA
Graphical/Terminal: graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- In an empty buffer, enter at least two word, say `foo bar`, such that `bar` is the last word in a line
- With point over `bar`, press `daw` or `vaw`

# Expected behavior
The whitespace before `bar` is deleted.

# Actual behavior
Only `bar` itself is deleted, but the whitespace stays there.

# Further notes
I bisected the recent `evil` commits, and the one I put above (`5826a8877736fc734ea9da7d2bba11ef2b05032c`) is the actual culprit. It mentions changing the behavior of specifically `daw`, but with a supposedly different outcome.

**Comment by tomdl89** [comment]
Thanks for the bug report @kenranunderscore - I'm surprised we don't have a test for that. I shall add one when I fix. Hopefully in the next few days.

**Comment by tomdl89** [comment]
@bcc32 fyi

**Comment by tomdl89** [comment]
@kenranunderscore this should now be fixed in master. Please let me know if you observe otherwise.

**Comment by bcc32** [comment]
Oops, what a basic mistake on my part!  Thank you for fixing this, @tomdl89.

**Comment by kenranunderscore** [comment]
Perfect, thanks for the quick fix :+1:
