### ISSUE TITLE
Deleting into register doesn't work

### ISSUE THREAD

**Issue by mcp292** [emacs-evil/evil#1645]
# MWE
```txt
line 1
line 2

last thing deleted
```

1. Go to the top of the file: `gg`.
2. Select the first two lines: `V j`.
3. Delete into register: `"rd`.
4. Delete what's remaining in file: `dd` `dd`.
5. Put from register: `"rp`.

# Problem
Step 5 doesn't work as intended. Behavior deviates from Vim.

**Comment by mcp292** [comment]
It seems to be the case that `dd` overwrites or clears the registers as even yanking into register and then deleting results in the same behavior.

**Comment by tomdl89** [comment]
@mcp292 I'm away from my pc right now. Can you replicate in a make Emacs session? I'd expect there would be tests for this

**Comment by mcp292** [comment]
I'm not sure what that is. Please advise.

**Comment by tomdl89** [comment]
If you have evil's source, run `make emacs` in the terminal in that directory. It'll try to autorun the tests which you can skip or wait for. That Emacs has evil but nothing else loaded, so eliminates other packages which may be interfering.

**Comment by mcp292** [comment]
Oh, I don't. Apologies I should have mentioned that I am using spacemacs.

**Comment by tomdl89** [comment]
No problem. Worth a shot. I'll take a look on the weekend

**Comment by mcp292** [comment]
Much appreciated!!

**Comment by tomdl89** [comment]
I can replicate and I'm pretty sure I know why this is happening. I'm really surprised we don't have a test against this, so I'll add that when I fix. Hopefully soon.

**Comment by tomdl89** [comment]
@mcp292 this should now be fixed in master. Please let me know if you observe otherwise.

**Comment by mcp292** [comment]
Outstanding work! Can confirm you fixed it!

I love how clean the solution is. Not sure why it works though.

**Comment by tomdl89** [comment]
`"r` sets `evil-this-register` to `r` so the next yank/delete command overwrites that register. In normal state, all commands reset it to nil after they run (using a post-command-hook) but in this case, the delete was in visual state, so it was never reset. I just made it so `evil-this-register` is reset when leaving visual state too.

**Comment by mcp292** [comment]
Ah! That was my confusion! I thought that the register was being cleared/reset, but it seems that the register was being overwritten. Thank you for explaining and for making the fix! I'd love to fund your efforts but don't see a link on your GH.
