### ISSUE TITLE
Cannot run fresh evil on new emacs installation

### ISSUE THREAD

**Issue by glenaddict** [emacs-evil/evil#1654]
# Issue type
- Bug report

# Environment

Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-08-15
Operating System: Ubuntu 20.04
Evil version: Evil version 1.15.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps

- I placed the following in my .emacs

;; Set up package.el to work with MELPA
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)

;; Download Evil
(unless (package-installed-p 'evil)
  (package-install 'evil))

;; Enable Evil
(require 'evil)
(evil-mode 1)

- Start Emacs

# Expected behavior
Evil works

# Actual behavior
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "calc-loaddefs.el")
  load("calc-loaddefs.el" nil t)
  require(calc)
  eval-buffer(#<buffer  *load*-528710> nil "/home/bob/.emacs.d/elpa/evil-20220812.1203/evil-co..." nil t)  ; Reading at buffer position 1036
  load-with-code-conversion("/home/bob/.emacs.d/elpa/evil-20220812.1203/evil-co..." "/home/bob/.emacs.d/elpa/evil-20220812.1203/evil-co..." nil t)
  require(evil-common)
  eval-buffer(#<buffer  *load*-784116> nil "/home/bob/.emacs.d/elpa/evil-20220812.1203/evil.el" nil t)  ; Reading at buffer position 5563
  load-with-code-conversion("/home/bob/.emacs.d/elpa/evil-20220812.1203/evil.el" "/home/bob/.emacs.d/elpa/evil-20220812.1203/evil.el" nil t)
  require(evil)
  eval-buffer(#<buffer  *load*> nil "/home/bob/.emacs" nil t)  ; Reading at buffer position 393
  load-with-code-conversion("/home/bob/.emacs" "/home/bob/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x1746a0482d913a43>) #f(compiled-function () #<bytecode -0x1f3c6feddc0a97f5>) t)
  command-line()
  normal-top-level()

# Further notes

**Comment by tomdl89** [comment]
Thanks for the bug report @glenaddict - so evil can't load `calc`? That seems strange. Did you build without it, or has emacs 29 broken being able to require it? Does `calc` appear when you M-x for it? If so, does it work? We can always make evil fail loading it silent, but I'd like to understand if there's an issue with emacs 29 or your build of it first.

**Comment by tomdl89** [comment]
Thanks for the update @glenaddict . I'll mark this as closed (for housekeeping) but will reopen it if you (or anyone else) finds that the issue does in fact lie with evil.
