### ISSUE TITLE
]p uses different register

### ISSUE THREAD

**Issue by mcp292** [emacs-evil/evil#1665]
# MWE
```txt
line 1
line 2
line 3
```

1. Go to top of file: `gg`.
2. Delete the first two lines: `V j d`.
3. Yank "line 3": `yy`.
4. Paste from register 2: `"2]p`.

# Problem
Step 4 doesn't work, but `"2p` does.

**Comment by tomdl89** [comment]
`]p` isn't implemented at all as far as I can see.

**Comment by mcp292** [comment]
`]p` pastes to next line as far as I understand. 

I don't get this from the documentation (`:h change.txt`):

> ["x]]p		    or					\*]p\* \*]\<MiddleMouse\>\*
> ["x]]\<MiddleMouse\>	Like "p", but adjust the indent to the current line.
> 			Using the mouse only works when 'mouse' contains 'n'
> 			or 'a'.

**Comment by mcp292** [comment]
From `describe-key`:

> ] p runs the command evil-unimpaired/paste-below (found in
> evil-normal-state-map), which is an interactive compiled Lisp function
> in ‘evil-unimpaired.el’.
> 
> It is bound to ] p.
> 
> (evil-unimpaired/paste-below)
> 
> Not documented.
>

**Comment by mcp292** [comment]
I should have mentioned I am using spacemacs!

**Comment by tomdl89** [comment]
> ] p runs the command evil-unimpaired/paste-below

Ah I see. I guess you'll need to open an issue on the evil-unimpaired project.
