### ISSUE TITLE
How to make/replace a region in visual state by elisp?

### ISSUE THREAD

**Issue by daanturo** [emacs-evil/evil#1668]
# Issue type

- Question

# Environment

Emacs version: 29.0.50
Operating System: Arch Linux
Evil version: 1.15.0
Evil installation type: straight
Graphical/Terminal: graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Question detail:
How do I construct an active region in visual state?

For vanilla Emacs, one can achieve that by manipulating the `point` and `mark`.

How do I do that in evil's visual state?

Particularly, I try to implement moving lines up/down:

Before moving the line "dolor" up:
![image](https://user-images.githubusercontent.com/32123754/187218141-a2a6bc1c-ed20-4d94-ba05-8db0a05686fe.png)

After moving, it looks like this:
![image](https://user-images.githubusercontent.com/32123754/187218180-9d060db1-a880-4105-985e-bbacbb427b24.png)

But I need this visual selection:
![image](https://user-images.githubusercontent.com/32123754/187218215-d9fb89e7-87fb-4e8f-ad45-80304d6b17dc.png)

**Comment by tomdl89** [comment]
@daanturo what have you tried? i.e. what keystrokes/elisp did you use to get the (undesired) result? (I'm asking as I hope it will help me actually understand the question, which I don't, yet)

**Comment by daanturo** [comment]
[my-move-lines](https://gitlab.com/daanturo/e/-/blob/4cc6169017635542d411dcab9d8e5e63903f1203/autoload/my-move-lines.el#L50)

It's an implementation of `M-up/down` (moving selected lines up/down).

The general idea is like this: 
- delete the lines that cover the region
- `forward-line` to the desired position
- insert deleted text and restore `point` & `mark`, therefore the region

It can restore vanilla Emacs' point and mark for now, but things get uncontrolled when I select text in visual state.

I vaguely know that `evil-visual-mark` and `evil-visual-point` are involved, but don't know which API to to utilize, like Emacs' `push-mark` for the mark and `goto-char` for point.

**Comment by daanturo** [comment]
Thank you, `evil-visual-make-region` (https://emacs.stackexchange.com/questions/34890/how-to-set-the-evil-visual-line-region-selection-programmatically-in-emacs-lis) gives me the desired results.
