### ISSUE TITLE
Question: How to bind "SPC SPC" to a function?

### ISSUE THREAD

**Issue by synic** [emacs-evil/evil#1670]
- Question

Emacs version: 28.1
Operating System: MacOS Monterey 12.5.1
Evil version: evil-git-201d22bcc
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

Right now I have my leader key set to SPC. I want to bind `SPC SPC` to a function (`avy-goto-word-or-subword-1`). How can I do that without the `evil-leader/set-key` that got deprecated?

**Comment by tomdl89** [comment]
Not at my PC right now, but does https://github.com/noctuid/evil-guide#leader-key help?
