### ISSUE TITLE
Regression for H/M/L bindings

### ISSUE THREAD

**Issue by snyball** [emacs-evil/evil#1674]
# Issue type
- Bug report

# Environment

Emacs version: 29.0.50
Operating System: Arch
Evil version: 1.15.0
Evil installation type: doom/straight.el `(package! evil :pin "157af04d2cf466e301e82b0e667c5e7203fd96a2")` (157af04d2cf466e301e82b0e667c5e7203fd96a2)
Graphical/Terminal: graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- `make emacs`
- Open file containing indented lines
- Move cursor to column `n < min-indent`
- Do one of:
  - Press `H`, with an indented line at the top
  - Press `M`, with an indented line in the middle
  - Press `L`, with an indented line at the bottom

# Expected behavior
The cursor should be at `^` / `_` i.e soft-bol.

# Actual behavior
The cursor is at column `n`.

# Further notes
Vim 9.0 and Neovim 0.7.2 disagree on what to do here (tested with `nvim --clean` and `vim --clean`.) Vim moves the cursor to soft-bol just like the original `vi`, while Neovim at some point decided to move it to column `n`.

Evil used to do what Vim did and currently does, i.e reset the column to `^` on `H`/`M`/`L` movement.

**Comment by snyball** [comment]
I've also opened an issue for this on the neovim tracker: https://github.com/neovim/neovim/issues/20296

**Comment by justinmk** [comment]
> Vim 9.0 and Neovim 0.7.2 disagree on what to do here

The disagreement is in the default value of 'startofline' option.

**Comment by snyball** [comment]
@justinmk Ah, gotcha. Didn't know about that option, then this is solved with

```emacs-lisp
(setq evil-start-of-line t)
```
