### ISSUE TITLE
Replacing single character with digraph is repeated incorrectly

### ISSUE THREAD

**Issue by wiktorkuchta** [emacs-evil/evil#1675]
# Issue type

- Bug report

# Environment

Emacs version: 28.1
Operating System: Fedora 36
Evil version: evil-git-26ec0cd
Evil installation type: Doom (?)
Graphical/Terminal: graphical (Wayland)
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Write some text and go to normal mode
- Replace a character with a digraph: `r` `CTRL-K` `a*` will replace it with α, for example
- Move the cursor to another character and repeat (`.`) the action

# Expected behavior
The character should be replaced with the character encoded by the digraph (α)

# Actual behavior
The character is replaced with the second character of the digraph (`*`)

# Further notes

**Comment by tomdl89** [comment]
(For my notes...) This happens because `evil-this-command-keys` uses `this-single-command-keys` which 

> returns the key sequence that invoked the present command... [except] ...if the command has called read-key-sequence, [where] it returns the last read key sequence.

 `evil-read-digraph-char` does call `read-key-sequence` (indirectly), which appears to be clobbering the "command" keys.

**Comment by wiktorkuchta** [comment]
Thanks for the quick response! Seems fixed now.

I found a similar old issue: #681, though I cannot reproduce it (maybe fixed already).
