### ISSUE TITLE
`:substitute` up to EOB does not work

### ISSUE THREAD

**Issue by axelf4** [emacs-evil/evil#1682]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu)
Operating System: NixOS 22.05
Evil version: Evil version evil-git-a8adc87
Evil installation type: MELPA
Graphical/Terminal: terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs using `make emacs`
- In the initial scratch buffer on line 4, which is the last line and where the cursor starts off, insert the text `foo`
- Run the Ex command `:s/foo` on that same line

# Expected behavior
The contents of the line should be replaced with nothing, as the command preview suggests. In fact, that is also what happens the matching buffer segment does not include the end of the buffer.

# Actual behavior
Nothing is substituted.

# Further notes

**Comment by axelf4** [comment]
I tried to sketch on a solution on [a branch here](https://github.com/axelf4/evil/tree/fix-sub-to-eob). Is it not as simple as that? I'll look into it more and maybe create a PR.

**Comment by tomdl89** [comment]
Yeah, looks pretty good to me. I think it was over complicated before. 👍
