### ISSUE TITLE
Error: "customize 'evil-undo-system' for redo functionality" even when variable is set.

### ISSUE THREAD

**Issue by JacksonGariety** [emacs-evil/evil#1697]
# Issue type

Bug report

# Environment

Emacs version: 28.2
Operating System: ArchLinux (kernal 5.19.13.arch1-1)
Evil version: 20221006.2227
Evil installation type: melpa
Graphical/Terminal: terminal
Tested in a `make emacs` session: Yes, still occurs.

# Reproduction steps
- Start Emacs
- `M-x set-variable` then `evil-undo-system` then `undo-redo`
- Optionally: `package-install` `undo-tree` or `undo-fu` (same result either way)
- type something
- hit `u` to undo
- hit `C-r` to redo

# Expected behavior
Text should reappear and no message should print to minibuffer

# Actual behavior
- get message "customize evil-undo-system for redo functionality" in minibuffer
- the text does not reappear

# Further notes
Started after updating yesterday (Oct 6th)

**Comment by tomdl89** [comment]
Have you searched the closed issues in this repo to see if this has been asked (and answered) before?

**Comment by JacksonGariety** [comment]
@tomdl89 Yes, the solution in #1372 does not work for this issue, which I believe was introduced yesterday. thx

**Comment by tomdl89** [comment]
I'm away from my pc for the weekend so can't take a look, but in the meantime, are you able to roll back to an earlier version to confirm this? I don't think we've merged anything even remotely in this area recently.

**Comment by JacksonGariety** [comment]
I think actually it has to do with a change I made to my config. My mistake.
