### ISSUE TITLE
Mouse highlighting does not disappear upon keyboard movement

### ISSUE THREAD

**Issue by gvfarns** [emacs-evil/evil#1698]
# Issue type
- Enhancement request

# Environment

Emacs version: GNU Emacs 28.1
Operating System: Fedora 36
Evil version: 1.15.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  No

# Reproduction steps

- Start Emacs
- Highlight text with mouse-1
- Press j or any other movement key

# Expected behavior

- Highlighted region disappears

# Actual behavior

- Highlighted region expands or contracts

# Further notes

The behavior appears rooted in the evil movement functions. If default emacs movements are used (for example, `forward-char`), the mouse-highlighted region will disappear. However, if evil movement functions are called (`evil-forward-char`), the highlighted region expands as if it had been created like a regular visual region.

The current behavior is problematic as clicking in the emacs window after being somewhere else often inadvertently highlights at least a few characters. Then the user is confused when movement starts highlighting. In addition, under this behavior, the user often cannot go into insert mode upon clicking into emacs and may accidentally delete a large area that was unexpectedly highlighted.  

I can imagine some folks wanting this behavior, but it would be nice if there was at least a switch (or other workaround) that allowed the default emacs behavior.

**Comment by tomdl89** [comment]
> If default emacs movements are used (for example, forward-char), the mouse-highlighted region will disappear.

Can you provide some repro steps for this? I can't replicate this.

As for the rest of the issue, how do you envisage evil handling non-movement keys? E.g. would `y` yank the selected region, or act as if it were in normal mode, waiting for a movement?

**Comment by gvfarns** [comment]
> Can you provide some repro steps for this? I can't replicate this.

I apologize. I just did a little testing, and it looks like I misspoke about the steps to reproduce. It appears that I am wrong in thinking the difference is driven by the motion commands. The effect appears to be caused simply by loading evil.  Hopefully the following steps are more reproducible.

## To see default emacs behavior

* Open a text or code file with `emacs -Q`
* Highlight a region with mouse 1
* M-x forward-char

You should see the highlighted region disappear. 

## To see evil behavior

Try using the following init.el

```
(setq package-archives '(("melpa" . "https://melpa.org/packages/")))
(package-initialize)
(setq use-package-always-ensure t)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile (require 'use-package))
(use-package evil
             :demand t
             :init
             (setq evil-want-keybinding nil)
             :config
             (evil-mode 1))
```

* Open emacs
* Highlight region with mouse 1
* M-x forward-char

The region remains highlighted.

**Comment by gvfarns** [comment]
If you can give me any hints about where to look for the source of this issue, I will try and get to the bottom of it and potentially submit a PR with a solution that won't break existing code. Sorry, my detective work on this is questionable.

**Comment by tomdl89** [comment]
Sure. So I did `C-h k` and clicked to find out that `evil-mouse-drag-region` is called. That function basically just calls `evil-mouse-drag-track` which is an awful 175 line function. This seems to be where initialization of visual state is triggered. So my thinking would be that you need to store the fact that "visual state was triggered by the mouse" in a global var, which can be accessed when the time comes to decide if a command should respect that visual region, or exit visual state and await a motion. That's where I'd start, anyway.

**Comment by gvfarns** [comment]
Thanks. Actually, if I remap `<down-mouse-1>` so that it calls `mouse-set-region` instead of `evil-mouse-set-region` (so the same functions are called whether evil is loaded or not), the behavior does not change. I therefore believe that it `evil-mouse-drag-region` is probably not the culprit. I'll keep looking around. But if you have any other ideas based on this information, please let me know.

**Comment by tomdl89** [comment]
My point is that you need to find a way to set a flag saying "the region just set was set by the mouse, not the keyboard" so you know to exit visual state when the next command is given. None of what you said surprises me, but also I don't think it's relevant to my suggestion. Thankfully `evil-mouse-set-region` and `evil-mouse-drag-region` _are_ called by `<down-mouse-1>` so we have control over what flags they do or don't set. The way to look at this is "what state do we need to be in when we yank/delete/etc?".

**Comment by gvfarns** [comment]
Thanks for your help. It seems to me that a fruitful direction would be to see how this is handled in base emacs. I did a comparison of all variables set when some text is highlighted in emacs with no evil and with evil. A difference I found was that `transient-mark-mode` was set to `(only . t)` in non-evil emacs when the mouse highlights. According to the docs, this temporarily sets transient-mark-mode until a subsequent point motion command.

If I set this at the end of `evil-mouse-drag-region`, then do `M-x forward-line`, then the region disappears, as would be desired. However, it does not disappear if I only do an evil motion. `forward-line` is defined in the C code and doesn't seem to do much, so I'm having a hard time finding the actual bit of code that, presumably, is calling `(deactivate-mark)` when `forward-line` is executed. All, oddly, `forward-char` does not clear the region, but `forward-char` followed by an evil motion does.  

I will keep looking. Let me know if this gives you any ideas.

**Comment by tomdl89** [comment]
@gvfarns I just pushed a branch to my evil fork with a very basic example of my idea. Maybe try it locally and see if that addresses what you want.

**Comment by gvfarns** [comment]
@tomdl89 Your branch "mouse-region-spike" works exactly right. You are a hero. I hope this can make it into the upstream.

**Comment by tomdl89** [comment]
Cool, I'm glad. It needs a bit more work, as I've noticed it doesn't like `v` `V` etc after clicking. Hopefully I'll take a look soon. I'll probably hide it behind a flag so you'll have to `setq` something once I merge.

**Comment by tomdl89** [comment]
I've merged this functionality into master. To take advantage of it, add:
```
(setq evil-transient-mouse-selection t)
```
to your config. If you want to use the mouse selection (like normal) press `v` to make the selection stick around.

Lemme know how you get on with it.

**Comment by gvfarns** [comment]
@tomdl89 I have been testing this and, so far, it is working exactly as desired. Thank you so much for implementing this! I suspect once knowledge of this has percolated into the evil community, everyone will want to set this flag. I really appreciate your hard work, and I know others do too.
