### ISSUE TITLE
`evil-interactive-form` void function definition with native compilation

### ISSUE THREAD

**Issue by adolfocorreia** [emacs-evil/evil#1699]
# Issue type
- Bug report

# Environment

Emacs version: GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-09-12
Operating System: archlinux
Evil version: 1.15.0 (20221006.2227)
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session: No
Tested in a clean Emacs environment without any additional packages loaded: Yes

# Reproduction steps
- Start Emacs
- Install evil from MELPA using quickstart instructions (README.md)
- `(require 'evil)`

# Expected behavior
Evil is loaded without warnings.

# Actual behavior
Evil is loaded with the following warning message:
`Warning (comp): /home/USER/.emacs.d/elpa/evil-20221006.2227/evil-common.el: Error: Symbol's function definition is void evil-interactive-form`

# Further notes
This warning only appears when using the `emacs-nativecomp` package in archlinux. There is no warning when using the regular `emacs` package. I suppose this issue might be related to this commit: https://github.com/emacs-evil/evil/commit/460af439e51da7f6602732318ff52820bd2286fd, since I did not have any such warning messages before.

**Comment by tomdl89** [comment]
Thanks for this. I'll take a look very soon.
