### ISSUE TITLE
Inconsistency between how Vim and Evil handle \d in substitute command

### ISSUE THREAD

**Issue by vaidyafamily** [emacs-evil/evil#1707]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-09-12
Operating System: Arch Linux
Evil version: 1.15.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Put the following in a buffer

````
 '(default ((t (:background "blue4" :foreground "white"))))
 '(mouse ((t (:foreground "black"))))
 '(cursor ((t (:background "gold"))))
 '(border ((t (:foreground "black"))))
 '(ecb-source-in-directories-buffer-face ((t (:foreground "LightBlue1"))))
 '(gnus-mouse-face ((t (:background "steel blue" :foreground "black"))))
 '(goto-address-mail-face ((t (:italic t :foreground "yellow2"))))
 '(goto-address-mail-mouse-face ((t (:background "yellow2" :foreground "black"))))
 '(goto-address-url-face ((t (:bold t :foreground "white"))))
 '(goto-address-url-mouse-face ((t (:background "steel blue" :foreground "black"))))
 '(list-matching-lines-face ((t (:bold t :foreground "white"))))
 '(view-highlight-face ((t (:background "steel blue" :foreground "black"))))
 '(erc-input-face ((t (:foreground "yellow2"))))
````

- Try executing the following ex-command in emacs:`%s/yellow\d/tmp/g`.

# Expected behavior

I expect all instances of the string 'yellow2' to be replaced by 'tmp'. I have confirmed that this works in Vim.

# Actual behavior

No substitutions are made.

**Comment by tomdl89** [comment]
@vaidyafamily try adding
```
(setq evil-ex-search-vim-style-regexp t)
```
to your config and let me know if that fixes it.

**Comment by vaidyafamily** [comment]
Thanks, sorry for the nonissue.
