### ISSUE TITLE
<leader> key exits operator pending state.

### ISSUE THREAD

**Issue by HalimNaim** [emacs-evil/evil#1711]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0) of 2022-01-24, modified by Debian

Operating System: Ubuntu 22.10
Evil version: Evil version evil-git-f921816
Evil installation type: Git
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
-  (evil-set-leader '(normal visual operator) (kbd "SPC"))
-  (evil-define-key '(normal visual operator) 'global (kbd "<leader>$") 'evil-end-of-line)
- C-x b *scratch*
- d (in Normal mode to start a deletion, mode changes to <O> and cursor is half height)
- : evil-send-leader (mode changes to normal mode, discarding the d) (or SPC)

# Expected behavior
Mode remains in Operator pending, action is performed after leader key action. (in my case, some avy jump)

# Actual behavior
As said above, mode changes to normal.

# Further notes
This works as expected in visual mode.

**Comment by tomdl89** [comment]
Thanks for the bug report. I can reproduce the bug. fyi, [general](https://github.com/noctuid/general.el) doesn't have this problem, so if you use that, or would consider using that, you'll have a workaround. I'm not sure I'll look at this soon, but feel free to make a PR if you do.
