### ISSUE TITLE
Bug Add a comma in org python source blocks. 

### ISSUE THREAD

**Issue by nicolas-graves** [emacs-evil/evil#1723]
# Automatic comma insertion in org-mode python-source blocks

- Bug report

# Environment

Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
Operating System: Guix
Evil version: 1.15.0
Org version: 9.5.5
emacs-python-black : 1.1.0
Evil installation type: Guix
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Open an org file
- Create a python source block formatted with python-black with a line starting with a *:
```
#+begin_src python
if append:
   df["D"].loc[
     idx[checks[dicname][name], fill_product, :, fill_country]
    ] += (
 proportions
  * df["D"].loc[idx[name, fill_product, :, fill_country]][0]
    )
#+end_src 
```
- Enter a newline with "o"

# Expected behavior
Simply start a new line. 

# Actual behavior
Starts a new line, but adds a comma in front of the *. 

# Further notes

**Comment by nicolas-graves** [comment]
It may actually be linked to org itself, I get the same error when I comment instead of `o`.

**Comment by tomdl89** [comment]
@nicolas-graves does your latter comment mean this issue can be closed?

**Comment by axelf4** [comment]
This is replicable in an `emacs -Q` session. Please post on the Org mode issue tracker instead.

**Comment by yantar92** [comment]
> This is replicable in an emacs -Q session. Please post on the Org mode issue tracker instead.

That's not a bug. "*" are escaped to avoid treating them as headings. See https://orgmode.org/manual/Literal-Examples.html
