### ISSUE TITLE
Using vertico for ex-command completion

### ISSUE THREAD

**Issue by arijit79** [emacs-evil/evil#1725]
- Enhancement request

# Environment

Emacs version: 29.0.60
Operating System: Arch Linux
Evil version: 1.15.0
Evil installation type: MELPA
Graphical/Terminal: Graphical under X
Tested in a `make emacs` session: Yes

When completing ex commands or arguments, evil shows a plain grid for alll the matching options even though I have vertico installed. Is there a way to use vertico over the default completion interface. Digging through the source code, I found out that it calls `completion-at-point` function. I configured by completion at point ui (i.e corfu) to show the completion but it seems it isn't workng properly with it.

So finally I want to know whether there is a way to use something like vertico for ex command completion

**Comment by axelf4** [comment]
Consult provides a `completion-in-region-function` that delegates to Minibuffer completion. If you install it, you may use

```elisp
(setq completion-in-region-function #'consult-completion-in-region)
```

**Comment by arijit79** [comment]
Okay I got that, but it also replaces my corfu completion popup with the minibuffer. Any fix for this?

**Comment by arijit79** [comment]
I fixed everything by adding a minibuffer hook like this
```elisp
  (add-hook 'minibuffer-setup-hook (lambda () (setq completion-in-region-function #'consult-completion-in-region)))
```
Thanks for the help. Closing off the issue.
