### ISSUE TITLE
Is there a way to restrict `C-o` and `C-i` to only make jumps within the current buffer (on-demand)?

### ISSUE THREAD

**Issue by TahaAhmedRasheed** [emacs-evil/evil#1728]
# Issue type
- Question

# Environment

Emacs version: GNU Emacs 28.2 (build 2, x86_64-w64-mingw32) of 2022-09-13
Operating System: Windows 11
Evil version: Evil version 1.15.0
Evil installation type: Provided by Doom Emacs.
Graphical/Terminal: Graphical

Title. I'd like to have both options - across buffers, and within a single buffer.

**Comment by tomdl89** [comment]
There is the customization option `evil-jumps-cross-buffers` so you could write a very small function which did something like:
```
(evil-define-motion evil-jump-forward-in-buffer (count)
  (let ((evil-jumps-cross-buffers nil))
    (evil-jump-forward count)))
```
and bind it to a key of your choice

**Comment by tomdl89** [comment]
I'll close, assuming this is helpful. Feel free to reopen if not.
