### ISSUE TITLE
Evil movements not working properly with new treesit navigation functions.

### ISSUE THREAD

**Issue by Dickby** [emacs-evil/evil#1729]
- Bug report

# Environment

Emacs version: GNU Emacs 30.0.50 (build 7, x86_64-pc-linux-gnu, GTK+ Version 3.24.35) of 2022-12-16
Operating System:  Arch-Linux
Evil version:  1.15.0
Evil installation type: straight
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  Yes 

# Reproduction steps
- Start Emacs
- open a C source file
- M-x c-ts-mode
- invoke evil-section-forward-begin
# Expected behavior
the cursor position should go to the next function signature below point
# Actual behavior
cursor goes to the opengine '{' of the function the cursor was in when using evil-section-forward-begin
# Further notes
Other evil-mode movements are effected too, the reproduction steps are an example for a evil motion command that does not work with the new treesit navigation functions.

**Comment by axelf4** [comment]
`evil-section-forward-begin` just uses the built-in functions `beginning-of-defun` and `end-of-defun`. That is to say, I do not think this is a concern of Evil.
