### ISSUE TITLE
Suppress escape to go back to normal mode when company-mode suggestions are open

### ISSUE THREAD

**Issue by rytswd** [emacs-evil/evil#1730]
# Issue type

- Question

# Environment

Emacs version: `GNU Emacs 28.2 (build 1, aarch64-apple-darwin22.1.0, Carbon Version 169 AppKit 2299) of 2022-11-13`
Operating System: macOS Ventura
Evil version: `Evil version 1.15.0`
Evil installation type: With Doom Emacs
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs with Doom Emacs
- Enable evil-mode and company-mode
- Go into insert mode
- Type some letters (e.g. `abc`), and get company suggestions up (automatically, or by using some backend such as `company-ispell`)
- (In case of a simple ispell use case, you would likely see `abcoulomb` as the only suggested word)
- Hit escape to close the suggestion from company-mode
- The suggestion from company-mode will close, but at the same time, evil-mode goes to normal mode

# Expected behavior
The behaviour is probably correct as is, but I'd like to adjust it so that if there is other modes picking up on escape, I'd like to suppress its effect in evil-mode, and stay in whichever mode I was in previously.

# Actual behavior
It looks as if the escape key is picked up by both evil-mode and company-mode?

# Further notes
I'm arguably new to evil-mode, and asked the same question in the discussion forum in company-mode ([here](https://github.com/company-mode/company-mode/discussions/1356#discussioncomment-4458006)), but was redirected to ask here instead.
I'm sure the evil-mode behaviour is intended and correct, but would like to see if there is some adjustments that could be made via some custom function or extra configuration variables.

Any pointer would be much appreciated! 🙏

**Comment by axelf4** [comment]
> It looks as if the escape key is picked up by both evil-mode and company-mode?

No, <kbd>ESC</kbd> is bound to only `evil-normal-state` as expected - Company completion is aborted due to the cursor being moved backwards when exiting Insert state. Instead, shadow that binding when Company is active with
```elisp
(define-key company-active-map [escape] 'company-abort)
```

(Tip: Find out what gets invoked with `C-h k`. Note that an extra `C-h` is needed by default when Company is active.)

**Comment by rytswd** [comment]
@axelf4 AH! That makes perfect sense, and thank you very much for your suggestion! It works exactly as I wanted 🥰
