### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by axelf4** [emacs-evil/evil#1748]
# Issue type

- Question

Hey @tomdl89, just checking in since you are the only current maintainer as far as I can see, and has said in the past that Evil then was not fully maintained. There are quite a few year-old pull requests and issues just sitting there, some of which are trivial bug fixes that require no or little to no corrections.

If the problem is just a lack of time, I would be more than willing to help out as a co-maintainer.

**Comment by tomdl89** [comment]
Hi @axelf4 apologies for the reduced activity on here from me recently. I hope to be more involved soon. Regardless though, I would love to have a co-maintainer! I'll add you now.
