### ISSUE TITLE
Yank on Windows 10 adds an additional newline

### ISSUE THREAD

**Issue by hkjels** [emacs-evil/evil#1751]
# Bug report

# Environment

Emacs version: GNU Emacs 30.0.50 (build 5, x86_64-w64-mingw32) of 2023-01-04
Operating System: Windows 10
Evil version: Evil version 1.15.0
Evil installation type: Melpa
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Open a file with content
- Copy a line `y y`
- Paste `p`

# Expected behavior
The pasted line should be equal to the one copied

# Actual behavior
There's an additional newline pasted, so there will be a blank line below your paste.

# Further notes
This behavior is not affected by numerical arguments to `evil-yank`.
So `4yy` `p` will copy & paste four lines, but only one additional newline at the end

**Comment by tomdl89** [comment]
@hkjels shall I take your issue title to mean it _only_ happens on Windows 10, or that this is the only OS on which you've tested this? This is heavily tested in evil's regression tests, which are run on Linux, so we know it doesn't happen there. I'd be very surprised if this is OS-related tbh. If you could test in a `make emacs` session that would be helpful, as I suspect this is related to your config.

**Comment by hkjels** [comment]
You are correct! There's something wrong, but the bug I'm experiencing is from another package apparently. I'm really sorry for wasting your time.

```ert
Selector: t
Passed:  216
Failed:  1 (1 unexpected)
Skipped: 1
Total:   218/218

Started at:   2023-01-11 10:09:46+0100
Finished.
Finished at:  2023-01-11 10:10:01+0100

....................................................................................................................s.....F...............................................................................................

F evil-test-logical-visual-next-line
    Test alternating between logical and visual next/previous line motions.
    (ert-test-failed
     ((should
       (=
	(current-column)
	1))
      :form
      (= 0 1)
      :value nil))
```

**Comment by hkjels** [comment]
Ohh. And yes, I've used this configuration with both MacOS and Linux without this issue :)
