### ISSUE TITLE
v$ does not appear to respect "evil-v$-excludes-newline" var in an org-mode file.

### ISSUE THREAD

**Issue by aeberts** [emacs-evil/evil#1758]
# Issue type
- Bug report

# Environment
Emacs version: GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.6.0, Carbon Version 165 AppKit 2113.6) of 2023-01-01
Operating System: MacOS 12.6 (Monterey)
Evil version: Evil version 1.15.0
Evil installation type:  evil installed as part of Doom Emacs
Graphical/Terminal: Running in GUI.
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Ensure that the evil var `evil-v$-excludes-newline` is non-nil
- Open any org-mode file that contains text
- Go to the beginning of any line that contains text.
- in normal mode, type $ -> cursor jumps to last visible character on line (expected behaviour)
- Return cursor to the beginning of the line
- Type v$ -> selects the entire visible line (i.e. selects all visible text including the newline character)

# Expected behavior
- typing v$ would select text up to and including the last visible character, but not the newline.

# Actual behavior
- typing v$ selects the visible characters including the newline.

# Further notes
v$ appears to work properly in *.txt files and elisp files

**Comment by axelf4** [comment]
Hmm, I cannot reproduce this. Could you give reproduction steps inside a `make emacs` session, otherwise the Doom Emacs issue tracker may be more appropriate?

**Comment by aeberts** [comment]
After some more testing, `v$` works normally when org-mode is not enabled. My guess is that this is due to a configuration setting buried somewhere. I think we can close this as `not a bug`.
