### ISSUE TITLE
evil-scroll-line-down with magit-blame does not always scroll

### ISSUE THREAD

**Issue by yamanq** [emacs-evil/evil#1765]
# Issue type

- Bug report

# Environment

Emacs version: 28.2
Operating System: Arch Linux
Evil version: 1.15.0 (2ce03d4)
Evil installation type: Git (straight.el)
Magit version: 30b0deba
Graphical/Terminal: Graphical X11
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No because magit is also required.

# Reproduction steps
- Start Emacs in a clean environment: `emacs -Q`
- Load magit and evil:
```elisp
(add-to-list 'load-path "/home/myuser/.emacs.d/.local/straight/repos/magit/lisp/")
(add-to-list 'load-path "/home/myuser/.emacs.d/.local/straight/repos/compat/")
(add-to-list 'load-path "/home/myuser/.emacs.d/.local/straight/repos/dash.el/")
(add-to-list 'load-path "/home/myuser/.emacs.d/.local/straight/repos/with-editor/lisp/")
(add-to-list 'load-path "/home/myuser/.emacs.d/.local/straight/repos/evil/")

(require 'magit)
(require 'evil)
```
- Open a heavily committed file, like the README.md of this repository
- M-x magit-blame
- b (show commits adding lines)
- C-e or M-x evil-scroll-line-down will both not have visible behavior
![image](https://user-images.githubusercontent.com/8166212/221476042-af92c3fe-46d7-4617-a77a-26019c67b4eb.png)

- Use the arrow keys to scroll down one line (so that the top visible line of the buffer is not a magit blame line)
![image](https://user-images.githubusercontent.com/8166212/221476146-faeb7320-436f-46a6-afa9-6959df296c55.png)

- C-e will now work until the top line is a magit blame line 
![image](https://user-images.githubusercontent.com/8166212/221476178-8fe0e646-cb7c-4cdf-9a29-1a645c1b3d9e.png)

# Expected behavior
evil-scroll-line-down should scroll down a line.

# Actual behavior
evil-scroll-line-down does not scroll down a line

# Further notes
Other movement commands work (tested evil-scroll-line-up, evil-scroll-down, evil-scroll-up, evil-scroll-page-down, evil-scroll-page-up)

**Comment by axelf4** [comment]
`evil-scroll-line-down` just calls the built-in function `scroll-up`. If it is not too much hassle, could you please try to reproduce the issue by running

    M-: (let (scroll-preserve-screen-position) (scroll-up 1)) RET

instead of `M-x evil-scroll-line-down RET`, and if that also exhibits the problem, moving the issue to the Magit/Emacs bug trackers?
