### ISSUE TITLE
How can I bind a key to a function behaves differently according to `evil-visual-tag`? 

### ISSUE THREAD

**Issue by templateK** [emacs-evil/evil#1792]
# Issue type
- Question

# Environment

Emacs version: GNU Emacs 28.2
Operating System: macOS Mojave
Evil version: Evil version 1.15.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
I want to a key behaves differently on each `visual-line-tag` and `visual-char-tag`.

If I want `v` key to select inner word on visual character mode and  to change into 
visual character mode on visual line mode, I can do following.
```elisp
;; '%' is a unused arbitrary key. It can be any key without conflict.
(define-key evil-visual-state-map "%" 'evil-visual-char)
(define-key evil-visual-state-map "v"
  (lambda () (interactive)
    (cond
     ((eq (evil-visual-tag) evil-visual-line-tag)
      (execute-kbd-macro (kbd "%")))
     (t (execute-kbd-macro (kbd "i w"))))))
```
The problem is, I have to bind an additional key to avoid conflict in `evil-visual-state-map`.
I don't know how to do this without any additional key binding.

# Further notes
In vim, we can do this without any additional key binding.
```vim
xnoremap <expr> v mode() == 'V' ? 'v' : 'iw'
```

**Comment by tomdl89** [comment]
There's no way to get as terse a solution as the vim approach, but you don't need to do any additional key binding. E.g. this would work:
```
(evil-global-set-key 'visual "v" (lambda () (interactive)
                                   (call-interactively
                                    (cl-case (evil-visual-type)
                                      ('line #'evil-visual-char)
                                      (t     #'evil-inner-word)))))
```
Does that help @templateK?

**Comment by templateK** [comment]
@tomdl89 Thank you for your suggestion. Unfortunately, the behavior of the above code is breaking the selection state when toggling between visual line, char mode. I think the behavior should be consistent.

Try evil command sequence `w V j w v` on  the beginning of the below content with your suggestion. https://github.com/emacs-evil/evil/issues/1792#issuecomment-1558942908
```
this is test sentence
this is test sentence
this is test sentence
this is test sentence
```
The `v` command should not move cursor because it is a command which is changing the visual mode type from visual line to visual char in visual line mode but it has a side effect of moving the cursor to the first column of the below line. Thus, breaking the selection. Key sequence emulation with `execute-kbd-macro` doesn't exhibit this side effect.

**Comment by templateK** [comment]
@axelf4 It works like charm.

Searching `evil-define-command` on web shows it to me at  [internals](https://evil.readthedocs.io/en/latest/internals.html) section on the evil official documentation.

I should've read the documentation more carefully but I think the chance of finding out this feature by myself 
would've been very slim since the documentation is very dry with no examples.

Thank you all for the great and kind answers. I'm happily closing the issue. ❤️
