### ISSUE TITLE
Meta key not working 

### ISSUE THREAD

**Issue by rootid** [emacs-evil/evil#1793]
# Issue type
Meta key not working  after installing and enabling the evil mode 

- Bug report
- Enhancement request
- Question
- Other

# Environment

Emacs version:  GNU Emacs 28.2 (build 1, x86_64-apple-darwin22.1.0) of 2023-01-07 
Operating System:  Mac OS Ventura 13.3 (22E252)
Evil version:  1.15.0 
Evil installation type:  NonGNU ELPA
Graphical/Terminal:  Terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): 

# Reproduction steps
- Start Emacs

# Expected behavior

# Actual behavior

# Further notes

**Comment by tomdl89** [comment]
Can you please provide repro steps @rootid ? I would have thought it's fairly obvious that this behaviour is not present in a normal install of evil. Also something more than "not working" as a bug description would be helpful. E.g. what happens when you `describe-key` `M-a` ?

**Comment by tomdl89** [comment]
Closing as this issue has insufficient detail. Please feel free to reopen if you have repro steps.
