### ISSUE TITLE
Backspace in org table editor shifts the entries

### ISSUE THREAD

**Issue by TheSafdarAwan** [emacs-evil/evil#1797]
# Issue type
Evil mode shifts the table entry in org mode when using backspace.

Example:
```org
| heading | description       |
|---------+-------------------|
| entry   | entry description |
|         |                   |
```

Now when **evil mode** is enabled try deleting characters from the entry it will shift the table.

After disable try this again and it won't shift the entry.
 

- Bug report

# Environment

Emacs version:  28.2
Operating System:  5.15.105-1-MANJARO x86_64 GNU/Linux
Evil version:  1.15.0
Evil installation type: 
Graphical/Terminal:  X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  NO

# Reproduction steps
- Start Emacs

Now when **evil mode** is enabled try deleting characters from the entry it will shift the table.

After disable try this again and it won't shift the entry.
 

# Expected behavior

# Actual behavior

# Further notes

**Comment by tomdl89** [comment]
Hi @TheSafdarAwan I don't follow, sorry. Can you paste three tables for me and two series of keypresses:

- Table before
- Keypresses without evil
- Table after without evil
- Keypresses with evil (if different)
- Table after with evil

Thanks

**Comment by TheSafdarAwan** [comment]
# Without Evil mode turned on
You have this table with two entries
```org
| heading | description         |
|---------+---------------------|
| entry 1 | entry description 1 |
| entry 2 | entry description 2 |

```
You put you put point(cursor) at the end of the `entry 1` description and backspace the ` 1` from the entry description.

While doing that org table editor will automatically re-align the table cell without shifting the `|` to the left even after pressing `backspace` two times.

```org
| heading | description         |
|---------+---------------------|
| entry 1 | entry description   |
| entry 2 | entry description 2 |
```
And you will get this table in result

# Now with evil mode turned on

If you repeat the same process with evil mode turned on you will get a table like this

```org
| heading | description         |
|---------+---------------------|
| entry 1 | entry description |
| entry 2 | entry description 2 |
```
And you have to press `TAB` to re-align the table again.

Now this isn't a big deal, we can re-align table easily but i think it breaks the whole experience of the org table editor, by shifting cells around.

**Comment by tomdl89** [comment]
Thanks @TheSafdarAwan I can replicate 👍 
Although it's something that maybe should be looked at (by evil or by org devs, I'm not 100% sure), have you checked to see if specific packages to integrate org with evil help you:
https://github.com/Somelauw/evil-org-mode
https://github.com/GuiltyDolphin/org-evil
Sorry I don't have time to check them out right now, but if they do work, I'll try to find some time to check whether it's worth borrowing their code which fixes it.

**Comment by TheSafdarAwan** [comment]
> 

@tomdl89 thanks for the reply i will try this out.
