### ISSUE TITLE
Feature Request: Replace Insert mode with emacs-state

### ISSUE THREAD

**Issue by jam1015** [emacs-evil/evil#1800]
# Enhancement Request
It would be cool to natively support using evil-emacs state instead of evil-insert mode. This would let users more effectively  leverage the power of emacs  plus vim keybindings.  My config does this but it is a bit of a hack and isn't always smooth.  For example I can switch between being in god mode or evil normal mode from evil emacs state. Natively supporting this in the package would let me simplify my config and perhaps that of others as well.

**Comment by tomdl89** [comment]
Hi @jam1015 are you aware of the customizable var `evil-disable-insert-state-bindings` ? I think setting this to `t` would get you most, if not all, of the way there.

**Comment by jam1015** [comment]
thanks! I'll close the issue because it seems to fulfill what I want.

**Comment by jam1015** [comment]
thanks! I'll close the issue because it seems to fulfill what I want.
