### ISSUE TITLE
Configuring EVIL to ignore certain regions when indenting

### ISSUE THREAD

**Issue by Occhioverde** [emacs-evil/evil#1812]
# Issue type

- Bug report / Question

# Environment

Emacs version:  GNU Emacs 29.0.92 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)
Operating System:  NixOS 23.11 (Tapir)
Evil version:  Evil version 1.15.0
Evil installation type:  Nix
Graphical/Terminal:  Graphical (X)
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  No

# Reproduction steps
- Start Emacs
- Open a Rust file with Yew HTML syntax, like the one provided below
- Try to indent a line (or region) inside `html! {}`
- The pseudo-HTML lines are randomly indented (as they do not match the Rust syntax)

# Expected behavior
EVIL should indent the lines correctly but, as this would be overly complicated, should at least ignore them to allow the user to indent them manually (like `rustfmt`).

# Actual behavior
EVIL tries to indent the lines even if they do not match the Rust syntax, aligning some and randomly creating new levels.

# Further notes
I don't know if this can actually be classified as a bug, but it would be awesome if there was a way to tell EVIL to not indent certain regions (particularly important when the auto-indent feature is enabled).

<details>
  <summary>Sample Rust + Yew code</summary>

  ```rust
use enclose::enclose;
use yew::prelude::*;

#[function_component]
fn App() -> Html {
    html! {
        <div>
            <h1>{"Test code"}</h1>
            <div>
                <p>{"This is a test code to show the issue with indentation"}</p>
            </div>
        </div>
    }
}

fn main() {
    yew::Renderer::<App>::new().render();
}
  ```
Tests that can be done with this code:
- Select all the lines and press `=` to indent
- Add a new (correctly indented) paragraph below the existing one and press enter to see EVIL move it to the left
</details>

**Comment by tomdl89** [comment]
Take a look at the source code for `evil-indent`: https://github.com/emacs-evil/evil/blob/master/evil-commands.el#L2027C1-L2049 it delegates to `indent-according-to-mode` or `indent-region`. These are both built-in emacs functions. In other words, this is an issue you have with emacs (or, probably more specifically rust-mode), not an issue with evil. Evil doesn't know about specific modes, nor does it want to. It trusts that emacs and mode-specific packages can be delegated to.

**Comment by Occhioverde** [comment]
Sorry for the noise. I'm still a bit of a beginner with Emacs, and I'm not so good at skimming through Elisp sources.
I will open an Issue with `rust-mode`. Thank you very much.
