### ISSUE TITLE
How can I use `evil-define-operator` with an interactive function?

### ISSUE THREAD

**Issue by Mango0x45** [emacs-evil/evil#1813]
# Issue type

- Question

# Environment

Emacs version: 28.2
Evil version: 1.15.0

# Question

I was wondering how/if I can create a custom operator with evil that calls an interactive function? In my specific case, I current have the `s` key in visual-mode bound to `sort-regexp-fields`:

```emacs-lisp
(evil-global-set-key 'visual (kbd "s") #'sort-regexp-fields)
```

This works fine for the most part, but I would also like to be able to call it in normal-mode on a region:

```
;; I should be able to do ‘sip’ to run ‘sort-regexp-fields’ on the paragraph

fff, eee, ddd
ccc, bbb, aaa
```

The issue is that `sort-regexp-fields` prompts you twice to input some stuff. This is behavior I’d like to maintain, but it seems that `evil-define-operator` doesn’t play well with interactive functions?

```emacs-lisp
(evil-define-operator mm/sort-regexp-fields (rrx krx beg end)
  (interactive "s\ns")
  (sort-regexp-fields nil rrx krx beg end))

;; Unknown interactive code ‘s\ns’
```

**Comment by tomdl89** [comment]
`evil-define-operator`'s `interactive` only parses special evil "types" when fed a string. You can however pass it a lisp expression, and it will handle it like normal `interactive`. E.g.:

```
(evil-define-operator mm/sort-regexp-fields (beg end rrx krx)
  (interactive (let ((range (evil-operator-range)))
                 (list (car range)
                       (cadr range)
                       (read-string "")
                       (read-string ""))))
  (sort-regexp-fields nil rrx krx beg end))
```

**Comment by Mango0x45** [comment]
Damn this works great! Huge thanks :)
