### ISSUE TITLE
How do I remap a particular key to the blackhole register?

### ISSUE THREAD

**Issue by Shaobin-Jiang** [emacs-evil/evil#1814]
# Issue type

- Question

# Environment

Emacs version: GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)
Operating System: Arch Linux on wsl
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: wslg

# Question

Back when I was using vim, I mapped `\` to `"_`, the blackhole register. Here, when I am using evil mode, I am at a loss as to how to do the same thing.

I have found out about the `evil-use-register`, but have not quite figured out how exactly to use it achieve what I want.

**Comment by tomdl89** [comment]
I have something like this is in my config:
```emacs-lisp
(evil-define-command evil-use-black-hole-register ()
  "Use `_' register."
  (interactive)
  (setq this-command 'evil-use-register
        evil-this-register ?_))

(evil-global-set-key 'motion "\\" 'evil-use-black-hole-register)
```

**Comment by Shaobin-Jiang** [comment]
That works perfectly! A thousand thanks @tomdl89
