### ISSUE TITLE
Something wrong with fun-name

### ISSUE THREAD

**Issue by dankessler** [emacs-evil/evil#1820]
Sorry for not following the bug-reporting template; I wanted to get this bug reported as quickly as possible as it might be quite critical.

See https://github.com/syl20bnr/spacemacs/issues/16119 and my comment here: https://github.com/emacs-evil/evil/commit/0cbd61f2de104fab16602d0418605cd0513b16f3#r124343503

**Comment by axelf4** [comment]
Sorry about that, it should be fixed now. The issue was that expanding the macro in a file not using lexical scoping would lead to `fun-name` not being captured by the lambda as a closure. Fixed by 1e9b2434264529fe0dd964b68fe89236a4abeac3.
