### ISSUE TITLE
Evil-snipe uses evil-unquote

### ISSUE THREAD

**Issue by BenedictHW** [emacs-evil/evil#1824]
- Bug report

# Environment

Emacs version: GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0) of 2023-07-25
Operating System: Windows 11
Evil version: 1.15.0
Evil installation type: Melpa
Graphical/Terminal: GUI
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Install Evil
- Install evil-snipe: https://github.com/hlissner/evil-snipe

# Expected behavior
Should load both packages successfully

# Actual behavior
evil-unquote is undefined.

# Further notes
https://github.com/emacs-evil/evil/commit/44add36 removes evil-unquote.

**Comment by hlissner** [comment]
Its removal didn't seem like a mistake so I've fixed evil-snipe, so this issue can be considered resolved.

**Comment by BenedictHW** [comment]
Thanks for the quick response!
