### ISSUE TITLE
Incompatibility with package indent-bars

### ISSUE THREAD

**Issue by walseb** [emacs-evil/evil#1837]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)
Operating System:  Linux NixOS
Evil version: 1.15.0
Evil installation type: Melpa via Nix
Graphical/Terminal: Graphical via X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Just tested on emacs -Q

# Reproduction steps
- Start Emacs
See steps and discussion here: https://github.com/jdtsmith/indent-bars/issues/22

In essence it's this:

1. Enable evil-mode and indent-bars-mode
2. Insert the following
```
                           foo




bar
```
3. Place cursor at the very end of `foo`
4. Press `j`

# Expected behavior
`evil-next-line` moves one line down

# Actual behavior
`evil-next-line` moves down to `bar`

**Comment by axelf4** [comment]
Other than at buffer boundaries, `evil-next-line` is just the standard `next-line` command but with `line-move-visual` set to `nil`, i.e. this is unlikely to be an issue with Evil. Could you please try to run

    M-: (let (line-move-visual) (line-move 1)) RET

without Evil mode, to see if a `nil` value of `line-move-visual` is indeed the cause?

**Comment by walseb** [comment]
Hi!

Sorry for the delay, I will reply soon.

**Comment by walseb** [comment]
Hello!

I tried what you suggested just now, and it resulted in the same problem, so it's not a problem with evil.

Thank you so much!
