### ISSUE TITLE
Missing Visual Mode command: v_g_CTRL-A

### ISSUE THREAD

**Issue by distobs** [emacs-evil/evil#1851]
Thank you devs for your amazing work!
# Issue type
- Enhancement request

# Environment

Emacs version: GNU Emacs 29.1
Operating System: EndeavourOS
Evil version: 1.15.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs.
- Start Evil.
- Write something like this in the scratch buffer:

```
0
0
0
0
```

- Select the numbers using Visual Block mode.
- Type the "g \<c-a\>" command while still on Visual mode.

# Expected behavior
- The command should work as specified in VIM's help pages:
https://vimhelp.org/change.txt.html#v_g_CTRL-A

# Actual behavior
- The command is undefined.

# Further notes

**Comment by tomdl89** [comment]
Have you seen https://github.com/juliapath/evil-numbers ?

**Comment by distobs** [comment]
> Have you seen https://github.com/juliapath/evil-numbers?

@tomdl89

Nope! I will look into it, thank you very much!

**Comment by distobs** [comment]
It worked! I think this can be closed.
