### ISSUE TITLE
evil-visual-char is not inclusive when using goto-char?

### ISSUE THREAD

**Issue by dvzubarev** [emacs-evil/evil#1852]
# Issue type
Bug report

# Environment

Emacs version: GNU Emacs 30.0.50 (build 13, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2023-12-24
Operating System: Ubuntu 22.04
Evil version: evil-git-fc6bd00
Evil installation type: manual
Graphical/Terminal: GUI
Tested in a `make emacs` session: Yes

# Reproduction steps
- make emacs
- M-x erase-buffer
- insert word
value
- 0 v M-g c 5
- only valu is selected

# Expected behavior
the whole word is selected

# Actual behavior
Point jumps to `u` letter.
When invoking M-g c 5  in normal state, cursor jumps to the `e` letter.

# Further notes

**Comment by tomdl89** [comment]
Thanks for the bug report @dvzubarev. This should now be fixed in master. Let me know if you observe otherwise.

**Comment by tomdl89** [comment]
In case you didn't know, `5go` is the evil way of doing `M-g c 5 [return]`, which was also not working, and is also now fixed.
