### ISSUE TITLE
the global ex command (:g) doesn't take a count

### ISSUE THREAD

**Issue by aidancz** [emacs-evil/evil#1858]
# Issue type

- Enhancement request

# Environment

Emacs version: 29.1 
Operating System: Arch Linux 
Evil version: 1.15.0 
Evil installation type: MELPA 
Graphical/Terminal: Graphical 
Tested in a `make emacs` session No(see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): 

# Reproduction steps

switch to scratch buffer with:

```
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with C-x C-f and enter text in its buffer.
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with C-x C-f and enter text in its buffer.
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; This buffer is for text that is not saved, and for Lisp evaluation.
```

and type ex command: `:g/create/-d`

# Expected behavior

```
;; To create a file, visit it with C-x C-f and enter text in its buffer.
;; To create a file, visit it with C-x C-f and enter text in its buffer.
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; This buffer is for text that is not saved, and for Lisp evaluation.

```

# Actual behavior

```
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; This buffer is for text that is not saved, and for Lisp evaluation.
```

# Further notes

**Comment by tomdl89** [comment]
Thanks for the bug report @aidancz - this is now fixed in master. It wasn't a bug for all of `g`'s subcommands - just delete, which had a performant version added recently which uses a stripped down version of emacs' `flush-lines` but ignores args.
