### ISSUE TITLE
Can't exit Visual-Block Mode with keyboard-escape-quit

### ISSUE THREAD

**Issue by Animeshz** [emacs-evil/evil#1886]
# Issue type
- Bug report

# Environment

Emacs version: GNU Emacs 29.2 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.18.0, Xaw3d scroll bars)
Operating System: Void Linux (installed using nix tho)
Evil version: GNU Emacs 29.2 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.18.0, Xaw3d scroll bars)
Evil installation type: Elpaca (use-package)
Graphical/Terminal: Xorg
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Get into visual-block mode `C-v`  (and compare it with other visual mode, `v` & `S-v`).
- Bind keyboard-escape-quit to `Esc` key, I used general for this,
  ```
  (general-def '(normal motion visual operator)
    "<escape>" #'keyboard-escape-quit))
  ```
- Hit `Esc` key.

# Expected behavior
Just like visual and visual-line mode, it should exit when hitting esc key (keyboard-escape-quit).

# Actual behavior
Doesn't exit the visual-block mode.

**Comment by tomdl89** [comment]
Thanks for the bug report @Animeshz - this should now be fixed in master.
