### ISSUE TITLE
'f' (search forward) becomes ';' repeat search on second search

### ISSUE THREAD

**Issue by jf** [emacs-evil/evil#1901]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 29.1 (build 1, aarch64-apple-darwin23.2.0, Carbon Version 170 AppKit 2487.3) of 2024-04-10
Operating System: macOS Sonoma
Evil version: Evil version 1.15.0
Evil installation type: ehh, no idea. Came with Doom Emacs
Graphical/Terminal: graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- open any text file with a reasonable amount of chars in one line (e.g. "the quick brown fox jumps over the lazy dog.")
- position cursor at front of line
- press `f e`
- press `f o`

# Expected behavior

I expect for `f` to do a forward search. **Always.**

# Actual behavior

But the second `f`, instead of allowing me to search for another char, simply behaves like `;`, so that instead of `f o` doing a search for `o`, I get `; o`, and I open a new line under the cursor.

**Comment by axelf4** [comment]
I am unable to reproduce using `make emacs`. You may be better off posting to the Doom Emacs issue tracker instead.

**Comment by tomdl89** [comment]
I can't replicate this with just evil. I'm almost certain, as you're using Doom, that this behaviour comes from https://github.com/hlissner/evil-snipe
