### ISSUE TITLE
`C-w <count> +` and `C-w <count> -` will not work; you *have* to put the count in front

### ISSUE THREAD

**Issue by jf** [emacs-evil/evil#1902]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 29.1 (build 1, aarch64-apple-darwin23.2.0, Carbon Version 170 AppKit 2487.3) of 2024-04-10
Operating System: macOS Sonoma
Evil version: Evil version 1.15.0
Evil installation type: ehh, no idea. Came with Doom Emacs
Graphical/Terminal: graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- press `C-w s` to split the frame
- now `C-w 5 +`
- now `C-w 5 -`

# Expected behavior

I expect for the `C-w` and `count` to work as intended, resizing up (with `C-w 5 +`) or down (`C-w 5 -`) the current pane.

# Actual behavior

`C-w 5 +` does nothing for the pane size. It moves the cursor *down*.
`C-w 5 -` ditto. It moves the cursor *up*.

**Comment by tomdl89** [comment]
@jf I've implemented this and merged to master. Let me know if it works as you expect.
