### ISSUE TITLE
search motions forget offset when repeated

### ISSUE THREAD

**Issue by totallyuniquelily** [emacs-evil/evil#1907]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 29.3 (build 2, x86_64-unknown-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-05-09
Operating System: Void Linux
Evil version: Evil version 1.15.0
Evil installation type: Straight
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs (with `make emacs`)
- open a scratch buffer and insert "first, second, third" (some words with `, ` between them)
- enable evil-search search module (M-: `(evil-select-search-module 'evil-search-module 'evil-search)`)
- go to beginning of line
- type `d/, /e`
- type `.` (the dot command)

additionally (optionally)
- type `/` and use arrow up to observe the search history

# Expected behavior
only the word "third" should be left.
the dot command should execute `d/, /e` (but instead it executes `d/, `).

# Actual behavior
", third" is left.
the dot command appears to not repeat search offsets.
after a command is repeated, the last search is replaced with a search that has the same pattern but no offset.

# Further notes
if the `n` motion is used, everything works as it should.

**Comment by tomdl89** [comment]
Thanks for the bug report @totallyuniquelily. This should now be fixed in master. Please let me know if you observe otherwise.
