### ISSUE TITLE
evil-jump-item issue with #ifdef #endif in c-ts-mode

### ISSUE THREAD

**Issue by kvaneesh** [emacs-evil/evil#1908]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2024-06-12

Operating System: Ubuntu 22.04
Evil version:  Evil version 1.15.0

Evil installation type:  MELPA stable
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  No

# Reproduction steps
evil-jump-item looks at major mode c-mode and c++-mode and hence doesn't work for specific jump w.r.t c-ts-mode

# Expected behavior
jump across #ifdef #else #endif

# Actual behavior
Doesn't jump

# Further notes
if we update      (memq major-mode '(c-mode c++-mode)) to also handle c-ts-mode I guess it will work?

**Comment by tomdl89** [comment]
@kvaneesh can you check out https://github.com/emacs-evil/evil/tree/c-ts-jump-item and let me know if that fixes it?
