### ISSUE TITLE
Emacs hangs on search in dired buffer

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#192]
Originally reported by: **Anonymous**

----------------------------------------

I have the following issue

1. I start Emacs, 
2. find-file and enter a directory
3. dired buffer opens
4. search with key "/"
5. type in some characters
6. on the third character, the buffer screen becomes blank and Emacs hangs

Greetings,

Nik

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/192

**Comment by wasamasa** [comment]
Not reproducible.
