### ISSUE TITLE
Face for last executed commands in cmd line

### ISSUE THREAD

**Issue by Doodler8888** [emacs-evil/evil#1927]
# Issue type

- Question

# The question

If i execute a command in a cmd buffer (':') let's say it was 'ls -la' and then relaunch it, i will see a suggestion the last executed command as a suggestion:

If I execute a command in the Ex command line (e.g., ':'), let's say it's 'ls -la', and then relaunch it, I will see the last executed command as a suggestion before starting to type anything:

![image](https://github.com/user-attachments/assets/25770d4a-a94c-4a21-a74f-53963b9db22e)

I want to change foreground for the suggestion face, but i can't find it anywhere:

![image](https://github.com/user-attachments/assets/47ff248b-2562-49a3-8f95-b6c2642151f4)

**Comment by axelf4** [comment]
It uses the `shadow` face.
