### ISSUE TITLE
Macro visual mode text replacement not working

### ISSUE THREAD

**Issue by sbond75** [emacs-evil/evil#1941]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 28.2 (build 2, x86_64-w64-mingw32) of 2022-09-13
Operating System: Windows 10
Evil version: evil-git-e41710d
Evil installation type: MELPA
Graphical/Terminal: X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes. **For this, used the Emacs configuration below.**

Emacs version: GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)
Operating System: NixOS
Evil version: evil-git-b7ab384
Evil installation type: manual
Graphical/Terminal: terminal

# Reproduction steps
- Start Emacs by using `make emacs`
- Enter this into emacs in the scratch buffer: `Gitest1<RETURN>test2<ESC>qzvkk:s/test/a/g<RETURN>qA<RETURN><RETURN>test1<RETURN>test2<ESC>@z`

# Expected behavior
The macro should replace this:
```
test1
test2
```
with this:
```
a1
a2
```

# Actual behavior
When replaying the macro, it only selects the text, then the macro finishes.

# Further notes
- This works as expected in vim on Linux and gvim on Windows.
- Running `M-x kmacro-edit-macro` shows that the macro was recorded correctly:
```
;; Keyboard Macro Editor.  Press C-c C-c to finish; press C-x k RET to cancel.
;; Original keys: v 2*k : s / t e s t / a / g RET

Command: last-kbd-macro
Key: none

Macro:

v                       ;; evil-visual-char
2*k                     ;; evil-previous-line
:                       ;; evil-ex
s                       ;; evil-substitute
/                       ;; evil-ex-search-forward
t                       ;; evil-find-char-to
e                       ;; evil-forward-word-end
s                       ;; evil-substitute
t                       ;; evil-find-char-to
/                       ;; evil-ex-search-forward
a /
g RET
```

**Comment by tomdl89** [comment]
Thanks for the bug report. This is a regression caused by me, so sorry about that. The offending commit is here: https://github.com/emacs-evil/evil/commit/0ad84c52169068021ec3372bf52503631f2261de
I will take a look this weekend and find a fix. Otherwise I'll revert the change.

**Comment by tomdl89** [comment]
@sbond75 this should now be fixed in master. Please let me know if you observe otherwise

**Comment by sbond75** [comment]
It works. Thank you for the fix!
