### ISSUE TITLE
C-S-J

### ISSUE THREAD

**Issue by aloispichler** [emacs-evil/evil#1942]
- Question

How do I bind `C-S-J`, that is, `Contro+Shift+J`?

I am getting `Error (use-package): evil/:init: C- must previx a single character, not <SHIFT>J`…

Thank you.

**Comment by tomdl89** [comment]
@aloispichler what have you tried?

**Comment by aloispichler** [comment]
`(define-key evil-insert-state-map (kbd "C-j") 'evil-scroll-line-down)`

**Comment by tomdl89** [comment]
Most mentions of "must prefix a single character..." errors from a web search seem to have been caused by pre-existing bad config / conflicting bindings. So worth just trying after restarting emacs, if you haven't already. Also, see what happens if you use the evil keybinding stuff:

```elisp
(evil-define-key 'insert 'global (kbd "C-S-J") 'evil-scroll-line-down)
```

**Comment by aloispichler** [comment]
Thank you. I had to restart and remove init.el~, but it works now.
Thanks again!
