### ISSUE TITLE
[Bug] `evil-next-visual-line` doesn't scoll past big diagnostics when  `flymake-show-diagnostics-at-end-of-line` is `t`

### ISSUE THREAD

**Issue by johnhamelink** [emacs-evil/evil#1946]
# Issue type

- Bug Report

# Environment

Emacs version: GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.2)
Operating System: NixOS 25.05 (Warbler)
Evil version: Evil version 1.15.0
Evil installation type: ELPA via [emacs-overlay](https://github.com/nix-community/emacs-overlay/)
Graphical/Terminal: Graphical (Wayland) and Terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): N/A (emacs-overlay handles this automatically)

# Reproduction steps
- Start Emacs
- Eval `(setq flymake-show-diagnostics-at-end-of-line t)`
- Open a typescript file, with typescript-ts-mode, flymake & eglot enabled
- In an emacs-lisp scratch buffer, make some errors and warnings which are long enough that the diagnostic becomes visually multiple lines in the window
- Eval `(evil-next-visual-line)`

# Expected behavior
Even though the overlay spans multiple visual lines, `evil-next-visual-line` would move point down to the next visual line that is considered navigable for point (and thus the overlay should be skipped over).

# Actual behavior
`evil-next-visual-line` does not move if the overlay spans multiple visual lines, even if the actual buffer text fits within a single visual line. It works fine when the overlay fits on the visual line.

# Further notes
- It seems that `evil-previous-visual-line` is not affected by this issue
- I tried this in the terminal and recorded it here so you can see what I mean: https://asciinema.org/a/YF08mgXiBK4JSh8plIw9WskrE
- My configuration can be found here: https://git.sr.ht/~johnhamelink/nix/tree/master/item/home/modules/emacs/src/config.el

**Comment by axelf4** [comment]
As `evil-next-visual-line` (except at BOB/EOB) just defers to the built-in `next-line` with `line-move-visual` set to `t` (which also does not skip past multiline diagnostics), please do open an issue on the GNU Emacs bug tracker instead.
