### ISSUE TITLE
C-u doesn't work in Normal mode

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#246]
Originally reported by: **Anonymous**

----------------------------------------

Can't scroll half-page up with C-u in <N> mode.
Some emacs command launches: http://o7.no/XLRvpb

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/246

**Comment by GordonGustafson** [comment]
I suggest closing this as "can't reproduce". The following gives the desired behavior of C-u in normal mode for me:

```
(setq evil-want-C-u-scroll t)
;; put evil on load path somehow
(add-to-list 'load-path "~/.emacs.d/evil")
(require 'evil)
(evil-mode 1)
```

**Comment by phunehehe** [comment]
In my case having a `evil-leader/set-key` before setting `evil-want-C-u-scroll` causes this problem.

**Comment by wasamasa** [comment]
If it's an autoloaded command, it will do `(require evil)`, resulting in the same behavior as described above.

**Comment by phunehehe** [comment]
oh now that makes total sense, thanks @wasamasa
