### ISSUE TITLE
opening new lines in longlines-mode

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#263]
Originally reported by: **George V. Reilly (Bitbucket: [georgevreilly](https://bitbucket.org/georgevreilly), GitHub: [georgevreilly](https://github.com/georgevreilly))**

----------------------------------------

A couple of days ago, I was editing a document in [Markdown mode](http://jblevins.org/projects/markdown-mode/). Many of the lines were very long, so I turned on longlines-mode to get decent line wrapping. Evil seemed to work fairly well.

I had one large block of preformatted text where the lines where short and separated by newlines even before longlines-mode was turned on. I had a lot of difficulty creating new lines of text in that region. The 'o' command didn't work. Typing some text and pressing Enter didn't work as expected. Lines started getting joined together. If I switched into Emacs state or if I turned off longlines-mode and used Normal state and Insert state, I was able to edit the preformatted block as expected.

I can't repro it now, so I can't give very specific repro steps.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/263

**Comment by wasamasa** [comment]
Closing as the original question has been resolved.
