### ISSUE TITLE
V highlight spanning vertical windows is out of sync

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#300]
Originally reported by: **Anonymous**

----------------------------------------

When highlighting lines in visual selection mode using the V key, the highligh in the non-active window is not updated.

How to reproduce, from "make emacs":

* Paste some random text in to the scratch buffer, such as this:  http://pastie.org/7997603

* Split the window vertically using C-w v

* Go in to visual line state by typing V

* At this point, the current line in both windows will become highlighted.

* Move point down some lines.

* Now only the highlights in the current window are updated.  The other window's highlights are not updated, and only the first line stays highlighted.

Here is a screenshot:  http://img1.imagilive.com/0613/evil-bug-130602a.png

I'm running:  GNU Emacs 24.3.50.1 (x86_64-unknown-linux-gnu, X toolkit, Xaw3d scroll bars) of 2013-05-25

With an evil I pulled today (Jun 2nd, 2013) out of git.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/300

**Comment by wasamasa** [comment]
I cannot reproduce this, the region is updated just fine in both windows.

**Comment by wasamasa** [comment]
I cannot reproduce this, the region is updated just fine in both windows.
