### ISSUE TITLE
Missing Manual Link

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#326]
Originally reported by: **Anonymous**

----------------------------------------

At the Emacs Wiki, (http://www.emacswiki.org/emacs/Evil#toc4)

<h2 id="toc4">Documentation</h2><p>A brief <a class="url http outside" href="https://gitorious.org/evil/evil/blobs/raw/doc/doc/evil.pdf">PDF manual</a> is available in the <code>/doc</code> subdirectory.</p>

The link should go here: https://gitorious.org/evil/evil/source/43db0bef8aee5b926ff3860d4401840e682e91c0:doc/evil.pdf

But instead, goes here : https://gitorious.org/evil/evil/raw/0b6300f3b16f93eb25dc9f1d1e2686ff6468d0cc:doc/evil

Try it, see for yourself. 

PS: The link is also dead at http://gitorious.org/evil/pages/Home. 

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/326

**Comment by wasamasa** [comment]
The Emacswiki points to the (now archived) Bitbucket PDF link which works fine. It also mentions this repository which has a README properly pointing to its PDF.
