### ISSUE TITLE
OSX: visual state copies the region on every single movement

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#336]
Originally reported by: **Bradley Wright (Bitbucket: [bradwright](https://bitbucket.org/bradwright), GitHub: [bradwright](https://github.com/bradwright))**

----------------------------------------

After each movement key `evil-visual-update-x-selection` is invoked, which ends up calling `x-select-text`. This has a side effect on OSX/Emacs 24.3 as follows:

Given the text `this-is-a-function`, with point on the last `n`:

* Hit `v`
* Hit `h`
* Hit `h`
* Hit `h`

If you have clipboard history, like in Alfred, you'll note the following history:

* tion
* ion
* on
* n

because it's calling `x-select-text` every single movement key.

This is quite annoying behaviour - I'd rather it explicitly copied to the clipboard only when I hit `y` or `c` during visual state.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/336

**Comment by wasamasa** [comment]
This should be fixed thanks to @hpdeifel changing `evil-visual-update-x-selection` to use the primary selection by default.
