### ISSUE TITLE
Evil wont build osx 10.8 emacs 24.3

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#340]
Originally reported by: **Anonymous**

----------------------------------------

When I try to build evil via el-get I get:
Compute dependencies
emacs --batch -Q -L . -L lib -f batch-byte-compile evil-vars.el
Wrote /Users/herdinger/test/evil/evil-vars.elc
emacs --batch -Q -L . -L lib -f batch-byte-compile evil-digraphs.el
Wrote /Users/herdinger/test/evil/evil-digraphs.elc
emacs --batch -Q -L . -L lib -f batch-byte-compile evil-common.el

In toplevel form:
evil-common.el:33:19:Warning: reference to free variable `evil-visual-state-p'
evil-common.el:34:19:Warning: reference to free variable `evil-visual-restore'
evil-common.el:35:19:Warning: reference to free variable `evil-motion-state'

In evil-line-move:
evil-common.el:1163:18:Warning: reference to free variable `line-move-visual'

In end of data:
evil-common.el:3327:1:Warning: the following functions are not known to be
    defined: declare-function, global-undo-tree-mode, characterp, read-key,
    beginning-of-visual-line, region-active-p, evil-visual-state-p,
    evil-visual-restore, match-substitute-replacement, evil-motion-state
Wrote /Users/herdinger/test/evil/evil-common.elc
emacs --batch -Q -L . -L lib -f batch-byte-compile evil-core.el

In toplevel form:
evil-core.el:104:1:Error: Symbol's value as variable is void: evil-visual-state-p

Also I tried fetching and compiling from source same thing.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/340

**Comment by wasamasa** [comment]
User didn't follow up, so no way to reproduce their issue.
