### ISSUE TITLE
CTRL-R CTRL-W in command mode

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#341]
Originally reported by: **Bailey Ling (Bitbucket: [bling](https://bitbucket.org/bling), GitHub: [bling](https://github.com/bling))**

----------------------------------------

*  emacs 24.3.1
*  evil c0991f0f1f1e147aca4bcec18f42d3da2aa68ebe

in vim, when you're in ex-command mode (e.g. after hitting `:`), you can use `CTRL-R CTRL-W` to insert the word under the cursor.

a common use case would be `:s/`, then `^r^w` to insert the word you want to replace.

currently, it displays an error message saying that the `^w` register is empty.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/341

**Comment by edkolev** [comment]
Seems like this have been fixed - I use it often without issues.

I tested with `make emacs` as well - it works as expected.
