### ISSUE TITLE
evil-ex-search-vim-style-regexp breaks *

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#347]
Originally reported by: **Bailey Ling (Bitbucket: [bling](https://bitbucket.org/bling), GitHub: [bling](https://github.com/bling))**

----------------------------------------

when `evil-ex-search-vim-style-regexp` is set to `t`, it breaks the `*` command, and displays the error "Invalid regular expression".

tested on c0991f0 and emacs 24.3

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/347

**Comment by pjones** [comment]
I ran into this today.  Here's my workaround:

```elisp
(defun pjones:evil-search-word (oldfun &rest args)
  (let ((evil-ex-search-vim-style-regexp nil))
    (apply oldfun args)))
(advice-add #'evil-ex-start-word-search :around #'pjones:evil-search-word)
```
