### ISSUE TITLE
RET in insert mode no longer autoindents

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#349]
Originally reported by: **George V. Reilly (Bitbucket: [georgevreilly](https://bitbucket.org/georgevreilly), GitHub: [georgevreilly](https://github.com/georgevreilly))**

----------------------------------------

Typing `RET` in insert mode used to automatically indent when `evil-auto-indent` was set to `t`. It no longer does, and the cursor is left at the beginning of the next line.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/349

**Comment by edkolev** [comment]
This probably can also be closed.

For me `RET` is bound to `newline` which respects `electric-indent-mode`.

I did the following test in emacs 25.3:
- `make emacs`
- clear scratch buffer
- `M-x perl-mode`
- enter `sub fake {RET`
- the resulting new line was correctly indented (`_` is the cursor):
```
sub fake {
    _
```

Also, `evil-auto-indent`'s doc states nothing about `RET`:
```
evil-auto-indent is a variable defined in ‘evil-vars.el’.
...
Documentation:
Whether to auto-indent when entering Insert state.

```

**Comment by wasamasa** [comment]
I agree that this is probably a non-issue by now.  The description of the variable is wrong though, the variable is checked from the replace (`r`) and open (`o` and `O`) commands.
