### ISSUE TITLE
Broken C-v + I

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#351]
Originally reported by: **Anonymous**

----------------------------------------

After doing a vertical downward selection with C-v, start inserting text with "I", and leave insert mode, the text I have written is inserted on the lines under the cursor instead of above.

I've attached an image because it's much easier to see the problem than to describe it.

I get the same problem with C-v + A, but not C-v + c.

I think that after a downward selection, the cursor used to move back to the topmost line when starting to insert text with I or A, but now it just stays on the last line.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/351

**Comment by GordonGustafson** [comment]
I suggest we close this is "can't reproduce" (I can't reproduce it either)
