### ISSUE TITLE
key-chord confuse evil's minibuffer echo system

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#365]
Originally reported by: **dewdrops NA (Bitbucket: [dewdrops](https://bitbucket.org/dewdrops), GitHub: [dewdrops](https://github.com/dewdrops))**

----------------------------------------

To reproduce:

- Start emacs with a very simple .emacs such as:

```
    (require 'evil)
    (evil-mode)
    (require 'key-chord)
    (key-chord-mode 1)
    (key-chord-define evil-insert-state-map ";s" 'set-mark-command)
    (key-chord-define evil-emacs-state-map ";s" 'set-mark-command)
```

- Open a file and keep evil in normal state.

- Press "1" and wait a second for the "1" is echoed in minibuffer.

- Press "1" again. This time, there will be "1 1 1" (mis)displayed in minibuffer instead of "1 1".

It seems that only what echoed in minibuffer is wrong, the prefix argument which following command really accepts is correct (11, not 111), and the key-chord bindings works as expected too.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/365

**Comment by axelf4** [comment]
Cannot reproduce.
