### ISSUE TITLE
Add customizable option that resembles `startofline`

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#391]
Originally reported by: **Vasilij Schneidermann (Bitbucket: [wasamasa](https://bitbucket.org/wasamasa), GitHub: [wasamasa](https://github.com/wasamasa))**

----------------------------------------

Evil seems to behave as if Vim's `startofline` option is always enabled, for example if you start a block selection with `C-v`, then hit `gg` or `G` to move the cursor to the beginning or end of file, it jumps to the beginning of the first or last line and turns the one-block wide selection into a rectangle between beginning or end of file and point.

In Vim you can adjust this behaviour by disabling its `startofline` option, then a rectangular selection will not jump to the start of line when moving to the beginning or end of line. In general it will modify several other motions to not do that, too. Could this be added as a customizable option to Evil?

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/391

**Comment by axelf4** [comment]
I believe this can be closed now given that `evil-start-of-line` exists.
