### ISSUE TITLE
Issues with org-src-mode

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#399]
Originally reported by: **Hanyu Xiao  (Bitbucket: [xiaohanyu](https://bitbucket.org/xiaohanyu), GitHub: [xiaohanyu](https://github.com/xiaohanyu))**

----------------------------------------

Hi, evilers:

I have a problem with org-mode's org-babel and evil. 

When I work with org-mode's source code block, I can type `C-c '` to switch to a source code block to focus on code editing. When it finished, I can switch back to the original org-mode. 

In `org-src-mode`, I can use `C-x C-s` to do `org-src-edit-save`, just like normal `C-x C-s` in other modes/buffers. However, I also want to use evil-ex's `evil-write` (bind to `:w`) in `org-src-mode`, how can I get this?

I'm thinking about method like `defadvice` or `(make-local-variable 'evil-ex-map)`, however, none of them work for me. So I'm here asking for some help.

Thanks.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/399

**Comment by edkolev** [comment]
Seems like this has has been resolved but not closed.

Either way, org-mode integration I think is out-of-scope of evil.
