### ISSUE TITLE
C-o across buffers after C-] broken

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#42]
Originally reported by: **Anonymous**

----------------------------------------

If I follow a tag in a TAG file using C-] that directs to another buffer, then pressing C-o does not return to the original buffer: it goes to the top of the current buffer, and pressing C-o again says "Mark popped".

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/42

**Comment by wasamasa** [comment]
This is implemented by `evil-jumps.el` from Bailey Ling. With it I can no longer repro the original description. `:jumps` works as well.
