### ISSUE TITLE
emacs 25.0.50, eval-last-sexp point off by 1

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#439]
Originally reported by: **Bailey Ling (Bitbucket: [bling](https://bitbucket.org/bling), GitHub: [bling](https://github.com/bling))**

----------------------------------------

if i have something like this:

    1.  (let ((foo "hello"))
    2.   (message foo))

and the point is on line 2 at the end and i run `eval-last-sexp`, i will get an error about foo being a void variable.  this is because it is evaluating `(message foo)` and not the entire let expression.  to eval this, you have to go into insert mode, which lets the point go past the last `)`, go into emacs state, or eval a region.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/439

**Comment by axelf4** [comment]
Fixed by commit 5539db58702227d7282b63c2f64b4e352d545033.
