### ISSUE TITLE
forward-sentence behavior

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#480]
Originally reported by: **Nicholas Chisholm (Bitbucket: [nchisholm](https://bitbucket.org/nchisholm), GitHub: [nchisholm](https://github.com/nchisholm))**

----------------------------------------

I noticed some unexpected behavior of the Emacs `forward-sentence` function (e.g. the one bound to M-e) when Evil-mode is enabled.  With Evil in normal mode, pressing M-e (or executing forward-sentence) gets stuck at line breaks coinciding with the ends of sentences.

For example, consider the text

```
#!lisp

;; This is a sentence.  And this is another one that
;; contains a line break.
;; Here is one last sentence.
```

Starting from the top, the point will advance no further than the period on the second line if `forward-sentence` is repeatedly executed.  The `backward-sentence` function (M-a) functions normally as far as I can tell.  Also, `forward-sentence` functions normally when in visual or insert mode.

Emacs version 24.4.1, Evil version 1.0-dev (installed from MELPA)

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/480

**Comment by cdlm** [comment]
Some perspective on this issue: it makes it hard to write text manipulation commands that run the same under normal Emacs or under Evil (I'm trying to write a custom `unfill-paragraph`).

Something helpful would be an Elisp macro for running code in emacs mode (a programmatic version of `evil-execute-in-emacs-state` that one could wrap around a few statements). I've had a go at it but this duplicates most of `evil-execute-in-emacs-state`/`evil-stop-execute-in-emacs-state` and I didn't manage to make it work (noob at elisp ☹️)

**Comment by wasamasa** [comment]
The problem is with doing things interactively, not programmatically.  Movement to the end of the line works fine, it's just `post-command-hook` that contains a function placing point back, thereby creating the illusion of Evil not allowing to place point beyond the last character in a line.  You can still writing code that goes to the newline and does whatever it needs to, Evil will merely adjust point after the command has been run.  If this confuses you while debugging, feel free to adjust the customizables mentioned in the previous post.

**Comment by cdlm** [comment]
Except the code I have expressed in terms of `{forward,backward}-{sentence,paragraph}` behaves differently depending on whether I'm in one of the evil states or in the emacs state. So there **is** some influence of the context on the movement functions.

BTW, elisp-noob question: are you suggesting that "doing things interactively" includes the body of an `(interactive)` defun?

**Comment by wasamasa** [comment]
There's no way to tell that without a minimal and self-contained repro.  Not to mention that this kind of question is better off for a mailing list, the Emacs Stackexchange or a new issue (why hijack this one in the first place?).  And no, I'm merely differentiating between executing a command and seeing where point moves vs. executing elisp code and using logging to see where point actually is.

**Comment by cdlm** [comment]
Granted. Just for the record, my code is derived from [this answer](https://emacs.stackexchange.com/a/473).
