### ISSUE TITLE
ex-substitute with % moves point.

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#493]
Originally reported by: **Anonymous**

----------------------------------------

In vim, when doing a substitution on the entire buffer, using %, and with the 'g' flag, the point is not moved. In Evil the point is moved to the location of the last substitution. Vim moves the point in every other case, using delimiters, and even % without 'g'. So I'm not sure if this is a bug in Vim, or Evil. 

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/493

**Comment by axelf4** [comment]
Vim 9.0.609 seems to at least now match Evil in where `:substitute` leaves the cursor.
