### ISSUE TITLE
Regarding initial states

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#497]
Originally reported by: **Vasilij Schneidermann (Bitbucket: [wasamasa](https://bitbucket.org/wasamasa), GitHub: [wasamasa](https://github.com/wasamasa))**

----------------------------------------

I've found out that Evil is basically using [a whitelist of major modes](https://bitbucket.org/lyro/evil/src/2785c9a2cbfef5bcc4e9c6bed6fdc76ce2c2ffbb/evil-vars.el?at=default#cl-527) to decide the initial state for buffers.  This approach is OK, but I wished to write less for configuration, so I wrote a hack that makes it not only compare against modes, but also check for derived modes and aliases in [my Emacs configuration](https://github.com/wasamasa/dotemacs/blob/master/init.org#evil).  That way one can for example mark `text-mode`, `prog-mode` and `fundamental-mode` as normal state modes and have nearly everything else covered because most modes in sufficiently recent Emacs versions derive from them.

However, it occurred to me that this could be done in an even simpler manner, simply by using the respective commands in the hooks these modes have.  Adding `evil-normal-state` to the hooks of the previously mentioned modes seems to have a very similiar effect and gets rid of the extra code I wrote.

Would either alternative be a possible candidate for inclusion into Evil?

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/497

**Comment by VanLaser** [comment]
Before moving to any PR (as proposed by @wasamasa in [#775](https://github.com/emacs-evil/evil/issues/775#issuecomment-322307014)), I'd like to show a reworked solution and put it before your judgement (tests, advise etc.). So far it touches no function (apart from advising one) and creates a new way of setting up the initial state for a mode and all the modes derived from it, based on the hooks they run (parent hook runs first, derived afterwards, minor modes after that - if I got that right). I hope this is the "other thread" I was supposed to be posting in the first place.

```emacs lisp
;; this is a temporary advice for `evil-initial-state'
(defun evil--around-evil-initial-state (fun &rest args)
  "Make `evil-initial-state' also look for an overriding buffer-local variable
`evil-init-state' and return its value instead."
  (let ((res (apply fun args)))
    (if (and (boundp 'evil-init-state) evil-init-state)
	evil-init-state
      res)))

;; if all goes well, the code above will be the last part of `evil-initial-state' instead
(advice-add 'evil-initial-state :around #'evil--around-evil-initial-state)

;; partial function later used to setup a dynamic state evil hook
(defun evil--set-initial-state-hook (state)
  "Function used in a dynamic hook to setup a mode's state."
  (message "(evil debug) state: %s" state)
  (set (make-local-variable 'evil-init-state) state))

;; the new evil "interface" to setup the mode state
(defun evil-set-initial-state-inherit (mode-hook state)
  "Set evil STATE for the mode associated with this MODE-HOOK.
The state will be also set for any derived mode, unless explicitly overridden
in such a mode."
  (let ((evil-hook (intern (concat "evil--set-initial-state-" (symbol-name mode-hook)))))
    ;; remove any previous similar hook for this MODE-HOOK
    (remove-hook mode-hook evil-hook)
    ;; redefine the hook for the specified STATE
    (defalias evil-hook (apply-partially #'evil--set-initial-state-hook state))
    ;; add the updated hook
    (add-hook mode-hook evil-hook)))

;; some tests:
(evil-set-initial-state-inherit 'prog-mode-hook 'emacs)
(evil-set-initial-state-inherit 'c-mode-common-hook 'visual)
(evil-set-initial-state-inherit 'c-mode-hook 'normal)
;; minor modes (works, but not if you disable/enable the mode afterwards)
(evil-set-initial-state-inherit 'git-gutter-mode-hook 'insert)
(evil-set-initial-state-inherit 'org-capture-mode-hook 'insert)
```

**Comment by VanLaser** [comment]
I still much prefer the *other* solution proposed by @wasamasa (non-hook based). I (hopefully) improved it below, so that it detects unorthodox parent -> derived mode relations (i.e. circular references - see Malabarba/paradox#86 ); to be safe, the search is also limited to a hierarchy of max 50 descendant modes (but that check is somewhat redundant -so it could be removed - what do you think?).

```emacs lisp
;; derived stuff:
;; the other approach (nicer IMHO)
(defun evil--real-function (fun)
  "Figure out the actual symbol behind a function.
Returns a different symbol if FUN is an alias, otherwise FUN."
  (let ((symbol-function (symbol-function fun)))
    (if (symbolp symbol-function)
        symbol-function
      fun)))

(defun evil--derived-mode-p (mode modes)
  (let ((parent (evil--real-function mode))
        (counter 0)
        (limit   50)
	visited-modes)
    (while (and parent (not (memq parent modes)))
      (push parent visited-modes)	; remember already visited parents
      (setq parent			; get the next parent
	    (evil--real-function (get parent 'derived-mode-parent)))
      (when (memq parent visited-modes)
	(error "Circular list detected. Aborting."))
      ;; (message "doom counter: %d" counter )
      (setq counter (1+ counter))
      (when (> counter limit)
        (error "Maximum loop iterations limit reached. Aborting.")))
    parent))

(with-eval-after-load 'evil-core
  (defun evil-initial-state (mode &optional default)
    "Return the Evil state to use for MODE.
Returns DEFAULT if no initial state is associated with MODE.
The initial state for a mode can be set with
`evil-set-initial-state'."
    (let (state modes)
      (catch 'done
        (dolist (entry (nreverse (evil-state-property t :modes)) default)
          (setq state (car entry)
                modes (symbol-value (cdr entry)))
          (when (or (memq mode modes)
                    (evil--derived-mode-p mode modes))
            (throw 'done state)))))))


;; quick test
(progn
  (require 'cc-mode)
  (evil-set-initial-state 'prog-mode 'insert)
  (put 'prog-mode 'derived-mode-parent 'c-mode) ; chicken, son of an egg
  (unwind-protect
      (message "c-mode state: %s" (evil-initial-state 'c-mode))
    (put 'prog-mode 'derived-mode-parent nil)))
```

**Comment by TheBB** [comment]
I consider this fixed since https://github.com/emacs-evil/evil/pull/985.
