### ISSUE TITLE
pulsing operator range

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#501]
Originally reported by: **Nick Felix (Bitbucket: [Dickby](https://bitbucket.org/Dickby), GitHub: [Dickby](https://github.com/Dickby))**

----------------------------------------

While playing around with `evil-mode` , I added 
`(pulse-momentary-highlight-region beg end)`
to every `cond`-case at the end of `evil-yank`.

With `pulse-iterations` set to 2, the behaviour is really nice:
the operator-selected region just flashes quickly, and since other default
operators use 'evil-yank' it works with them too.

I wondered if this could be implemented as an option to toggle.

It's not working with `visual-block`.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/501

**Comment by wasamasa** [comment]
@Dickby @syl20bnr I believe this can be closed in favor of https://github.com/edkolev/evil-goggles.

**Comment by Dickby** [comment]
yes it can be closed!

**Comment by edkolev** [comment]
For the record, evil-goggles doesn't use `evil-operator-range` because:
- it's not simple to use different faces for different operators - `evil-operator-range` would have to check who is the top-level caller function
- more importantly, doesn't work with `evil-inhibit-operator`
