### ISSUE TITLE
When saving the buffer, change list got emptied.

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#522]
Originally reported by: **ReneFroger (Bitbucket: [ReneFroger](https://bitbucket.org/ReneFroger), GitHub: [ReneFroger](https://github.com/ReneFroger))**

----------------------------------------

I use Emacs 24.4 in GUI-mode

From the Vim / Evil documentation: 

         g;          Go to [count] older position in change list.

         g,          Go to [count] newer cursor position in change list.

When I save the buffer inside Vim, and then press `g;`, it will go to the latest changed postion. 

In Evil, after saving a buffer, I press `g;`, which calls the function `(goto-last-change ARG)`. But I got the error message that there is no further change info. 

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/522

**Comment by ReneFroger** [comment]
Is this bug still open? It was surprisingly to see my comments back here from somewhere, thanks for that!

**Comment by wasamasa** [comment]
Why, yes, it is.

**Comment by TheBB** [comment]
Undo-tree is no longer default after #1360, so closing.
