### ISSUE TITLE
Evil uses the clipboard instead of the primary selection for mouse selection

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#532]
Originally reported by: **hpdeifel (Bitbucket: [hpdeifel](https://bitbucket.org/hpdeifel), GitHub: [hpdeifel](https://github.com/hpdeifel))**

----------------------------------------

I'll copy and paste my email (Subject: visual-mode and X-selections)
from 2012:

    I think that the interaction between visual-mode and the X11 selections
    is not optimal. Since I don't know if the current behavior is
    intentional, I haven't yet opened a bug report.
    
    The selected text in visual-mode is currently copied via the function
    x-select-text. With the Emacs 24.1 default configuration, this copies to
    the X-selection CLIPBOARD (configurable through
    x-select-enable-clipboard and x-select-enable-primary.)
    
    In the rest of Emacs, this function is only used for the explicit
    copy/yank commands. Copying the active region is controlled by the
    variable select-active-regions and uses the PRIMARY X-selection by
    default.
    
    This behavior is consistent with most other X applications: The mouse
    selection is saved in PRIMARY and the explicit copy/paste commands use
    the CLIPBOARD.
    
    Thus, it would be nice if Evil would also use the PRIMARY selection by
    default for the selected text in visual-mode.
    
    I currently use the following redefinition of
    evil-visual-update-x-selection, that does what I need:
    
    #+BEGIN_SRC elisp
    (defun evil-visual-update-x-selection (&optional buffer)
      "Update the X selection with the current visual region."
      (with-current-buffer (or buffer (current-buffer))
        (when (and (evil-visual-state-p)
                   (fboundp 'x-select-text)
                   (or (not (boundp 'ns-initialized))
                       (with-no-warnings ns-initialized))
                   (not (eq evil-visual-selection 'block)))
          (x-set-selection 'PRIMARY (buffer-substring-no-properties
                                     evil-visual-beginning
                                     evil-visual-end))
          (setq x-last-selected-text-primary ))))
    #+END_SRC

@lyro suggested to use the following code instead:

```
(defun evil-visual-update-x-selection (&optional buffer)
  "Update the X selection with the current visual region."
  (with-current-buffer (or buffer (current-buffer))
    (when (and (evil-visual-state-p)
               (fboundp 'x-set-selection)   ; <-- small change, hope it works ;)
               (or (not (boundp 'ns-initialized))
                   (with-no-warnings ns-initialized))
               (not (eq evil-visual-selection 'block)))
      (x-set-selection 'PRIMARY (buffer-substring-no-properties
                                 evil-visual-beginning
                                 evil-visual-end))
      (setq x-last-selected-text-primary ))))
```

So, I've been using this (my version) for two and a half years and I
still like it. It makes x-selection handling in evil much more
consistent with the rest of the environment and more importantly: With
emacs itself.

- Emacs version: GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.9)
- Evil version: 1.1.6
- Operating system: Gentoo Linux
- X: True

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/532

**Comment by patbl** [comment]
Does the last line of that fix work? I thought `setq` required two arguments.

```
(setq x-last-selected-text-primary )
```

**Comment by wasamasa** [comment]
In earlier versions of Emacs this set the variable to `nil`, more recent ones started treating this usage as an error.

That aside, `x-last-selected-text-primary` is not a defined variable in Emacs 25.3, so I doubt this line would do anything useful.  It appears it has been renamed to `gui--last-selected-text-primary`, as for the actual value searching the web gives you results such as https://stackoverflow.com/questions/17127009/how-to-disable-emacs-evil-selection-auto-copies-to-clipboard#23254728.

**Comment by hpdeifel** [comment]
Indeed, I certainly did not intend to use any obscure `setq` semantics and probably failed at copy&pasting the stackoverflow snippet you mentioned. But since I had this code in my config for quite a white, the last line doesn't seem to have been very important.

I don't use this code any more for other reasons, but I'm still annoyed by the original issue from time to time.

**Comment by olejorgenb** [comment]
This issue is quite annoying. Any progress?

**Comment by hpdeifel** [comment]
Laziness is a virtue.. I'm working on it

**Comment by ninrod** [comment]
gentleman, I don't know if I understood the issue correctly, but I'm using this snippet to great success: 

```elisp
(fset 'evil-visual-update-x-selection 'ignore);; Amazing hack lifted from: http://emacs.stackexchange.com/a/15054/12585
```

**Comment by hpdeifel** [comment]
Nah, that disables it completely. We want it to copy to the PRIMARY selection instead of the CLIPBOARD like the rest of emacs and most X programs.

**Comment by wasamasa** [comment]
Closing as this has been implemented by the referenced PR and works for me.
