### ISSUE TITLE
Global yank into register

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#534]
Originally reported by: **Chris Laverdiere (Bitbucket: [CMLaverdiere](https://bitbucket.org/CMLaverdiere), GitHub: [CMLaverdiere](https://github.com/CMLaverdiere))**

----------------------------------------

Yanking all lines matching a pattern into a single register doesn't work in evil mode. In Vim, you can do 'g/pattern/y A' to append all matches to some register 'a'.

See: http://stackoverflow.com/questions/1474966/how-do-i-yank-all-matching-lines-into-one-buffer

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/534

**Comment by edkolev** [comment]
This was fixed a few months ago, in this commit I think https://github.com/emacs-evil/evil/commit/5dc2f713f1a383d12270e8c542b37894695ff0bc

This issue can be closed.

**Comment by wasamasa** [comment]
Thanks, this indeed works now!
