### ISSUE TITLE
Magit 2.1 takes over normal-mode

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#535]
Originally reported by: **Anonymous**

----------------------------------------

Maybe it's a magit issue, but with the latest release, when in normal-mode keys like `k` or `i` still call the magit functions instead of `evil-previous-line` in insert-mode (whereas `j` still does next line, since magit does not set it).

I have in `.emacs`, explicitly removed magit from `emacs-state-modes`, and do not allow overriding:

```
(setq evil-emacs-state-modes ())
(setq evil-insert-state-modes ())
(setq evil-motion-state-modes ())
(setq evil-overriding-maps ())
```

this used to be fine (normal-mode being “normal”) up to the latest upgrade.

(`evil-version` says 1.1.6)

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/535

**Comment by edkolev** [comment]
Since we have the `evil-magit` integration package, I think this can be safely closed.

**Comment by TheBB** [comment]
@edkolev I think you can close issues?

**Comment by TheBB** [comment]
Once you respond to the invite link to join this repo, at least.

**Comment by ninrod** [comment]
I can't. I think that all members can't. only owners.

**Comment by edkolev** [comment]
Hey, no I can't, I have only the `Comment` button.

I responded to the invite a few weeks ago (1-2 hours after I got it).

I haven't tried recently, but I think I can't create branches either.

**Comment by TheBB** [comment]
Yeah, you responded to the invitation to join the organization, but not the one to join this repository. Let me withdraw the invite and issue a new one.

**Comment by wasamasa** [comment]
I agree here, this level of integration is best provided by a package like evil-magit.
