### ISSUE TITLE
Normal mode "d" acts like "dd", "c" acts like "cc", etc.

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#571]
Originally reported by: **Anonymous**

----------------------------------------

Every so often, Evil will break, and hitting "d" in normal mode will act like "dd", "c" act like "cc" and so forth. Obviously this renders it unusable.

Disabling evil-mode and re-enabling it doesn't solve the problem. Nor does entering visual or insert mode in Evil. The only cure I've found is to shut down and restart emacs.

I've yet to determine the cause. It happens frequently enough to be frustrating, but not often enough that I've been able to discern a pattern. The issue affects all buffers, so I don't believe it's a problem with a conflicting minor mode.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/571

**Comment by rogual** [comment]
Are you on Windows? I get this too sometimes, but only on my Windows machine.

**Comment by noctuid** [comment]
This has happened to me on linux as well, but it's a really rare issue (and I have no idea how to reproduce it).

**Comment by ninrod** [comment]
I think I never got this.

**Comment by serycjon** [comment]
I get this issue relatively frequently. Unfortunately I have no idea how to reproduce it or how to get some useful information about what is going on.  Anybody managed to get rid of it?

**Comment by wilbowma** [comment]
I get this regularly on Manjaro, none of the above seemed to work. Based on some hints above, I tried running ":exit-minibuffer". This rearranged a lot of my buffers, but did seem to solve the problem.
