### ISSUE TITLE
Seek Forward When evil-select-paren Fails

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#574]
Originally reported by: **noctuid (Bitbucket: [noctuid](https://bitbucket.org/noctuid), GitHub: [noctuid](https://github.com/noctuid))**

----------------------------------------

This is already how `evil-select-quote` acts. The [textobjectify](https://github.com/paradigm/TextObjectify) vim plugin was created because of the differences between the quote and paren text objects in vim. `evil-select-quote` already works when the open and close quote are not on the same line unlike vim's default quote text objects, so I'm wondering if it would also be acceptable to add this to evil even though it is not how vim acts by default.

If you do not think this should be the default behaviour for `evil-select-paren`, then that is fine since it is easy for the user to add. I am creating my own "(", "[", etc. text objects that do seek currently, but I wanted to check if you would consider adding this to evil before I publish a package that does this.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/574

**Comment by axelf4** [comment]
#1673 resolved this issue.
