### ISSUE TITLE
Option to make Y yank from cursor to end of line instead of yanking whole line

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#576]
Originally reported by: **Paweł Kraśnicki (Bitbucket: [pkkm](https://bitbucket.org/pkkm), GitHub: [pkkm](https://github.com/pkkm))**

----------------------------------------

The behavior of Y in Vim is inconsistent with `D` and `C`. A lot of Vim users rebind `Y` to `y$`; Neovim contributors are even considering making it a default. Doing this in Evil may be hard for someone who recently switched from Vim, so I think it would be helpful if there was a variable similar to `evil-want-C-u-scroll`, which would make `Y` behave like `y$` when set to a non-nil value.

Here's the part of my init which does this, though I don't know if that's the most elegant way:

```
#!elisp
(evil-define-operator evil-yank-to-eol (beg end type register yank-handler)
  "Yank to end of line."
  :motion evil-end-of-line
  (interactive "<R><x><y>")
  (evil-yank beg end type register yank-handler))
(bind-key "Y" nil evil-normal-state-map)
(bind-key "Y" #'evil-yank-to-eol evil-motion-state-map)
```
(I bind in `evil-motion-state-map` to work around [another bug](https://bitbucket.org/lyro/evil/issues/575/cant-yank-in-motion-state-eg-in-help).)

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/576

**Comment by Ghasak** [comment]
with the `evil--goggles I also have added support to highlight the yanked to end of line using 
```lisp 
;; ------------- Yank to end of line (Y)   ----------------
(evil-define-operator evil-yank-to-eol (beg end type register yank-handler)
  "Yank to end of line."
  :motion evil-end-of-line
  (interactive "<R><x><y>")
  (evil-yank beg (point-at-eol) type register yank-handler))

(bind-key "Y" nil evil-normal-state-map)
(bind-key "Y" #'evil-yank-to-eol evil-motion-state-map)

(with-eval-after-load 'evil-goggles
  ;; Adding custom yank to evil-goggles
  (add-to-list 'evil-goggles--commands
                '(evil-yank-to-eol :face evil-goggles-yank-face :switch evil-goggles-enable-yank :advice evil-goggles--generic-async-advice))
  ;; Ensure evil-goggles-mode is enabled
  (evil-goggles-mode))

(evil-define-key 'normal evil-motion-state-map (kbd "Y") #'evil-yank-to-eol)
```
