### ISSUE TITLE
Selecting paragraphs in latex mode

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#595]
Originally reported by: **Arun Isaac (Bitbucket: [arunisaac](https://bitbucket.org/arunisaac), GitHub: [arunisaac](https://github.com/arunisaac))**

----------------------------------------

Say, I have an equation environment in latex mode like so:
```
#!latex

\begin{equation}
  \label{eq:mass-energy-equivalence}
  E = mc^2
\end{equation}
```
If I have point on line 3 (E = mc^2), and do a "vip", only that line gets selected, whereas in vim, all four lines get selected. Similarly, if I do a "vap" only lines 3 and 4 get selected.

In fundamental mode, "vip" and "vap" work normally as they would in vim.

Could this be something to do with the way latex mode modifies the behaviour of *forward-paragraph* and *backward-paragraph*? If so, is it within the scope of evil to fix this?

I am running emacs 24.5.1 in X and evil-hg-09d1e27bb12a on Parabola GNU/Linux.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/595

**Comment by wasamasa** [comment]
An alternative solution is to override the definition of `forward-evil-paragraph` to use the initial value of `paragraph-start`:

```elisp
(with-eval-after-load 'evil
  (defun forward-evil-paragraph (&optional count)
    "Move forward COUNT paragraphs.
Moves point COUNT paragraphs forward or (- COUNT) paragraphs backward
if COUNT is negative.  A paragraph is defined by
`start-of-paragraph-text' and `forward-paragraph' functions."
    (let ((paragraph-start "\f\\|[ \t]*$"))
      (evil-motion-loop (dir (or count 1))
        (cond
         ((> dir 0) (forward-paragraph))
         ((not (bobp)) (start-of-paragraph-text) (beginning-of-line)))))))
```
