### ISSUE TITLE
Change line operation edge case

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#603]
Originally reported by: **Spencer Boucher (Bitbucket: [justmytwospence](https://bitbucket.org/justmytwospence), GitHub: [justmytwospence](https://github.com/justmytwospence))**

----------------------------------------

Strictly speaking, this isn't a bug report because the line change operation is working it should be, but there is a very annoying edge case.

I use evil-mode in ERC, eshell, and comint buffers. Very frequently I will want to change the line at the prompt for these modes, so I press `cc` or `S` (usually `cc` because muscle memory). This kills the line as intended. The problem is a newline is then inserted. Although this is the desired behavior anywhere else in the buffer, it causes a few problems at the very end of a comint-type buffer. For instance, pressing `G` in normal mode will now take me to the useless, empty line *below* the prompt in eshell or comint. Even more annoying, ERC sends the trailing newline as an IRC message with a single blank space.

Would it be worth adding an option to disable adding the newline if it would result in a new line at the end of the buffer? If not, how can I work around this issue? 

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/603

**Comment by axelf4** [comment]
Fixed by #1637.
