### ISSUE TITLE
:put support

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#609]
Originally reported by: **Kevin Brubeck Unhammer (Bitbucket: [unhammer](https://bitbucket.org/unhammer), GitHub: [unhammer](https://github.com/unhammer))**

----------------------------------------

From what I can tell, there's no support for :put, which I find handy for line-wise pasting of unlinewise-yanked text.

http://vimdoc.sourceforge.net/htmldoc/change.html#:put

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/609

**Comment by tomdl89** [comment]
Implemented in #1449
