### ISSUE TITLE
Is there any way to remap evil ex commands for a buffer and/or mode

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#622]
Originally reported by: **Justin Burkett (Bitbucket: [justbur](https://bitbucket.org/justbur), GitHub: [justbur](https://github.com/justbur))**

----------------------------------------

I would like to configure :wq to call with-editor-finish in a magit commit buffer, and looking through the evil-ex sources I don't see an easy way to do this. Essentially I'd like to be able to do something like
```elisp
(define-key with-editor-mode-map [remap evil-save-and-close] 'with-editor-finish)
```
and have it apply to the ex command.

Is there some support for a simple way of doing this in evil? Thanks and feel free to close this if it's not an appropriate place to ask this. 

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/622

**Comment by nawordar** [comment]
@justbur I would like to add this `:wq` remap to my emacs config, but I cannot find this pull request and I don't know what functions/macros it adds. Could you please show me a snippet that remaps `:wq` using the functions added by your PR?

**Comment by TheBB** [comment]
It should be as simple as this.

```elisp
(local-set-key [remap evil-save-and-close] 'some-other-function)
```

Note that you need to remap the actual command, not `"wq"` itself. You can use `(evil-ex-binding "wq")` to see what its default binding is.

This must be evaluated in a buffer where you would like the remapping to take effect.

**Comment by Alexander-Shukaev** [comment]
Here is how I historically solved that issue for myself:

```emacs-lisp
(put 'evil-ex-commands 'permanent-local t)

(defun evil-ex-define-cmd-local (cmd function)
  (eval-when-compile
    (documentation 'evil-ex-define-cmd))
  (unless (local-variable-p 'evil-ex-commands)
    (setq-local evil-ex-commands (copy-alist evil-ex-commands)))
  (evil-ex-define-cmd cmd function))
```

**Comment by nawordar** [comment]
Thank you. I will try both solutions. I was curious though, if this PR added a more streamlined method to do that.

**Comment by nawordar** [comment]
> It should be as simple as this.
> 
> ```emacs-lisp
> (local-set-key [remap evil-save-and-close] 'some-other-function)
> ```
> 
> Note that you need to remap the actual command, not `"wq"` itself. You can use `(evil-ex-binding "wq")` to see what its default binding is.
> 
> This must be evaluated in a buffer where you would like the remapping to take effect.

Alright, I found the [line](https://github.com/emacs-evil/evil/blob/4dc63903d9688e2ce838a220b0e24d8f14a64c12/evil-ex.el#L635) that was changed. It seems that it just adds support for what you mentioned. I am new to emacs and lisp so everything is so confusing for me.

**Comment by nawordar** [comment]
Interestingly enough, I have found that magit already remaps that command:
```emacs-lisp
(defvar with-editor-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map "\C-c\C-c"                           'with-editor-finish)
    (define-key map [remap server-edit]                  'with-editor-finish)
    (define-key map [remap evil-save-and-close]          'with-editor-finish)
    (define-key map [remap evil-save-modified-and-close] 'with-editor-finish)
    (define-key map "\C-c\C-k"                           'with-editor-cancel)
    (define-key map [remap kill-buffer]                  'with-editor-cancel)
    (define-key map [remap ido-kill-buffer]              'with-editor-cancel)
    (define-key map [remap iswitchb-kill-buffer]         'with-editor-cancel)
    (define-key map [remap evil-quit]                    'with-editor-cancel)
    map))
```
I was pretty sure, that my commits are discarded when I type `:wq`. Guess I need to check again.

**Comment by TheBB** [comment]
Indeed, `(evil-ex-binding "wq")` evaluates to `with-editor-finish` in those buffers.

**Comment by MyriaCore** [comment]
Was there never any sugar that made its way to a PR? Just stumbled upon this thread thinking `evil-ex-define-cmd-local` already existed. Why'd it get closed?
