### ISSUE TITLE
Dot doesn't repeat indent operation in visual mode

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#626]
Originally reported by: **Steven Allen (Bitbucket: [Stebalien](https://bitbucket.org/Stebalien), GitHub: [Stebalien](https://github.com/Stebalien))**

----------------------------------------

To reproduce, enter visual mode, indent with `>`, and then type `.`. That is, on a line with text, type: `v>.`

Expected Result: The text is indented twice.

Actual Result: The text is indented once (for the `>`) and then emacs says `. is undefined`.

This happens in both the terminal and GUI.

Emacs: 24.5

Evil: 20160224.1517

OS: Arch Linux

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/626

**Comment by chrissound** [comment]
I'm running into this same issue... Just me?

**Comment by wasamasa** [comment]
I don't use Spacemacs and I cannot reproduce this.  Please do what the original poster has been asked to, use `make emacs` in Evil's source directory to reproduce this with a minimal setup.

**Comment by hliebert** [comment]
I also have this issue, but only when selecting multiple lines. Select using `V`, indent using `>`, repeat with `.`. Error message: `. is undefined.`

**Comment by wasamasa** [comment]
Please make a separate bug report and make sure to repro this without Spacemacs, otherwise your bug report will be closed for the same reason as this one.
