### ISSUE TITLE
showcmd-like behavior

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#633]
Originally reported by: **Anonymous**

----------------------------------------

I'm looking for behavior similar to vim's [`showcmd`](http://vimdoc.sourceforge.net/htmldoc/options.html#%27showcmd%27) option. In vim, if I type `4w`, the `4` will be echoed to the bottom of the screen, until I press `w`. Similarly, if I type `dw`, the `d` will echo to the bottom, until I press `w`.

In evil mode, the former case works: I can type `4w` and my keystrokes will be echoed: ![4w](http://i.imgur.com/LAEJoZu.png) However, if I type an operator, eg `dw`, evil goes into operator-pending state but does not echo the `d` to the bottom of the screen. So what I'm asking for is: I would like to see the partial operators echoed, as with the `showcmd` option.

Relevant discussion in spacemacs gitter: https://gitter.im/syl20bnr/spacemacs?at=56de377819834f3c3535a8b0

I'm using emacs 24.5.1 in X, and evil 20160306.2312 on Arch Linux.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/633

**Comment by dudelson** [comment]
Was this closed because it's not possible in emacs 25 after all?

**Comment by wasamasa** [comment]
Hard to tell because the original issue tracker has been disabled and this is a migrated issue (like most).  It doesn't help that no link to the question has been added, so you'll have to ask Frank Fischer about it.
