### ISSUE TITLE
evil-jump-backward switches buffers

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#684]
Originally reported by: **Constantine (Bitbucket: [Hi-Angel](https://bitbucket.org/Hi-Angel), GitHub: [Hi-Angel](https://github.com/Hi-Angel))**

----------------------------------------

Since some moment evil-jump-backward *(C-o in normal mode)* instead of going to a previous location in the current buffer, switches to a previous buffer, rendering the command almost unusable.

Emacs version: GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.10.8) of 2016-04-25

Evil version: 1.2.12

Operating System: Ubuntu-16.04

Whether you use Emacs in X or terminal mode: X

A minimal example to reproduce the error:

* Open Emacs (i.e. it would show \*scratch\* buffer).
* Open a file.
 * Press C-o whilst in «normal mode» — it ought to do nothing, as no movement was in the buffer yet.
 * Suddenly find yourself in the \*scratch\* buffer
* ☹

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/684

**Comment by salamynder** [comment]
+1 for defcustom switch between these two behaviours :)

**Comment by Hi-Angel** [comment]
> BTW, if C-o opens a new buffer, you can always come back with C-i.

@VanLaser yeah, except that I gonna stuck in a random place instead of getting where I was before in the buffer.

**Comment by VanLaser** [comment]
@Hi-Angel - random place? Maybe using 'save-place-mode' would help?

**Comment by Hi-Angel** [comment]
@VanLaser being random is in the sense that I have been editing a function in buffer α, then I jumped to a definition buffer β, then I jumped to a new definition, which in turn led me to buffer α. Now I want to get back to the function I been editing, but <kbd>C-o</kbd> leads me to buffer β, so I stuck in random place in buffer α, and need to manually search where I was editing the function.

A workaround in this particular case is to press <kbd>u</kbd> then <kbd>C-r</kbd>, but there're many situations, like for code exploration, when I can't easily return back.

**Comment by VanLaser** [comment]
No, it's not random, you should simply continue to press `C-o` until you land back to the exact desired position.

**Comment by Hi-Angel** [comment]
@VanLaser the problem is that in real usecases I walk around in too many different buffers, so when I back to where I'm doing something, I have to press <kbd>C-o</kbd> like a dozen times. It defeats whole purpose of <kbd>C-o</kbd> because it's really faster to just go manually find where I was.

**Comment by Hi-Angel** [comment]
I honestly curious: what workflow do you people using that you have no such a problem? How do you explore the code?

**Comment by ninrod** [comment]
I usually I use bookmarks for that, coupled with a customized ibuffer-vc. But you do have a point.

**Comment by VanLaser** [comment]
@Hi-Angel  - I understand you, but I think you want to force a thing that in Vim *is* in a certain way (and which evil tries to emulate ...), to match your workflow. So your point is good, but I think you should add (or ask for) a *new* / different feature to Evil's history , not modify *this* behavior.

**Comment by ninrod** [comment]
@Hi-Angel, I had some degree of success with emacs `push-mark` feature. Maybe you could look into that.

**Comment by Hi-Angel** [comment]
@VanLaser I agree. There's a [pull-requested patch](https://github.com/emacs-evil/evil/pull/749) adding the new flag. Almost works for me, just a small annoyance I mentioned in the comment there. The original author seems to be inactive, so I don't think the comments get addressed. I'll may be try to fix that myself, then with the changes it will be ready for merge.

**Comment by VanLaser** [comment]
What could also be useful (maybe) would be an enhanced output of the `:jumps` command, one that shows a little bit of context of what's at that jump location - so one could next just select that "line" to go there directly (helm-like interface and selection) ..

**Comment by Hi-Angel** [comment]
Fixed by commit [dc93693666659](https://github.com/emacs-evil/evil/commit/dc936936666595afdbdbb4cc44c1f82e74c6802c). Thank you wasamasa and c4eater.

Note, that because this report originally migrated from BitBucket, I can't close it.

**Comment by TheBB** [comment]
Thanks!
