### ISSUE TITLE
error when folder of an open buffer is deleted outside emacs

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#691]
Originally reported by: **Fang Qiang (Bitbucket: [godblessfq](https://bitbucket.org/godblessfq), GitHub: [godblessfq](https://github.com/godblessfq))**

----------------------------------------

Hello everyone,

I get this error when I am trying to swtch buffer and a folder of an open buffer is deleted outside emacs:

Error in post-command-hook (evil-mode-check-buffers): (file-error "Setting current directory" "directory not found")

I think it would be better to just close the buffer or
offer the user to save open files elsewhere instead of giving
error and block all other commands.

what do you think?
Thank you!

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/691

**Comment by axelf4** [comment]
This would be a bug in `define-globalized-minor-mode`, and should probably go in the Emacs issue tracker instead. Regardless, it may have been fixed at some point since I am unable to reproduce.
