### ISSUE TITLE
Missing window navigation keys

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#694]
Originally reported by: **Anonymous**

----------------------------------------

Hi evil-mode,

New evil-mode user here; I just made the switch from vim to emacs last week.

I really really miss the following key definitions from vim:

```
#!elisp

(define-key evil-window-map (kbd "<right>") 'evil-window-right)
(define-key evil-window-map (kbd "<left>") 'evil-window-left)
(define-key evil-window-map (kbd "<up>") 'evil-window-up)
(define-key evil-window-map (kbd "<down>") 'evil-window-down)
```

...namely, the C-W <arrow key> navigation.

Would appreciate it if these were added to evil-mode

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/694

**Comment by axelf4** [comment]
Fixed by #1643.
