### ISSUE TITLE
ZQ should also work in motion state

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#695]
Originally reported by: **Wouter Bolsterlee (Bitbucket: [wbolster](https://bitbucket.org/wbolster), GitHub: [wbolster](https://github.com/wbolster))**

----------------------------------------

...while ZZ should only work in normal state (as it currently is).

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/695

**Comment by tomdl89** [comment]
No longer seems to be an issue. Please re-open if you observe otherwise.
