### ISSUE TITLE
key-translation-map not used by evil-repeat

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#706]
Originally reported by: **Wouter Bolsterlee (Bitbucket: [wbolster](https://bitbucket.org/wbolster), GitHub: [wbolster](https://github.com/wbolster))**

----------------------------------------

my key-translation-map maps a few keys on my keyboard to other keys. this works fine when inserting text, but when i use `evil-repeat` to repeat the last action, any input will be "replayed" but _without_ the key-translation-map applied.

for example, i have `-` mapped to `_` (to avoid emacs pinky problems), and i can type things like `foo_bar_baz` just fine (without using the shift key at all) after pressing `i` to enter `insert-state`. but when i press `.` afterwards, suddenly another `foo-bar-baz` (with dashes!) appears.

this is particularly annoying since it also applies to repeating things like `cio` to change the symbol at point.

(maybe related in some way to #177)

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/706

**Comment by axelf4** [comment]
Cannot reproduce anymore.
