### ISSUE TITLE
Binding a key in lisp-mode-map with evil-define-key can bind it in emacs-lisp-mode-map

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#709]
Originally reported by: **Anonymous**

----------------------------------------

Because the `evil-get-auxiliary-map` used in `evil-define-key*` doesn't set `ignore-parent` to a non-nil value, using `evil-define-key` with `lisp-mode-map` can actually end up binding the keys in `lisp-mode-shared-map`. This results in key bindings specified for `lisp-mode-map` ending up in `emacs-lisp-mode-map`.

This behavior doesn't seem very intuitive to me. Are there a lot of cases where having `ignore-parent` as nil here makes more sense? If not, I think it would be better to set it to `t` in `evil-define-key*`. Otherwise, it could potentially be nice to add a disclaimer in the docstring that the parent keymap could end up being used.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/709

**Comment by noctuid** [comment]
Is there any opposition to this? If not, this is a very simple change, and I'd be happy to make a pull request if it would be accepted. It's really annoying to, for example, bind a key in `image-mode-map`, have that same key end up being bound in `message-mode-map`, and then manually have to put `evil-get-auxiliary-map` beforehand in my config to prevent this. I've had this problem with several other keymaps as well.

**Comment by wasamasa** [comment]
No objection here. I recall a more recent ticket about the same issue where I asked for clarification, if I find it again I'd close it in favor of this one.

**Comment by noctuid** [comment]
This can be closed now.

**Comment by wasamasa** [comment]
OK.
