### ISSUE TITLE
swiper integration

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#712]
Originally reported by: **Nick Felix (Bitbucket: [Dickby](https://bitbucket.org/Dickby), GitHub: [Dickby](https://github.com/Dickby))**

----------------------------------------

A swiper search is repeatable with evil-search-next and evil-search-previous, but it doesn't set the direction of the search.

More clear if i search for a string with swiper jump to one of the candidates and press "n" for jumping to the next match, the used direction depends on the last evil-search command before the swiper call.

 if The last evil-search was forward it jumps forward and if it was evil-search-backward it will continue backwards.

It would be nice if the direction was depending on the swiper jump direction, or if it would be forward all the time to make it more predictable.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/712

**Comment by edkolev** [comment]
I believe this issue can now be closed. It's fixed in swiper in this commit https://github.com/abo-abo/swiper/commit/fc2e1984fdc6a373d2f85a99a05e27926db52bc9

**Comment by TheBB** [comment]
Excellent :+1:
