### ISSUE TITLE
in eww, evil-scroll-down gives (wrong-type-argument integer-or-marker-p nil)

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#713]
Originally reported by: **Kevin Brubeck Unhammer (Bitbucket: [unhammer](https://bitbucket.org/unhammer), GitHub: [unhammer](https://github.com/unhammer))**

----------------------------------------

Using Emacs  "25.1.50.2" in X with evil  "1.2.12" (20160827.1510 from melpa), if I do M-s M-w to search for something with eww, the evil-scroll-down function on C-d gives 

```
#!emacs-lisp

Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  evil-scroll-down(nil)
  funcall-interactively(evil-scroll-down nil)
  call-interactively(evil-scroll-down nil nil)
  command-execute(evil-scroll-down)
```
but still scrolls down. In other major modes, it works fine.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/713

**Comment by duzaichuan** [comment]
Same error in GNU 26.1. Besides eww, also happens in mu4e:header, elfeed-search and nov-mode.
