### ISSUE TITLE
bug report: evil-delete-marks

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#715]
Originally reported by: **Liu233w (Bitbucket: [Liu233w](https://bitbucket.org/Liu233w), GitHub: [Liu233w](https://github.com/Liu233w))**

----------------------------------------

    (evil-delete-marks "a")
    ->
    Wrong type argument: arrayp, 0

https://bitbucket.org/lyro/evil/src/f2648b841f9bcded8764ce63410065d2b8c5f856/evil-commands.el?at=default&fileviewer=file-view-default#evil-commands.el-3030

Changing `((= (aref i ?\ )) (cl-incf i))` to `((= (aref marks i) ?\ ) (cl-incf i))` should work.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/715

**Comment by tmalsburg** [comment]
I'm getting a different error message:

    eval: Wrong number of arguments: (1 . 2), 0

A fix would be great since there seems to be no way to delete marks at this time.

**Comment by tomdl89** [comment]
Resolved by #1428
