### ISSUE TITLE
Entering replace state doesn't show "-- REPLACE --" message in the echo area

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#719]
Originally reported by: **bmag (Bitbucket: [bmag](https://bitbucket.org/bmag), GitHub: [bmag](https://github.com/bmag))**

----------------------------------------

For some reason, entering `replace` state doesn't show a `"-- REPLACE --"` message in the echo area, despite `replace` state being defined with `:message "-- REPLACE --"`. Entering `insert` state does show a `"-- INSERT --"` message.

This also affects custom-made states, e.g.  Spacemacs' `hybrid` state.

System:

- Emacs version: 25.1.1
- Evil version: evil-git-cf951a5
- OS: Windows 10

Repro steps:

- `emacs -Q -L path/to/evil -l evil`
- `M-x evil-mode`
- `R`

Observed behavior:

I am now in `replace` state, but the echo area does not show a `"-- REPLACE --"` message. No such message in the `*Messages*` buffer either.

Expected behavior:

Enter `replace` state, and also show a `"-- REPLACE --"` message in the echo area. (similar to `"-- INSERT --"` for `insert` state)

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/719

**Comment by axelf4** [comment]
I could not reproduce this using `make emacs` with the current master branch on GNU Emacs 28.2.
