### ISSUE TITLE
In daemon mode, ZZ, :quit etc. don't kill buffer

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#723]
Originally reported by: **Beojan Stanislaus (Bitbucket: [beojan](https://bitbucket.org/beojan), GitHub: [beojan](https://github.com/beojan))**

----------------------------------------

In daemon mode, `ZZ`, `:quit` etc. don't kill the buffer. Hence, if I open a file with `emacsclient filename`, edit, and close with `ZZ`, when I open a new `emacsclient`, the last edited file re-opens. This doesn't match VIM behavior of closing the file when using `:quit`.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/723

**Comment by sanel** [comment]
Although I'm not issue reporter, I've encountered it few times in the past. However, I'm not able to reproduce it any more. Here are my steps:

```
emacslient foo.txt
;; do something
;; :quit or ZZ
emacsclient
;; foo.txt is no longer in buffer list
```
