### ISSUE TITLE
repeat command (.) doesn't properly apply numeric modifier

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#724]
Originally reported by: **Garrett Reid (Bitbucket: [garrettreid](https://bitbucket.org/garrettreid), GitHub: [garrettreid](https://github.com/garrettreid))**

----------------------------------------

With Emacs 25.1.1 and Evil (as installed via Spacemacs), if you have a file with the following content:
```
test1
test2
```

If you navigate to the start of line 1, then 3sbi<esc> to substitute 3 characters, then insert "bi", you'll have:
```
bit1
test2
```

Now, if you navigate down to start of line 2, and press . to repeat the last action, you'll have:
```
bit1
biest2
```
In Vim, that'd give you:
```
bit1
bit2
```

This also applies to other actions (say, x to delete). Starting with the original file and applying 3x (delete 3 characters) to start of the first line:
```
t1
test2
```

Then navigate down to beginning of second line, and press . to repeat action. You'll get:
```
t1
est2
```
And in Vim:
```
t1
t2
```

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/724

**Comment by Deewiant** [comment]
#683 duplicate.
#9 related?

**Comment by TheBB** [comment]
Yes, also https://github.com/emacs-evil/evil/issues/731
