### ISSUE TITLE
cw misses one character in emacs-lisp-mode when word is surrounded by - and a symbol

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#728]
Originally reported by: **Anonymous**

----------------------------------------

Emacs version: 26.0.50.1 (HEAD as of yesterday)
Evil version: 20160827.1510
OS: macOS Sierra
Mode: GUI

In the scratch buffer, insert:

```elisp
-word)
```

Then under `w`, type in command mode `cw`. You should get:

```elisp
-d)
```

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/728

**Comment by tomdl89** [comment]
Duplicate of #721
