### ISSUE TITLE
Calling interactive function with digit in name.

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#729]
Originally reported by: **Shtucer (Bitbucket: [Shtucer](https://bitbucket.org/Shtucer), GitHub: [Shtucer](https://github.com/Shtucer))**

----------------------------------------

I have some function with digit in name `dos2unix` for example.

```
#!lisp

(defun dos2unix ()
    (interactive)
    (set-buffer-file-coding-system 'unix 't))

```
when I need to call this I press `colon` then `dos2unix` and `Return`. Emacs says:

`Unknown command: 'dos'`

Same thing happen for `js2-mode` function.

`M-x dos2unix` works fine.

`M-x js2-mode` works fine. 

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/729

**Comment by wasamasa** [comment]
This seems to be a matter of the Ex grammar as defined in `evil-ex-grammar` in `evil-ex.el`.  If you replace the definition of `binding` ("[~&*@<>=:]+\\|[[:alpha:]-]+\\|!") with "[~&*@<>=:]+\\|[[:alnum:]-]+\\|!", things magically work.  I don't quite understand why though, so I'll study the code a bit more.  It doesn't help that edebugging makes `evil-ex` itself fail...
