### ISSUE TITLE
Scrolling with C-e and C-y doesn't scroll cursor

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#734]
Originally reported by: **Anonymous**

----------------------------------------

Scrolling with C-e and C-y in Vim also scrolls the cursor while in Evil it stays in the same place visually (but not contextually).  So the behaviour is different from Vim.

* Emacs version: 24.4.1
* Evil version: 1.0-dev
* OS: Linux «host» 4.2.0-0.bpo.1-amd64 #1 SMP Debian 4.2.6-3~bpo8+2 (2015-12-14) x86_64 GNU/Linux

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/734

**Comment by jojojames** [comment]
You can set scroll-preserve-screen-position to nil to get evil's functionality.

The problem is I'd like to get something like this for 'smoother' scrolling in Emacs.

```elisp
;; https://stackoverflow.com/questions/3631220/fix-to-get-smooth-scrolling-in-emacs
(setq scroll-margin 5
      scroll-step 1
      scroll-conservatively 10000
      scroll-preserve-screen-position 1) ;; <----
```

```elisp
(evil-define-command evil-scroll-line-up (count)
  "Scrolls the window COUNT lines upwards.
If COUNT is not specified the function uses
`evil-scroll-line-count', which is the last used count."
  :repeat nil
  :keep-visual t
  (interactive "<c>")
  (progn
    (setq count (or count evil-scroll-line-count))
    (setq evil-scroll-line-count count)
    (scroll-down count)))

(evil-define-command evil-scroll-line-down (count)
  "Scrolls the window COUNT lines downwards.
If COUNT is not specified the function uses
`evil-scroll-line-count', which is the last used count."
  :repeat nil
  :keep-visual t
  (interactive "<c>")
  (progn
    (setq count (or count evil-scroll-line-count))
    (setq evil-scroll-line-count count)
    (scroll-up count)))
```

I wonder if it would be appropriate to just set it to nil before calling scroll-up/scroll-down and resetting it to its original value after the fact.

Something like this,

```elisp
  (evil-define-command evil-scroll-line-up (count)
    "Scrolls the window COUNT lines upwards.
If COUNT is not specified the function uses
`evil-scroll-line-count', which is the last used count."
    :repeat nil
    :keep-visual t
    (interactive "<c>")
    (progn
      (setq count (or count evil-scroll-line-count))
      (setq evil-scroll-line-count count)
      (let ((spsp scroll-preserve-screen-position))
        (setq scroll-preserve-screen-position nil)
        (scroll-down count)
        (setq scroll-preserve-screen-position spsp))))

  (evil-define-command evil-scroll-line-down (count)
    "Scrolls the window COUNT lines downwards.
If COUNT is not specified the function uses
`evil-scroll-line-count', which is the last used count."
    :repeat nil
    :keep-visual t
    (interactive "<c>")
    (progn
      (setq count (or count evil-scroll-line-count))
      (setq evil-scroll-line-count count)
      (let ((spsp scroll-preserve-screen-position))
        (setq scroll-preserve-screen-position nil)
        (scroll-up count)
        (setq scroll-preserve-screen-position spsp))))
```

**Comment by wasamasa** [comment]
@jojojames You can just use `(let ((scroll-preserve-screen-position nil)) ...)`, no need to `setq` anything.

**Comment by jojojames** [comment]
@wasamasa 

Thanks for the tip. Would this be sufficient for a pull request?

```elisp
  (evil-define-command evil-scroll-line-up (count)
    "Scrolls the window COUNT lines upwards.
If COUNT is not specified the function uses
`evil-scroll-line-count', which is the last used count."
    :repeat nil
    :keep-visual t
    (interactive "<c>")
    (progn
      (setq count (or count evil-scroll-line-count))
      (setq evil-scroll-line-count count)
      (let ((scroll-preserve-screen-position nil))
        (scroll-down count))))

  (evil-define-command evil-scroll-line-down (count)
    "Scrolls the window COUNT lines downwards.
If COUNT is not specified the function uses
`evil-scroll-line-count', which is the last used count."
    :repeat nil
    :keep-visual t
    (interactive "<c>")
    (progn
      (setq count (or count evil-scroll-line-count))
      (setq evil-scroll-line-count count)
      (let ((scroll-preserve-screen-position nil))
        (scroll-up count))))
```

Not sure if anyone wants to preserve the old behavior so maybe this should be customizable?

**Comment by wasamasa** [comment]
To be honest, I don't see the difference.  Could you perhaps put it into clearer words than the original bug report?

**Comment by jojojames** [comment]
Sure, the bug report description was a little confusing to me too.

If you have a file like this.

1.
2.
3. [CURSOR IS HERE] // (defun function)
4.
5.

Pressing C-e or C-y in vim
2.
3. [CURSOR IS HERE] (defun)
4.
5.
6.

The cursor moves/stays 'with the original line'.

Evil/Emac's current behavior is.
1.
2.
3. [CURSOR IS HERE] (defun)
4.
5.

After C-e / C-y
2.
3.
4. (defun)
5. [CURSOR IS HERE]
6.

The cursor has moved away from its original line.

**Comment by ninrod** [comment]
I cannot reproduce. `C-e / C-y` for me behaves exactly like the first case you described (in normal mode)

**Comment by jojojames** [comment]
Did you also set this variable to 1?

(setq scroll-preserve-screen-position 1)

NOTE: I didn't submit the original bug, but I saw it myself with my own configuration set.

I think it's reasonable c-e/c-y behaves like vim even if the user changes that variable to 1 (away from its default).

**Comment by ninrod** [comment]
hi @jojojames 

`C-h v` tells me:

```txt
scroll-preserve-screen-position is a variable defined in ‘C source code’.
Its value is nil
```

So no.

**Comment by jojojames** [comment]
Yup. You can reproduce it by setting that value to 1.

The bug only exists because we're using the implementatin of scroll-up/scroll-down which changes behavior based off that variable.

See my previous comment, I think it's reasonable C-e/C-y still matches vim's behavior even with that variable changed (as leveraging scroll-up/scroll-down is just an implementation detail).

**Comment by ninrod** [comment]
Oh, ok I see your point.

**Comment by wasamasa** [comment]
@jojojames OK, I've had it customized to `t` and uncustomized when trying to repro it.  Feel free to open a PR!
