### ISSUE TITLE
Add a simple config in readme to bootstrab evil

### ISSUE THREAD

**Issue by ninrod** [emacs-evil/evil#740]
This is pretty important for would be vim expatriates. 

I was thinking in something along the lines of:

```elisp
(require 'package)
(setq package-archives '(("melpa" . "http://melpa.org/packages/")))
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package evil
  :ensure t
  :config
  (evil-mode))
```

**Comment by therockmandolinist** [comment]
I think this is good to have in general. And though I prefer `use-package` myself (who wouldn't), I'm not sure it's evil-mode's responsibility to include the setup up use-package in the readme. I think the installation instructions should be something more along the lines of: 

### Installation
Using [use-package](https://github.com/jwiegley/use-package) (recommended):
```emacs-lisp
(use-package evil
  :ensure t
  :config
  (evil-mode))
```
Using [way to install packages # 2]...
```emacs-lisp
(code here)
```
Using [way to install packages # 3]...
```emacs-lisp
(code here)
```

etc.

Linking use-package can introduce it to new users while not including code that isn't strictly specific to evil-mode installation. Although I definitely see your point that as an entry point into emacs from vim (meaning you evil-mode is the first thing you look at) it might make the transition more simple and seamless, so I'm just thinking aloud.

**Comment by ninrod** [comment]
@therockmandolinist, yes I think that `evil-mode` fills a particular niche for vim expatriates. I would go so far as to say that evil-mode is a prereq for a vimmer to switch to emacs. It's the very first thing that a vimmer would do in emacs and it has to work on the first try, without hassle, fullproof, if the experience is to be non traumatic.

**Comment by edkolev** [comment]
I think it would be helpful to also replace the `evil.pdf` with more documentation in the README, and more importantly include common (not all) settings like `evil-want-C-w-delete`, `evil-want-Y-yank-to-eol` in the REAME

**Comment by TheBB** [comment]
@Benaiah was interested in doing documentation I think.
