### ISSUE TITLE
Please recreate release tags for melpa-stable!

### ISSUE THREAD

**Issue by mdorman** [emacs-evil/evil#744]
For the moment evil's not available through melpa stable because there are no tags for releases.

**Comment by TheBB** [comment]
It won't matter anyway because it has dependencies that aren't on melpa-stable. Once they're there, it'll happen.

Duplicate of https://github.com/emacs-evil/evil/issues/458, see also https://github.com/emacs-evil/evil/issues/737#issuecomment-273774216
