### ISSUE TITLE
fix melpa evil description

### ISSUE THREAD

**Issue by ninrod** [emacs-evil/evil#753]
the description of evil in https://melpa.org/#/evil says this:

```txt
...
Evil lives in a Git repository. To obtain Evil, do

     git clone git://gitorious.org/evil/evil.git
...
```

Update to reflect Evil's new home.

**Comment by therockmandolinist** [comment]
This actually comes from the evil.el file, in the `;;; Commentary:` section. A PR may be more apt.

**Comment by wasamasa** [comment]
This should hopefully be updated in a few hours, but I've had issues before over cached descriptions.  If that happens, we'll have to prod MELPA.

**Comment by TheBB** [comment]
Looks good now.

**Comment by wasamasa** [comment]
MELPA Stable does still show the old one.  Perhaps that will go away once every release has been tagged and a new one is out?

**Comment by TheBB** [comment]
Yeah it should. If everyone are ok with https://github.com/emacs-evil/evil/pull/757 we should merge it and tag a 1.3.
