### ISSUE TITLE
enter visual mode when select a block of text using mouse

### ISSUE THREAD

**Issue by chantisnake** [emacs-evil/evil#756]
on vim if you set `behave xterm` then if you select a block of text using the mouse, the editor will enter `visual` mode instead of `replace` mode.

Is there a setting in evil that will allow me to do that?

**Comment by TheBB** [comment]
Turn on `xterm-mouse-mode`.

**Comment by chantisnake** [comment]
thank you, that is very helpful!

**Comment by chantisnake** [comment]
hum, it is not working now...

![capture](https://cloud.githubusercontent.com/assets/10100995/23473710/159c22d2-fea9-11e6-8eda-38e0396a3e61.gif)

I am using spacemacs:
#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html coq auto-completion better-defaults emacs-lisp git markdown org emoji windows-scripts markdown html python yaml vimscript latex javascript spell-checking syntax-checking ess version-control shell spacemacs-ui spacemacs-ui-visual)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by wasamasa** [comment]
Sorry, but I can't help you neither with Spacemacs nor with Windows-specific issues.

**Comment by michael-angelozzi** [comment]
I have the same issue with Ubuntu 18.04 and Emacs 26.3.
