### ISSUE TITLE
evil-paste-after and evil-paste-before paste in same line

### ISSUE THREAD

**Issue by matijazezelj** [emacs-evil/evil#763]
Hi,

if i yank or delete line and paste it somewhere in text it just pastes it in same line but after/before the cursor

this seems to be working fine on emacs 24.4(my debian server) but on arch with latest emacs(25.1.1) and latest evil it causes problems

Can this be fixed?

showcase:
```
one
two
three
four
```

yank line two, cursor on three - paste(p) - cursor is on letter "t"

```
one
two
ttwohree
four
```

yank line two, cursor on three - paste(P) - cursor is on letter "t"
```
one
two
twothree
four
```

**Comment by TheBB** [comment]
Are you yanking the *line* with `yy` or `Y` or are you yanking it in some other way (say, `0y$`)?

From what you describe it seems you're just yanking the characters `two` instead of the *line* `two`, and that is expected behaviour if you do it that way. If you yank the actual line you should see it pasted as a line.

**Comment by TheBB** [comment]
In other words, please clarify your repro steps with the actual keys pressed.

**Comment by matijazezelj** [comment]
Sorry i did not clarify.
i tried `0y$`, `Y` and `yy`. they all produce same output:

```
one
two
ttwohree
four
```
same thing with delete , i used `dd` on line `two` and `p` on line `three` got:
```
one
ttwohree
four
```

**Comment by TheBB** [comment]
I can't reproduce this, sorry. Do you see this behaviour from `make emacs` in a fresh clone of evil?

**Comment by matijazezelj** [comment]
I just ran it:

```
$ make emacs
Compute dependencies
emacs -Q -L . -L lib -l goto-chg.el -l evil-tests.el \
--eval "(evil-mode 1)" \
--eval "(evil-tests-initialize '() '() t)" &
```

```
Selector: t
Passed: 181
Failed: 0
Total:  181/181

Started at:   2017-02-10 16:42:26+0100
Finished.
Finished at:  2017-02-10 16:42:36+0100
```

**Comment by TheBB** [comment]
Seems like it's working then (yes, we do have tests covering this case).

**Comment by matijazezelj** [comment]
I just found out that it works in shell version of emacs.

So this only affects gui version. 
tried emacs, remacs, built from abs on arch, built from source .. every time it is the same in GUI

**Comment by TheBB** [comment]
But if it works with `make emacs`, and not in your regular config, I can only assume that your config is the problem.

**Comment by matijazezelj** [comment]
I removed my .emacs.d and downloaded spacemacs, same issue. So it cannot be my config.

**Comment by TheBB** [comment]
Spacemacs is your config. If it works with `make emacs` and not elsewhere, it's probably the fault of the elsewhere. If it *doesn't* work with `make emacs` we can try to deal with it here. However since the tests pass in `make emacs` it leads me to believe the former. (I note that it doesn't seem like you have tried to actually repro this exact issue in `make emacs`, which you should try.)

**Comment by matijazezelj** [comment]
but still it's strange. if i remove .emacs.d, (i have no .emacs file), create new .emacs.d, clone only evil there
```
~/.emacs.d % ls -la
total 28
drwxr-xr-x   3 matija matija  4096 Feb 10 19:42 .
drwxr-xr-x 169 matija matija 20480 Feb 10 19:43 ..
drwxr-xr-x   6 matija matija  4096 Feb 10 19:43 evil
```
start emacs -Q
add
```
(add-to-list 'load-path "~/.emacs.d/evil")
(require 'evil)
(evil-mode 1)
```
to init.el

exit emacs 
open new emacs with emacs -Q -l init.el to only load those 3 lines so i have evil now
and then 
```
one
two
three
four
```
on line `two` do `yy` 
go to line `three`
do `p`
```
one
two
ttwohree
four 
```

I'm really out of ideas
i even purged emacs from my system to make sure /usr/share/emacs/site-lisp was empty and started emacs i built from scratch with only evil installed and stil got same issue.

It's some library in arch that is making trouble here. can you think of any lib that could cause this to fail?

**Comment by wasamasa** [comment]
@matijazezelj The proper way to test is with `emacs -q` and `emacs -Q`, as seen in [this flowchart](http://brause.cc/emacs-flowchart.png).  Once you're in a minimal session, use `M-x package-initialize`, then `M-x evil-mode` and try reproducing the problem.

**Comment by Dickby** [comment]
I can't reproduce it on arch linux with emacs from the official repos,

**Comment by matijazezelj** [comment]
as some of you might have seen on irc - this is the issue on my end. something is broken with emacs binaries/libraries. 

I've setup similar env in virtual machine and it works there. I'll keep digging. will send my findings if i find the issue.

**Comment by wasamasa** [comment]
@matijazezelj I have a crazy theory of what's going on.  As you've proved that the input and executed Emacs commands are identical in both shell and GUI, what if they do actually result in the same output, but Emacs doesn't display it correctly in the GUI?  Easiest way of verifying this is saving the output to a file and inspecting it elsewhere, like in your shell.  And yes, I've had this once, with the Intel driver causing crazy mouse cursor flickering under very specific circumstances after updating to Emacs 25 on Arch.  Switching to the modesetting driver fixed it for me.

**Comment by wasamasa** [comment]
@matijazezelj I have a crazy theory of what's going on.  As you've proved that the input and executed Emacs commands are identical in both shell and GUI, what if they do actually result in the same output, but Emacs doesn't display it correctly in the GUI?  Easiest way of verifying this is saving the output to a file and inspecting it elsewhere, like in your shell.  And yes, I've had this once, with the Intel driver causing crazy mouse cursor flickering under very specific circumstances after updating to Emacs 25 on Arch.  Switching to the modesetting driver fixed it for me.

**Comment by matijazezelj** [comment]
@wasamasa I tried it, same thing. Even set modesetting. Same issue. Maybe this is a good chance for me to learn emacs keybindings. Or just reinstall OS:)

**Comment by matijazezelj** [comment]
@wasamasa i found the issue

http://wikemacs.org/wiki/Evil#Enter_an_emacs_mode_in_a_given_state

this caused evil to go full retard. strange how it broke whole emacs, looks like that was loaded with evil everytime.

anyhow, without that in my config evil works as expected
