### ISSUE TITLE
Keep tracking new contributors in evil.el?

### ISSUE THREAD

**Issue by wasamasa** [emacs-evil/evil#764]
Under the previous maintainership, every new contributor to Evil was added to `evil.el`, with their full name and email address.  I've noticed that us current maintainers failed to do the same for the pull requests that were accepted on this repository.  How shall we proceed about this, by adding the last few contributors to `evil.el` and keeping up the tradition or by adding a remark that the tradition has been dropped and contributors can be found in the log?

**Comment by TheBB** [comment]
I vote for the latter.

**Comment by wasamasa** [comment]
Alright, if nobody else feels like voting, I consider this decided.  Feel free to close this ticket with a commit changing `evil.el` as described above.

**Comment by TheBB** [comment]
Done https://github.com/emacs-evil/evil/commit/5538143e8681a07b646e88fecf5cb32f33323d90
