### ISSUE TITLE
abbrev.el integration

### ISSUE THREAD

**Issue by edkolev** [emacs-evil/evil#765]
I noticed that abbrevs aren't expanded when leaving insert state. For example, with `undefined` abbreviated as `undef` (for haskell):
- typing this expands the abbrev: `undef<SPC>` => `undefined`
- typing this doesn't expand `undef<ESC>` => `undef`

Vim's behaviour is to expand abbrevs when leaving insert mode.

I believe this should fix it in evil-integration.el:
```
(with-eval-after-load 'abbrev
  (add-hook 'evil-insert-state-exit-hook 'expand-abbrev))
```

I'll create a PR if this is the right behaviour and the right way to implement it.

**Comment by therockmandolinist** [comment]
I think it would be nice to implement this as a user option (sure, it could default to `t`), since on first thought this sounds a bit odd to me, but if it's vim's behavior I can see why it should be included.
