### ISSUE TITLE
evil-paste-after messes up here doc highlighting in CPerl mode

### ISSUE THREAD

**Issue by CeleritasCelery** [emacs-evil/evil#773]
A Here doc is a multi-line string surrounded by tags that are defined by the user. The built in `cperl-mode` highlights these tags as a string. When pasting into a cperl here doc with Emacs built-in `yank` command everything works as expected and the text is added to the string and font-locked as such. However if I use `evil-paste-after` on a blank line in the here doc it changes all text after point till the end of the document to a comment face. Though `evil-paste-before` only exhibits this behavior when you do not copy an entire line (i.e. don't use `yy` to copy).

To reproduce:
 have a file in cperl-mode that looks like such

```
#!/usr/bin/env perl

my $here_doc = <<'_HERE_';
this is here doc line

_HERE_
```

then try and copy the line that says "this is a here doc line" with `yy`, move cursor down to the blank line and paste it with `evil-paste-after`. You will see that both the pasted line and the terminating `_HERE_` will become font locked with the `font-lock-comment-face`. The only way to fix it is to try and "mess with" starting tag till cperl-mode re-parses the here doc and sees that something is wrong.  

I will be happy to help with debugging this if I can get some direction from the experts.

**Comment by wasamasa** [comment]
I suspect this is unrelated to Evil as I've managed reproducing it this way:

Press `O` with point on the empty line and you'll get "_HERE_" fontify as a comment.  Alternatively, use `M-: (insert "\n")` which is what `O` is ultimately doing.  Same works in `emacs -Q`, so I'll close this.

Regarding debugging advice, dive into `cperl-find-pods-heres` which is a mere thousand lines of extraordinarily hairy looking code.  Good luck!

**Comment by CeleritasCelery** [comment]
Thanks for advice.
