### ISSUE TITLE
Consider derived modes in evil's initial states

### ISSUE THREAD

**Issue by blaenk** [emacs-evil/evil#775]
I remember finding some code (vaguely remember it was from @wasamasa) that advises the `evil-initial-state` function to assume a match when the current mode is _or derives from_ a mode in the list of initial state modes. For example, if I add `prog-mode` to `evil-normal-state-modes` then any mode that derives from `prog-mode` will be considered a match and therefore start in normal mode.

I'm wondering if this is still necessary, if perhaps this functionality has since been added to evil by way of some opt-in flag and I wasn't aware.

If not, I'm wondering if something like this can be added (again, in an opt-in manner if necessary).

Here's the code:

``` elisp
  (defun my-evil--real-function (fun)
    "Figure out the actual symbol behind a function.
Returns a different symbol if FUN is an alias, otherwise FUN."
    (let ((symbol-function (symbol-function fun)))
      (if (symbolp symbol-function)
          symbol-function
        fun)))

  (defun my-evil--derived-mode-p (mode modes)
    (let ((parent (my-evil--real-function mode)))
      (while (and parent (not (memq parent modes)))
        (setq parent (my-evil--real-function (get parent 'derived-mode-parent))))
      parent))

  (with-eval-after-load 'evil-core
    (defun evil-initial-state (mode &optional default)
      "Return the Evil state to use for MODE.
Returns DEFAULT if no initial state is associated with MODE.
The initial state for a mode can be set with
`evil-set-initial-state'."
      (let (state modes)
        (catch 'done
          (dolist (entry (nreverse (evil-state-property t :modes)) default)
            (setq state (car entry)
                  modes (symbol-value (cdr entry)))
            (when (or (memq mode modes)
                      (my-evil--derived-mode-p mode modes))
              (throw 'done state)))))))
```

**Comment by wasamasa** [comment]
Yes, that code is mine and no, nothing of the sort has been integrated.  Personally, I'd prefer seeing a better approach to this, like by using hooks to set initial states (which works for minor modes, but not for major ones as Evil is activated afterwards...).  The above approach is significantly hackier as seen in https://github.com/Malabarba/paradox/issues/86.

**Comment by wasamasa** [comment]
Closing in favor of #497.

**Comment by VanLaser** [comment]
I have to say I still like this solution the best, and was looking for it as I also remembered seeing this code at Bitbucket. Wouldn't it be possible just to break the (improbable) "endless loop" case by limiting the  to some reasonable number? (assuming I understood the problem)

**Comment by VanLaser** [comment]
>  Personally, I'd prefer seeing a better approach to this, like by using hooks to set initial states

@wasamasa Something like this perhaps? (Of course, just a demo) Derived mode hooks run after the parent ones, so they can override, or not, a buffer-local variable setup by parent, here called `evil-init-state`:

```emacs-lisp
;; this should be done probably in a macro, and create such a hook
;; for all possible evil states (NOTE that evil allows creation of new, custom states)
(defun evil--start-in-emacs-state-hook ()
  (set (make-local-variable 'evil-init-state) 'emacs))
(defun evil--start-in-normal-state-hook ()
  (set (make-local-variable 'evil-init-state) 'normal))
(defun evil--start-in-insert-state-hook ()
  (set (make-local-variable 'evil-init-state) 'insert))
;; etc.

;; the following should be wrapped in a convenience function/macro
;; (`evil-set-initial-state' ?)
;; that removes all other evil--start-in-* hooks, then adds the right hook
;; for the specified `mode' and `state' arguments. For now, demo:

;; install hooks that set the desired initial state for the mode, *and* its
;; derived modes, unless a derived mode overrides the local value.

;; demo: all programming modes start in normal state
(add-hook 'prog-mode-hook     #'evil--start-in-normal-state-hook)
;; c modes (derived from ^) start in emacs state
(add-hook 'c-mode-common-hook #'evil--start-in-emacs-state-hook )
;; but c++ (derived from ^) starts in insert state
(add-hook 'c++-mode-hook #'evil--start-in-insert-state-hook)

;; finally, the function `evil-initial-state' should check if the mode
;; has a valid `evil-init-state' local variable and use it. For demo purposes,
;; I'm using an advice instead:

(defun evil--around-evil-initial-state (fun &rest args)
  (let ((res (apply fun args)))
    (if (and (boundp 'evil-init-state) evil-init-state)
	evil-init-state
      res)))

(advice-add 'evil-initial-state :around #'evil--around-evil-initial-state)



```

**Comment by wasamasa** [comment]
If I understand correctly, your goal is to mark a buffer so that Evil can pick up the intended initial state when it's initialized.  This might indeed be a solution to the above problem.  Aborting a loop by checking whether it has been run too often is an ugly solution, but would allow to abort with an error so that the user knows what went wrong.  I'd accept a PR that applies both to Evil proper.

I only wish you posted your comment in the other thread because I'll surely miss it when digging this issue out again ._.
