### ISSUE TITLE
:reg not working after I used shell-pop

### ISSUE THREAD

**Issue by wginolas** [emacs-evil/evil#781]
Hi,

I get the following error when I use the :register command after I use the shell-pop package:

    sort: Wrong type argument: number-or-marker-p, :shell-pop

As far as I understand shell-pop uses the keyword symbol ":shell-pop" as register name in: https://github.com/kyagi/shell-pop-el/blob/master/shell-pop.el#L308

After that evil-register-list (https://github.com/emacs-evil/evil/blob/master/evil-common.el#L2129) fails to sort the registers.

I will try to provide a fix for this issue in the next few days.

**Comment by wasamasa** [comment]
Um, isn't this a bug in shell-pop?  The docstring of `window-configuration-to-register` states that the argument ought to be a character, violating this assumption yields errors when calling `M-x list-registers` with more than one known register.  As the error can be reproduced outside of Evil, I'm closing this issue.

**Comment by wginolas** [comment]
Ah, you are right. Thanks for the clarification.
