### ISSUE TITLE
[help] how to directly apply an evil ex command as a function?

### ISSUE THREAD

**Issue by ninrod** [emacs-evil/evil#783]
Hi. I want to define a command that will run `:'<,'>norm @z` when called. I'm trying this:

```elisp
(defun ninrod/apply-z-macro ()
  (interactive)
  (evil-ex-call-command "'<,'>" "norm" "@z"))
```

but it is not really working and I'm suspecting it is because of the range argument. How would one correctly implement the desired behaviour?

I'm beggining to think I should use the `evil-ex-normal` function, but how would I pass the BEG and END parameters? 

edit: I'm having some success with this:

```elisp
(defun ninrod/apply-z-macro ()
    (interactive)
    (evil-ex "'<,'>norm @z"))
```

But it still places me in ex mode. I have to hit a final `<RET>`. It is already fast, but I'd like to save that last `<RET>` hit.

**Comment by TheBB** [comment]
`(evil-ex-execute "'<,'>norm @z")`

**Comment by TheBB** [comment]
For the record, I mean to use this as an issue tracker, not as an all-in-one help forum as Spacemacs does.

**Comment by TheBB** [comment]
Ah, I was too quick here, sorry about that. You have to create a let-bound environment like `evil-ex` does before you call `evil-ex-execute`. Essentially you want to replicate [this code](https://github.com/emacs-evil/evil/blob/master/evil-ex.el#L176-L195), except you already know what `result` is (your ex code) and you don't need the minibuffer macro either.
