### ISSUE TITLE
evil-jump-item fails in cperl-mode on qq{ .. } qw { .. } qq( ..) qw( .. ), etc

### ISSUE THREAD

**Issue by djstauffer** [emacs-evil/evil#784]
I found this problem while working on some perl code in cperl-mode:

If you place the cursor on the opening paren in this code:

`use List::Util qw(:all);`

... and then press '%' to run `evil-jump-item`, nothing happens.  It's the same story for any of the 'q' type constructs ( `qq{ .. }, qw{ .. }, q{}, qq( ..) qw( .. ),q(), qq[ ..], qw[ .. ]`, q[ .. ] -- you get the idea).

When you do this in vim, the cursor advances to the matching paren/bracket, as you would expect.

**Comment by djstauffer** [comment]
OK, well "nothing happens" is not entirely accurate.  You will get the message "No matching item found on the current line" in the echo area.

**Comment by wasamasa** [comment]
This has most likely to do with the fact that in Perl, `qw(` is the string starter.  If you try using `%` on `"(:all")`, things work as expected as the parentheses are not what starts the string.  You'll notice the same happening with non-Evil stuff, such as parentheses highlighting with `show-parens-mode` (doesn't even consider `qw(` an opening paren), `show-smartparens-mode` (considers `qw(` an unmatched paren) and generic Emacs movement (try `C-M-n`).  In other words, there is an underlying reason for all of these to fail and it has to do with syntax tables, something Vim lacks.

However Evil's check for whether failure to find a matching paren with syntax table powered functions (`scan-lists`, `forward-list`, `backward-list`) looks at whether something is (according to syntax tables) of string nature, but fails utilizing this information and instead relies on `(bounds-of-thing-at-point 'evil-string)`.  I'll have to investigate into that unused variable.

**Comment by djstauffer** [comment]
Yeah, I figured this boiled down to the way emacs was parsing the file (and that syntax tables would be involved).  If I had the time I might try to do a deep dive on the code and see if I could figure out how to work around it.  But presently that isn't possible.

**Comment by wasamasa** [comment]
Note that the thing you have to take a deep dive into is `cperl-mode.el` and `syntax.c`, not Evil.  It appears it sets a syntax property of string fence on the string starter, whatever that may be...

**Comment by wasamasa** [comment]
Closing as this cannot be reproduced with evil-matchit.
