### ISSUE TITLE
Paradox commit-list integration

### ISSUE THREAD

**Issue by blaenk** [emacs-evil/evil#789]
I use [Paradox](https://github.com/Malabarba/paradox) which allows one to press `l` on a package to see its commit list ([source here](https://github.com/Malabarba/paradox/blob/master/paradox-commit-list.el)). It's nice to be able to get a summary of the changes since the last update.

When I do so on `evil`, I get a message saying `Package nil is not a GitHub repo`. I figured perhaps setting the repository url (if there is such a thing) in the melpa recipe.

I'm not sure if it's an issue in Paradox or in evil's Melpa recipe or something. This happened before the transition to GitHub but at that time I attributed it to the obvious, that it wasn't a GitHub repo.

cc @Malabarba

**Comment by blaenk** [comment]
It seems like the GitHub metadata is pulled from a pre-compiled source that's hosted here:

https://raw.githubusercontent.com/Malabarba/paradox/data/data-hashtables

I notice it doesn't include evil, so either the data is outdated or possibly the program that constructs that data is missing evil because it lacks some information that would make it stand out as a GitHub repo.

**Comment by blaenk** [comment]
It seems like that data is computed from the melpa recipes data found [here](https://melpa.org/recipes.json) which does contain repo information, so I suspect it's simply a matter of Paradox' data not being updated. I'll close this and raise an issue there.

**Comment by Malabarba** [comment]
Yes. Paradox data is, unfortunately, quite outdated. I need to setup a server somewhere to update it.
