### ISSUE TITLE
Disabling reusage of evil scroll count

### ISSUE THREAD

**Issue by wasamasa** [emacs-evil/evil#790]
Reported on the [Emacs Stackexchange](http://emacs.stackexchange.com/questions/31236/disabling-reusage-of-evil-scroll-count):

> If evil-scroll-line-down is not given a count argument, the last count is used. This is not the behaviour of vim, which scrolls one line if no count is specified. How can I get vim behaviour?

In fact, if you use `:help CTRL-E` in Vim, it says nothing about retaining the last count.  I'm considering to just remove the special treatment and make the respective commands take an `(interactive "p")` spec to fill in the argument.  This would make https://github.com/emacs-evil/evil/pull/782 and https://github.com/emacs-evil/evil/issues/778 obsolete.

**Comment by TheBB** [comment]
How about a compromise, make it configurable? I love to be able to scroll a bit more than one line with these functions.

**Comment by wasamasa** [comment]
An even more generic way would be a command that repeats the last motion.  There are several Vim plugins trying to give you this, but in Evil we'd have the ability to do that with everything declared a motion.
