### ISSUE TITLE
Making Evil installable from MELPA Stable

### ISSUE THREAD

**Issue by wasamasa** [emacs-evil/evil#792]
While MELPA Stable does have tagged releases of Evil, installing it fails currently as the dependencies cannot be satisfied.  Evil depends on two packages, `undo-tree` and `goto-chg`.  `undo-tree` has been taken care of as its author uses a self-hosted Git repository and [pushes tagged versions to GNU ELPA](http://elpa.gnu.org/packages/undo-tree.html).

`goto-chg` on the other hand is more of a problem.  Its author gifted it and `key-chord.el` to the world via EmacsWiki, hence why it is installable via regular MELPA, but not MELPA Stable.  Solving this issue would allow to close https://github.com/emacs-evil/evil/issues/458 and inform MELPA about it at https://github.com/melpa/melpa/pull/2262 and https://github.com/melpa/melpa/issues/2813.  I can think of the following solutions:

1. Contact the author and convince them to either host the package themselves and ensure tagged releases make it to MELPA Stable or GNU ELPA or pass over hosting to us so that we can do it.  I've contacted the author two weeks ago and got no answer yet.  Judging from https://github.com/melpa/melpa/pull/2262#issuecomment-66738265 the author considers this problem solved as [they've pushed a release to Marmalade](https://marmalade-repo.org/packages/goto-chg).
2. Fork from the version as found on Marmalade and host it along with our own repositories, therefore making `emacs-evil/goto-chg` the canonical source for the package.  The problem with this is that we wouldn't have the author's approval and might therefore not have MELPA's approval either to change the recipe to point at our repository.
3. Vendor the package.  The sources do already have a `lib/` directory, intended to be used by tests and people who want to use Evil without package.el.  We'd therefore move the package into the project root and update it from Marmalade while we're at it.  We still have no approval from the author and risk getting out of date if they ever resurface, but at least there's no disapproval from MELPA involved.  Another downside is that while Evil is the only package depending on it, there may be other users of it.  If MELPA decides to remove goto-chg from their package listings, that would upset these users.
4. Rewrite the package based on observation of its behavior and include that clean-room implementation into Evil.  Massively overkill if you ask me, but that way nobody would be inconvenienced.

@TheBB @therockmandolinist @purcell @milkypostman What do you think?

**Comment by ninrod** [comment]
I think That if 1) does not work, 4) would the an ideal solution as goto-chg does not seem to require to many lines of code.

**Comment by TheBB** [comment]
I'm thinking we vendor it, but move all the names under the evil namespace, to avoid conflicts with other potential users of the package. Seems to me the solution with the fewest question marks.

**Comment by purcell** [comment]
Can `evil` use [goto-last-change.el](https://github.com/camdez/goto-last-change.el/blob/master/goto-last-change.el) instead?

Otherwise, regarding the options you outlined, (1) is obviously the best option, and if the author is unresponsive, I'm happy to point MELPA at a fork that you all will actively maintain. Don't vendor it, don't add prefixes if you fork it.

**Comment by edkolev** [comment]
It could be my own setup, or could be caused by undo-tree, but `g ;` / `g ,` work so unreliably for me, they're almost useless.

Hence, a rewrite seems like an option for me. And maybe the rewrite should use `buffer-undo-tree` instead of `buffer-undo-list`

**Comment by wasamasa** [comment]
@purcell `goto-last-change.el` does only provide backward, not forward motion.  Having hooks or using advice would allow us to implement that by setting up a buffer-local "change list" and cursor, append entries to it as one jumps to the last change, then traverse these backwards if one jumps to a more recent change.

@edkolev Ouch.  A rewrite based on `goto-last-change.el` would be the least risky option, as outlined above.  Could you try out whether that package works better for you in terms of jumping to the last changes?

**Comment by edkolev** [comment]
I used `goto-last-change.el` today but it doesn't work much differently. I often got this error:
`Invalid undo entry: undo-tree-canary`  (https://github.com/camdez/goto-last-change.el/blob/master/goto-last-change.el#L119)

I would typically get it after saving the file and trying to `g ;`. I could try to come up with solid steps to reproduce this in case that would be useful.

I have a hunch that undo-tree is mistreating `buffer-undo-list`.

**Comment by wasamasa** [comment]
@edkolev Let's just say that undo-tree is doing weird things with `buffer-undo-list`.  I used to get that error when using it with a persistent undo file and went away from that.  From then on, I no longer got the error.

**Comment by wasamasa** [comment]
@edkolev I've analyzed the problems in undo-tree and wrote its author a lengthy mail about my findings and possible fixes.  We might very well get this fixed once and for all, but it's likely that `goto-last-change.el` would need to get adjusted as well.

**Comment by edkolev** [comment]
Thanks for looking into this!

Maybe the author could give some general guidelines on how to do this, like is it even possible to implement something like `undo-tree-goto-last-change` without modifying the core of undo-tree.

**Comment by wasamasa** [comment]
I have an idea how and am currently talking it out with undo-tree's author.

**Comment by wasamasa** [comment]
Fixed as Evil can be installed from MELPA Stable.

**Comment by agsdot** [comment]
Cool! Evil can be installed from melpa stable, now that both dependencies of undo-tree and goto-chg are under git version control and are no longer on emacswiki.

Question though. Won't Melpa Stable as of October 1, 2017, install Evil 1.2.12? That tag (1.2.12) looks like it correspond to a date on the "[Stable](https://github.com/emacs-evil/evil/tree/stable)" branch of Evil.

@wasamasa , should the Stable branch on github.com/emacs/emacs-evil be updated to another tagged version? Not sure where you want it "synced" up with master. At the present commit or a previous commit on master, but Stable 1.2.12 is from April 4, 2016, quite outdated.

Thanks!

**Comment by wasamasa** [comment]
@agsdot It will, yes.  @TheBB planned on making a 1.2.13 release and I don't plan on interferring with his plans.

**Comment by agsdot** [comment]
Cool! Thanks @wasamasa and @TheBB. Was scanning stable.melpa.org and was wondering why evil looked seemingly out of date.

Great seeing all the progress on evil and the other github.com/emacs-evil/ projects since your team took over. 

:+1:

**Comment by TheBB** [comment]
Sorry guys, I'm reading the comments but not much else. Since it seems to me there aren't any significant outstanding issues, I'll cut a release tomorrow.

**Comment by agsdot** [comment]
:+1:

**Comment by TheBB** [comment]
1.2.13 is out

**Comment by agsdot** [comment]
@TheBB nice!

Should the stable branch be updated as well to 1.2.13, or is the stable branch no longer being used?

**Comment by wasamasa** [comment]
It's most definitely stale and to be honest, the workflow of tagging a suitable commit on master and pushing a tag is much less involved.
