### ISSUE TITLE
copy-from-{above,below} doesn't respect replace-state

### ISSUE THREAD

**Issue by ivanbrennan** [emacs-evil/evil#794]
In vim, copying from above (C-y) or below (C-e) while in replace mode does what you'd expect: replace the current character with the character directly above/below it. In evil-replace-state, however, calling evil-copy-from-{above,below} *inserts* the character, pushing subsequent text over to make room. This defeats the purpose of replace mode, and is actually a workflow I use frequently.

To repro, start emacs with this minimal init file:
```emacs-lisp
(require 'package)
(setq package-archives '(("gnu"   . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)
(require 'evil)
(evil-mode)
```

Insert the following text in the scratch buffer:
```emacs-lisp
'abc
'xyz
```

Then, with point before the *x* in *xyz*, enter evil-replace-state and call evil-copy-from-above. The result:
```emacs-lisp
'abc
'axyz
```

**Comment by ivanbrennan** [comment]
I've written a quick and dirty workaround, but I'm not familiar with the internals of evil-replace-state so I don't know that it covers all cases. It has worked for me so far, though.

```emacs-lisp
(defun evil-consume-next-char-if-replacing (&rest _args)
  (when (evil-replace-state-p)
    (delete-char 1)))

(advice-add 'evil-copy-from-above :after #'evil-consume-next-char-if-replacing)
(advice-add 'evil-copy-from-below :after #'evil-consume-next-char-if-replacing)
```

**Comment by wasamasa** [comment]
Ugh, you've reminded me that `self-insert-command` [is special](http://emacshorrors.com/posts/self-insert-command.html).  One of the special things it does is implementing `overwrite-mode` which is what Evil reuses for replace state.  So, unless Evil uses `self-insert-command` to insert the character from above, replace state won't work perfectly.

Not sure whether it's better to reinvent it (and keep using `insert`) or to coerce these commands into using `self-insert-command` to handle this perfectly.

**Comment by ninrod** [comment]
Good one. I did not even know that this existed.
