### ISSUE TITLE
insert-state-bindings: complete-{next,previous}-line not bound

### ISSUE THREAD

**Issue by ivanbrennan** [emacs-evil/evil#799]
I've been trying to figure out why `C-x C-n` and `C-x C-p` aren't bound to evil-complete-next-line and evil-complete-previous-line, despite appearing as such in [evil-insert-state-bindings](https://github.com/emacs-evil/evil/blob/d36020ee5f4e82cee08dbaa5a2f82e32e45195f1/evil-maps.el#L362-L363).

To repro:
- start Emacs with this minimal init.el
```emacs-lisp
(require 'package)
(package-initialize)
(require 'evil)
(evil-mode +1)
```
- `C-x b RET` (switch to scratch buffer)
- `i` (evil-insert)
- `C-h c C-x C-n` (run describe-key-briefly on `C-x C-n`)
  - Emacs reports that `C-x C-n` is bound to set-goal-column

I found the cause in [evil-update-insert-state-bindings](https://github.com/emacs-evil/evil/blob/d36020ee5f4e82cee08dbaa5a2f82e32e45195f1/evil-maps.el#L376), which uses `lookup-key` to check whether each key is already bound and avoid clobbering the user's custom bindings. The [following line](https://github.com/emacs-evil/evil/blob/d36020ee5f4e82cee08dbaa5a2f82e32e45195f1/evil-maps.el#L399) doesn't behave as expected for `C-x C-n` and `C-x C-n`:
```emacs-lisp
(null (lookup-key evil-insert-state-map (car binding)))
```
The lookup-key expression evaluates to `1`. From the lookup-key documentation:
> A number as value means KEY is "too long"; that is, characters or symbols in it except for the last one fail to be a valid sequence of prefix characters in KEYMAP. The number is how many characters at the front of KEY it takes to reach a non-prefix key.

This is telling us that `C-x` is not a valid prefix key in evil-insert-state-map. The null-check misinterprets this non-nil value as an indication that the key is bound.

I've worked around this by adding the following to my init.el:
```emacs-lisp
(define-prefix-command 'evil-completion-map)
(add-to-list 'evil-insert-state-bindings
             '("\C-x" . evil-completion-map))

(evil-update-insert-state-bindings)
```

I'm happy to put up a PR defining evil-completion-map and adding it to evil-insert-state-bindings, if that seems like a reasonable solution. I should mention I'm using Emacs 25.2.1, and have not tried to repro/fix on other versions.

**Comment by wasamasa** [comment]
Is this possibly related to https://github.com/emacs-evil/evil/pull/785?  Please test whether this PR fixes it for you.

**Comment by ivanbrennan** [comment]
@wasamasa Indeed, that does fix it. Thanks! Should I close this issue or keep it open as a little extra fire-power for your PR?

**Comment by wasamasa** [comment]
No need to keep it open, but given that PRs may only get merged by someone else than their author, I'd like @TheBB to take a closer look at this one :>

**Comment by ninrod** [comment]
ideally, it should be closed when the PR is merged, no? Like, if you include "fix #799" in the commit message, then the action of actually merging the PR should auto close this.

**Comment by wasamasa** [comment]
The PR does already close another issue it was created for.  As this one is a duplicate, I see no reason for keeping it open.

**Comment by TheBB** [comment]
I'll get to it, I promise! :-)
