### ISSUE TITLE
Any plan on supporint moving to next/prev match in incremental search with C-g/t

### ISSUE THREAD

**Issue by purpleP** [emacs-evil/evil#800]
I think not a lot of people appreciate this feature, but it's actually very useful. For example

```
some(a, b, some(), some(), some(a, b(), c(), some()))
           ^                               ^
```
First mark is the cursor position and the second one is the place up to which I want to change.

Previously all I could do without using a plugin like easy-motion is to count the number of parens and do a `c4f)`, which is very short, but requires a lot of time to count parens.
Or do `vf);;;c` which is quite fast and repeatable with `.`, but I find the following new way more natural, because of avoiding the visualmode and doing this in more mentally simpler `command,motion` approach.

With this new vim feature I can do this with `c/)C-gC-gC-g`. Would be really cool to this this in evil.

**Comment by wasamasa** [comment]
Could it be that this works out of the box when using `C-s` repeatedly?  Not like I'd want to bind `C-g` anyway as that's been special-cased by Emacs to abort the current operation...

**Comment by purpleP** [comment]
@wasamasa at least not with `evil-search` as for C-g - I don't care about emacs key-bindings. I've already made escape abort almost anything and either I would use emacs with key bindings I want or won't use at all. I thought emacs is about extensibility and customization, you know.

**Comment by wasamasa** [comment]
Well, it works for me with both modes of operation.  Setting `evil-search` does *not* introduce new keys or keymaps, so it's to be expected that isearch's commands continue working normally.

As for customization, sure, feel free to `(define-key isearch-mode-map (kbd "C-g") 'isearch-repeat-forward)` and `(define-key isearch-mode-map (kbd "C-g") 'isearch-repeat-forward)` if you prefer those keys.  The functionality *is* there.

**Comment by purpleP** [comment]
@wasamasa hmm... this doesn't do anything for me. `C-g` still aborts search and `C-t` is undefined

**Comment by wasamasa** [comment]
You'll have to bisect your Emacs then.  Alternatively, try `make emacs` from a Git checkout of this repository, it will give you a minimal Emacs session with only Evil enabled.  From there on, I can press `ggwc/f<C-s><C-s><C-s><RET>` and it changes the first line to ";; for Lisp evaluation".

**Comment by purpleP** [comment]
I've commented the  `'(evil-search-module (quote evil-search))` and now everthing works as you've said. Are you sure that it works for you with `evil-search` as a search-module?

**Comment by wasamasa** [comment]
Hm, looks like I forgot actually enabling it (because I don't use custom.el), so I've never enabled the other search module.  This way it doesn't work at all because pressing `C-s` will search with the *previous* search pattern and unlike with isearch, the current one is only saved into the `evil-ex-search-pattern` variable once you've finished entering it.  I guess this calls for a separate issue because it's no longer about incremental search (aka isearch), but Evil's replacement for it.
