### ISSUE TITLE
`evil-delete-backward-word` (C-w in insert state) copies the deleted text, unlike in vim

### ISSUE THREAD

**Issue by braham-snyder** [emacs-evil/evil#801]
Setting the `nil` at the very end of its definition (below) to the black hole register, `?_`, seems like the simplest fix.

```
(evil-define-command evil-delete-backward-word ()
  "Delete previous word."
  (if (and (bolp) (not (bobp)))
      (progn
        (unless evil-backspace-join-lines (user-error "Beginning of line"))
        (delete-char -1))
    (evil-delete (max
                  (save-excursion
                    (evil-backward-word-begin)
                    (point))
                  (line-beginning-position))
                 (point)
                 'exclusive
                 nil)))
```

I suppose the current behavior is consistent with `backward-kill-word`, but this isn't deliberate, is it?

**Comment by wasamasa** [comment]
Well spotted!  I reckon using `evil-delete` makes no sense if the result isn't saved in a register, so the proper patch would involve `delete-region`.
