### ISSUE TITLE
Evil search and clear across multiple buffers

### ISSUE THREAD

**Issue by naclander** [emacs-evil/evil#803]
In vim, searching for a keyword causes that keyword to highlight both in the current active buffer, as well as other buffers. 

In Emacs, matching words highlight on the current active buffer, but a user has to manually switch to another buffer and press `n` ( to search forward ) for matches to become highlighted. 

Evil should behave the same way as vim, and highlight all matches across all buffers automatically. This could be extended by giving users the ability to choose whether to highlight just the current buffer, all buffers in the current frame, or all buffers completely. 

Naturally, `evil-ex-nohighlight` should clear all matches across all buffers. Or again, the user should have the ability to toggle this.

**Comment by wasamasa** [comment]
For the record, this is not vanilla Vim behavior and requires `set hlsearch`.  Similarly, getting this in Evil requires customizing `evil-search-module` to `evil-search` which gives you persistent search highlights for the current buffer which can be cleared with `:nohl` and customized with `evil-ex-search-persistent-highlight`.  If you want it to be extended to highlight beyond the current window, please open a more specific issue for that.

**Comment by naclander** [comment]
My wording may have been unclear, as I'm jumping between emacs/evil and vim nomenclature. 

I am using the `evil-search-module` like you said. Likewise, I have evil-ex-search-persistent-highlight set to true.

The situation I was describing is when I have multiple split buffers open in a single frame ( a single window? Not sure about naming here ), if I search for a word in one buffer, I want it to also highlight across all the split buffers I am looking at. 

So either I am misunderstanding your explanations to my problem or my issue is as you said, "[highlighting] beyond the current window'

**Comment by kyrias** [comment]
That is exactly what you asked for yes, having the search results highlighted in other windows.
