### ISSUE TITLE
How to handle shadowed bindings on some modes?

### ISSUE THREAD

**Issue by LaloHao** [emacs-evil/evil#812]
Im trying to enable these keys for `rjsx-mode'
```emacs
C-d             rjsx-delete-creates-full-tag
  (that binding is currently shadowed by another mode)
<               rjsx-electric-lt
  (that binding is currently shadowed by another mode)
```

`<` works without defining anything even if it says `shadowed`, but `C-d` doesnt work at all 

```emacs
(evil-define-minor-mode-key evil-insert-state-map 'rjsx-mode (kbd "C-d") 'rjsx-delete-creates-full-tag)
```

using evil 20170323.1140 from MELPA
Thanks in advance

**Comment by wasamasa** [comment]
I'm not sure why you're using `evil-define-minor-mode-key` on a major mode.  I'd try `(evil-define-key 'insert rjsx-mode-map (kbd "C-d") 'rjsx-delete-creates-full-tag)`.  Also, verify whether a binding was successful with `F1 k` in insert state.

**Comment by LaloHao** [comment]
That worked, but for some reason i need to type a space before `C-d` or it deletes char
