### ISSUE TITLE
Feature Request: evil-search-module "search failed" in the style of isearch

### ISSUE THREAD

**Issue by naclander** [emacs-evil/evil#813]
By default, `evil-search-module` is set to `isearc`h. When searching using `isearch` for a match that doesn't exist, `isearch` will highlight the portion of the word that doesn't exist in the minibufffer, helping the user see which part of their search query wasn't found. 

For example, when searching for `"setqq"` the last `"q"` would be highlighted, indicating that `setqq` isn't found but `setq` is. 

When the `evil-search-module` is switched to `evil-search`, typing a search that doesn't exist shows a less helpful `[search failed]` message. 

I think we should keep the same message style as in isearch, as it provides more information about _why_ a search failed, and does so in a cleaner way.

**Comment by wasamasa** [comment]
Not too surprising, after all the purpose of `evil-search` is to provide a search that's closer to what Vim provides.  While emulating its full error catalog is overkill (the real thing displays "E486: Pattern not found: setqq"), I don't see how going towards isearch makes it conform better (with the `C-t`/`C-g` feature being an exception as it's isearch-like, but available in the original as well).

**Comment by naclander** [comment]
@wasamasa When I try to search in vim, and I trype `setqq`  I don't see an error until I press enter. I am specifically talking about not yet pressing return ( only a "live' search ). So what `evil-search` and `isearch` are doing are going above and beyond vanilla vim anyway. 

Since that's the case, I think the `isearch` behavior is more user-friendly, do you disagree? 

If your argument is that `evil-search` should match as close to vim as possible, then it arguably shouldn't be showing any error messages at all until the user presses return to indicate they are done typing their regex search query. 

I agree that we shouldn't emulate the error catalog in full, and I agree that evil should conform to vim as much as possible, but in this case evil is already going beyond what vim provides, so I think this is a reasonable feature request, do you disagree?

**Comment by wasamasa** [comment]
I'm against castration of existing features and against going far and beyond faithful Vim emulation. After all, I'm a maintainer, my job is to know when to say no. Feel free to create a new search combining the best aspects of both Emacs and Vim, just don't expect it to become part of Evil.
