### ISSUE TITLE
Is there a way to make regular expression vim like?

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [emacs-evil/evil#814]
In vim, the digit in regex is replaced by `\d`
In emacs, it is uncomfortable to use `[[:digit:]]`
Could make emacs regex a vim like?

**Comment by therockmandolinist** [comment]
@earthIsAPrisonIfYouNotAwareItCanNotOut Note `[0-9]` is less to type and also accepted.

**Comment by wasamasa** [comment]
Sure, customize `evil-search-module` to `evil-search` and `evil-ex-search-vim-style-regexp` to `t`, that allows searching for `\d` and getting a number to match.

**Comment by blahgeek** [comment]
> Sure, customize `evil-search-module` to `evil-search` and `evil-ex-search-vim-style-regexp` to `t`, that allows searching for `\d` and getting a number to match.

Is there any reason these settings are not default? Shouldn't we try to provide a vim-like experience by default?

**Comment by wasamasa** [comment]
It has its costs to enable that feature as it's slower than vanilla and may expose new bugs.
