### ISSUE TITLE
Settings not being respected in use-package

### ISSUE THREAD

**Issue by legendre6891** [emacs-evil/evil#815]
I have the following piece of code in my `init.el`. 
```
(use-package evil
    :ensure t

    :init
    (progn
      (setq evil-ex-search-vim-style-regexp t
            evil-symbol-word-search t
            evil-want-C-u-scroll t
            evil-want-Y-yank-to-eol t))

    :config
    (progn
      (evil-mode t)
      (evil-escape-mode)))
```

However, none of the settings (e.g. `evil-want-C-u-scroll`, `evil-want-Y-yank-to-eol`) are being respected. More precisely, when I check the variable names using `C-h v`, the symbols values are being set; however, the behavior of `Y`, and `C-u` are still the defaults. 

I did some debugging and found that these settings *must* be set using Customize instead of in the init file. Is this intended behavior?

**Comment by therockmandolinist** [comment]
I set these in use-package as described here just fine. One thing I will say is I don't use `progn`, as you don't actually need to for use-package. But it''s odd that you say the variables are set yet behavior isn't following them...

**Comment by edkolev** [comment]
I don't see an issue with the posted config, I would suggest looking for the problem someplace else in your config, e.g. check the Messages buffer or binary-search your init.el file for issues.

This is what I have, you can see how to get rid of the progns, but having them isn't the issue in my opinion
```emacs-lisp
(use-package evil
  :ensure t
  :init
  (setq evil-search-module 'evil-search)
  (setq evil-ex-complete-emacs-commands nil)
  (setq evil-vsplit-window-right t)
  (setq evil-split-window-below t)
  (setq evil-shift-round nil)
  (setq evil-want-C-u-scroll t)
  (setq evil-maybe-remove-spaces t)
  :config
  (evil-mode)
  ;; ......
)
```

**Comment by wasamasa** [comment]
This isn't as much of an Evil problem as invalid use-package usage.

**Comment by VanLaser** [comment]
> I did some debugging and found that these settings must be set using Customize instead of in the init file. Is this intended behavior?

*Only* if evil is already loaded when you set them. So perhaps evil somehow gets loaded before your `use-package evil` ... code (maybe another package requires it).
