### ISSUE TITLE
"dw" is an unknown command

### ISSUE THREAD

**Issue by jtpavlock** [emacs-evil/evil#816]
I'm going through evil-tutor and I get to the part where it says to type  `dw` to delete a word.

However, `dw` returns "unknown command". Is this expected behavior? I'm extremely new to Vim and Evil. 

Here's what I have in my config:

       (use-package evil
       :chords
       (("jk" . evil-normal-state))
       :config
       (evil-mode t))

**Comment by wasamasa** [comment]
Does this only happen with evil-tutor?  If yes, this isn't an issue with Evil and ought to be reported in their repository instead.

**Comment by jtpavlock** [comment]
It happens outside of evil-tutor as well.

Starting with a fresh init.el i.e. it only contains
'(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)'

and then trying to 
' M-x package-refresh-contents
  M-x package-install RET evil'

I can't even find evil in the list of packages to install it

**Comment by wasamasa** [comment]
That could be the fault of not using the HTTPS URL or your the refreshing step not being successful.  Whatever the problem is, it sounds like something more fundamental than Evil is broken for you.

**Comment by jtpavlock** [comment]
downloading through git with
`git clone https://github.com/emacs-evil/evil`
and installing with
```
(add-to-list 'load-path "~/.emacs.d/evil")
(require 'evil)
(evil-mode 1)
```
yields the same `dw` issue as before. I think you may be right there's a more fundamental issue here, but I wish I knew how to track it down.

**Comment by jtpavlock** [comment]
just to add some information, when I try and tab complete `:d` to see possible commands I get

```
Possible completions are:
d 	delete 	delm
delm! 	delmarks 	delmarks!
```

**Comment by wasamasa** [comment]
If you've gone as far as cloning Evil's repository, you might as well run `make emacs` from the directory and test in there.  Also, just to make sure, what is your Emacs version (as reported by `M-x emacs-version`) and operating system?

**Comment by jtpavlock** [comment]
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-17 on lgw01-04, modified by Debian

and 

Ubuntu 16.04.2 LTS

make emacs is giving me the same behavior

**Comment by wasamasa** [comment]
I'm sorry if this sounds ridiculous, but are you actually pressing `d` and `w` in normal state?  What you've described sounds as if you're trying to execute `:dw` which will fail, as that's not a valid ex command.

**Comment by jtpavlock** [comment]
remember when I said I was extremely new to vim? I was under the impression dw was like an emacs command that you had to execute in an `M-x` i.e. `:` interface.

This is huge. Also, I'm retarded.

Thanks for putting up with me through this
