### ISSUE TITLE
Using logical lines for <num>j and <num>k

### ISSUE THREAD

**Issue by zhiwei-nu** [emacs-evil/evil#817]
I use `evil-next-visual-line` for normal navigations, but sometimes i do `5j` to move up 5 lines, for example but it only counts visual lines. 

In Vim, I can do this:
```
" Prevents us from moving irregularly for soft-wrapped lines
nnoremap <expr> j v:count ? 'j' : 'gj'
nnoremap <expr> k v:count ? 'k' : 'gk'
```

I have mapped the relevant keys as below: 
```
  (define-key evil-motion-state-map "j" 'evil-next-line)
  (define-key evil-motion-state-map "k" 'evil-previous-line)
  (define-key evil-operator-state-map "j" 'evil-next-line)
  (define-key evil-operator-state-map "k" 'evil-previous-line)
  (define-key evil-normal-state-map "j" 'evil-next-visual-line)
  (define-key evil-normal-state-map "k" 'evil-previous-visual-line)
```
This works for operators (like `d5j`) but not for motions.

Is there any way to get this to work? Thanks in advance!

**Comment by wasamasa** [comment]
The mappings look somewhat bogus to me.  Adding a binding for motion state and normal state doesn't make a difference unless you've customized a mode to start in motion state.  Customizing operator state shouldn't be needed either.

The way to solve this is by writing your own command and binding it:

```elisp
(evil-define-motion my-evil-next-line (count)
  (interactive "P")
  (let ((command (if count 'evil-next-line 'evil-next-visual-line)))
    (setq count (prefix-numeric-value count))
    (funcall command count)))

(define-key evil-motion-state-map (kbd "j") 'my-evil-next-line)
```

**Comment by zhiwei-nu** [comment]
@wasamasa i tried this, but it messes up other commands, so actions like `d5j` will have very different behavior

**Comment by wasamasa** [comment]
Works fine for me.  You'll have to be more specific than "messes up other commands".

**Comment by zhiwei-nu** [comment]
@wasamasa Thanks for responding! So to elaborate, one issue is that when i do `d<num>j`, for example, it deletes from where my cursor is instead of the start of line:

![image](https://cloud.githubusercontent.com/assets/27188482/25554805/a83efa2c-2d09-11e7-8da6-0268729abebe.png)

with this config:
![image](https://cloud.githubusercontent.com/assets/27188482/25554810/be152fce-2d09-11e7-88a2-36607484bd97.png)

It's worse when commenting out things:
![image](https://cloud.githubusercontent.com/assets/27188482/25554828/1c3260d6-2d0a-11e7-8ee1-42c3c5854158.png)

![image](https://cloud.githubusercontent.com/assets/27188482/25554831/2d7559ca-2d0a-11e7-87d5-6fa7848fd7a6.png)

Would you happen to know what causes this?

**Comment by wasamasa** [comment]
Looks like it's only calling `evil-next-visual-line` for you which shouldn't be the case if only the proposed function is used.  Perhaps you still have other bindings active from previous customization attempts?  Please try reproducing with a minimal init file.

**Comment by zhiwei-nu** [comment]
You can take a look at the  [config](https://github.com/zweicoder/dotfiles/blob/test-evil-line-motion/.spacemacs), I've stripped down most things and still have the same issue.

**Comment by zhiwei-nu** [comment]
From what I observed, the `command` is correct, but it seems things go wrong when we call the function. Just to test it out i put `(if count 'evil-next-line 'evil-next-line)`, and the result was the same.

**Comment by wasamasa** [comment]
Yeah, no, I won't debug Spacemacs for you. What I had in mind was something very close to `emacs -Q`, like what you get when running `make emacs` from inside a Git checkout of this repository.

**Comment by zhiwei-nu** [comment]
Solved. The fix was to put `:type line`, like so:
```
  (evil-define-motion my-evil-next-line (count)
    :type line
    (let ((command (if count 'evil-next-line 'evil-next-visual-line)))
      (message (symbol-name command))
      (funcall command (prefix-numeric-value count))))
```
