### ISSUE TITLE
how to use :norm

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [emacs-evil/evil#819]
sometimes it is conveniently to type normal command `(:norm)` ~~in global command `(:g)`~~
as this example:
<pre><code>
use File::Basename;
my $name = "/usr/local/bin/perl";
my $basename = basename $name;  # gives 'perl'

v

use File::Basename;
my $name1 = "/usr/local/bin/perl";
my $basename1 = basename1 $name1;  # gives 'perl'

</pre></code>
how do with this code by evil?

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
Sorry for the wrong title
this code is meant to search `$name | $basename`
then use normal command `A1` to add digit 1

**Comment by wasamasa** [comment]
I still don't see any actual example usage (as in, keystrokes you hit).  I don't see how `A1` would add a digit at the end of the word, as `A` goes to the end of the line.  Please post something that's actually executable in Vim, then I can see whether it is implemented in Evil or if not, how it could be enhanced to support this usecase.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
It let my IQ offline
but I find the solution in :s 
`:%s/\v(base)?name/&1/g`
thanks for patient reply
