### ISSUE TITLE
evil-search-next gets stuck when searching for newlines

### ISSUE THREAD

**Issue by oskarkv** [emacs-evil/evil#823]
OS: Linux Mint
Emacs version: 24.5.1
Evil version: f0684c1f6644a8c4e0e5fce50a1a04796555eaf1
Running GUI in X.

# Steps to reproduce.

1. `make emacs`
2. (All tests pass.)
3. In a buffer with
```
line1
line2
line3
```
4. Search for a newline with `/ C-q C-j RET`. Press `n` several times. Press `N` several times.

# Observed behavior

The cursor gets stuck on the first match when using `n`, i.e. pressing `n` again does not move on to the next match. But `N` works as expected.

Setting `evil-search-module` to `evil-search` via the customization interface fixes the problem.

**Comment by justbur** [comment]
I think this is a bad interaction with `evil-move-beyond-eol`. 

Try 

```elisp
(setq evil-move-beyond-eol t)
```

**Comment by oskarkv** [comment]
> (setq evil-move-beyond-eol t)

Yes, that works.
