### ISSUE TITLE
Can't replace newlines with :s

### ISSUE THREAD

**Issue by oskarkv** [emacs-evil/evil#824]
OS: Linux Mint
Emacs version: 24.5.1
Evil version: f0684c1f6644a8c4e0e5fce50a1a04796555eaf1
Running GUI in X.

# Steps to reproduce.

1. `make emacs`
2. (All tests pass.)
3. In a buffer with
```
line1
line2
line3
```
4. Try to replace the newlines with the character a, by pressing `:%s/ C-q C-j /a/ RET`.
5. Observe the preview before pressing `RET`.

# Observed behavior

The preview is wrong. It looks like only the newlines after `line1` and `line3` (but not `line2`) are going to be replaced. When pressing `RET`, nothing changes, i.e. the buffer remains unchanged. Emacs says "Replaced 0 occurrences".

**Comment by justbur** [comment]
I think this one is a problem with the bounds on the line by line search. I'm submitting a PR that fixes it.

**Comment by oskarkv** [comment]
Apparently it works with the `g` flag. But I think it should work without. It does in Vim. And the preview is still wrong without `g`.

**Comment by justbur** [comment]
@oskarkv Try #825

Yes, when the g flag is used the replacements are performed according to a different function. It's the line by line changes that had a bug in them.

**Comment by oskarkv** [comment]
It works, but the preview is still wrong. It only shows every second replacement. Typing that extra g immediately shows all replacements in the preview.

**Comment by justbur** [comment]
Different part of the code. I think I got it now. Try the PR again when you get a chance.

**Comment by oskarkv** [comment]
Yeah, it works. Good job!

**Comment by justbur** [comment]
Here's another problem that I just found and haven't fixed

Start (note extra empty line on last line)
```
[a]bc
def
ghi

```
Command `:%s/\n/Z/`
```
abcZdefZghiZZ
```
Command `:%s/\n/Z/g`
```
abcZdefZghiZ
```

The cause is [here](https://github.com/emacs-evil/evil/blob/master/evil-commands.el#L3347-L3350)

cc @wasamasa

**Comment by wasamasa** [comment]
Looks like the edge case wasn't handled well enough to me.
