### ISSUE TITLE
(evil-next-line 3) does not work in visual line mode, but does in regular visual mode

### ISSUE THREAD

**Issue by oskarkv** [emacs-evil/evil#826]
OS: Linux Mint
Emacs version: 24.5.1
Evil version: f0684c1f6644a8c4e0e5fce50a1a04796555eaf1
Running GUI in X.

# Steps to reproduce.

1. `make emacs`
2. (All tests pass.)
3. Eval `(define-key evil-motion-state-map (kbd "M-S") (lambda () (interactive) (evil-next-line 3)))` (I chose M-S because it isn't used by anything else, as far as I know. Have tried with other keys too.)
4. Open a buffer with multiple lines.
5. Go into visual mode `v`, visual block mode `C-v`, and visual line mode `V`, and try pressing `M-S` in each.
6. Type `:(evil-next-line 3)` while in visual line mode.

# Observed behavior

The key `M-S` works in visual mode and visual block mode, but not in visual line mode. In visual line mode, point does not move, and the visual selection remains intact.

Typing `:(evil-next-line 3)` while in visual line mode works.

`evil-next-visual-line` and the `previous` ones have the same problem.

**Comment by oskarkv** [comment]
I was told I should use `evil-define-motion` for this, and so I did
```
(evil-define-motion 15-lines-down ()
  (evil-next-visual-line 15))
```
And now it works. If that is the intended behavior then close this issue.

By the way, I suggest including the documentation for `evil-define-motion` from [the PDF manual](https://raw.githubusercontent.com/emacs-evil/evil/master/doc/evil.pdf) in the docstring, so it's easily accessible in Emacs.

**Comment by wasamasa** [comment]
> One could perhaps reasonably expect my original attempt to work.

Not really.  Keep in mind that `evil-define-motion` does not only define a command, but also adds metadata to it that is read in by Evil at a different time (like, in visual line mode when deciding what to do with the visual selection).  Defining a plain function will *not* do this and therefore fail behaving as expected.  The specific keyword responsible for correct visual selection behavior is most likely `:keep-visual` as it's used in the `evil-define-motion` macro and mentioned in the commentary above the visual state definition:

> If the command is a motion, the translation is postponed until a non-motion command is invoked (distinguished by the :keep-visual command property).

This also means that you should be able to achieve your goal with `evil-declare-motion` as it sets that metadata.

Documentation fixes are always a good idea, feel free to make a PR for it.
