### ISSUE TITLE
fix docstring of evil-select-inner-object

### ISSUE THREAD

**Issue by ninrod** [emacs-evil/evil#838]
there is no forward or backward named argument for the function `evil-select-inner-object`, 
so, if I'm not mistaken, they should not appear on the [docstring](https://github.com/emacs-evil/evil/blob/master/evil-common.el#L2942-L2951).

```elisp
(defun evil-select-inner-object (thing beg end type &optional count line)
  "Return an inner text object range of COUNT objects.
If COUNT is positive, return objects following point; if COUNT is
negative, return objects preceding point.  FORWARD is a function
which moves to the end of an object, and BACKWARD is a function
which moves to the beginning.  If one is unspecified, the other
is used with a negative argument.  THING is a symbol understood
by thing-at-point. BEG, END and TYPE specify the current
selection. If LINE is non-nil, the text object should be
linewise, otherwise it is character wise."
```

**Comment by ninrod** [comment]
I've hit this while trying to find a fix for #834

**Comment by edkolev** [comment]
In case you have the motivation, you can run `checkdoc` in this file, as well as all the others.

I think it would be nice to have a `make checkdoc` helper which would do this. `make checkdoc` could also be hooked into `make test` so travis would detect such inconsistencies.

**Comment by wasamasa** [comment]
Could this be a copy-paste fail?  I dimly recall a few more of those in the codebase, checkdoc should hopefully catch them.

**Comment by ninrod** [comment]
yep, I ran checkdoc and got this: 

```txt
Buffer comments and tags:  Ok
Documentation style:       85 Errors
Message/Query text style:  Ok
Unwanted Spaces:           Ok
```

but the majority of errors where out of order errors.
