### ISSUE TITLE
cw is equivalent to ce (in vim: ce != cw)

### ISSUE THREAD

**Issue by ninrod** [emacs-evil/evil#840]
# Issue type
- Bug report

# Environment

Emacs version: GNU Emacs 25.2.1 (x86_64-apple-darwin16.4.0, NS appkit-1504.81 Version 10.12.3 (Build 16D32)) of 2017-03-11

Operating System:  macOS Sierra.

Evil version: 1.2.12
Evil installation type: MELPA through use package.
Graphical/Terminal: Graphical
Terminal multiplexer: does not apply. 

# Reproduction steps
- Start Emacs
- open any blank buffer in text-mode.
- now type exactly this:
- cursor is in []. 
```txt
[f]oo bar
```
now type `cw`

# Expected behavior
the buffer should now display:
```txt
bar
```

# Actual behavior
the buffer instead displays:
```txt
 bar # one extra space lingers that should have been deleted
```

# Further notes

vim behaves as expected and deletes that space.

`cw` should be equivalent to `dwi`.

**Comment by wasamasa** [comment]
Cannot reproduce that in Vim, to change including the space I need to use `caw`. Are you sure you're using no extra config?

**Comment by ninrod** [comment]
> Cannot reproduce that in Vim, to change including the space I need to use caw. Are you sure you're using no extra config?

@wasamasa, you are absolutely, right, with `vim -u NONE` the problem vanishes.

now, I thought vim would make `cw` and `dw` equivalent. So actually in vim `ce` is equivalent to `cw`, right?

**Comment by ninrod** [comment]
so the motion `w` behaves differently in `v`, `c` and `d` operations. that's kind of weird. Is there a logic here?

**Comment by Dickby** [comment]
isn't the variable `evil-want-change-word-to-end` exactly for changing this behaviour?

**Comment by ninrod** [comment]
> isn't the variable evil-want-change-word-to-end exactly for changing this behaviour?

@Dickby thank you! this is fantastic info. did not know that this option even existed.
