### ISSUE TITLE
move evil-surround to the emacs-evil org

### ISSUE THREAD

**Issue by ninrod** [emacs-evil/evil#842]
I have @timcharper [blessing](https://github.com/emacs-evil/evil/issues/769#issuecomment-298420311) to move [evil-surround](https://github.com/timcharper/evil-surround) to the evil org. 

How should we go about this?

**Comment by TheBB** [comment]
That's awesome. I have invited you to the organization. When you accept, I'll create an empty repository called evil-surround for you and give you write access to it. Then you can push it there, change whatever URLs you need to, and then finally go to MELPA and update its build URL.

**Comment by TheBB** [comment]
Of course I can do the migration too, if that's what @wasamasa wants.

**Comment by wasamasa** [comment]
It might be better for @TheBB to do the migration so that issues can be transferred.  The whole point of @ninrod taking over maintainership was to get the package into better shape, no?

**Comment by edkolev** [comment]
As a regular evil-surround user, I'm willing to contribute to evil-surrond.

However, the lack of tests in that repo is a show-stopper for me. For example, `VSb` behaves differently in emacs than in vim -- emacs doesn't indent after surrounding, plus inserts a fake line 4-5 spaces below the newly surrounded line. So far I've preferred to cleanup the spaces and indent myself, rather than deal with a zero-tests repo.

@ninrod let me know if you want help with improving the evil-surround package

**Comment by ninrod** [comment]
folks, this is great news.

Migrating the issues should be useful. if @TheBB can do that, awesome.

@edkolev, by all means please let's write some tests for evil-surround! Yes let's all improve the package! maybe even setup travis and coverage analysis. I don't know how to do that, so it should be fun and I'll learn much elisp in the process.

**Comment by TheBB** [comment]
The easiest way to do this is to get @timcharper to transfer ownership of the repo to us. That will bring issues and PRs along with it. I've sent him an invite to the organization so when he accepts, he will be able to go into the admin page for his own repo and transfer ownership. @ninrod I assume you can ping him to do this.

**Comment by ninrod** [comment]
@TheBB, yes I can ping him. If I understand correctly, he must transfer the ownership of the repo to the github.com/emacs-evil organisation, right?

**Comment by TheBB** [comment]
Yes

**Comment by ninrod** [comment]
@TheBB, @timcharper responded my ping just a few minutes ago. He said this:

> Found the invite; transfer initiated. Thanks!

**Comment by TheBB** [comment]
Excellent, you both have write access automatically I see. Once you have changed the melpa recipe this can be closed then.

**Comment by ninrod** [comment]
awesome! I should be able to work on this soon.

**Comment by ninrod** [comment]
just an update: I have submitted pull [4785](https://github.com/melpa/melpa/pull/4785) to melpa. Just waiting for that to be merged in to close this.

**Comment by ninrod** [comment]
Gentleman, seems that we're live. [#4785](https://github.com/melpa/melpa/pull/4785) is merged in melpa.

**Comment by wasamasa** [comment]
Great!
