### ISSUE TITLE
Searching for substring that an org-mode link contains freezes Emacs

### ISSUE THREAD

**Issue by rieje** [emacs-evil/evil#843]
# Issue type
Bug report

# Environment
Emacs version: 25.2-1
Operating System: Arch Linux
Evil version: 20170531.1149
Evil installation type: MELPA
Graphical/Terminal: X

# Reproduction steps
- Delete everything in emac.d for a fresh install. Create init.el with the following contents:
     
    (require 'package)
    (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
    (package-initialize)
- Start emacs, do the following:
    
    M-x package-refresh-contents
    M-x package-install RET evil
    M-x evil-mode
    C-x C-f <org-file containing a shortcut-link> 
    /<substring of a link that is shortcuted> followed by a letter 

For example, the org-mode has the shorcut link: `[[https://www.reddit.com/r/vim/comments/626no2/vim_without_nerd_tree_or_ctrlp/][file navigation and search]]`. The URL contains the substring `ctrl`, so you search via `/ctrl` and Emacs will hang.

# Expected behavior
Should search for the substring without issues.

# Actual behavior
Emacs freezes until I cancel it via `C-g`.

# Further notes

This issue only seems to affects links are shortcut-hyperlinked (i.e. when org-mode converts the format [[url][name-of-link]] to a clickable name_of_link. Also, if the full url is anywhere else in the document (i.e. not shortcut-linked by org-mode), then you won't have problems searching for the substring.

**Comment by wasamasa** [comment]
Thanks, I can reproduce this one.  After toggling link display with `M-x org-toggle-link-display` the issue disappears, so this suggests that either something is wrong in Evil's wrapper around isearch or Org's hacks to isearch (the sources contain stuff for dealing with invisibility, but it's not obvious whether this applies to folded content only or links as well).

**Comment by Alexander-Shukaev** [comment]
See last workaround for clue: syl20bnr/spacemacs#3623

**Comment by Miciah** [comment]
I made #1070 to fix this issue.  Feedback welcome!

Notes: To reproduce this issue, I had to make sure `evil-search-wrap` was set to `t`, and I had to make sure Evil was using isearch: `(evil-select-search-module 'evil-search-module 'isearch)`.
