### ISSUE TITLE
Suggestion: create a reusable evil-test-helpers package to make testing evil extensions simpler

### ISSUE THREAD

**Issue by edkolev** [emacs-evil/evil#846]
# Issue type

- Enhancement request

I think it would make sense to split `evil-tests.el` into `evil-tests-helpers.el` and `evil-tests.el`and  create a new Melpa package from `evil-tests-helpers.el`. It will contain functions like `evil-test-buffer`.

As a result, evil extensions will be able to reuse the helper functions. Now, I copy-paste parts of `evil-tests.el` to make writing tests easier and consistent with evil itself. Example: https://github.com/edkolev/evil-lion/blob/master/test/evil-lion-test.el#L257

I can prepare a PR (here and in melpa's repo) in case you think this is an improvement.

**Comment by wasamasa** [comment]
Sounds good to me.  I'd be in for this change, as long as `evil-tests-helpers.el` remains in this repository so that Evil itself doesn't need to do anything else than `(require 'evil-tests-helpers)` in its test file.

**Comment by expez** [comment]
I wanted this earlier, I ended up copying what I needed into [evil-smartparens](https://github.com/expez/evil-smartparens/blob/master/tests/evil-tests/evil-tests.el#L12) too.

**Comment by ninrod** [comment]
@edkolev excelent ideia.

**Comment by edkolev** [comment]
https://github.com/emacs-evil/evil/pull/850 is now merged, closing.

**Comment by edkolev** [comment]
As a consequence of #850, the `evil` melpa package now includes evil-test-helpers.el. This is due to the default melpa regex for package files which is:
```
  ("*.el" "*.el.in" "dir"
   "*.info" "*.texi" "*.texinfo"
   "doc/dir" "doc/*.info" "doc/*.texi" "doc/*.texinfo"
   (:exclude ".dir-locals.el" "test.el" "tests.el" "*-test.el" "*-tests.el"))
```

Infesting the official `evil` package with evil-test-helpers.el doesn't seem right to me.

Maybe the file should be renamed to `evil-util-tests.el` so it's not included in the package (it will be matched by `*-tests.el`)? Alternatively, the melpa recipe can be modified.

**Comment by wasamasa** [comment]
I'd modify the recipe to explicitly excluse the helper file.  Less surprises and all that.

**Comment by edkolev** [comment]
OK, I suggest this Melpa recipe:
```emacs-lisp
(evil :repo "emacs-evil/evil"
      :fetcher github
      :files ("evil*.el"
              "doc/*.texi"
              (:exclude "evil*test*.el")))
```

With this recipe, the only difference in the installed files in `.emacs.d/elpa/evil-XYZ` is the `evil-test-helpers.el` file.

Let me know if I should submit this to Melpa.

This is also a good time to revise what goes into the Melpa package, for example Magit packages its COPYING file https://github.com/melpa/melpa/blob/master/recipes/magit

**Comment by wasamasa** [comment]
The proposed recipe looks good, can you post a recipe for the test helpers package, too?  I don't have any opinion on the inclusion of COPYING as every file has a short license hint that refers to it and an URL to the file as fallback.  Therefore it doesn't really matter if you include it.

**Comment by edkolev** [comment]
Sure, here's the proposed test helpers recipe:
```emacs-lisp
(evil-test-helpers :repo "emacs-evil/evil"
                   :fetcher github
                   :files ("evil-test-helpers.el"))
```

**Comment by wasamasa** [comment]
Thanks, this looks good.

**Comment by edkolev** [comment]
FYI this is the recipe for evil now

```emacs-lisp
(evil :repo "emacs-evil/evil"
      :fetcher github
      :files (:defaults
              (:exclude "evil-test-helpers.el")))
```

Relevant changes:
https://github.com/melpa/melpa/pull/4849/commits/7a961d672e8279f2c60ca261b0f11eaee5e9e4c7
https://github.com/melpa/melpa/pull/4849/commits/f0f4874fad07ecd381c882138f3fd8d743ce6839

**Comment by wasamasa** [comment]
Great, does this mean this issue can be closed?

**Comment by edkolev** [comment]
Not yet, there're a few issues that need to be addressed (I just submitted a PR) before the evil-test-helpers package can be accepted in Melpa.

**Comment by wasamasa** [comment]
Feel free to close this then.

**Comment by edkolev** [comment]
The Melpa PR is now merged.
