### ISSUE TITLE
`:%s/$/ foo/g` hangs Emacs

### ISSUE THREAD

**Issue by wasamasa** [emacs-evil/evil#849]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.10) of 2017-04-22
Operating System: Arch Linux
Evil version: HEAD
Evil installation type: manual
Graphical/Terminal: graphical

# Reproduction steps
- Start Emacs
- Open buffer with text
- `:%s/$/ foo/g`

# Expected behavior
Every line should get " foo" appended

# Actual behavior
Emacs hangs, interrupting the hang with `C-g` reveals that the first line has been changed to `something foo foo foo foo foo foo foo ...`, indicating that something in the replacement code makes this operation not terminate.

# Further notes
Reported on `#evil-mode` by @rgrinberg, CC @justbur.

**Comment by justbur** [comment]
well that's annoying. `(re-search-forward "$")` is special because the end of the match is also the beginning of the match so it matches the same eol over and over. Submitting a PR

**Comment by rgrinberg** [comment]
Thank you!
