### ISSUE TITLE
Shouldn't term-mode be in evil-emacs-state-modes?

### ISSUE THREAD

**Issue by Ambrevar** [emacs-evil/evil#854]
# Issue type

- Enhancement request

I don't see the point in having modal bindings in `term` mode while it confuses some programs, most notably `vi`! :)

**Comment by wasamasa** [comment]
What exactly is the proposed enhancement, changing the default initial state for `term-mode`?

**Comment by Ambrevar** [comment]
Exactly.

**Comment by wasamasa** [comment]
There's no way I'll change a default unless there is an overwhelming majority in favor of it.

**Comment by Ambrevar** [comment]
What was the point of setting `term-mode` to insert-state in the first place?

**Comment by wasamasa** [comment]
`¯\_(ツ)_/¯`

Feel free to use `git blame`, contact the author and annoy the truth out of them, it's a waste of time compared to putting `(evil-set-initial-state 'term-mode 'emacs)` into your init file.
