### ISSUE TITLE
Search and replace in nXML mode fails

### ISSUE THREAD

**Issue by fredrik-jansson-se** [emacs-evil/evil#859]
# Bug

- Bug report

# Environment

Emacs version: GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu) of 2017-06-21
Emacs version: GNU Emacs 25.2.1 (x86_64-apple-darwin15.6.0) of 2017-04-24
Operating System:  Ubuntu 16.04.2 LTS 
Operating System: OS X El Capitan
Evil version: Evil version 1.2.12
Evil installation type: MELPA
Graphical/Terminal: Terminal
Terminal multiplexer: tmux (no difference w/o)

# Reproduction steps
- Start Emacs
- Create XML buffer:

`
<a>
  <init></init>
  <init></init>
  <init></init>
  <init></init>
  <init></init>
  <init></init>
</a>
`

- Search and replace:
:%s/init/foo/gc
y
y

# Expected behavior
`
<a>
  <foo></foo>
  <init></init>
  <init></init>
  <init></init>
  <init></init>
  <init></init>
</a>
`

# Actual behavior
`
<a>
  <foo></init>
  <init></init>
  <init></init>
  <init></init>
  <init></init>
  <init></init>
<foo
`

# Further notes

**Comment by TheBB** [comment]
@justbur This looks like a regression from https://github.com/emacs-evil/evil/commit/155ee40cd4a6041b548a06420767d8aabdba7fd0

**Comment by justbur** [comment]
nxml-mode is super annoying it turns out. It randomly changes the match-data even while we're in the `evil-ex-substitute` routine. pr coming

**Comment by TheBB** [comment]
Thanks :smile:. The joys of implicit state…

**Comment by fredrik-jansson-se** [comment]
Thanks for the fix!
