### ISSUE TITLE
`.` repeats the wrong history

### ISSUE THREAD

**Issue by MaikKlein** [emacs-evil/evil#862]
# Issue type
- Bug report

# Environment

Emacs version:  GNU Emacs 25.2.2

Operating System: Ubuntu 16.04 x64
Evil version: evil-20170613.110
Evil installation type: spacemacs
Graphical/Terminal: gui

# Reproduction steps
- Start Emacs
http://i.imgur.com/yPeIOy1.gif

I can not really reproduce it but it happens very often. In the gif above I press `cwInput` then `www` and the I press `.` . But instead of applying `cwInput` it removes the first character. It is often is really random what happens when I press `.`. 

# Expected behavior
Evil should repeat the last action

# Actual behavior
Evil repeats some random action

# Further notes

**Comment by edkolev** [comment]
Seems like an issue caused by some other package. Maybe binary searching your config could show which package exactly.

**Comment by wasamasa** [comment]
I'm afraid I can't do anything about this until you find a proper repro working inside a minimal Emacs session.  Please reopen if you do.
