### ISSUE TITLE
Zero register does not work at all, 1-9 incorrectly

### ISSUE THREAD

**Issue by quicknir** [emacs-evil/evil#864]
# Issue type

- Bug report

# Environment

Emacs version: 25.1 (spacemacs)
Operating System: Linux (RHEL 6)
Evil version:  20170512.1253
Evil installation type: MELPA
Graphical/Terminal: GUI

# Reproduction steps
- Start Emacs
- do `yy` to yank a line
- try to paste with `"0p`

# Expected behavior
Register 0 should get populated by yanking. Registers 1-9 should never be affected by yanking, only by operations that delete text.

# Actual behavior
- Nothing is pasted.
- Run evil show registers, 0 not shown
- However, register 1 contains contents of line

I know similar issues have been discussed in #339 before. Supposedly issues with 0 have been resolved, but that's not what I'm seeing. It's also incorrect that 1-9 take on the contents of things that have been yanked but maybe this is more annoying to do in emacs and is considered WONTFIX.

**Comment by justbur** [comment]
`"0p` works for me. It is true that yanked text gets added to 1-9 (in addition to deleted text).

**Comment by quicknir** [comment]
@justbur Hmm, I restarted spacemacs and it seems like it is working again. I guess something got corrupted, I can't easily figure out what now. If the behavior of 1-9 is considered WONTFIX then I can go ahead and close this. Sorry about that.

**Comment by jojojames** [comment]
@quicknir If you're on emacs 26, you can M-x debug-watch on the variable evil-was-yanked-without-register. If it gets changed, you'll find the culprit.

For me, I've only noticed it broken when using evil-mc.

If that was your problem, as a quick fix.

```
  ;; https://github.com/gabesoft/evil-mc/issues/70
  (add-hook 'evil-mc-after-cursors-deleted
            (lambda ()
              (setq evil-was-yanked-without-register t)))
```

**Comment by quicknir** [comment]
@jojojames By "using evil-mc" you mean when multiple cursors were active, or when the package was installed, generally?

**Comment by jojojames** [comment]
If you flip it on even once, you'll see the behavior.

**Comment by quicknir** [comment]
@jojojames Wow, excellent catch, thanks for the fix!

**Comment by quicknir** [comment]
I guess the conclusion from this issue is that the behavior of 1-9 likely won't be fixed (which is fine), and that my issues with 0 reflect some kind of bug in evil-mc, so I will report this issue there. Should I close this then?

**Comment by jojojames** [comment]
@quicknir It'd be good to leave it open in my opinion. The 1-9 behavior does seem like a bug.

**Comment by tomdl89** [comment]
Commit to fix: https://github.com/emacs-evil/evil/commit/25fc5c6647979357cf3e39f0667a9b7ae5266af9
