### ISSUE TITLE
Plans for universal Evil bindings (including third-party special modes)?

### ISSUE THREAD

**Issue by Ambrevar** [emacs-evil/evil#872]
# Issue type

- Question

I recently re-configured the full set of EMMS bindings to make them blend in with Evil.  It was a lot of work and I feel like sharing, lest this effort would go to waste.

It brought me to reflect on the more general question of all the special modes that are left untouched by Evil.
A recurring example is the use of `n`/`p` for going up and down and not `j`/`k`.
For those who love their Vi-style bindings and dislike disturbing context switches, Evil can be quite a hassle to live with, if not completely deterring Evil newcomers from adopting it for good.

Some efforts has been made into making some special modes more Evil, most notably Ediff, Magit and Org-mode.
What about going further down that road? Do you have any plan or procedure for extending special-mode bindings?

1. Would you accept pull requests of mode-dedicated bindings?
2. If yes, would you consider bindings for third-party packages too?
3. If no for `1` and `2`, anybody is free to maintain a separate extension on ELPA.  Any guidelines for those packages?

**Comment by wasamasa** [comment]
1. No.
2. No.
3. Just use Spacemacs. Chances are they solved the same problem and if not, they'd be delighted to accept PRs to fix this.

**Comment by Ambrevar** [comment]
Using Spacemacs is off consideration, really: I'm talking making those bindings universally available.
I'll go my own way, then.
