### ISSUE TITLE
How to define a defun text object

### ISSUE THREAD

**Issue by Ambrevar** [emacs-evil/evil#874]
# Issue type

- Question

I'm trying to define a defun text object (that works with `beginning-of-defun` and `end-of-defun` in any major mode that supports it).

Most of the code is already there so I've just added this to my config:

```
(evil-define-text-object evil-a-defun (count &optional beg end type)
  "Select a defun."
  (evil-select-an-object 'evil-defun beg end type count))

(evil-define-text-object evil-inner-defun (count &optional beg end type)
  "Select inner defun."
  (evil-select-inner-object 'evil-defun beg end type count))

(define-key evil-outer-text-objects-map "d" 'evil-a-defun)
(define-key evil-inner-text-objects-map "d" 'evil-inner-defun)
```

The inner text object works perfectly but the outer one fails, e.g. wih `yad` inside a function:

```
Debugger entered--Lisp error: (scan-error "Unbalanced parentheses" 16358 16430)
  signal(scan-error ("Unbalanced parentheses" 16358 16430))
  evil-motion-range(evil-a-defun nil nil)
  evil-operator-range(t)
  byte-code("\306\307\310\"\205[...])
  call-interactively(evil-yank nil nil)
  command-execute(evil-yank)
```

I'm trying to wrap my ahead around the evil code, so far without success. Any lead?

**Comment by wasamasa** [comment]
What I typically do in that situation is instrumenting the mysteriously failing function (in this case, `evil-select-an-object`) with `C-u C-M-x` to see what exactly it's doing, extract the problematic point positions and try reproducing the error without Evil.  This does typically give me enough insight to figure out that it's only a specific major mode this is failing for, as the span of an `evil-defun` object is determined by the `beginning-of-defun-function` and `end-of-defun-function` variables.

**Comment by edkolev** [comment]
I use the following, but it doesn't distinguish b/w inner and outer text object. BTW `m` as in "method". Vim's ruby ftplugin uses `m`, I think other ftplugins do too.

```emacs-lisp
   (evil-define-text-object evgeni-inner-defun (count &optional beg end type)
     (save-excursion
       (mark-defun)
       (evil-range (region-beginning) (region-end) type :expanded t)))

   (define-key evil-inner-text-objects-map "m" 'evgeni-inner-defun)
   (define-key evil-outer-text-objects-map "m" 'evgeni-inner-defun)
```

**Comment by Ambrevar** [comment]
I ran Edebug and it seems that there is a design issue either in `forward-evil-defun` or in `evil-select-an-object`.

I don't think the issue is major-mode specific as it fails for all the major-modes I've tried. In different ways, admittedly, but the root of the bug might be the same.

Try a `yad` with the point on `printf`:
```
#include <stdio.h>

int main() {
	printf("hello worldl\n");
}
```

At some moment the buffer is narrowed to the `int main() {` line, the point is at the beginning and `end-of-defun` is called, which raises the error.



Bonus question: how do you accomodate Evil with Edebug? For me, when Edebug just starts, `n` will incorrectly run `evil-search-next`. `f` works however, and once `f` has been pressed, all other keys are correctly mapped.

Also I cannot seem to be able to call `edebug-step-in` (bound to `i`) despite the point being _before_ a list.  When I do I immediately get a backtrace:

    (error "You must be before a list form")
    ...

**Comment by wasamasa** [comment]
I use the following for edebug integration:

```elisp
(add-hook 'edebug-mode-hook 'evil-normalize-keymaps)
```

To use `i`, point must be immediately before the form, not the space before it.  If the cursor is displayed as a block, the character it precedes is highlighted.  Some people use the vertical bar for this reason as it makes it easier to remember that point is between characters in Emacs and on characters in Vim.

**Comment by Ambrevar** [comment]
Thank you for the tip, works perfectly.

Have you investigated my example?

**Comment by wasamasa** [comment]
No.

**Comment by Hi-Angel** [comment]
@Ambrevar works for me. I bound the object to `m` though, in case it mysteriously influences anything. By the way, thanks for the code, that was exactly what I was just searching for.

**Comment by ninrod** [comment]
@wasamasa holy jesus, this `(add-hook 'edebug-mode-hook 'evil-normalize-keymaps)` hack is awesome. thanks a ton.

**Comment by Ambrevar** [comment]
@Hi-Angel: Does the "around text object" work for you?  Can you share your exact configuration?

**Comment by Hi-Angel** [comment]
@Ambrevar well, for testing I just created a .cpp file with three functions, and I see for me <kbd>dim</kbd> works same way as <kbd>dam</kbd>. I'm okay with that, I don't really know how semantically they should differ with regard to a function-text-object.

As for configuration — well, do you want me to paste my `.emacs`? The thing is, it depends on different other files, can't say offhand how many and which ones *(I can make a snapshot with whole `~/.emacs.d` dir though)*; so if you try it, it might not even load… I think it'd be more productive if I simply tested whether I experience your problem with `emacs -Q`. Just tell me how to load evil from there — when I'm trying to `load-file` `evil.el`, it throws "*Cannot open load file: No such file or directory, evil-vars*".

**Comment by Hi-Angel** [comment]
@Ambrevar anyways, if you're curious, [here's my .emacs](https://gist.github.com/Hi-Angel/f5de6c2ec2f5ee503670e083ea1c7459).

**Comment by Kazark** [comment]
FWIW, I found in Scala at least, the `p` (paragraph) text object works as a text object for methods.

**Comment by dominikh** [comment]
@Ambrevar did you ever manage to resolve your issue with `evil-select-an-object`?

**Comment by Ambrevar** [comment]
No, I haven't follow up with it, sorry.

**Comment by Hi-Angel** [comment]
FTR: here's setup I'm currently using and it's working for me:

```
;; add a "function" text object
(evil-define-text-object evil-a-defun (count &optional beg end type)
  "Select a defun."
  ;; (evil-select-an-object …) for me often results in errors, so reimplement it with
  ;; inner-object instead
  (pcase-let ((`(,beg ,past_end) (evil-select-inner-object 'evil-defun beg end type count)))
    (goto-char past_end)
    (let ((lst-space-addr (re-search-forward "[^[:space:]\n]" nil t)))
      (if lst-space-addr
          `(,beg ,(- lst-space-addr 1))
        `(,beg ,(point-max))))))

(evil-define-text-object evil-inner-defun (count &optional beg end type)
  "Select inner defun."
  (evil-select-inner-object 'evil-defun beg end type count))

(define-key evil-outer-text-objects-map "m" 'evil-a-defun)
(define-key evil-inner-text-objects-map "m" 'evil-inner-defun)
```

Worth noting that despite what I said above about `evil-select-an-object` not resulting in errors for me, apparently later I did have errors sometimes. It might have been fixed already, it's been 3 years. However, now that I'm testing `evil-select-an-object`, I see that in combination with the code from the 1st post here it behaves same way as `evil-select-inner-object`, i.e. it doesn't select whitespace in addition to a function body. So I recommend using the custom code in my message instead of `evil-select-an-object` — mine does select a whitespace.
