### ISSUE TITLE
Count pattern

### ISSUE THREAD

**Issue by SP00KYB00G13** [emacs-evil/evil#875]
# Issue type
Enhancement request

# Environment
Emacs version: 25.1.1
Operating System: Ubuntu 12.04.5
Evil version: 1.2.12
Evil installation type: MELPA
Graphical/Terminal: Terminal
Terminal multiplexer: no

# Reproduction steps
- Start Emacs
- open any file (text)
- `:%s/<pattern>//gn`

# Expected behavior
Count the occurrences of `<pattern>` without modifying the buffer

# Actual behavior
Performs a substitution on `<pattern>` (essentially deletes `<pattern>` because there is no arg passed to replace)

**Comment by TheBB** [comment]
I can't reproduce this starting from `make emacs` in the evil repo root. I'm getting the number of occurences just like in vim. Can you provide more exact repro steps, starting with that step, also giving the contents of the buffer and the exact pattern you are using?

(By the way, I had to edit your report a bit, some of the text was not showing because I guess github filters out things that look like tags.)

**Comment by SP00KYB00G13** [comment]
Not a problem, starting from terminal:

```
echo "hi
hi
hello
hi" > meow

emacs -nw meow
```

In emacs:

```
:%s/hi//gn
```

After the command my buffer looks as follows:

```
 
 
hello
 
```

I expected the buffer to be unmodified such as :

```
hi
hi
hello
hi
```

**Comment by justbur** [comment]
Can't reproduce this, but it looks like you might have a version of evil before the n flag was implemented which was recently.

**Comment by SP00KYB00G13** [comment]
I am running `Evil Version 1.2.12` isnt this the latest?

**Comment by wasamasa** [comment]
Not necessarily, after there have been quite a few commits ever since that release.  Please update to the latest Git snapshot.

**Comment by TheBB** [comment]
I asked you to start with `make emacs` in the repository root. :-)

**Comment by SP00KYB00G13** [comment]
This the repo this error is fixed ! Can someone point me to some documentation on `make emacs` ? 

And also just out of curiousity when will the next "official" release be that includes these changes ?

**Comment by wasamasa** [comment]
` make emacs` is a Makefile target with the following comment: "# Load Evil in a fresh instance of Emacs and run all tests.".  There are enough changes for a release to be made, but you'll have to ask @TheBB on that.  Ultimately, the release happens when it's ready.
