### ISSUE TITLE
Wrapping paragraphs with :gq collapses sequences of whitespaces

### ISSUE THREAD

**Issue by Ptival** [emacs-evil/evil#877]
# Issue type
- Bug report

# Environment

Emacs version: 25.2.1
Operating System: NixOS
Evil version: 1.2.12
Evil installation type: MELPA
Graphical/Terminal: X
Terminal multiplexer: N/A

# Reproduction steps
- Start Emacs
- Write a block of text like `a.  b`
- Hit, in sequence, `{`, `gq`, `}` to reformat / rewrap the text

# Expected behavior
- `a.  b`

# Actual behavior
- `a. b`

# Further notes
- The `foo.  bar.` convention is often used by people to distinguish between actual end of sentences and periods that may have other meaning like in `e.g.` or `Ronald Mc. Donald` or w/e...
- I filed this as a bug report in that it does not behave like vanilla vim. But I'd be okay with it being counted as an enhancement, since the current behavior is reasonable but not perfect.

**Comment by wasamasa** [comment]
Sorry, I cannot reproduce this.  Evil delegates this operation to `fill-region` which behavior depends on the major mode and customizables such as `sentence-end-double-space`.  Please double-check that you're experiencing this with zero configuration and that it happens in any mode.  If it only happens for a specific configuration or mode, tell us.

**Comment by Ptival** [comment]
Ah, thanks, it has indeed to do with my borrowed configuration. Sorry!
