### ISSUE TITLE
Double single quotes does not jump to line jumped from

### ISSUE THREAD

**Issue by rieje** [emacs-evil/evil#880]
# Issue type
- Bug report

# Environment

Emacs version: 25.2-2
Operating System: Arch Linux

Evil version: 1.2.12
Evil installation type: MELPA
Graphical/Terminal: X
Terminal multiplexer: N/A

# Reproduction steps
- Start Emacs
`''` (double single quotes) to jump back to line in current buffer previously jumped from.

# Expected behavior
Should jump to line in current buffer previously jumped from.

# Actual behavior
Does not jump to line in current buffer previously jumped from (not sure where it jumps to--it's hard to guess where.

# Further notes
In vim, `''` (double single quotes) [jump back (to line in current buffer where jumped from)](http://vim.wikia.com/wiki/Using_marks). So go to an arbitrary line, mark it like `ma`, go to a different line, then `'a` to jump to the marked line. From here, `''` should go back to the line jumped from, but it does something different (not sure what). Not sure if bug or intended, but I am looking for vim's behavior.

**Comment by dajva** [comment]
WFM. Both `''` and ` `` ` seems to work fine now.
