### ISSUE TITLE
Can not yank register content into search mode

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [emacs-evil/evil#886]
# Type

- Question

# Environment

Emacs version: 25.1
Operating System: Mac
Evil version: evil-20170712.2350
Evil installation type: MELPA
Graphical/Terminal: Graphical

# Reproduction steps

`"ayl`   save special character (like ») into register
`/^Ra`  **can not use search mode to find the register's content**

# Further notes

I can yank the register content directly use `"ap (in normal mode)` and `^Rap (in insert mode)`
If can use `f^Ra (in normal mode)`, something might be easier

**Comment by wasamasa** [comment]
What exactly is the question here?

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
Above my reproduction steps 
Can not use register into search mode

**Comment by wasamasa** [comment]
I still don't see any question.

**Comment by therockmandolinist** [comment]
@wasamasa, I believe @earthIsAPrisonIfYouNotAwareItCanNotOut is saying that they're encountering a bug. Usually, The key sequence `"ayl` will save the char at point into the `a` register. You should then be able to search for this character (or whatever was saved into the `a` register) by pressing `/` `C-r` `a`, but for some reason they are not able to do this. 

I can't reproduce this, though.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
@therockmandolinist, in my evil, I will create many macro and sometimes using `( / or f )` to find some special characters. In vim way, I think about the register is a better choice. I raise the issue as a question because I think it may have a default emacs choice instead of vim

**Comment by therockmandolinist** [comment]
@earthIsAPrisonIfYouNotAwareItCanNotOut I can't really understand what you're trying to say - what I am saying is that I believe the behavior you have described as not working _does_ work for me. I do have `evil-search-module` set to `'evil-search`. Don't know if that's helpful. Again, your point is very unclear.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
@therockmandolinist ,thanks a lot, I will check it out

**Comment by jrwats** [comment]
@dieggsy, thanks for that.  This is the top result for "evil-mode search register", and I was having the exact same issue attempting to search for the "default register" (") after a yank and failing.  Updating `evil-search-module` was the answer.  Kinda curious why this wouldn't be the default setting for `evil-mode`...

**Comment by wasamasa** [comment]
It's too bug-riddled for that. Isearch is rock-solid in comparison.
