### ISSUE TITLE
C-u and C-d scrolling too much

### ISSUE THREAD

**Issue by wolfv6** [emacs-evil/evil#890]
# Issue type
- Bug report

# Environment
Emacs version: 25.2.1
Operating System: Linux Fedora 26
Evil version: evil-git-8e1af145
Evil installation type: MELPA stable from Spacemacs
Graphical/Terminal: Wayland
Terminal multiplexer:  no

# Reproduction steps
- Start Emacs
open org file with many headings
fold all the headings
scroll using C-u and C-d
 
# Expected behavior
scroll half screen up & down

# Actual behavior
scroll 3/4 screen up & down

# Further notes
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by wasamasa** [comment]
Sorry, I cannot reproduce this.  Please try providing an example (like by replacing every letter in your org file with `x`) and check whether you still get this from `make emacs` in an Evil checkout.

**Comment by wolfv6** [comment]
@wasamasa 

[Example with instructions on top line.](https://drive.google.com/open?id=0B6rxjFGf59mbdU1FNzB5STNlMWs)

I read this in https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports
2. Test the bug in a clean Emacs environment without any additional packages loaded (besides Evil itself). You can easily get such an environment by executing either make emacs (for X).

I am using Wayland, not X.
How to restore Emacs after testing the bug on clean Emacs?

**Comment by wasamasa** [comment]
You won't even be able to run regular Emacs on Wayland without xwayland which ends up running Emacs in X, so same steps apply for you, too.  If you're the same person as on https://emacs.stackexchange.com/q/34623/10, the second concern is invalid.  Get a copy of Evil's repo and run `make emacs` inside it.

**Comment by wasamasa** [comment]
Even with your file I'm unable to reproduce this, so I suspect this is a Spacemacs problem.  If you get the same result, I'll consider this one's closed.

**Comment by wolfv6** [comment]
I tested on a a clean Emacs environment with org-mode installed.
The first few times I tried C-d and C-u it scrolled half screen as it should.
Then I tried some more C-u and C-d, and it scroll more that one screen full, and stayed that way.
C-d was pressed once between each of the attached screen shots.
C-u was similar in the opposite direction.
![screenshot from 2017-08-03 12-26-38](https://user-images.githubusercontent.com/1121166/28937805-4ca9274c-7849-11e7-9aa0-be53e79eb1d9.png)
![screenshot from 2017-08-03 12-26-54](https://user-images.githubusercontent.com/1121166/28937819-521c86ba-7849-11e7-806e-c2fdc3977263.png)
![screenshot from 2017-08-03 12-27-29](https://user-images.githubusercontent.com/1121166/28937821-5541b022-7849-11e7-8c5e-74a969e41f5c.png)

**Comment by wasamasa** [comment]
This kind of thing can only happen if something set `evil-scroll-count` to a non-zero value.  If you get into that state, I recommend using `F1 l` to see the keystrokes that led to this and reopen this bug.  You can reset with `evil-scroll-count-reset`.

**Comment by wolfv6** [comment]
I ran the test again, but the results where different today.

C-d functions as intended.
C-u is unresponsive, but if it is follow by up or down arrow, scrolls by 1/2 screen in direction of arrow.

F1 l:
[self-insert-command]
 [self-insert-command]
 [self-insert-command]
 <help-echo> <help-echo> <help-echo> <help-echo> <help-echo>
 <help-echo> <tool-bar> <open-file> [menu-find-file-existing]
 C-d [evil-scroll-down]
 C-d [evil-scroll-down]
 C-d [evil-scroll-down]
 C-u [universal-argument]
 C-u [universal-argument-more]
 <up> [evil-previous-line]
 C-u [universal-argument]
 <up> [evil-previous-line]
 C-d [evil-scroll-down]
 C-u [universal-argument]
 <up> [evil-previous-line]
 <f1> l [view-lossage]

M-x describe-variable evil-scroll-count:

    evil-scroll-count is a variable defined in ‘evil-vars.el’.
    Its value is 0
    Local in buffer test_scroll.org; global value is the same.

I "make emacs" and tested three times and got the above results each time.

**Comment by vyp** [comment]
Did you `(setq evil-want-C-u-scroll t)`?

**Comment by wolfv6** [comment]
I did not (setq evil-want-C-u-scroll t).   Where should I put that?  I only know Spacemacs, I don't know where emacs things go.

**Comment by vyp** [comment]
Well then I think that C-u behaviour is expected. :)

When you open emacs, there should be a `*scratch*` buffer in `Lisp Interaction` mode. Type `(setq evil-want-C-u-scroll t)` there and evaluate that expression by pressing `C-x C-e` with your cursor on the closing parenthesis.

I don't know about Spacemacs, but I'd assume it already sets this so you wouldn't need to put it anywhere, but otherwise it would go in `.spacemacs` of course. For normal emacs, `.emacs.d/init.el` is basically the equivalent to `.spacemacs`.

**Comment by wolfv6** [comment]
Thanks vyp.  But (setq evil-want-C-u-scroll t) in \*scratch\* and pressing C-x C-e with cursor on the closing parenthesis didn't change the C-u behavior.

**Comment by TheBB** [comment]
`evil-want-C-u-scroll` is a variable with a nontrivial setter so you probably want to `(custom-set-variables '(evil-want-C-u-scroll t))` instead. `setq`ing it after evil has loaded probably won't do much.

Spacemacs sets this by default so if you don't have this binding then you may have done something to change it.

**Comment by vyp** [comment]
@TheBB Good catch :+1:, I see that in my config I set it before loading evil.

**Comment by wolfv6** [comment]
Ya, thanks TheBB, that worked in clean Emacs environment with org-mode.  So C-u and C-d work as intended in Evil.
So the bug is probably in Spacemacs.  I will open an issue on the Spacemacs repo.

**Comment by wasamasa** [comment]
Well, no, it's not a bug in this sense.  It just happens that Emacs puts a rather important keybinding on `C-u`.  Read up in the Emacs manual what the universal argument is and why you'd want to use it.  Instead of unconditionally rebinding it, Evil offers a customization option so that you only get the scrolling command if you've enabled it yourself.  If you want to have both, rebind either of them to a different key.
