### ISSUE TITLE
Residual content in evil registers.

### ISSUE THREAD

**Issue by abhi18av** [emacs-evil/evil#891]
Hi evil-emacs team :)

Hey, i've been having a problem in which the residual test is automatically entered into a buffer when I open a new buffer in `spacemacs`.

I've narrowed it down from many possible issues to the one with registers as documented here https://github.com/syl20bnr/spacemacs/issues/8025 

Could you give me some pointers towards the solution?

**Comment by wasamasa** [comment]
Evil doesn't persist registers, so your assumption is invalid.  The issue does therefore lie within Spacemacs plus your own customizations, so I can't help you with that.
