### ISSUE TITLE
Visual mode over reaches to right by one character.

### ISSUE THREAD

**Issue by wolfv6** [emacs-evil/evil#894]
# Issue type
- Bug report

# Environment
Emacs version: 25.2.1
Operating System: Linux Fedora 26
Evil version: evil-git-8e1af145
Evil installation type: MELPA stable from Spacemacs
Graphical/Terminal: Wayland
Terminal multiplexer: no
Tested in a [clean environment](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports): Yes

# Reproduction steps
- Start Emacs
- Copy the examples provided below in the "Further notes" section.
- For each example, place cursor on letter 's', and test the Vi command.

# Expected behavior
Visual mode select region like vim.

# Actual behavior
Compared to vim, Evil visual mode reaches to right by one extra character.

# Further notes
For all examples, the initial cursor position is on the letter 's'.
```
ORIGINAL TEXT          COMMAND    VIM RESULT        EVIL RESULT     COMMENT
the test word          vwd        the teword        the teord
the test word          vbd        the st word       the t word
Big shiny.  Word.      v)d        Big Word.         Big ord.
Word.  Big shiny.      v(d        Word.  shiny.     Word.  hiny.
(test)                 vF(d       st)               t)
test                   v$         te                te              Evil also deletes carriage return
```

**Comment by wasamasa** [comment]
I can't reproduce this, although in another way than you'd expect: While I can reproduce the results for Evil, I cannot reproduce your results for Vim.  Vim gives me consistently the same thing as what you'd put there for Evil, including deletion of carriage return (assuming you meant `v$d` there).

**Comment by wolfv6** [comment]
Turns out that the "VIM RESULTS" I posted were non-standard vim behavior caused by "behave mswin" in my .vimrc file:
```
source $VIMRUNTIME/mswin.vim
behave mswin
```
Thank you wasamasa, I had no idea.
That has been in my vimrc since I learned vim, and I was not aware that this behavior was different than standard vim.  Now to learn the proper vi way.
