### ISSUE TITLE
Return value of `evil-paste-{after,before}' is incorrect for line-wise pastes

### ISSUE THREAD

**Issue by olmokramer** [emacs-evil/evil#898]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 25.2.1
Operating System: Arch Linux
Evil version: 1.2.12
Evil installation type: MELPA (I think, but I'm unsure, I used `use-package evil`)
Graphical/Terminal: Graphical
Tested in a [clean environment](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports): Yes

# Reproduction steps
- Start Emacs
- Go to `*scratch*` buffer
- Place point on first line (`;; This buffer is for text...`)
- Press following key sequence
  `yyo(evil-paste-after 1)<ESC><C-j>`
  this is Vim notation (how would Emacs users say this?), but it does the following:
  * Line-wise yank first line: `yy`
  * Insert on next line: `o`
  * Text to insert: `(evil-paste-after 1)`
  * Quit insert mode: `<ESC>`
  * Eval last sexp and insert into buffer: `<C-j>`

# Expected behavior
The docstrings of `evil-paste-{after,before}` say that the functions shall return the pasted text, so I would expect the pasted text to be inserted twice after the line with `(evil-paste-after 1)`: once because of the paste and another time because `<C-j>` inserts the result of the evaluation into the buffer.

# Actual behavior
The following text is inserted into the buffer (i.e. a load of stuff in addition to the pasted text):
```elisp
#(";; This buffer is for text that is not saved, and for Lisp evaluation.
" 0 3 (face font-lock-comment-delimiter-face fontified t yank-handler (evil-yank-line-handler nil t)) 3 70 (face font-lock-comment-face fontified t yank-handler (evil-yank-line-handler nil t)) 70 71 (face font-lock-comment-face fontified t yank-handler (evil-yank-line-handler nil t)))
;; This buffer is for text that is not saved, and for Lisp evaluation.
```

**Comment by wasamasa** [comment]
This is still a string, but with extra text properties.  It will behave just like a normal string, except that you can look up string properties (such as `face`, `fontified` and `yank-handler`) and retrieve their values.  Also, it prints weirdly, but that's not our fault.  In other words, ENOTABUG.

**Comment by olmokramer** [comment]
Aha, learned something new today. Sorry to bother you
