### ISSUE TITLE
the feature require to erase incorrect characters

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [emacs-evil/evil#899]
# Issue type

- Enhancement request

# Environment

Emacs version: 25.1
Operating System: osx
Evil version: latest version
Evil installation type: MELPA
Graphical/Terminal: graphical
Tested in a [clean environment](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports): no

# Reproduction steps
- Start Emacs
- type some text
- erase incorrect characters
case:
we don't know that objects's
^
keystrokes:
$dFs

# Expected behavior

we don't know that object
# Actual behavior

we don't know that objects

**Comment by vyp** [comment]
I think you were trying to report this as a bug rather than enhancement request? In any case, if I understand correctly, I don't think this is a bug because this is the same behaviour as vim (test with `vim -u NONE`). Remember that even after pressing `$` to go to the end of the line, the cursor is still on the 'left' of the last character, hence why there is still an 's' remaining after doing `dFs` from there.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
I have the same idea with you. I also think this is not a bug, but I expect to know how vimer to avoid this keystroke and get the correct result

**Comment by vyp** [comment]
As in my point was that the correct result *is* "`objects`". So I'm not really sure what enhancement you would like to see?

If you're just asking a question, I guess you would just have to press `x` after doing `$dFs`? (Or in this case you can achieve your desired result with the same number of keystrokes by doing `$FsD`.)

**Comment by wasamasa** [comment]
This is an issue tracker for Evil, not a place to find out how to achieve things in Vim.  For that kind of thing, you're better off asking [r/vim](https://www.reddit.com/r/vim) or `#vim` on Freenode.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
This problem puzzles me many times, thanks for respond @vyp.
This issue is just a feature request, delete characters from right to left at any point

**Comment by Dickby** [comment]
try `dvFs`
