### ISSUE TITLE
repeat with count does not work for repeations recorded by change

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#9]
Originally reported by: **Frank Fischer (Bitbucket: [lyro](https://bitbucket.org/lyro), GitHub: [lyro](https://github.com/lyro))**

----------------------------------------

The current version of `evil-execute-repeat-with-count` only deals with keystrokes.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/9

**Comment by ninrod** [comment]
I think this is solved.

**Comment by wasamasa** [comment]
I don't really understand what else there is than recording keystrokes. Can you give an example demonstrating that this issue has been resolved?

**Comment by ninrod** [comment]
I was seeing [this](https://github.com/emacs-evil/evil/issues/724#issuecomment-275061356) thread and tried this example: 

```text
[t]est1 test2 test3 test4
test1 test2 test3 test4
```

`c2wworks [ESC]0j.`

```text
works test3 test4
works test3 test4
```

**Comment by wasamasa** [comment]
Sorry, I didn't look at the title.  Looks like this has been fixed indeed as I can repro your example.
