### ISSUE TITLE
undo issue in visual mode

### ISSUE THREAD

**Issue by pera** [emacs-evil/evil#903]
# Issue type

- Bug report

# Environment

Emacs version: 25.2.1
Operating System: Arch Linux
Evil version: 1.2.12
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a [clean environment](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports): Yes

# Reproduction steps
- Start Emacs
- On a scratch buffer write two lines, for instance:
```
first line
second line
```
- Use visual block mode to add some characters at the beginning of both lines (i.e. `0 ^v k I`)
- Add two characters, which will result in something like:
```
;;first line
;;second line
```
- Press escape and then `u` to undo. The (erroneous) result will be:
```
;;first line
;second line
```
- If you press `u` one more time, the result will be the correct one, this is:
```
first line
second line
```

**Comment by VanLaser** [comment]
I'm also on Arch Linux, `evil` installed from MELPA, with emacs 26.0.50 (git) and I don't have that behavior. Did you customize `evil-want-fine-undo` by any chance?

**Comment by ninrod** [comment]
can't reproduce.

**Comment by pera** [comment]
OK I just tried this using the git version and now it works, so I am closing this ticket. Maybe I used the MELPA stable version, I'm not sure now...

Thanks!

**Comment by ninrod** [comment]
just use melpa unstable for evil. it's updated every 3 hours.

**Comment by pera** [comment]
@ninrod I am doing exactly that now :) thank you.

**Comment by wasamasa** [comment]
@pera Note that you did not test in a clean environment as described in the link, it specifically tells you to run `make emacs` in a Git checkout of Evil.  This is done to ensure you're not on an outdated version, yet you closed this ticket for that reason.  It appears that I'll have to be more specific here instead of linking people to something they won't click...

**Comment by pera** [comment]
@wasamasa I did read that link, but it doesn't says that I **must** run `make emacs`:

> Test the bug in a clean Emacs environment without any additional packages loaded (besides Evil itself). You can easily get such an environment by executing either make emacs (for X) [...]

What I did instead was start emacs with the `-q` argument to not load the packages from my init.el, and then manually load Evil. 

Also, why does Evil have different releases using the same version number? is 1.2.12 a RC? Thanks.
