### ISSUE TITLE
org-copy-visible doesn't copy exactly what's visually selected

### ISSUE THREAD

**Issue by rieje** [emacs-evil/evil#907]
# Issue type
- Bug report

# Environment

Emacs version: 25.2.1
Operating System: Arch Linux
Evil version: 1.2.12
Evil installation type: MELPA
Graphical/Terminal: Graphical

# Reproduction steps
- Start Emacs, evaluate `(setq org-hide-emphasis-markers t)`. Open a org file containing the following line: 
    ~$ firejail --get=<id> <file>~

which is shown in the visible buffer as
    
    $ firejail --get=<id> <file>

Then, visually select via `v` from the first charcter `$` to the last character `>` of the line. What's copied via `org-copy-visible` into the clipboard is:

    ~$ firejail --get=<id> <file>

instead of 

    $ firejail --get=<id> <file>

Also, copying the entire line with `V` via `org-copy-visible` will yield `~$ firejail --get=<id> <file>~`.

# Expected behavior

It should just copy what's visible, which is `$ firejail --get=<id> <file>`.

**Comment by wasamasa** [comment]
I can repro the same problem without Evil.  Please raise a bug for Org instead.
