### ISSUE TITLE
Make it possible to remove dired-mode from overriding maps

### ISSUE THREAD

**Issue by jackkamm** [emacs-evil/evil#908]
# Issue type
- Enhancement request

# Environment

Emacs version: GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.16) of 2017-07-16
Operating System: Arch Linux
Evil version: evil-git-875f704d
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Further notes
Within dired-mode, keys such as `g`, `G`, `w`, `v` execute dired commands, instead of the usual normal-state motions. However, I would prefer to use the normal motions, and manually switch to insert-state or emacs-state to execute the dired commands.

Ideally I could simply remove `dired-mode` from the `evil-overriding-maps` list. However `dired-mode` is not present in this list, instead `(evil-make-overriding-map dired-mode-map 'normal)` is called in `evil-integration.el` after `dired` is loaded.

**Comment by jackkamm** [comment]
On second thought, an easier way to achieve my goal was to start `dired-mode` in `motion-state`:
```
(evil-set-initial-state 'dired-mode 'motion)
```
Sorry for polluting the issue page, and thanks for your great work on this package.

**Comment by VanLaser** [comment]
If you want some "purified" evil states, you can do something like this:

```emacs-lisp
  ;; don't let modes override any states (!)
  (setq evil-overriding-maps nil
        evil-intercept-maps nil
        evil-pending-intercept-maps nil
        evil-pending-overriding-maps nil)
  ;; subvert evil-operation.el overrides (dired, ibuffer etc.)
  (advice-add 'evil-make-overriding-map :override #'ignore)
  (advice-add 'evil-make-intercept-map  :override #'ignore)
  (advice-add 'evil-add-hjkl-bindings   :override #'ignore)
```

**Comment by vyp** [comment]
I just want to add to check out the excellent and comprehensive https://github.com/noctuid/evil-guide for some more helpful tips. (For example, it has both of your use cases. 🙂)
