### ISSUE TITLE
C-w in insert state does not populate the " register

### ISSUE THREAD

**Issue by diamond-lizard** [emacs-evil/evil#910]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 25.2.1 (x86_64-pc-linux-gnu) of 2017-06-03
Operating System: Gentoo Linux amd64
Evil version: evil-git-88268b4
Evil installation type: manual
Graphical/Terminal: terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- In insert state:
1 - type any text.
2 - type C-w

# Expected behavior
1 - a word is deleted backwards
2 - the " register is populated with the deleted word

# Actual behavior
1 - a word is deleted backwards
2 - the " register remains unchanged

# Further notes
In vim 8.0, the behavior is as described in "Expected behavior" above.

**Comment by VanLaser** [comment]
I propose changing `delete-char` and `delete-region` with `evil-delete`:

```emacs-lisp
(evil-define-command evil-delete-backward-word ()
  "Delete previous word."
  (if (and (bolp) (not (bobp)))
      (progn
        (unless evil-backspace-join-lines (user-error "Beginning of line"))
	(evil-delete (save-excursion (1- (point))) (point)))
    (evil-delete (max
                    (save-excursion
                      (evil-backward-word-begin)
                      (point))
                    (line-beginning-position))
                   (point))))
```

**Comment by wasamasa** [comment]
I'd suspect this is the fault of `C-w` not being mapped to an Evil command.  Considering that I can replicate what @VanLaser described, I consider this issue not terribly important and will close it for the time being.
