### ISSUE TITLE
Create an 'evil-change-workaround-functions' list to allow 3rd party 'evil-change' functions

### ISSUE THREAD

**Issue by jgkamat** [emacs-evil/evil#916]
# Issue type

- Enhancement request

# Environment

Emacs version: GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.12) of 2017-04-23, modified by Debian
Operating System: Debian 9
Evil version: Evil version 1.2.12
Evil installation type: Melpa
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Define your own version of `evil-change`. For example:
```
(evil-define-operator my-evil-change (beg end type register yank-handler delete-func)
	(interactive "<R><x><y>")
	(evil-change beg end type register yank-handler delete-func))
```
- Bind 'c' to said function
`(define-key evil-normal-state-map "c" #'my-evil-change)`
- change a word (`cw`) as shown in examples

# Expected behavior
`f|oo bar` -> `f| bar`

# Actual behavior
`f|oo bar` -> `f|bar`

# Further notes

This is caused by hardcoding `evil-change` [in these lines](https://github.com/emacs-evil/evil/blob/dc936936666595afdbdbb4cc44c1f82e74c6802c/evil-commands.el#L309-L311).

There are a couple projects that re-define the `c` operator in order to add more featues, and when they do so, they do not get the workaround that `evil-change` does (in those lines). 

The best solution (I think, currently) would be to add a variable such as `evil-change-workaround-functions`, so such packages could add their `evil-change` functions to the list and get the workaround. This idea [came from this issue comment](https://github.com/emacs-evil/evil-surround/issues/117#issuecomment-317364008).

This would help solve:
- https://github.com/luxbock/evil-cleverparens/issues/59
- https://github.com/emacs-evil/evil-surround/issues/117
- https://github.com/expez/evil-smartparens/issues/20

I would be happy to solve this myself. If no one objects, I'll try and submit a preliminary patch in a couple days. Let me know if an evil maintainer would like to take this before me though.

**Comment by wasamasa** [comment]
Generally speaking I approve of this idea.  Hardcoding magic values is bad, putting them into a documented variable is much better.  I'm not happy about the proposed variable name though, I'd rather name it `evil-change-commands` because it's about commands specifically and "workaround" doesn't make it clearer what it's about.  The intended usage of the variable would be like `(let ((evil-change-commands (cons 'my-evil-change-command evil-change-commands))) ...)`.  Feel free to prepare a PR to close this issue.
