### ISSUE TITLE
column edit not working when using hybrid mode (alias insert state to emacs state)

### ISSUE THREAD

**Issue by seudut** [emacs-evil/evil#920]
# Issue type
Column edit  is very convenient. Seems Evil has also implemented this feature, and it works in most case. But when I use a hybrid mode, in which insert state is aliased to emacs state as below,
```
(defalias 'evil-insert-state 'evil-emacs-state)
```
this feature won't work anymore. 

E.g. If I want to comment out (for C/C++ file, insert "//" at the start of the lines) three lines below the cursor, I can input as below,

<kbd>Ctrl + V</kbd>, 
<kbd>3j</kbd>, 
<kbd> I </kbd>, 
<kbd>//</kbd>, 
<kbd>Esc</kbd>

- Bug report

# Environment

Emacs version: 25.2.1
Operating System:  macOS Sierra
Evil version: 1.2.12
Evil installation type: melpa
Graphical/Terminal:  iTerm2
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  No

here is the output of `(version)'
```
GNU Emacs 25.2.1 (x86_64-apple-darwin16.4.0, NS appkit-1504.81 Version 10.12.3 (Build 16D30))
 of 2017-09-06
```
# Reproduction steps
1. Start Emacs with a clean initial file `test.el` using command `emacs -Q -l test.el`.
below is all content of `test.el`. it only loads `evil`. 

```
(add-to-list 'load-path "~/.emacs.d/elpa/evil-20170904.1346")
(require 'evil)
(evil-mode t)
(defalias 'evil-insert-state 'evil-emacs-state)
(define-key evil-emacs-state-map [escape] 'evil-normal-state)
(define-key evil-emacs-state-map (kbd "<ESC>") 'evil-normal-state)
```
2. press <kbd>Ctrl + V</kbd> to enter to visual block mode.
3. move the cursor down or up to select the lines to edit.
4. press <kbd>  I </kbd> to enter into Insert mode
5. insert the contents 
6. press <kbd>Esc</kbd> to finish, after this, all the line selected will be insert the same contents

# Expected behavior

After <Esc> above,  the contents in step 5 above will be inserted into the same position of all the lines selected in step 3.
# Actual behavior

Only the first line  has been modified.
While, if I remove the `(defalias 'evil-insert-state 'evil-emacs-state)` line in the test.el, then evil works as expected.

So looks like this config to alias insert state to emacs has conflict with this feature.

# Further notes

**Comment by wasamasa** [comment]
That's correct.  If you break insert state and use a command that relies on insert state recording information for repeating a block edit, it's no wonder that won't work.  All I can say to this is "Don't do that then".  Perhaps you'll want to go for the less invasive option of modifying the insert state keymap to not have any keybindings except for the escape key bound, this can be done in recent versions by customizing `evil-insert-state-bindings` or `evil-disable-insert-state-bindings` *before* loading up Evil.
