### ISSUE TITLE
Remove dependency on goto-chg

### ISSUE THREAD

**Issue by syl20bnr** [emacs-evil/evil#922]
We need to bust the dependency on goto-chg as MELPA is going to remove all packages from the wiki.
Source: https://github.com/melpa/melpa/pull/5008

cc @wasamasa  @TheBB

**Comment by jgkamat** [comment]
#458 and #792 are related and contain discussion on this as well (this is needed to get pure melpa stable working as well).

**Comment by ninrod** [comment]
this seems rather urgent.

**Comment by wasamasa** [comment]
https://github.com/emacs-evil/goto-chg

I'll be submitting this to MELPA so that Evil can install the dependency from MELPA and MELPA Stable.

**Comment by wasamasa** [comment]
Fixed as Evil can be installed from MELPA Stable.
