### ISSUE TITLE
how to append command to the end of macro

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [emacs-evil/evil#923]
# Issue type

- Question

# Environment

Emacs version: 25.1
Operating System: OSX
Evil version: latest version
Evil installation type: MELPA
Graphical/Terminal: Graphical

# Reproduction steps
- Start Emacs
- create macro 'a' and add command 'j0x'
- expect to append command 'x' at the end of macro 'a' (how to achieve?)
- use macro 'a' again, and the command is 'j0xx'

**Comment by TheBB** [comment]
Macros are stored in registers. E.g. after `qaj0xq`,

    ELISP> (get-register ?a)
    "j0x"
    ELISP> (set-register ?a (concat (get-register ?a) "x"))
    "j0xx"

AFAIK neither evil nor vim has an interface to append to macros, but so long as you keep `a` stored, you can of course do `qb@axq` and use `b` instead.

**Comment by TheBB** [comment]
Or I could be retarded. To append to a register, use the capital letter.

`qAxq` appends `x` to the macro stored in `a`.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
two ways at a time, excellent!

**Comment by VanLaser** [comment]
But why is this an issue?

**Comment by TheBB** [comment]
Well, it shouldn't be.

**Comment by wasamasa** [comment]
I'm generally against questions that aren't related to Evil, but are about Vim usage.

@earthIsAPrisonIfYouNotAwareItCanNotOut Please ask `#vim` or [r/vim](https://www.reddit.com/r/vim/) instead.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
sorry for it, but I don't familiar with that channel
