### ISSUE TITLE
Suggestion: autoload ex commands

### ISSUE THREAD

**Issue by edkolev** [emacs-evil/evil#926]
# Issue type

- Question / Suggestion

# Further notes

I've been thinking about autoload-ing ex commands, for example `evil-ex-global`. This is how I see things would work:
1. in evil-maps.el, the `:global` command will be registered `(evil-ex-define-cmd "g[lobal]" 'evil-ex-global)`
2. (new file) evil-ex-commands.el will define `evil-ex-global` with an autoload cookie; Note: this new file will not be required by evil-maps.el
3. in evil-ex.el, when the minibuffer completion is active, function `evil-ex-argument-completion-at-point` will check if the ex command `:global` has an autoloaded binding with `autoloadp` and, if yes, force the autoload with `autoload-do-load`

Notes:
- Step 3. is necessary because without it evil-ex-global's interactive statement `(interactive "<r><g/><!>")` wouldn't be processed
- Step 3. could be modified to force the autoload only if the binding (`evil-ex-normal` in this example) starts with "evil"; this will prevent forcing autoload of non-evil commands, e.g. `:checkdoc`
- I'm not sure exactly how this will work if the end user doesn't generate autoloads (using `borg` or some other means of accumulating packages)

So my question is: would you consider this a good addition to evil? I'm willing to contribute this change

**Comment by wasamasa** [comment]
Not sure if I'm not reading this properly, but I'm missing out on the why behind this addition.  Autoloads are intended to be used on the main entry points of a package and in the case of a major/minor mode it would precede that definition.  Once the mode is enabled, everything else is loaded alongside with it.  How would adding more autoloads improve things?

**Comment by edkolev** [comment]
The reason I got thinking about this in the first place was that quite a few ex commands are defined (like :sort, :normal, etc) when `(evil-mode)` is executed but they might end up never being used by the user. I thought that it would make sense to delay the loading of the ex commands until used.

The other reason is a recent package I've been playing with, [evil-expat](https://github.com/edkolev/evil-expat), which defines ex commands (e.g. :rename, inspired by :Rename from [vim-eunuch](https://github.com/tpope/vim-eunuch)), but there isn't a simple way to autoload these commands. It's possible to autoload `evil-expat-rename` (the function behind :rename, with `(interactive "<!><f>")` interactive declaration) but then the `<f>` ex argument completion will not be able to provide completion if you enter `:rename /tm<TAB>`.  The point `3.` described above would address this issue, `1.` and `2.` I figured would be nice to have to slightly reduce the time `(evil-mode)` takes to run.

If 3. were implemented, the :rename ex command could be autoloaded like so:
1. file evil-expat.el will have `(evil-ex-define-cmd "rename" 'evil-expat-rename)`
2. file evil-expat-commands.el will have
```
;;;###autoload(autoload 'evil-expat-ename "evil-expat-commands" nil t)
(evil-define-command evil-expat-rename (bang new-name)
  (interactive "<!><f>")
  ...
```

Without 3., it's still possible to autoload, but a bit more verbose, using a wrapper function:
1. file evil-expat.el will have
1.1. `(evil-ex-define-cmd "rename" 'evil-expat-rename-wrapper)`
1.2.
```
(evil-define-command evil-expat-rename-wrapper (bang new-name)
  (interactive "<!><f>")
  (evil-expat-rename bang new-name))
```

2. file evil-expat-commands.el will have
```
;;;###autoload
(defun evil-expat-rename (bang new-name)
  ...)
```

**Comment by wasamasa** [comment]
This still doesn't make much sense to me.  How do you plan on entering an ex command if ex hasn't been loaded yet?  If loading times are your real concern, measure what exactly takes so long (I have my own theories, but haven't been able to confirm them yet).

**Comment by edkolev** [comment]
Closing since the PR was merged.
