### ISSUE TITLE
misleading error message on `za` without running a supported folding minor mode 

### ISSUE THREAD

**Issue by unhammer** [emacs-evil/evil#932]
Could we rename 
https://github.com/emacs-evil/evil/blob/ca6e155878c4a398fa4c297ea8b6a329cfc40ca9/evil-commands.el#L2696
to say something like

 "Folding is not supported for any of these major/minor modes. You may want to try M-x hs-minor-mode RET first, or see variable `evil-fold-list'."

I at first thought evil had some built-in folding that happened to not support any of the stuff I tried. A slightly improved message would make this more discoverable.

**Comment by edkolev** [comment]
I ran into this the other day and this message was actually helpful to me (resulting in this commit https://github.com/emacs-evil/evil/commit/16db0051f2773bcd3a1d5befdcd6f36fc6b13c77)

Maybe the message can be changed to include a list of supported modes (like hs-minor-mode / vdiff-mode), however, this might turn out to be too noisy if the number of supported modes increases. In any case, I don't think evil should do heuristics to suggest you use a particular mode, like hs-minor-mode.

**Comment by unhammer** [comment]
hs-minor-mode comes builtin with Emacs, so I'd say it makes sense to suggest it (though perhaps in the help for a variable like `evil-fold-list`?)

**Comment by wasamasa** [comment]
Just because `hs-minor-mode` is built-in doesn't mean its folding will work for your current buffer.  If anything I'd change the message to suggest enabling any of the minor modes in `evil-fold-list` for folding to work.
