### ISSUE TITLE
vit selecting inside incorrect HTML element

### ISSUE THREAD

**Issue by nickenchev** [emacs-evil/evil#933]
# Issue type

- Bug report

# Environment
Emacs version: 25.2.1
Operating System: macOS Sierra 10.12.6
Evil version: 1.2.13
Evil installation type: MELPA via Pallet
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): 

# Reproduction steps
- Start Emacs
Use the following HTML to test:

```
<div class="grid-x">
	<div class="large-offset-1 large-4 medium-offset-2 medium-8 small-12 left">
		<h1>Test test</h1>
		<h2>Test test test test</h2>
		<h2>Test test test test</h2>

		<i class="fa fa-2x fa-facebook-official" aria-hidden="true"></i>
		<i class="fa fa-2x fa-twitter" aria-hidden="true"></i>
		<i class="fa fa-2x fa-instagram" aria-hidden="true"></i>
		<i class="fa fa-2x fa-youtube-play" aria-hidden="true"></i>
	</div>

	<div class="large-offset-1 large-6 medium-offset-2 medium-8 small-12 right">
		<h5>Over</h4>
		<p class="textstyle-36px">30,000</p>
		<h5></h5>
		<hr>
		<h5>Over</h4>
		<p class="textstyle-36px">1,000</p>
		<h5></h5>
	</div>
</div>
```

# Expected behavior
Content inside the root div should be selected.

# Actual behavior
Content inside the 2nd nested div is selected.

# Further notes
Place cursor as per 1st screenshot:
<img width="1396" alt="screen shot 2017-10-05 at 4 43 13 pm" src="https://user-images.githubusercontent.com/8262271/31251777-2786db78-a9ed-11e7-8ba0-17ee5c2b3d28.png">

Type "vit" and content in the wrong div is selected
<img width="1396" alt="screen shot 2017-10-05 at 4 43 20 pm" src="https://user-images.githubusercontent.com/8262271/31251794-36e4b388-a9ed-11e7-9bd7-d20f8f6c7ff5.png">

**Comment by TheBB** [comment]
It's worth noting that if you balance your closing tags properly, it works just fine. The docstrings of evil's XML tag text objects seem to suggest that unbalanced tags result in undefined behaviour. I don't mind changing that if the fix is not extremely difficult, but I probably will not be losing sleep over it TBH.

**Comment by nickenchev** [comment]
Yeah, just noticed the heading tags don't match, corrected them and it worked. Thanks, I hadn't actually looked through that code much as its some early stuff a co-worker wrote yesterday. That being said, even give the messed up version, using "vit" in Vim, the correct element is selected. To your point, I wouldn't lose sleep over it either, but thought it was worth pointing out.

**Comment by wasamasa** [comment]
Considering that this is undefined behavior, I'm closing this one.
