### ISSUE TITLE
Support for M-x repeat command after using evil-execute-macro

### ISSUE THREAD

**Issue by dericbytes** [emacs-evil/evil#935]
- Enhancement request

# Environment

Emacs version: GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5) of 2016-08-25
Operating System: Windows 8.1 + Oracle Vm VirtualBox + debian stretch
Evil version: Evil version evil-git-2a918c4
Evil installation type: el-get
Graphical/Terminal: GUI

# Expected behavior
M-x repeat after running evil-execute-macro will re play the last macro

# Actual behaviour
Nothing. Except for message 'Repeating command evil-execute-macro'

# Further notes

I wrote this hack and it seems to work. Hope it gives you some ideas on how to add it.

```
(defun repeat-evil-macro-dem (&optional arg)
   "Repeat last evil macro that ran.
    NOTE: needs to be run as next command after macro ran"
   (interactive "*P")
   (evil-normal-state)
   (evil-execute-macro
    arg
    (evil-get-register evil-last-register t))
   (setq last-repeatable-command 'repeat-evil-macro-dem))
```

```
(defadvice repeat (before repeat-dem activate)
   (when (and (functionp 'evil-execute-macro)
	      (functionp 'repeat-evil-macro-dem))

     (when (or (equal last-command 'evil-execute-macro)
	       (equal last-repeatable-command 'evil-execute-macro))

       (setq last-repeatable-command 'repeat-evil-macro-dem))))

```

**Comment by wasamasa** [comment]
I'm sorry, but no.  There's two perfectly well functioning ways of repeating in Evil, `.` for the last command and `@@` for the last macro.
