### ISSUE TITLE
how to disable evil mouse event

### ISSUE THREAD

**Issue by windrg** [emacs-evil/evil#936]
# Issue type

- Question

# Environment

Emacs version: GNU Emacs 26.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-16
Operating System: Ubuntu 16.04
Evil version: Evil version 1.2.13
Evil installation type: elpa
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  No

# Reproduction steps
- Start Emacs

# Expected behavior
disable evil mouse events forever or temporarily

# Actual behavior
unable to disable evil mouse events

# Further notes
I've made these bindings.

```
  (define-key prog-mode-map [double-down-mouse-1] 'evil-jump-to-tag)
  (define-key evil-motion-state-map [down-mouse-1] nil)
  (define-key prog-mode-map [mouse-8] 'xref-pop-marker-stack)

```
It works but there's a little problem. If the postion to go is different with the current, then evil/emacs goes into visual mode. I've tried to figure out but I couldn't.

Fortunately, I've figured out what's happenning once double-clicking thru command-log-mode. Here those are.

```

<down-mouse-1>
       evil-mouse-drag-region
<mouse-1>  mouse-set-point
<double-down-mouse-1>
       evil-jump-to-tag
```

I think those preceding 2 and are causing the weird visual selection and wrong cursor postion.

Please let me know if you know how to disable those 2 only once I'd like to jump to the definition by double-clicking.

Thanks. in advance.

**Comment by wasamasa** [comment]
If you've already unbound `evil-mouse-drag-region`, that's all you can do from Evil's side.  All Evil does here is translating changes to the region to the respective state, so even with Evil disabled you should run into that issue.  Feel free to play around with the keybindings defined in `mouse.el`, but beware that this might do far more than rendering dragging inoperable.
