### ISSUE TITLE
Mouse click messes up repeat

### ISSUE THREAD

**Issue by unhammer** [emacs-evil/evil#939]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-19, modified by Debian
Operating System: Xubuntu 17.04 Zesty
Evil version: evil-git-b6ed94c
Evil installation type: git
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Type `icake coffee` and hit Escape
- Type `ry`
- Click with the mouse at the last letter of `cake`
- Enter `.`

# Expected behavior
Change the `e` in `cake` to `y`

# Actual behavior
Nothing happens

# Further notes
I have no idea what gvim does, but it'd be quite useful if this worked as in "Expected behavior"

**Comment by wasamasa** [comment]
I've managed to reproduce this, Evil records the events for the mouse command and replays them.  So, what happens here is that if you hit `.` after clicking, it clicks again, doing seemingly nothing.  My naïve solution to this is preventing mouse commands from being recorded at all as this is Vim we're emulating, not Acme.

**Comment by b3n** [comment]
I found this annoying too, so I had a little look into it. Reverting https://github.com/emacs-evil/evil/commit/3af5f5c5730d216ee74ee732b6f02a9203c94844 fixed it for me.
