### ISSUE TITLE
Option to allow evil-change to not touch the kill ring

### ISSUE THREAD

**Issue by concretevitamin** [emacs-evil/evil#946]
This is a simple feature request: adapting https://github.com/emacs-evil/evil/pull/853 to `evil-change` will be immensely useful!

**Comment by wasamasa** [comment]
I'll have to decline here.  Not only do you ignore the issue template, you propose breaking API.  The docstring of `evil-yank` which change and delete options use is explicit here, "Saves the characters in motion into the kill-ring.".
