### ISSUE TITLE
yy does not copy \n in graphical emacs

### ISSUE THREAD

**Issue by lpenz** [emacs-evil/evil#947]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.15) of 2017-07-22
Operating System: Debian Stretch
Evil version: Evil version 1.2.13
Evil installation type: manual
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs GUI
- Open a file
- Use yy to yank the current line
- Check using :registers that the yanked line has no ^J (newline) at end
- Use p to paste

# Expected behavior
- :registers should have the ^J at the end of the line
- Pasting it should create a new line below the current one

# Actual behavior
- :registers has no ^J at the end of the line
- Pasting it inserts the chars in the current line, just after the cursor

# Further notes
It works as expected in terminal emacs - that's quite strange.

**Comment by wasamasa** [comment]
Cannot reproduce in `make emacs`, a line yanked with `yy` has `^J` at the end.

**Comment by ninrod** [comment]
cannot reproduce.

**Comment by wasamasa** [comment]
@lpenz I'm not referring to building Emacs, I'm referring to running `make emacs` as described in [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports).  This is for making sure you're testing the bug without any interference of your init file and with the latest version of Evil.

**Comment by lpenz** [comment]
I just figured out it was a clipboard manager in X (gpaste) that was messing it up.
Sorry for the trouble, and thanks for the help!
