### ISSUE TITLE
Cursor stuck at RTL line 

### ISSUE THREAD

**Issue by sadid** [emacs-evil/evil#953]
# Issue Type
Bug report

# Environment

Emacs version: Gnu Emacs 25.3.1
Operating System: Arch Linux x64 (4.13.8)
Evil version: 1.2.13
Evil installation type: MELPA
Graphical/Terminal: X (GTK++)

# Reproduction steps
- Open Attached file in Emacs
- Go to the end of the document with "j" or "G"
- Try to come back to the first line using "k". The cursor stuck at the RTL (Right to Left) line. 

# Expected behavior
- while press "k", the cursor goes up to the beginning of the file (just where gg goes). 

# Actual behavior
- wile press "k", the cursor stuck on RTL line. 

# Further notes
It's 3 simple lines. Two LTR (Left-To-Rigth) and 1 RTL in the middle.
One can copy/paste the below line in as a .tex or .text file (as far as I tested) and use vim motions. 

```latex
This is a test: When the cursor goes below RTL line it can't get up here by ``k''. It stuck. 


در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم در این الگوریتم

You can go up to the first or second line by pressing ``k''. 
It seems that evil mode think the RTL line is the beginning of the document. 

```

**Comment by wasamasa** [comment]
Sorry, but I cannot reproduce this from `make emacs`. This line is there for a reason in the bug template, don't delete it when submitting a bug report.
