### ISSUE TITLE
`C-[` doesn't exit search

### ISSUE THREAD

**Issue by auwsmit** [emacs-evil/evil#957]
# Issue type

- Bug report

# Environment

Emacs version: 25.3.1
Operating System: Windows 10
Evil version: evil-git-b388c94
Evil installation type: MELPA (I think.. I have both melpa and melpa-stable as sources)
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Set the `evil-search-module` option to `evil-search` before requiring `evil`
  - e.g. `(setq evil-search-module 'evil-search)`
- Start Emacs
- Perform an evil search with `/`
- Press `C-[` to exit search

# Expected behavior
It should exit command/search state (is it even a state?) into normal state

# Actual behavior
It awaits more input for a key combination `ESC-`

# Further notes
Similar issue: #514 

It seems that, due to `C-[` being translated to `ESC` by terminals and Emacs, it's been problematic to remap and has had edge-case issues in the past. But nonetheless, it shouldn't be impossible to get working as expected

**Comment by wasamasa** [comment]
Sorry, but I cannot reproduce this with a graphical session. `C-[` does the right thing, just as `ESC` would. Might be a Windows thing, weird stuff in your init file, who knows, only a proper repro can rule the latter two out.

**Comment by auwsmit** [comment]
Sorry about that! I think I found the setting that causes the bug (also updated my original post): The `evil-search-module` option set to `evil-search`. When set to its default value `isearch`, `C-[` exits from `/` just fine as you experienced.

**Comment by wasamasa** [comment]
Thank you, that's something I can work with!

It seems this is the fault of `evil-ex-search-keymap` not having a binding for `ESC` or rather, `<escape>` to abort search.  Try `(define-key evil-ex-search-keymap (kbd "<escape>") 'abort-recursive-edit)`.

**Comment by auwsmit** [comment]
It works! Thanks a ton.

**Comment by auwsmit** [comment]
woops, sorry for closing if you didn't want it closed
