### ISSUE TITLE
M-x help results in "Args out of range" error in Evil+Icicles setup

### ISSUE THREAD

**Issue by c4eater** [emacs-evil/evil#958]
# Issue type
- Bug report

# Environment
Emacs version: GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 2.20.1) of 2017-10-27
Operating System: CentOS 6.5
Evil version: evil-git-3735da8
Evil installation type: manual
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Load Evil and enable Evil mode (M-x evil-mode)
- Load Icicles and enable Icy mode (M-x icy-mode)
- Type `M-x help` <RET>

# Expected behavior
Emacs help screen should show up.

# Actual behavior
The following error appears in *Messages*:
> icicle-execute-extended-command: Args out of range: "", 0, -1

# Further notes
This bug occurs on the boundary of two plugins, Evil and Icicles. It shows up only when evil-mode and icy-mode are both active. If only Evil mode, or only Icicles mode, or neither one is active, `M-x help` works fine. `M-x eval-expression (help)` always works fine. From a quick look, the bug probably occurs because Evil modifies the contents of (this-command-keys) before Icicles' version of M-x invokes "call-interactively".

**Comment by wasamasa** [comment]
Please provide a backtrace with `M-x toggle-debug-on-error`.  Also, how does Evil modify `(this-command-keys)`?  If you're sure that's the problem, can you further minimize the problem so that Evil is no longer involved?

**Comment by c4eater** [comment]
Hi,

Attaching the debug log.

By "modifying `(this-command-keys)`", I meant modifying the correspondent array of keycodes (sorry for probable confusion).

There are 2 reasons that make me think that the modification of this array (more exactly, clearing it) is the root cause:

1. When I dump the output of `(this-command-keys-vector)` right before Icicles invokes `call-interactively`: 
- in an environment where `M-x help` works (e.g. Icicle with Evil mode off) I get `[^M]`.
- in an environment where `M-x help` fails (Emacs+Evil both on) I get an empty array.

2. When I turn off Evil but insert `(clear-this-command-keys)` before Icicles invokes `call-interactively`, I get the same "args out of range error". Evil code also has `clear-this-command-keys` as rgrep shows.

I believe item #2 also answers your question on minimizing the problem.
[evil-debug.log](https://github.com/emacs-evil/evil/files/1433820/evil-debug.log)

**Comment by wasamasa** [comment]
Thanks, with this I can minimize it even further:

```elisp
(defun test ()
  (interactive)
  (clear-this-command-keys)
  (call-interactively 'help 'record-it))
```

Execute `M-x test` and see it error out the same way, no Icicles or Evil required.  I reckon this is an Emacs bug, so feel free to `M-x report-emacs-bug` and follow up here with their results.  If and only if the official response is to not ever do such a thing, then I'll reconsider whether this ought to be fixed on Evil's or Icicles' behalf.

**Comment by OrionRandD** [comment]
Args out of range: "", 0

Using doom-Emacs

If I call browse-url-xdg-open

You can invoke command ‘browse-url-xdg-open’ using ‘C-x g’
on
https://wikipedia.org

with evil-mode on I get:

icicle-execute-extended-command: Args out of range: "", 0


If I "C-z" on doom-Emacs, disabling evil-mode, and 
call browse-url-xdg-open

You can invoke command ‘browse-url-xdg-open’ using ‘C-x g’
on
https://wikipedia.org

It opens my GUI browser

I'd like to find where the error is:
1. In evil-mode?
or in
2. In icicle-mode?

Thx
