### ISSUE TITLE
 evil-normal-state after typing if invokes python-skeleton-if

### ISSUE THREAD

**Issue by joonro** [emacs-evil/evil#963]
# Bug

- Bug report

# Environment

Emacs version: GNU Emacs 25.3.1 (x86_64-w64-mingw32)
Operating System: Windows 10
Evil version: 1.2.13
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session: No

# Reproduction steps
- Start Emacs
- Open a python file so `python.el` is loaded
- type `if `
- press <ESC> to run `evil-normal-state`

# Expected behavior
- Normal state is activated

# Actual behavior
- `python.el`'s `python-skeleton-if` is invoked.

**Comment by wasamasa** [comment]
The only way I can reproduce this from `make emacs` is by customizing `python-skeleton-autoinsert` which means that I want this behavior. It happens to use an abbrev table for this, so just like in Vim hitting `ESC` in insert state will expand them.  If you don't like this behavior, customize ` evil-want-abbrev-expand-on-insert-exit` but keep in mind that for `if` followed by `SPC` to trigger the expansion you'll need to have `abbrev-mode` enabled.

@edkolev This made me notice that calling `expand-abbrev` after exiting insert state will unconditionally expand it, even if `abbrev-mode` isn't activated.  Is this really what we want?

**Comment by edkolev** [comment]
Hm, I don't thinks so, I'll open a PR.

Maybe the solution here is to always have an evil-insert-state-exit-hook (no matter what's the value of `evil-want-abbrev-expand-on-insert-exit`), then the hook function will call `expand-abbrev` only if both `abbrev-mode` is active and `evil-want-abbrev-expand-on-insert-exit` is non-nil.

**Comment by joonro** [comment]
Thanks a lot for quick reply. I now think there must be something going on with my settings, since it happens even though I have `nil` for `python-skeleton-autoinsert`. In addition, even after changing `evil-want-abbrev-expand-on-insert-exit` to `nil`, this still happens.

Do you have any idea what is likely causing this? I guess I have to go through my init file line-by-line to find out what is causing this.

**Comment by wasamasa** [comment]
@edkolev I haven't used abbrev in Vim or Emacs, so I'd make the choice dependent on whether you can trigger them in Vim by any other action than `ESC`. If typing a space afterwards suffices, I'd go by the Emacs behavior of requiring an enabled `abbrev-mode` first.

@joonro First of all, ensure you cannot reproduce this with `emacs -q` (or more easily, `make emacs` as described in the official repro steps). Once that's confirmed, comment out half of your init file and recur until you find the culprit.

**Comment by joonro** [comment]
@wasamasa Something is strange. I did `emacs -q`, and then only evaluated the following so I can use evil-mode:

```
(when (>= emacs-major-version 24)
  (require 'package)
  (package-initialize)
  (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
  (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
  )
```

And then ran `(evil-mode 1)`. 

When I do `if<ESC>` in a python-mode buffer, I'm getting `Symbol’s function definition is void: python-skeleton-if`.

**Comment by wasamasa** [comment]
Do `M-x toggle-debug-on-error`, provoke the error and copy-paste the backtrace.

**Comment by joonro** [comment]
```
Debugger entered--Lisp error: (void-function python-skeleton-if)
  python-skeleton-if()
  abbrev-insert(if #("if" 0 2 (fontified t face font-lock-keyword-face)) 1 3)
  #[0 "\304 \211@A\211@A\211@A\211@A\n\211\205O
  abbrev--default-expand()
  expand-abbrev()
  run-hooks(evil-insert-state-exit-hook)
  evil-insert-state(-1)
  evil-change-state(nil)
  evil-normal-state()
  funcall-interactively(evil-normal-state)
  call-interactively(evil-normal-state nil nil)
  command-execute(evil-normal-state)
```
I could not copy & pasted binary stuff so I attached the screenshot:

![image](https://user-images.githubusercontent.com/1063143/32629708-b595e732-c55f-11e7-9b9f-9999ca25cf4a.png)

**Comment by wasamasa** [comment]
Hm, this doesn't make any sense. The only way that could happen is if `python.el` hasn't been loaded yet or the `python.el` that got loaded doesn't have skeleton definitions (which you could verify by using `emacs -Q`).  Anyway, this is far beyond what Evil is supposed to do.

**Comment by joonro** [comment]
I'm not sure about why `python.el` is not loaded, but I think my original problem is caused by `expand-abbrev` being a member of `evil-insert-state-exit-hook`:

```
evil-insert-state-exit-hook is a variable defined in ‘evil-states.el’.
Its value is
(expand-abbrev evil-stop-track-last-insertion evil-cleanup-insert-state)
```

`(setq evil-insert-state-exit-hook (remove 'expand-abbrev evil-insert-state-exit-hook))
` solved my original issue. (Thank you very much for your help!!) Is it supposed to be there by default?

**Comment by joonro** [comment]
FYI, for some reason `(setq evil-want-abbrev-expand-on-insert-exit nil)` does not affect this behavior.

**Comment by wasamasa** [comment]
It has to be set *before* loading Evil to affect it because if it's set too late, Evil won't see it and add `expand-abbrev` to `evil-insert-state-exit-hook`.

**Comment by joonro** [comment]
Thanks! However for some reason it still does not work:

```
(use-package evil
  :init
  (setq evil-want-abbrev-expand-on-insert-exit nil)
  :config
  (evil-mode 1))
```

I tried to put `(setq evil-want-abbrev-expand-on-insert-exit nil)` before `(use-package evil` but still `expand-abbrev` was in `evil-insert-state-exit-hook`.

**Comment by edkolev** [comment]
Setting `evil-want-abbrev-expand-on-insert-exit` to nil before loading evil works for me. @joonro are you sure evil hasn't already been `require`-ed by the time the `evil-want-abbrev-expand-on-insert-exit` var is set?

**Comment by joonro** [comment]
You are right. I was using `powerline-evil` and it was implicitly calling `evil`. Not only I was able to fix the issue, but I found `telephone-line`, which looks much better than the old `powerline-evil`. Thank you very much!
