### ISSUE TITLE
Replace associative with object style notation

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [emacs-evil/evil#969]
# Issue type

- Question

# Environment

Emacs version: 25.3
Operating System: osx
Evil version: latest version
Evil installation type: MELPA
Graphical/Terminal: graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): no

# Reproduction steps
- Start Emacs
- type `$a = $some_array['key_name'];`
- type `:%s/\['\(.\{-}\)'\]/->\1/g`

# Expected behavior

$a = $some_array->key_name;

# Actual behavior

$a = $some_array['key_name'];

# Further notes
I think the `{-}` in ex mode is something like a match group
how to express in evil?

**Comment by wasamasa** [comment]
I'd be inclined to use `da}` and insert the key manually (and maybe record a macro). If you need to do it with regex, two typical ways to do it would be `%s/\[\(.*?\)\]/->\1/g` and `%s/\[\([^][]*\)\]/->\1/g`, with the latter one being more efficient as it doesn't require backtracking.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
> with the latter one being more efficient as it doesn't require backtracking.
anything detail appreciate

**Comment by wasamasa** [comment]
http://www.regular-expressions.info/catastrophic.html

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
# Reproduction steps
- Start Emacs
- type `ABC`
- type `:%s/\([^][]*\)/\1->/g`


# Expected behavior

ABC->

# Actual behavior

ABC->->

# Further notes
the `[^][]*` can be replaced with [\d\D]?

**Comment by wasamasa** [comment]
@justbur Could you please take a look at why the above does two instead of one replacement?

@earthIsAPrisonIfYouNotAwareItCanNotOut No, it means matching all characters except `]` and `[`. This doesn't make any sense for your example because there's no brackets involved. If you want to put something at the end of line, I'd use `:s/$/->`.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
sorry to trouble you again
there is something wrong with `:s/$/->`
the prompt popup can be removed
how to express "matching all possible characters" in evil (like `[\d\D]*`?

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
It also make me a puzzle what the `{-}` means in vim?

**Comment by VanLaser** [comment]
It means "not be greedy, much as little as possible".

**Comment by justbur** [comment]
@wasamasa It's because the newline characters are being matched. Do you know what the rules are for matching newlines? Do they have to be explicitly specified in the regex somehow?

**Comment by wasamasa** [comment]
At this point it's merely regex questions, so consult `:help regex` in Vim and `(info "(elisp) Regular Expressions")` in Emacs.

**Comment by justbur** [comment]
> there is something wrong with :s/$/->
the prompt popup can not be removed

I have no idea what this refers to

Referring to the second reported issue, a command that works (and is better in my opinion) is `:%s/\([^][\n]+\)/\1->/g`, which explicitly excludes the newline and also excludes zero-length matches. I'll look into that documentation, but I don't have enough time right now.

**Comment by wasamasa** [comment]
I don't know either.  I've suspected that there's both a zero-length and non-zero-length match, but it's kind of silly for it to behave this way considering Vim doesn't.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
> I have no idea what this refers to

after executing `:s/$/->`, the prompt content is still not clear away

<img width="157" alt="2017-11-21 8 55 50" src="https://user-images.githubusercontent.com/16307328/33049390-d856d9ea-ce9a-11e7-8277-f5a7dd560567.png">

**Comment by justbur** [comment]
> after executing :s/$/->, the prompt content is still not clear away

I don't experience this. I'll need better reproduction steps to test it.

**Comment by justbur** [comment]
@wasamasa I think #972 fixes all of the issues identified here that we can. The `\{-}` syntax is not part of the Emacs regexp syntax ([see here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Backslash.html#Regexp-Backslash)), but you can use `?` instead. Also, while `[^][]]*` does not span newlines in vim, it does in Emacs. The following is taken from [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Special.html#Regexp-Special)

>‘[^ ... ]’
>
>‘[^’ begins a complemented character alternative. This matches any character except the ones specified. Thus, ‘[^a-z0-9A-Z]’ matches all characters except letters and digits.
‘^’ is not special in a character alternative unless it is the first character. The character following the ‘^’ is treated as if it were first (in other words, ‘-’ and ‘]’ are not special there).
>
>A complemented character alternative can match a newline, unless newline is mentioned as one of the characters not to match. This is in contrast to the handling of regexps in programs such as grep.
>
>You can specify named character classes, just like in character alternatives. For instance, ‘[^[:ascii:]]’ matches any non-ASCII character. See Char Classes.

**Comment by wasamasa** [comment]
@justbur I'm not sure what might cause the stray prompt, but while merging #956 I noticed that the part that clears substitution highlighting and the overlay isn't in the unconditionally executing part of `unwind-protect`, so you may want to fix that.
