### ISSUE TITLE
evil-insert-state-entry-hook is not working

### ISSUE THREAD

**Issue by casouri** [emacs-evil/evil#973]
# Issue type

- Bug report

# Environment

Emacs version: Spacemacs v.0.300.0@25.3.1
Operating System: macOS High Sierra
Evil version: evil-git-36c15b79
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- in init.el add: ```(add-hook 'evil-insert-state-entry-hook (lambda () (message "enter insert mode")))```
- try to enter insert mode

# Expected behavior

message "enter insert mode"

# Actual behavior

nothing happened, nor any log in \*Message\* buffer 

# Further notes

I am just testing with a message lambda. I have a custom function that I want to be called when entering insert mode. When I call it directly with M-x function it works. But adding hook to that function does not work. the function is not called when entering insert mode, just like the message lambda.

**Comment by wasamasa** [comment]
Sorry, but if you claim to have done the `make emacs` reproduction, I expect the reproduction steps to not involve an `init.el`.  The whole point of `make emacs` is to not be depending on an init file doing who knows what and additionally, to ensure you're using the latest version of Evil (as it's run in Evil's git repository).

Needless to say, I cannot reproduce this.

**Comment by casouri** [comment]
The problem is fixed somehow. If anyone encounter it, please check https://emacs.stackexchange.com/questions/36972/add-hook-evil-insert-state-entry-hook-is-not-calling-the-function

**Comment by lujianmei** [comment]
I got the same error on Mac.
evil-insert-state-entry-hook 
evil-insert-state-exit-hook 
will not be called.

**Comment by TheBB** [comment]
I can't reproduce this from `make emacs`. Please provide some details.

**Comment by jiahut** [comment]
```
  (setq issw_default_lang_source "com.sogou.inputmethod.sogou.pinyin")

  (defun my/enter-insert-state-hook()
    (interactive)
    (shell-command (concat "issw " issw_default_lang_source)))

  (defun my/exit-insert-state-hook()
    (interactive)
    (setq issw_default_lang_source (shell-command-to-string "issw"))
    (shell-command "issw com.apple.keylayout.US"))

  (add-hook 'evil-insert-state-entry-hook 'my/enter-insert-state-hook)
  (add-hook 'evil-insert-state-exit-hook  'my/exit-insert-state-hook)
  (add-hook 'evil-replace-state-entry-hook 'my/enter-insert-state-hook)
  (add-hook 'evil-replace-state-exit-hook  'my/exit-insert-state-hook)
````
it does not work ,nothing happen

**Comment by TheBB** [comment]
I don't know what *issw* is or does, but if I replace your shell commands with calls to `message` I do get messages. So I'm afraid I continue to be unable to reproduce this.

**Comment by jiahut** [comment]
> > I don't know what _issw_ is or does, but if I replace your shell commands with calls to `message` I do get messages. So I'm afraid I continue to be unable to reproduce this.
> 
> I'm using `spacemas`, I don't know if that makes a difference

I just got it because I'm using the hybrid mode, thinks.
