### ISSUE TITLE
what is the "<R>" option in the interactive form?

### ISSUE THREAD

**Issue by ninrod** [emacs-evil/evil#981]
# Issue type

- Question

In perusing various evil source repos, I stumbled upon the `"<R>"` option usage in (interactive) form, specially appering in `evil-define-operator` forms.

So what exactly is the `"<R>"` option used in [here](https://github.com/emacs-evil/evil/blob/61440c035c2720eb6c3cdad7b5b24a19929810c4/evil-commands.el#L1813)?

This option does not appear in the the [official code list](https://www.gnu.org/software/emacs/manual/html_node/elisp/Interactive-Codes.html) for the interactive form.

Was it created? How exactly is this working? what does it do?

Thanks in advance for any help

**Comment by wasamasa** [comment]
https://github.com/emacs-evil/evil/blob/61440c035c2720eb6c3cdad7b5b24a19929810c4/evil-types.el#L288-L290

**Comment by TheBB** [comment]
Those are special interactive codes that only work in `evil-define-command` and `evil-define-operator`.

**Comment by ninrod** [comment]
ahh! thanks
