### ISSUE TITLE
Have evil-ex-substitute open folds automatically

### ISSUE THREAD

**Issue by noctuid** [emacs-evil/evil#983]
I couldn't find an issue for this already, but it would be great if `evil-ex-substitute` automatically opened folds after moving the point when used with confirmation (otherwise you can't see what is being replaced).

**Comment by wasamasa** [comment]
How would this work in a generic way? It's not like there's one way of folding (like in the certain text editor this package seeks to emulate) and people love inventing their own competing version.

**Comment by noctuid** [comment]
I'd think it would be fine to either just use `evil-open-fold` or do it however isearch does it. I guess a hook could be provided as well, but evil already supports all the types of folding I personally use.

**Comment by wolfv6** [comment]
This would be a real nice feature (but I have not idea of how to implement it).

**Comment by justbur** [comment]
Should it leave them open (easy) or re-close them (more difficult)?

**Comment by noctuid** [comment]
Vim re-closes them, but I'd be fine with them being left open. I'd actually probably prefer them being left open, but it doesn't really seem like a big deal either way.

**Comment by justbur** [comment]
I’ll do a simple solution then and we can make it more sophisticated later

**Comment by wolfv6** [comment]
Either way would be a great improvement.  Although I would prefer re-close closed headings like Vim.

**Comment by justbur** [comment]
Please test #1009. I think I found a simple solution that only opens folds temporarily. I believe this only works for folding that has built-in support for similar functionality in isearch.
