### ISSUE TITLE
master doesn't work

### ISSUE THREAD

**Issue by mriehl** [emacs-evil/evil#987]
# Issue type
- Bug report

# Environment

Emacs version: 25.3.1
Operating System: Irrelevant
Evil version: latest melpa build
Evil installation type: MELPA
Graphical/Terminal: No difference
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Install evil from melpa

# Expected behavior
- It does not shred my init.el

# Actual behavior
- It shreds my init.el
Loading evil dies with `End of file during parsing: /path/to/evil-commands.el`

# Further notes
https://github.com/emacs-evil/evil/commit/620026182c799b511e155d1ea81fe76811134eb6 seems to have completely broken the file (cc @wasamasa )
with `curl https://raw.githubusercontent.com/emacs-evil/evil/6c756cfd46f6e7c52aafe133f36881febe2c2fb0/evil-commands.el > evil-commands.el` everything works fine.
with `curl https://raw.githubusercontent.com/emacs-evil/evil/master/evil-commands.el > evil-commands.el` I get the end of file error.

**Comment by mriehl** [comment]
I'm using `curl https://raw.githubusercontent.com/emacs-evil/evil/6c756cfd46f6e7c52aafe133f36881febe2c2fb0/evil-commands.el > evil-commands.el` as a workaround for now. I guess using stable would also work.

**Comment by wasamasa** [comment]
Sorry about that, that was merge conflict resolution going wrong.

That aside, rather curious definition of shredding (try `man shred` to get an overall idea what it means to shred a file).
