### ISSUE TITLE
Evil Mode removes Imagemagick support (!?)

### ISSUE THREAD

**Issue by naclander** [emacs-evil/evil#996]
# Issue type

- Bug report

# Environment

Emacs version: verified on 27.0.50, 26.1 pre ( does NOT occur on 25.3.1 )
Imagemagick version: 6 and 7
Operating System: Arch Linux, 
Evil version: 1.2.13
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes 
emacs compilation flags: "--with-imagemagick 'CFLAGS=-Ofast -march=native -frename-registers -funroll-loops' CC=gcc"

# Reproduction steps

## Repro 1
- Start `emacs -Q`
* evaluate `(image-type-available-p 'imagemagick)` -> should return `t`, or `imagemagick`
* run `(package-initialize)`
* run `(evil-mode)`
* evaluate `(image-type-available-p 'imagemagick)` -> now returns `nil`

## Repro 2 ( with make emacs from evil source )
* launch emacs from evil source directory using make emacs
* Evil should already be loaded, so just eval `(image-type-available-p 'imagemagick)` -> should return `nil`

# Expected behavior
evil mode should not affect imagemagick support

# Actual behavior
evil mode disables imagemagick support

# Further notes
I'm fully aware that this makes no sense, but I was able to confirm this with one other person. If you cannot reproduce this with the latest version of emacs please feel free to close this, as it is most likely something specific to my system. However, since someone else was able to corroborate this, I decided to open the bug report.

**Comment by wasamasa** [comment]
Sorry, but I cannot repro this with ImageMagick 6 (Emacs doesn't even support ImageMagick 7) on master.  The check returns t both with and without Evil.  Anything different from that would be bizarre to say the least.

**Comment by naclander** [comment]
To those who happen to run into this problem, and specifically on Arch Linux, ensure that emacs is compiled with ImageMagick version 6 as wasamasa said, and that the package config path is properly set, like so: `PKG_CONFIG_PATH="/usr/lib/imagemagick6/pkgconfig" ./configure`
