### ISSUE TITLE
What is the difference between evil-mode and turn-on-evil-mode?

### ISSUE THREAD

**Issue by socketwiz** [emacs-evil/evil#998]
# Issue type
- Question

# Environment

Emacs version: GNU Emacs 25.3.1
Operating System: macOS High Sierra
Evil version: 1.2.13
Evil installation type: MELPA stable
Graphical/Terminal: Graphic
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- `i` to get into insert mode
- type some text
- key `<C-[>`

# Expected behavior
- Leave insert mode

# Actual behavior
- Stays in insert mode

# Further notes
I've tried this with a vanilla emacs and nothing but evil installed with the same results.

This works fine when you run `(evil-mode 1)` however I've been scaling back the places I run evil-mode and have been using `(turn-on-evil-mode)` based on what major-mode is found as opposed to `(evil-mode 1)`.  If if I'm in a mode I don't want evil in I run `(turn-off-evil-mode)`.  For the most part this seems to work well but I found at least this one inconsistency and I'm wondering if there are others.  Is this expected behavior or have I found an anomaly?

**Comment by wasamasa** [comment]
`evil-mode` is implemented in terms of `turn-on-evil-mode` which enables it for the current buffer only (as it wraps `evil-local-mode`.  Using `evil-local-mode` in place of `evil-mode` is **not** supported because it omits the extra state keeping (as you've observed).
