### ISSUE TITLE
If `x` is included at the beginning of one line of a paragraph, `}` fails in Visual state 

### ISSUE THREAD

**Issue by wickedjargon** [emacs-evil/evil#999]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 25.2.1 (x86_64-mingw32) of 2017-04-24
Operating System: Windows 10 Home 64-bit
Evil version: 1.2.13
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- set Major mode to Markdown
- paste a paragraph of text where one of the lines starts with `x`, for example:

blah blah blah
+ blah blah
blah blah blah

- in insert mode execute:
1 `gg` 
- `}`

# Expected/actual behavior
when pressing `}` in insert mode, cursor should move to end of paragraph, but evil thinks that the line starting with `+` is the beginning of a new paragraph

**Comment by wasamasa** [comment]
This is a faulty repro for a few reasons:

- "paste a paragraph of text where one of the lines starts with x, for example:" <- The following text has no such line
- "in insert mode execute:" <- The whole point of insert state (it's not a mode, modes are something different in Emacs) is to insert letters as you type them, so this isn't right either
- "but evil thinks that the line starting with + is the beginning of a new paragraph" <- You mentioned lines starting with "x" above...

I'll reopen once this has a repro I can actually work with.
